/**
 * Auth service error codes used across Helix services and clients.
 *
 * Keep these codes stable. They are part of the public contract between
 * the Auth service, User service, frontend, tests, logs, and dashboards.
 */

export const AuthErrorCode = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_SESSION: 'INVALID_SESSION',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
  INVALID_VERIFICATION_TOKEN: 'INVALID_VERIFICATION_TOKEN',
  INVALID_PASSWORD_RESET_TOKEN: 'INVALID_PASSWORD_RESET_TOKEN',

  EMAIL_REQUIRED: 'EMAIL_REQUIRED',
  PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  PASSWORD_TOO_LONG: 'PASSWORD_TOO_LONG',
  PASSWORD_TOO_WEAK: 'PASSWORD_TOO_WEAK',
  PASSWORD_REUSED: 'PASSWORD_REUSED',

  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  EMAIL_NOT_REGISTERED: 'EMAIL_NOT_REGISTERED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
  EMAIL_VERIFICATION_REQUIRED: 'EMAIL_VERIFICATION_REQUIRED',
  EMAIL_VERIFICATION_EXPIRED: 'EMAIL_VERIFICATION_EXPIRED',
  EMAIL_VERIFICATION_FAILED: 'EMAIL_VERIFICATION_FAILED',

  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_ALREADY_EXISTS: 'ACCOUNT_ALREADY_EXISTS',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_PENDING_VERIFICATION: 'ACCOUNT_PENDING_VERIFICATION',

  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  SESSION_REFRESH_FAILED: 'SESSION_REFRESH_FAILED',
  SESSION_CREATION_FAILED: 'SESSION_CREATION_FAILED',

  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  TOKEN_MISSING: 'TOKEN_MISSING',
  TOKEN_SIGNATURE_INVALID: 'TOKEN_SIGNATURE_INVALID',
  TOKEN_AUDIENCE_INVALID: 'TOKEN_AUDIENCE_INVALID',
  TOKEN_ISSUER_INVALID: 'TOKEN_ISSUER_INVALID',

  MFA_REQUIRED: 'MFA_REQUIRED',
  MFA_NOT_ENABLED: 'MFA_NOT_ENABLED',
  MFA_ALREADY_ENABLED: 'MFA_ALREADY_ENABLED',
  MFA_CODE_INVALID: 'MFA_CODE_INVALID',
  MFA_CODE_EXPIRED: 'MFA_CODE_EXPIRED',
  MFA_CHALLENGE_FAILED: 'MFA_CHALLENGE_FAILED',

  PASSWORD_RESET_REQUIRED: 'PASSWORD_RESET_REQUIRED',
  PASSWORD_RESET_EXPIRED: 'PASSWORD_RESET_EXPIRED',
  PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED',

  LOGOUT_FAILED: 'LOGOUT_FAILED',
  REGISTER_FAILED: 'REGISTER_FAILED',
  LOGIN_FAILED: 'LOGIN_FAILED',
  REFRESH_FAILED: 'REFRESH_FAILED',

  JWKS_UNAVAILABLE: 'JWKS_UNAVAILABLE',
  SIGNING_KEY_UNAVAILABLE: 'SIGNING_KEY_UNAVAILABLE',
} as const;

export type AuthErrorCode = (typeof AuthErrorCode)[keyof typeof AuthErrorCode];

export const AUTH_ERROR_CODES = Object.values(AuthErrorCode);

export const isAuthErrorCode = (value: unknown): value is AuthErrorCode =>
  typeof value === 'string' &&
  AUTH_ERROR_CODES.includes(value as AuthErrorCode);
