/**
 * User service error codes used across Helix services and clients.
 *
 * Keep these codes stable. They are part of the public contract between
 * the User service, Auth service, frontend, tests, logs, and dashboards.
 */

export const UserErrorCode = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_PROFILE_NOT_FOUND: 'USER_PROFILE_NOT_FOUND',
  USER_PROFILE_ALREADY_EXISTS: 'USER_PROFILE_ALREADY_EXISTS',

  USER_DISABLED: 'USER_DISABLED',
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_DELETED: 'USER_DELETED',
  USER_LOCKED: 'USER_LOCKED',

  INVALID_USER_ID: 'INVALID_USER_ID',
  INVALID_USERNAME: 'INVALID_USERNAME',
  INVALID_DISPLAY_NAME: 'INVALID_DISPLAY_NAME',
  INVALID_AVATAR_URL: 'INVALID_AVATAR_URL',
  INVALID_PROFILE_PAYLOAD: 'INVALID_PROFILE_PAYLOAD',
  INVALID_PREFERENCES_PAYLOAD: 'INVALID_PREFERENCES_PAYLOAD',

  USERNAME_REQUIRED: 'USERNAME_REQUIRED',
  USERNAME_TOO_SHORT: 'USERNAME_TOO_SHORT',
  USERNAME_TOO_LONG: 'USERNAME_TOO_LONG',
  USERNAME_INVALID_FORMAT: 'USERNAME_INVALID_FORMAT',
  USERNAME_RESERVED: 'USERNAME_RESERVED',
  USERNAME_TAKEN: 'USERNAME_TAKEN',

  DISPLAY_NAME_REQUIRED: 'DISPLAY_NAME_REQUIRED',
  DISPLAY_NAME_TOO_LONG: 'DISPLAY_NAME_TOO_LONG',

  EMAIL_REQUIRED: 'EMAIL_REQUIRED',
  EMAIL_INVALID: 'EMAIL_INVALID',
  EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',

  PROFILE_UPDATE_FAILED: 'PROFILE_UPDATE_FAILED',
  PREFERENCES_UPDATE_FAILED: 'PREFERENCES_UPDATE_FAILED',
  CONSENT_UPDATE_FAILED: 'CONSENT_UPDATE_FAILED',

  USER_SETTINGS_NOT_FOUND: 'USER_SETTINGS_NOT_FOUND',
  USER_SETTINGS_UPDATE_FAILED: 'USER_SETTINGS_UPDATE_FAILED',

  ONBOARDING_STATE_INVALID: 'ONBOARDING_STATE_INVALID',
  ONBOARDING_UPDATE_FAILED: 'ONBOARDING_UPDATE_FAILED',
} as const;

export type UserErrorCode = (typeof UserErrorCode)[keyof typeof UserErrorCode];

export const USER_ERROR_CODES = Object.values(UserErrorCode);

export const isUserErrorCode = (value: unknown): value is UserErrorCode =>
  typeof value === 'string' &&
  USER_ERROR_CODES.includes(value as UserErrorCode);
