// libs/content/src/en/technology/security.ts

import type { ReadonlyCardArray } from '../../types';

/**
 * Security, compliance, signing, scanning, runtime detection, policy-as-code,
 * and supply-chain automation used by Helix AI.
 */
export const securityCards = [
  {
    title: 'Security & Compliance',
    description:
      'Secrets management, TLS automation, vulnerability scanning, static and dynamic analysis, runtime detection, policy-as-code, SIEM, incident visibility, and supply-chain security for Helix AI’s cloud-native platform.',
    listItems: [
      {
        text: 'HashiCorp Vault',
        href: 'https://www.hashicorp.com/en/products/vault',
        role: 'Secrets Management',
        detailedDescription:
          'Vault provides identity-based secrets management for storing, accessing, distributing, rotating, and auditing sensitive data such as credentials, tokens, certificates, API keys, and encryption material. It helps centralize secret access across humans, machines, services, and automation workflows. Helix AI can use Vault for connector secrets, API credentials, database credentials, certificate workflows, KMS-style encryption, and audited secret access.',
      },
      {
        text: 'cert-manager',
        href: 'https://cert-manager.io/',
        role: 'TLS Certificate Automation',
        detailedDescription:
          'cert-manager is a Kubernetes-native certificate-management controller for issuing, renewing, and managing TLS certificates from ACME, Vault, self-signed, private PKI, and other issuers. It helps automate certificate lifecycle management across namespaces, ingress resources, gateways, and internal services. Helix AI can use cert-manager for public TLS, internal mTLS support, service certificates, webhook certificates, and GitOps-managed certificate automation.',
      },
      {
        text: 'Trivy',
        href: 'https://trivy.dev/',
        role: 'Vulnerability & Misconfiguration Scanner',
        detailedDescription:
          'Trivy is a security scanner for container images, filesystems, Git repositories, Kubernetes resources, infrastructure-as-code, dependencies, secrets, licenses, and SBOMs. It is useful in CI/CD pipelines, local development, container registries, and cluster-security workflows. Helix AI can use Trivy for image scanning, IaC review, dependency vulnerability detection, Kubernetes checks, and supply-chain reporting.',
      },
      {
        text: 'Grype',
        href: 'https://github.com/anchore/grype',
        role: 'SBOM Vulnerability Scanner',
        detailedDescription:
          'Grype is an open-source vulnerability scanner for container images and filesystems that can work directly with SBOMs generated by tools such as Syft. It helps identify known vulnerabilities across operating-system packages and application dependencies. Helix AI can use Grype as a second vulnerability-scanning layer for container images, release artifacts, generated SBOMs, and CI security gates.',
      },
      {
        text: 'Clair',
        href: 'https://github.com/quay/clair',
        role: 'Container Vulnerability Scanner',
        detailedDescription:
          'Clair is an open-source vulnerability scanner for container images and application packages. It indexes vulnerability metadata and helps identify known issues in containerized software. Helix AI can use Clair-style scanning for defense-in-depth around image security, registry workflows, base-image validation, and vulnerability visibility.',
      },
      {
        text: 'Dockle',
        href: 'https://github.com/goodwithtech/dockle',
        role: 'Container Image Linter',
        detailedDescription:
          'Dockle is a container image linter that checks Docker images for security best-practice issues, configuration weaknesses, and avoidable risks. It is useful alongside vulnerability scanners because it focuses on image-hardening behavior rather than only known CVEs. Helix AI can use Dockle for Dockerfile and container-image hygiene, CI checks, and release-quality container validation.',
      },
      {
        text: 'Chainguard Images',
        href: 'https://www.chainguard.dev/chainguard-images',
        role: 'Minimal Secure Images',
        detailedDescription:
          'Chainguard Images provide hardened, minimal container images designed to reduce attack surface and improve supply-chain posture. They are useful when teams want smaller base images, signed artifacts, SBOM support, and regularly maintained image foundations. Helix AI can use Chainguard Images for production services, security-sensitive workloads, CI runners, and hardened container baselines.',
      },
      {
        text: 'Syft',
        href: 'https://github.com/anchore/syft',
        role: 'SBOM Generator',
        detailedDescription:
          'Syft is an open-source tool for generating software bills of materials from container images, filesystems, archives, and source repositories. It can produce SBOMs in common formats for later vulnerability scanning, compliance review, and artifact provenance. Helix AI can use Syft for release artifacts, container images, dependency inventories, compliance evidence, and supply-chain transparency.',
      },
      {
        text: 'Cosign',
        href: 'https://github.com/sigstore/cosign',
        role: 'Artifact Signing & Verification',
        detailedDescription:
          'Cosign is part of the Sigstore ecosystem and is used for signing and verifying container images, blobs, attestations, and other software artifacts. It supports key-based and keyless signing workflows depending on the trust model. Helix AI can use Cosign for signed container images, SBOM attestations, provenance evidence, release verification, and GitOps admission policies.',
      },
      {
        text: 'Rekor',
        href: 'https://github.com/sigstore/rekor',
        role: 'Transparency Log',
        detailedDescription:
          'Rekor is a transparency log for recording metadata about signed software artifacts in the Sigstore ecosystem. It provides an auditable record that can support artifact verification and supply-chain provenance workflows. Helix AI can use Rekor-backed workflows for signed releases, verifiable builds, artifact provenance, and evidence around software supply-chain integrity.',
      },
      {
        text: 'CodeQL',
        href: 'https://codeql.github.com/',
        role: 'Semantic Code Analysis',
        detailedDescription:
          'CodeQL is a semantic code analysis engine that treats code as data and enables security queries across supported languages. It powers code scanning workflows and can identify vulnerabilities, insecure patterns, and data-flow issues in application code. Helix AI can use CodeQL for repository security checks, GitHub Advanced Security workflows, pull-request scanning, and SAST coverage for critical code paths.',
      },
      {
        text: 'Semgrep',
        href: 'https://semgrep.dev/',
        role: 'Static Analysis Scanner',
        detailedDescription:
          'Semgrep is a fast static-analysis tool for finding bugs, security issues, and policy violations using readable rules across many languages and frameworks. It is useful for custom organization policies, secure coding checks, and pull-request feedback. Helix AI can use Semgrep for lightweight SAST, custom code rules, framework-specific checks, and developer-friendly security automation.',
      },
      {
        text: 'Bandit',
        href: 'https://bandit.readthedocs.io/',
        role: 'Python Static Analyzer',
        detailedDescription:
          'Bandit is a security-oriented static-analysis tool for Python code. It scans Python source for common insecure patterns, risky API usage, and potential vulnerabilities. Helix AI can use Bandit for Python AI services, data-processing scripts, automation utilities, and ML-related backend code.',
      },
      {
        text: 'gosec',
        href: 'https://github.com/securego/gosec',
        role: 'Go Static Analyzer',
        detailedDescription:
          'gosec is a security scanner for Go source code that checks for common security problems and risky coding patterns. It is useful in CI pipelines and local development for Go services, CLIs, and infrastructure tooling. Helix AI can use gosec for Go-based agents, telemetry components, internal tools, and cloud-native services.',
      },
      {
        text: 'OWASP ZAP',
        href: 'https://www.zaproxy.org/',
        role: 'Dynamic Application Scanner',
        detailedDescription:
          'OWASP ZAP is an open-source dynamic application security testing tool for finding vulnerabilities in running web applications and APIs. It can support automated scanning, manual testing, spidering, active scans, and CI/CD security workflows. Helix AI can use ZAP for web-app testing, API security checks, staging validation, regression testing, and security review before production releases.',
      },
      {
        text: 'Nikto',
        href: 'https://cirt.net/Nikto2',
        role: 'Web Server Scanner',
        detailedDescription:
          'Nikto is an open-source web server scanner that checks for dangerous files, outdated components, insecure configurations, and common web-server issues. It is useful as a supplemental DAST-style tool alongside deeper application scanners. Helix AI can use Nikto for quick exposure checks, staging environment scans, reverse-proxy validation, and web-server hardening reviews.',
      },
      {
        text: 'Checkov',
        href: 'https://www.checkov.io/',
        role: 'Infrastructure-as-Code Scanner',
        detailedDescription:
          'Checkov scans infrastructure-as-code and cloud-native configuration for security and compliance issues across tools such as Terraform, Kubernetes, CloudFormation, Helm, Dockerfiles, and CI/CD configuration. It helps catch misconfigurations before deployment. Helix AI can use Checkov for Terraform review, Kubernetes policy checks, GitOps manifests, container configuration, and compliance-oriented CI gates.',
      },
      {
        text: 'tfsec',
        href: 'https://github.com/aquasecurity/tfsec',
        role: 'Terraform Scanner',
        detailedDescription:
          'tfsec is a static-analysis security scanner focused on Terraform configuration. It checks infrastructure code for common misconfigurations and insecure patterns before resources are deployed. Helix AI can use tfsec for Terraform modules, cloud-resource reviews, infrastructure pull requests, and defense-in-depth alongside broader IaC scanners.',
      },
      {
        text: 'Kubescape',
        href: 'https://kubescape.io/',
        role: 'Kubernetes Security Scanner',
        detailedDescription:
          'Kubescape is a Kubernetes security platform for scanning clusters, manifests, workloads, RBAC, images, and configurations against security frameworks and best practices. It can help identify cluster risk and workload misconfiguration. Helix AI can use Kubescape for Kubernetes posture management, pre-deployment checks, cluster audits, RBAC review, and security dashboards.',
      },
      {
        text: 'kube-hunter',
        href: 'https://github.com/aquasecurity/kube-hunter',
        role: 'Kubernetes Pen-Test Scanner',
        detailedDescription:
          'kube-hunter is a Kubernetes penetration-testing tool that looks for exposed services, risky cluster configurations, and known security weaknesses. It is useful for controlled security assessments of Kubernetes environments. Helix AI can use kube-hunter carefully in lab or approved environments to validate cluster exposure and hardening assumptions.',
      },
      {
        text: 'Falco',
        href: 'https://falco.org/',
        role: 'Runtime Threat Detection',
        detailedDescription:
          'Falco is a cloud-native runtime security tool that detects suspicious behavior from Linux systems, containers, Kubernetes workloads, and cloud-native environments. It can observe system calls and events to identify unexpected activity at runtime. Helix AI can use Falco for runtime threat detection, workload behavior monitoring, container escape signals, suspicious process activity, and Kubernetes security alerts.',
      },
      {
        text: 'CrowdSec',
        href: 'https://www.crowdsec.net/',
        role: 'Collaborative Intrusion Prevention',
        detailedDescription:
          'CrowdSec is a collaborative security engine that detects malicious behavior from logs and signals, then can apply remediation through bouncers and shared intelligence. It is useful for protecting exposed services from abusive traffic and known attack patterns. Helix AI can use CrowdSec for edge protection, homelab security, SSH and web-service defense, and community-informed blocking workflows.',
      },
      {
        text: 'Wazuh',
        href: 'https://wazuh.com/',
        role: 'SIEM & XDR Security Platform',
        detailedDescription:
          'Wazuh is an open-source security platform for threat detection, endpoint monitoring, log analysis, file integrity monitoring, vulnerability detection, compliance visibility, and incident response workflows. It is useful for collecting security signals from hosts, containers, cloud environments, and applications into a centralized monitoring and response layer. Helix AI can use Wazuh for SIEM-style visibility, endpoint telemetry, compliance evidence, security alerting, vulnerability reporting, file integrity monitoring, and correlation across infrastructure and application security events.',
      },
      {
        text: 'Kyverno',
        href: 'https://kyverno.io/',
        role: 'Kubernetes Policy Engine',
        detailedDescription:
          'Kyverno is a Kubernetes-native policy engine that can validate, mutate, generate, and clean up Kubernetes resources using policies expressed as Kubernetes resources. It supports admission control and supply-chain-style checks such as image verification depending on configuration. Helix AI can use Kyverno for namespace hardening, required labels, image policies, gateway rules, security baselines, and GitOps-enforced platform controls.',
      },
      {
        text: 'Gatekeeper',
        href: 'https://open-policy-agent.github.io/gatekeeper/',
        role: 'Kubernetes Admission Controller',
        detailedDescription:
          'Gatekeeper is a Kubernetes admission controller for enforcing constraints over Kubernetes resources. It helps teams define reusable guardrails for admission control, cluster configuration, security baselines, and compliance policy enforcement. Helix AI can use Gatekeeper where strict Kubernetes admission control, organization-wide policy checks, and compliance enforcement are required.',
      },
      {
        text: 'Renovate',
        href: 'https://github.com/renovatebot/renovate',
        role: 'Dependency Update Automation',
        detailedDescription:
          'Renovate automates dependency updates by scanning repositories and opening pull requests for package, container image, GitHub Action, Helm chart, Dockerfile, and infrastructure dependency changes. It is highly configurable and works well in monorepos. Helix AI can use Renovate for dependency hygiene, automated update PRs, release grouping, security updates, and long-term maintenance workflows.',
      },
      {
        text: 'Dependabot',
        href: 'https://github.com/dependabot',
        role: 'Dependency & Security PR Bot',
        detailedDescription:
          'Dependabot helps keep dependencies updated by opening pull requests for version updates and known security vulnerabilities in supported ecosystems. It integrates closely with GitHub repositories and dependency alerts. Helix AI can use Dependabot for GitHub-native dependency maintenance, security patches, lockfile updates, and repository automation.',
      },
      {
        text: 'Snyk',
        href: 'https://snyk.io/',
        role: 'Vulnerability & License Scanning',
        detailedDescription:
          'Snyk provides developer-focused security tools for scanning open-source dependencies, containers, infrastructure-as-code, code, and license risk. It can integrate into developer workflows, CI/CD pipelines, and repository platforms. Helix AI can use Snyk where teams want commercial vulnerability intelligence, developer remediation guidance, license visibility, and platform-level security reporting.',
      },
      {
        text: 'Mend',
        href: 'https://www.mend.io/',
        role: 'Software Composition Analysis',
        detailedDescription:
          'Mend provides software supply-chain and application security tooling focused on dependency risk, open-source vulnerabilities, license compliance, container security, and remediation workflows. It is often used by organizations that need governance around third-party code. Helix AI can use Mend-style tooling for enterprise dependency visibility, compliance reporting, license management, and remediation workflows.',
      },
      {
        text: 'Mend Bolt for GitHub',
        href: 'https://github.com/marketplace/mend',
        role: 'SCA GitHub App',
        detailedDescription:
          'Mend Bolt for GitHub is a GitHub Marketplace app for surfacing open-source vulnerability and license information in repository workflows. It can help teams understand risk in pull requests and dependency changes. Helix AI can use this kind of GitHub-integrated SCA workflow for repository security visibility and developer-facing remediation feedback.',
      },
      {
        text: 'GitHub Advanced Security',
        href: 'https://github.com/features/security',
        role: 'Code & Secret Scanning',
        detailedDescription:
          'GitHub Advanced Security provides security features such as code scanning, secret scanning, dependency review, and security insights for GitHub repositories. It integrates with pull requests and repository workflows to surface issues close to developers. Helix AI can use GitHub Advanced Security for CodeQL scanning, leaked-secret detection, dependency review, organization security reporting, and secure development workflows.',
      },
      {
        text: 'The Update Framework',
        href: 'https://theupdateframework.io/',
        role: 'Secure Artifact Delivery',
        detailedDescription:
          'The Update Framework is a specification and framework for securing software-update systems against common supply-chain attacks. It uses signed metadata, role separation, expiration, and delegation patterns to improve trust in software delivery. Helix AI can use TUF concepts and Notary-style workflows for secure artifact distribution, update verification, plugin marketplace safety, and signed release channels.',
      },
    ],
    image: '/images/technology/security.png',
    link: '/technology/security',
    buttonText: 'Explore security',
  },
] as const satisfies ReadonlyCardArray;

/**
 * Backwards-compatible PascalCase export.
 *
 * Prefer `securityCards` for new imports.
 */
export const SecurityCards = securityCards;