# These funding links power GitHub's "Sponsor" button.
# GitHub expects this file at: .github/FUNDING.yml

github:
  - SinLess-Games
  - Sinless777

custom:
  - "https://aerealith.com"
  - "https://sinlessgamesllc.com"

patreon: sinlessgames
ko_fi: sinlessgames
