// .github/scripts/utils/validators/dependency-rules.schema.js
// =============================================================================
// Aerealith AI Dependency Rules JSON Schema
// -----------------------------------------------------------------------------
// Purpose:
//   JSON Schema definition for `.github/repo-management/dependency-rules.yaml`.
//
// Used by:
//   - .github/scripts/repo/validate-configs.js
//   - .github/scripts/repo/assign-labels.js
//   - .github/scripts/repo/assign-milestones.js
//   - .github/scripts/repo/enforce-pr-rules.js
//   - .github/scripts/repo/run-repo-management.js
//   - .github/scripts/security/summarize-dependencies.js
//   - .github/scripts/security/create-security-issues.js
//   - .github/scripts/security/run-policy-gate.js
//   - .github/scripts/release/validate-release-source.js
//   - .github/scripts/utils/config-loaders/dependency-rules.js
//
// Notes:
//   - This schema validates dependency automation policy shape only.
//   - Runtime policy decisions still belong in the loader/evaluator.
//   - Dependency automation must never trigger releases.
//   - Security patches may auto-merge only after strict checks pass.
//   - Attestations are not generated by dependency workflows.
// =============================================================================

const REGEX_STRING = {
  type: "string",
  minLength: 1,
  description: "A JavaScript-compatible regular expression string.",
};

const STRING_ARRAY = {
  type: "array",
  items: {
    type: "string",
    minLength: 1,
  },
  uniqueItems: true,
  default: [],
};

const LABEL_NAME = {
  type: "string",
  minLength: 1,
  maxLength: 100,
};

const LABEL_ARRAY = {
  type: "array",
  items: LABEL_NAME,
  uniqueItems: true,
  default: [],
};

const GITHUB_LOGIN = {
  type: "string",
  minLength: 1,
  pattern: "^[A-Za-z0-9-]+(\\[bot\\])?$",
};

const LOGIN_ARRAY = {
  type: "array",
  items: GITHUB_LOGIN,
  uniqueItems: true,
  default: [],
};

const BRANCH_PATTERN_ARRAY = {
  type: "array",
  items: REGEX_STRING,
  uniqueItems: true,
  default: [],
};

const GLOB_ARRAY = {
  type: "array",
  items: {
    type: "string",
    minLength: 1,
  },
  uniqueItems: true,
  default: [],
};

const CHECK_ARRAY = {
  type: "array",
  items: {
    type: "string",
    minLength: 1,
  },
  uniqueItems: true,
  default: [],
};

const UPDATE_TYPE = {
  type: "string",
  enum: [
    "major",
    "minor",
    "patch",
    "digest",
    "pin",
    "pinDigest",
    "rollback",
    "bump",
    "lockfile",
    "security_patch",
  ],
};

const UPDATE_TYPE_ARRAY = {
  type: "array",
  items: UPDATE_TYPE,
  uniqueItems: true,
  default: [],
};

const DEPENDENCY_TYPE = {
  type: "string",
  enum: [
    "production",
    "development",
    "optional",
    "peer",
    "engines",
    "packageManager",
    "github-actions",
    "docker",
    "unknown",
  ],
};

const MANAGER_ARRAY = {
  type: "array",
  items: {
    type: "string",
    enum: [
      "npm",
      "pnpm",
      "github-actions",
      "dockerfile",
      "docker-compose",
      "regex",
      "custom.regex",
      "nvm",
      "node",
      "unknown",
    ],
  },
  uniqueItems: true,
  default: [],
};

const SEVERITY = {
  type: "string",
  enum: ["critical", "high", "medium", "moderate", "low", "warning", "unknown"],
};

const SEVERITY_ARRAY = {
  type: "array",
  items: SEVERITY,
  uniqueItems: true,
  default: [],
};

const LICENSE_ARRAY = {
  type: "array",
  items: {
    type: "string",
    minLength: 1,
  },
  uniqueItems: true,
  default: [],
};

const RULE_ACTION = {
  type: "string",
  enum: ["off", "warn", "fail", "label", "comment", "block"],
  default: "warn",
};

const POLICY_BLOCK = {
  type: "object",
  additionalProperties: false,
  properties: {
    description: {
      type: ["string", "null"],
      default: null,
    },
    labels: LABEL_ARRAY,
    automerge_allowed: {
      type: "boolean",
      default: false,
    },
    review_required: {
      type: "boolean",
      default: false,
    },
    review_required_for_major: {
      type: "boolean",
      default: false,
    },
    dependency_dashboard_approval_required: {
      type: "boolean",
      default: false,
    },
    minimum_release_age: {
      type: ["string", "null"],
      default: null,
    },
    milestone: {
      type: ["string", "null"],
      default: null,
    },
  },
  default: {},
};

const SEVERITY_POLICY_BLOCK = {
  type: "object",
  additionalProperties: false,
  properties: {
    block_merge: {
      type: "boolean",
      default: false,
    },
    block_release: {
      type: "boolean",
      default: false,
    },
    block_deploy: {
      type: "boolean",
      default: false,
    },
    create_issue: {
      type: "boolean",
      default: false,
    },
    priority_label: {
      type: ["string", "null"],
      default: null,
    },
    severity_label: {
      type: ["string", "null"],
      default: null,
    },
  },
  default: {},
};

const DEPENDENCY_RULES_SCHEMA = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://github.com/SinLess-Games/Aerealith-AI/schemas/dependency-rules.schema.json",
  title: "Aerealith AI Dependency Rules",
  description: "Schema for .github/repo-management/dependency-rules.yaml.",
  type: "object",
  additionalProperties: false,

  required: [
    "version",
    "repository",
    "tooling",
    "automation_tools",
    "dependency_pull_requests",
    "dependency_types",
    "update_types",
    "security_updates",
    "auto_merge",
    "manual_review",
    "package_groups",
    "path_rules",
    "required_checks",
    "security_gates",
    "release_exclusion",
    "schedules",
    "groups",
    "issue_creation",
    "comments",
    "enforcement",
    "safety",
  ],

  properties: {
    version: {
      type: "integer",
      minimum: 1,
      default: 1,
    },

    repository: {
      type: "object",
      additionalProperties: false,
      required: ["owner", "name", "default_branch"],
      properties: {
        owner: {
          type: "string",
          minLength: 1,
          default: "SinLess-Games",
        },
        name: {
          type: "string",
          minLength: 1,
          default: "Aerealith-AI",
        },
        full_name: {
          type: "string",
          minLength: 1,
          default: "SinLess-Games/Aerealith-AI",
        },
        default_branch: {
          type: "string",
          const: "main",
          default: "main",
        },
      },
    },

    tooling: {
      type: "object",
      additionalProperties: false,
      properties: {
        package_manager: {
          type: "string",
          const: "pnpm",
          default: "pnpm",
        },
        pnpm_version: {
          type: "string",
          default: "10.23.0",
        },
        node_version: {
          type: "string",
          default: "24.15.0",
        },
        monorepo_tool: {
          type: "string",
          const: "nx",
          default: "nx",
        },
        primary_language: {
          type: "string",
          default: "TypeScript",
        },
      },
      default: {},
    },

    automation_tools: {
      type: "object",
      additionalProperties: {
        type: "object",
        additionalProperties: false,
        properties: {
          enabled: {
            type: "boolean",
            default: true,
          },
          role: {
            type: ["string", "null"],
            default: null,
          },
          config_file: {
            type: ["string", "null"],
            default: null,
          },
          branch_patterns: BRANCH_PATTERN_ARRAY,
          authors: LOGIN_ARRAY,
          labels: LABEL_ARRAY,
        },
      },
      properties: {
        renovate: {
          type: "object",
          additionalProperties: false,
          properties: {
            enabled: {
              type: "boolean",
              default: true,
            },
            role: {
              type: ["string", "null"],
              default: "dependency-update",
            },
            config_file: {
              type: ["string", "null"],
              default: ".github/renovate.json5",
            },
            branch_patterns: BRANCH_PATTERN_ARRAY,
            authors: LOGIN_ARRAY,
            labels: LABEL_ARRAY,
          },
          default: {},
        },
        dependabot: {
          type: "object",
          additionalProperties: false,
          properties: {
            enabled: {
              type: "boolean",
              default: true,
            },
            role: {
              type: ["string", "null"],
              default: "security-and-actions-update",
            },
            config_file: {
              type: ["string", "null"],
              default: ".github/dependabot.yaml",
            },
            branch_patterns: BRANCH_PATTERN_ARRAY,
            authors: LOGIN_ARRAY,
            labels: LABEL_ARRAY,
          },
          default: {},
        },
        mend: {
          type: "object",
          additionalProperties: false,
          properties: {
            enabled: {
              type: "boolean",
              default: true,
            },
            role: {
              type: ["string", "null"],
              default: "security-management",
            },
            config_file: {
              type: ["string", "null"],
              default: null,
            },
            branch_patterns: BRANCH_PATTERN_ARRAY,
            authors: LOGIN_ARRAY,
            labels: LABEL_ARRAY,
          },
          default: {},
        },
      },
      default: {},
    },

    dependency_pull_requests: {
      type: "object",
      additionalProperties: false,
      properties: {
        release_allowed: {
          type: "boolean",
          default: false,
        },

        required_labels: LABEL_ARRAY,
        recommended_labels: LABEL_ARRAY,
        release_blocking_labels: LABEL_ARRAY,
        release_labels_forbidden: LABEL_ARRAY,

        allowed_base_branches: STRING_ARRAY,
        allowed_authors: LOGIN_ARRAY,
        allowed_branch_patterns: BRANCH_PATTERN_ARRAY,

        require_linked_issue: {
          type: "boolean",
          default: false,
        },
        require_milestone: {
          type: "boolean",
          default: true,
        },
        default_milestone: {
          type: "string",
          default: "Dependencies — Renovate Weekly Updates",
        },

        title_prefixes: {
          type: "object",
          additionalProperties: false,
          properties: {
            allowed: STRING_ARRAY,
          },
          default: {},
        },

        body_requirements: {
          type: "object",
          additionalProperties: false,
          properties: {
            require_update_summary: {
              type: "boolean",
              default: true,
            },
            require_package_list: {
              type: "boolean",
              default: true,
            },
            require_release_note_summary: {
              type: "boolean",
              default: false,
            },
            require_security_context_for_security_updates: {
              type: "boolean",
              default: true,
            },
          },
          default: {},
        },
      },
      default: {},
    },

    dependency_types: {
      type: "object",
      additionalProperties: POLICY_BLOCK,
      properties: {
        production: POLICY_BLOCK,
        development: POLICY_BLOCK,
        optional: POLICY_BLOCK,
        peer: POLICY_BLOCK,
        github_actions: POLICY_BLOCK,
        docker: POLICY_BLOCK,
        lockfile: POLICY_BLOCK,
      },
      default: {},
    },

    update_types: {
      type: "object",
      additionalProperties: POLICY_BLOCK,
      properties: {
        patch: POLICY_BLOCK,
        minor: POLICY_BLOCK,
        major: POLICY_BLOCK,
        digest: POLICY_BLOCK,
        pin: POLICY_BLOCK,
        lockfile: POLICY_BLOCK,
        security_patch: POLICY_BLOCK,
      },
      default: {},
    },

    security_updates: {
      type: "object",
      additionalProperties: false,
      properties: {
        enabled: {
          type: "boolean",
          default: true,
        },
        release_allowed: {
          type: "boolean",
          default: false,
        },
        default_milestone: {
          type: "string",
          default: "Security — Dependency Vulnerability Response",
        },
        labels: LABEL_ARRAY,

        automerge_allowed: {
          type: "boolean",
          default: true,
        },
        review_required: {
          type: "boolean",
          default: false,
        },

        require_all_checks: {
          type: "boolean",
          default: true,
        },
        require_security_gate: {
          type: "boolean",
          default: true,
        },
        require_dependency_review: {
          type: "boolean",
          default: true,
        },
        require_codeql: {
          type: "boolean",
          default: true,
        },
        require_sonarqube: {
          type: "boolean",
          default: true,
        },

        block_if_exploit_known: {
          type: "boolean",
          default: false,
        },
        create_security_issue_for_failed_patch: {
          type: "boolean",
          default: true,
        },
        create_security_issue_for_unpatchable_alert: {
          type: "boolean",
          default: true,
        },

        severity_policy: {
          type: "object",
          additionalProperties: SEVERITY_POLICY_BLOCK,
          properties: {
            critical: SEVERITY_POLICY_BLOCK,
            high: SEVERITY_POLICY_BLOCK,
            medium: SEVERITY_POLICY_BLOCK,
            moderate: SEVERITY_POLICY_BLOCK,
            low: SEVERITY_POLICY_BLOCK,
          },
          default: {},
        },

        security_issue_template: {
          type: "object",
          additionalProperties: false,
          properties: {
            title: {
              type: "string",
              default: "[Security]: Dependency vulnerability",
            },
            labels: LABEL_ARRAY,
            milestone: {
              type: "string",
              default: "Security — Dependency Vulnerability Response",
            },
          },
          default: {},
        },
      },
      default: {},
    },

    auto_merge: {
      type: "object",
      additionalProperties: false,
      properties: {
        enabled: {
          type: "boolean",
          default: true,
        },
        strategy: {
          type: "string",
          enum: ["merge", "squash", "rebase"],
          default: "merge",
        },

        allowed_pr_types: UPDATE_TYPE_ARRAY,
        allowed_authors: LOGIN_ARRAY,
        allowed_branch_patterns: BRANCH_PATTERN_ARRAY,

        required_labels: LABEL_ARRAY,
        required_any_labels: LABEL_ARRAY,
        required_absent_labels: LABEL_ARRAY,

        required_checks: CHECK_ARRAY,
        required_status: CHECK_ARRAY,

        require_branch_up_to_date: {
          type: "boolean",
          default: true,
        },
        require_no_requested_changes: {
          type: "boolean",
          default: true,
        },
        require_no_conflicts: {
          type: "boolean",
          default: true,
        },

        allow_patch: {
          type: "boolean",
          default: true,
        },
        allow_minor: {
          type: "boolean",
          default: true,
        },
        allow_major: {
          type: "boolean",
          default: false,
        },
        allow_security_patch: {
          type: "boolean",
          default: true,
        },
        allow_lockfile: {
          type: "boolean",
          default: true,
        },

        block_if_files_changed: GLOB_ARRAY,
        manual_review_required_if_files_changed: GLOB_ARRAY,
      },
      default: {},
    },

    manual_review: {
      type: "object",
      additionalProperties: false,
      properties: {
        required_for: {
          type: "object",
          additionalProperties: false,
          properties: {
            update_types: UPDATE_TYPE_ARRAY,
            package_groups: STRING_ARRAY,
            labels: LABEL_ARRAY,
          },
          default: {},
        },
        labels_to_add: LABEL_ARRAY,
        milestone: {
          type: ["string", "null"],
          default: null,
        },
      },
      default: {},
    },

    package_groups: {
      type: "object",
      additionalProperties: {
        type: "object",
        additionalProperties: false,
        properties: {
          description: {
            type: ["string", "null"],
            default: null,
          },
          match_package_names: GLOB_ARRAY,
          managers: MANAGER_ARRAY,
          labels: LABEL_ARRAY,
          automerge_allowed: {
            type: "boolean",
            default: false,
          },
          review_required: {
            type: "boolean",
            default: false,
          },
          review_required_for_major: {
            type: "boolean",
            default: false,
          },
          milestone: {
            type: ["string", "null"],
            default: null,
          },
        },
      },
      default: {},
    },

    path_rules: {
      type: "object",
      additionalProperties: {
        type: "object",
        additionalProperties: false,
        properties: {
          patterns: GLOB_ARRAY,
          labels: LABEL_ARRAY,
          milestone: {
            type: ["string", "null"],
            default: null,
          },
          automerge_allowed: {
            type: ["boolean", "null"],
            default: null,
          },
        },
      },
      default: {},
    },

    required_checks: {
      type: "object",
      additionalProperties: CHECK_ARRAY,
      properties: {
        dependency_pr: CHECK_ARRAY,
        dependency_auto_merge: CHECK_ARRAY,
        security_dependency_pr: CHECK_ARRAY,
        security_patch_auto_merge: CHECK_ARRAY,
        release_eligibility: CHECK_ARRAY,
        security_gate: CHECK_ARRAY,
        codeql: CHECK_ARRAY,
        sonarqube: CHECK_ARRAY,
        dependency_review: CHECK_ARRAY,
        pnpm_audit: CHECK_ARRAY,
      },
      default: {},
    },

    security_gates: {
      type: "object",
      additionalProperties: false,
      properties: {
        strict: {
          type: "boolean",
          default: true,
        },

        block_merge_on: {
          type: "object",
          additionalProperties: false,
          properties: {
            vulnerabilities: SEVERITY_ARRAY,
            codeql: SEVERITY_ARRAY,
            sonarqube_quality_gate_failed: {
              type: "boolean",
              default: true,
            },
            dependency_review_failed: {
              type: "boolean",
              default: true,
            },
            secret_findings: {
              type: "boolean",
              default: true,
            },
            disallowed_licenses: {
              type: "boolean",
              default: true,
            },
            malicious_packages: {
              type: "boolean",
              default: true,
            },
          },
          default: {},
        },

        warn_on: {
          type: "object",
          additionalProperties: false,
          properties: {
            vulnerabilities: SEVERITY_ARRAY,
          },
          default: {},
        },

        licenses: {
          type: "object",
          additionalProperties: false,
          properties: {
            enabled: {
              type: "boolean",
              default: true,
            },
            block_unknown_license: {
              type: "boolean",
              default: false,
            },
            forbidden: LICENSE_ARRAY,
            allowed: LICENSE_ARRAY,
          },
          default: {},
        },

        dependency_review: {
          type: "object",
          additionalProperties: false,
          properties: {
            fail_on_severity: SEVERITY_ARRAY,
          },
          default: {},
        },

        pnpm_audit: {
          type: "object",
          additionalProperties: false,
          properties: {
            enabled: {
              type: "boolean",
              default: true,
            },
            fail_on: SEVERITY_ARRAY,
            warn_on: SEVERITY_ARRAY,
          },
          default: {},
        },

        container_scanning: {
          type: "object",
          additionalProperties: false,
          properties: {
            enabled: {
              type: "boolean",
              default: true,
            },
            fail_on: SEVERITY_ARRAY,
            warn_on: SEVERITY_ARRAY,
          },
          default: {},
        },
      },
      default: {},
    },

    release_exclusion: {
      type: "object",
      additionalProperties: false,
      properties: {
        enabled: {
          type: "boolean",
          default: true,
        },

        dependency_changes_never_release: {
          type: "boolean",
          default: true,
        },
        security_dependency_changes_never_release: {
          type: "boolean",
          default: true,
        },
        lockfile_only_changes_never_release: {
          type: "boolean",
          default: true,
        },
        github_actions_dependency_changes_never_release: {
          type: "boolean",
          default: true,
        },

        block_release_if_author: LOGIN_ARRAY,
        block_release_if_branch_matches: BRANCH_PATTERN_ARRAY,
        block_release_if_labels_present: LABEL_ARRAY,

        remove_release_labels_if_present: {
          type: "boolean",
          default: true,
        },
        release_labels_to_remove: LABEL_ARRAY,
      },
      default: {},
    },

    schedules: {
      type: "object",
      additionalProperties: {
        type: "object",
        additionalProperties: true,
        properties: {
          normal_updates: {
            type: "object",
            additionalProperties: false,
            properties: {
              description: {
                type: ["string", "null"],
                default: null,
              },
              schedule: STRING_ARRAY,
            },
            default: {},
          },
          lockfile_maintenance: {
            type: "object",
            additionalProperties: false,
            properties: {
              description: {
                type: ["string", "null"],
                default: null,
              },
              schedule: STRING_ARRAY,
            },
            default: {},
          },
          triggers: STRING_ARRAY,
        },
      },
      default: {},
    },

    groups: {
      type: "object",
      additionalProperties: {
        type: "object",
        additionalProperties: false,
        properties: {
          managers: MANAGER_ARRAY,
          update_types: UPDATE_TYPE_ARRAY,
          labels: LABEL_ARRAY,
          security: {
            type: "boolean",
            default: false,
          },
        },
      },
      default: {},
    },

    issue_creation: {
      type: "object",
      additionalProperties: false,
      properties: {
        enabled: {
          type: "boolean",
          default: true,
        },

        create_issue_for: STRING_ARRAY,

        repeated_failure_threshold: {
          type: "integer",
          minimum: 1,
          default: 3,
        },

        default_labels: LABEL_ARRAY,
        security_labels: LABEL_ARRAY,

        default_assignees: LOGIN_ARRAY,

        default_milestone: {
          type: ["string", "null"],
          default: null,
        },
        security_milestone: {
          type: ["string", "null"],
          default: null,
        },
        major_upgrade_milestone: {
          type: ["string", "null"],
          default: null,
        },
      },
      default: {},
    },

    comments: {
      type: "object",
      additionalProperties: false,
      properties: {
        enabled: {
          type: "boolean",
          default: true,
        },

        add_pr_comment_on_policy_failure: {
          type: "boolean",
          default: true,
        },
        add_pr_comment_on_release_exclusion: {
          type: "boolean",
          default: true,
        },
        add_pr_comment_on_auto_merge_blocked: {
          type: "boolean",
          default: true,
        },
        add_workflow_summary: {
          type: "boolean",
          default: true,
        },

        comment_footer: {
          type: "object",
          additionalProperties: false,
          properties: {
            start: {
              type: ["string", "null"],
              default: "<!-- aerealith-dependency-rules:start -->",
            },
            end: {
              type: ["string", "null"],
              default: "<!-- aerealith-dependency-rules:end -->",
            },
          },
          default: {},
        },

        summary: {
          type: "object",
          additionalProperties: {
            type: "boolean",
          },
          default: {},
        },
      },
      default: {},
    },

    enforcement: {
      type: "object",
      additionalProperties: {
        type: "object",
        additionalProperties: false,
        properties: {
          action: RULE_ACTION,
          label: {
            type: ["string", "null"],
            default: null,
          },
          labels: LABEL_ARRAY,
          message: {
            type: ["string", "null"],
            default: null,
          },
        },
      },
      properties: {
        missing_dependency_labels: {
          type: "object",
          additionalProperties: false,
          properties: {
            action: RULE_ACTION,
            label: {
              type: ["string", "null"],
              default: "dependencies",
            },
            labels: LABEL_ARRAY,
            message: {
              type: ["string", "null"],
              default:
                "Dependency pull requests must include dependency labels.",
            },
          },
          default: {},
        },

        release_label_on_dependency_pr: {
          type: "object",
          additionalProperties: false,
          properties: {
            action: RULE_ACTION,
            label: {
              type: ["string", "null"],
              default: "no-release",
            },
            labels: LABEL_ARRAY,
            message: {
              type: ["string", "null"],
              default:
                "Dependency pull requests must not carry release labels.",
            },
          },
          default: {},
        },

        dependency_auto_merge_blocked: {
          type: "object",
          additionalProperties: false,
          properties: {
            action: RULE_ACTION,
            label: {
              type: ["string", "null"],
              default: "automation:needs-review",
            },
            labels: LABEL_ARRAY,
            message: {
              type: ["string", "null"],
              default: "Dependency auto-merge is blocked by policy.",
            },
          },
          default: {},
        },

        failed_security_gate: {
          type: "object",
          additionalProperties: false,
          properties: {
            action: RULE_ACTION,
            label: {
              type: ["string", "null"],
              default: "blocked-by-security",
            },
            labels: LABEL_ARRAY,
            message: {
              type: ["string", "null"],
              default: "Security gate failed for dependency pull request.",
            },
          },
          default: {},
        },
      },
      default: {},
    },

    safety: {
      type: "object",
      additionalProperties: false,
      properties: {
        dry_run_supported: {
          type: "boolean",
          default: true,
        },
        debug_supported: {
          type: "boolean",
          default: true,
        },

        do_not_push_to_main: {
          type: "boolean",
          default: true,
        },
        do_not_create_release: {
          type: "boolean",
          default: true,
        },
        do_not_publish_npm: {
          type: "boolean",
          default: true,
        },
        do_not_publish_containers: {
          type: "boolean",
          default: true,
        },
        do_not_deploy_production: {
          type: "boolean",
          default: true,
        },

        do_not_auto_merge_if_unknown_author: {
          type: "boolean",
          default: true,
        },
        do_not_auto_merge_if_missing_required_checks: {
          type: "boolean",
          default: true,
        },
        do_not_auto_merge_if_security_gate_failed: {
          type: "boolean",
          default: true,
        },
        do_not_auto_merge_if_review_requested: {
          type: "boolean",
          default: true,
        },
        do_not_auto_merge_if_conflicts: {
          type: "boolean",
          default: true,
        },
        do_not_auto_merge_if_release_label_present: {
          type: "boolean",
          default: true,
        },

        protected_labels: LABEL_ARRAY,
        labels_to_never_remove_automatically: LABEL_ARRAY,
        labels_to_force_on_dependency_prs: LABEL_ARRAY,
        labels_to_force_on_security_dependency_prs: LABEL_ARRAY,
      },
      default: {},
    },
  },
};

function getDependencyRulesSchema() {
  return DEPENDENCY_RULES_SCHEMA;
}

module.exports = {
  DEPENDENCY_RULES_SCHEMA,
  schema: DEPENDENCY_RULES_SCHEMA,
  getDependencyRulesSchema,

  REGEX_STRING,
  STRING_ARRAY,
  LABEL_NAME,
  LABEL_ARRAY,
  GITHUB_LOGIN,
  LOGIN_ARRAY,
  BRANCH_PATTERN_ARRAY,
  GLOB_ARRAY,
  CHECK_ARRAY,
  UPDATE_TYPE,
  UPDATE_TYPE_ARRAY,
  DEPENDENCY_TYPE,
  MANAGER_ARRAY,
  SEVERITY,
  SEVERITY_ARRAY,
  LICENSE_ARRAY,
  RULE_ACTION,
  POLICY_BLOCK,
  SEVERITY_POLICY_BLOCK,
};
