import type { PolicyDocument } from '../../types';

export const aiTransparencyPolicy = {
  slug: 'ai-transparency',
  path: '/Policies/ai-transparency',
  meta: {
    title: 'AI Transparency Policy',
    description:
      'Explains how Aerealith AI uses artificial intelligence, automation, memory, tools, and human oversight.',
    effectiveDate: '2026-05-18',
    lastUpdated: '2026-05-18',
    owner: 'SinLess Games LLC',
    status: 'draft',
  },
  relatedPolicies: [
    {
      label: 'Terms of Use',
      href: '/Policies/terms-of-use',
    },
    {
      label: 'Privacy Policy',
      href: '/Policies/privacy-policy',
    },
    {
      label: 'Data Policy',
      href: '/Policies/data-policy',
    },
    {
      label: 'Security Policy',
      href: '/Policies/security-policy',
    },
    {
      label: 'Acceptable Use Policy',
      href: '/Policies/acceptable-use',
    },
    {
      label: 'Responsible AI Policy',
      href: '/Policies/responsible-ai',
    },
    {
      label: 'User-Generated Content Policy',
      href: '/Policies/user-generated-content',
    },
    {
      label: 'Copyright Takedown Policy',
      href: '/Policies/copyright-takedown',
    },
    {
      label: 'Underage Policy',
      href: '/Policies/underage',
    },
    {
      label: 'Subprocessor Vendor List',
      href: '/Policies/subprocessor-vendor-list',
    },
    {
      label: 'Support Policy',
      href: '/Policies/support',
    },
  ],
  sections: [
    {
      id: 'purpose',
      title: '1. Purpose',
      body: [
        'This AI Transparency Policy explains how Aerealith AI uses artificial intelligence, automation, memory, integrations, tools, and generated outputs.',
        'Aerealith AI is designed to help users think, create, automate, analyze, monitor, and act across connected systems. Because AI systems can produce inaccurate, incomplete, biased, or unexpected results, this policy explains what users should expect, what Aerealith AI can and cannot do, and when human review is required.',
        'This policy is intended to support transparency, user control, responsible use, and informed decision-making.',
      ],
    },
    {
      id: 'scope',
      title: '2. Scope',
      body: [
        'This policy applies to Aerealith AI, including:',
        'This policy applies to individual users, organizations, developers, administrators, and anyone using Aerealith AI through an account, workspace, API key, integration, shared agent, embedded assistant, or connected service.',
      ],
      bullets: [
        'Web, desktop, mobile, browser, terminal, and API experiences',
        'AI chat, assistant, agent, and automation features',
        'Memory and personalization features',
        'Search, retrieval, summarization, and analysis features',
        'Tool use and connected integrations',
        'Plugins, workflows, dashboards, templates, personalities, and marketplace items',
        'Cloud-hosted, self-hosted, hybrid, and air-gapped deployments, where applicable',
      ],
    },
    {
      id: 'what-aerealith-ai-is',
      title: '3. What Aerealith AI Is',
      body: [
        'Aerealith AI is an artificial intelligence assistant platform operated by SinLess Games LLC.',
        'Aerealith AI may help users:',
        'Aerealith AI is not a human, attorney, doctor, financial advisor, accountant, therapist, emergency responder, government official, or licensed professional.',
      ],
      bullets: [
        'Draft, rewrite, summarize, and organize content',
        'Analyze files, messages, code, logs, events, and structured data',
        'Generate ideas, plans, checklists, workflows, and documentation',
        'Search, retrieve, compare, and explain information',
        'Create dashboards, reports, and operational summaries',
        'Assist with development, infrastructure, automation, and technical workflows',
        'Execute approved actions through connected tools, plugins, and integrations',
        'Personalize responses based on user-controlled preferences and memory',
      ],
    },
    {
      id: 'no-claim-of-human-status-or-sentience',
      title: '4. No Claim of Human Status or Sentience',
      body: [
        'Aerealith AI may use natural language, memory, personas, tone settings, and assistant identities to provide a more helpful experience.',
        'However:',
        'Any references to assistant identity, personality, memory, continuity, or companionship are product features and should not be understood as proof of sentience or human status.',
      ],
      bullets: [
        'Aerealith AI is not human.',
        'Aerealith AI is not sentient.',
        'Aerealith AI does not have personal feelings, consciousness, legal personhood, or independent rights.',
        'Aerealith AI may model empathy behaviorally, but it does not experience emotions.',
        'Aerealith AI may use a name, voice, avatar, or persona, but these are interface and personalization features.',
        'Aerealith AI does not replace the user’s judgment, responsibility, or legal obligations.',
      ],
    },
    {
      id: 'ai-generated-output',
      title: '5. AI-Generated Output',
      body: [
        'Aerealith AI may generate text, code, summaries, recommendations, classifications, plans, images, structured data, reports, or other outputs.',
        'AI-generated output may be:',
        'Users are responsible for reviewing, validating, testing, and approving AI-generated output before relying on it, publishing it, deploying it, sending it, or using it to make decisions.',
      ],
      bullets: [
        'Incorrect',
        'Incomplete',
        'Outdated',
        'Misleading',
        'Biased',
        'Inconsistent',
        'Unsuitable for a specific use case',
        'Based on incomplete or misunderstood context',
        'Affected by user-provided information, retrieved information, tool results, model limitations, or system constraints',
      ],
    },
    {
      id: 'user-responsibility',
      title: '6. User Responsibility',
      body: [
        'You are responsible for:',
        'Aerealith AI may assist with decision-making, but it should not be treated as the sole source of truth.',
      ],
      bullets: [
        'Reviewing Aerealith AI outputs before use',
        'Verifying facts, numbers, citations, code, configurations, and recommendations',
        'Testing generated code, scripts, automations, infrastructure changes, and workflows',
        'Ensuring your use complies with applicable laws, contracts, policies, and professional obligations',
        'Ensuring you have the right to upload, process, share, or connect data',
        'Confirming that any automated action is authorized, safe, and appropriate',
        'Applying human judgment to high-impact, regulated, sensitive, or irreversible decisions',
      ],
    },
    {
      id: 'human-review-requirements',
      title: '7. Human Review Requirements',
      body: [
        'Human review is required before using Aerealith AI output for:',
        'Organizations may configure additional review requirements, approval gates, audit controls, or restricted-action policies.',
      ],
      bullets: [
        'Legal, medical, financial, tax, insurance, or investment decisions',
        'Employment, hiring, firing, discipline, promotion, or compensation decisions',
        'Housing, education, credit, lending, benefits, eligibility, or essential service decisions',
        'Safety-critical systems or infrastructure',
        'Production infrastructure changes',
        'Security-sensitive changes',
        'Identity, access, permissions, secrets, or credential management',
        'Public statements, official notices, contracts, regulatory filings, or compliance submissions',
        'Actions that may materially affect another person’s rights, safety, privacy, finances, employment, reputation, or access to services',
        'Any irreversible or destructive automation',
      ],
    },
    {
      id: 'professional-advice-disclaimer',
      title: '8. Professional Advice Disclaimer',
      body: [
        'Aerealith AI may help draft, explain, summarize, compare, or organize information related to legal, medical, financial, security, compliance, tax, employment, or business topics.',
        'Aerealith AI does not provide professional advice.',
        'Users should consult a qualified professional before relying on Aerealith AI output for regulated, specialized, or high-impact matters.',
      ],
    },
    {
      id: 'sources-retrieval-and-citations',
      title: '9. Sources, Retrieval, and Citations',
      body: [
        'Aerealith AI may use information from:',
        'When citations, links, source references, or provenance are provided, they are intended to help users verify the answer. Citations do not guarantee that the output is complete, correct, current, or suitable for a particular use.',
        'When no source is provided, users should treat the output as generated assistance that may require independent verification.',
      ],
      bullets: [
        'User-provided prompts',
        'Uploaded files',
        'Connected accounts and integrations',
        'Search tools',
        'Internal documentation',
        'Workspace knowledge bases',
        'Organization-approved sources',
        'Publicly available information',
        'Model training data',
        'Tool and plugin results',
        'Short-term and long-term memory, when enabled',
      ],
    },
    {
      id: 'currentness-and-knowledge-limits',
      title: '10. Currentness and Knowledge Limits',
      body: [
        'Aerealith AI may not always know the latest information.',
        'Information may be outdated when it relates to:',
        'When current accuracy matters, users should request verification using approved live sources or independently confirm the information.',
      ],
      bullets: [
        'Laws, regulations, standards, policies, and compliance requirements',
        'Prices, product availability, subscriptions, and billing terms',
        'Security vulnerabilities and patches',
        'Software versions, APIs, packages, and dependencies',
        'News, public events, elections, weather, sports, and market data',
        'Company policies, vendor terms, or third-party service behavior',
      ],
    },
    {
      id: 'memory-and-personalization',
      title: '11. Memory and Personalization',
      body: [
        'Aerealith AI may support memory and personalization features.',
        'Memory may be used to improve continuity, preferences, context, project awareness, assistant behavior, and user experience.',
        'Depending on user and organization settings, Aerealith AI may remember information such as:',
        'Users and organization administrators may have controls to view, edit, delete, export, pause, disable, scope, or restrict memory, depending on the deployment and subscription.',
        'Aerealith AI should not store sensitive information unless allowed by user settings, organization policy, or explicit user instruction.',
        'Memory behavior is governed by the applicable Privacy Policy, Data Policy, Security Policy, and organization settings.',
      ],
      bullets: [
        'User preferences',
        'Assistant identity settings',
        'Workspace or project context',
        'Organization preferences',
        'Prior decisions',
        'Automation preferences',
        'Repeated workflows',
        'Technical environment details',
        'Communication style preferences',
      ],
      links: [
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy-policy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data-policy',
        },
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
      ],
    },
    {
      id: 'context-use',
      title: '12. Context Use',
      body: [
        'Aerealith AI may use available context to provide better responses.',
        'Context may include:',
        'Aerealith AI may not always use every available piece of context. Some context may be excluded due to privacy settings, permissions, security controls, relevance, size limits, technical limits, or organization restrictions.',
      ],
      bullets: [
        'Current conversation content',
        'Prior conversation summaries',
        'User preferences',
        'Workspace settings',
        'Organization policies',
        'Connected files',
        'Integration results',
        'Tool outputs',
        'System settings',
        'Feature flags',
        'Subscription entitlements',
        'Safety and policy constraints',
      ],
    },
    {
      id: 'tools-integrations-and-automations',
      title: '13. Tools, Integrations, and Automations',
      body: [
        'Aerealith AI may use tools, APIs, plugins, integrations, and automations to perform actions or retrieve information.',
        'Examples may include:',
        'Tool use may require user permission, organization approval, integration authorization, API credentials, or role-based access.',
        'Aerealith AI should not perform high-risk, destructive, irreversible, or sensitive actions without appropriate authorization, confirmation, and logging.',
      ],
      bullets: [
        'Reading files',
        'Searching documents',
        'Summarizing emails',
        'Creating drafts',
        'Scheduling calendar events',
        'Opening support tickets',
        'Generating code',
        'Updating project artifacts',
        'Querying analytics',
        'Monitoring infrastructure',
        'Triggering workflows',
        'Interacting with approved third-party services',
      ],
    },
    {
      id: 'automated-actions',
      title: '14. Automated Actions',
      body: [
        'Some Aerealith AI features may take actions automatically based on user-approved rules, workflows, triggers, schedules, or organization policies.',
        'Automated actions may include:',
        'Users and organizations are responsible for configuring automation safely.',
        'Automation should include reasonable safeguards, such as:',
      ],
      bullets: [
        'Notifications',
        'Summaries',
        'Reports',
        'File organization',
        'Ticket creation',
        'Draft creation',
        'Monitoring checks',
        'Dashboard updates',
        'Workflow execution',
        'Approved system actions',
        'Permission checks',
        'Approval gates',
        'Audit logs',
        'Scope limits',
        'Rate limits',
        'Rollback plans, where practical',
        'Error handling',
        'Human review for sensitive actions',
        'Clear ownership of the automation',
      ],
    },
    {
      id: 'model-routing-and-ai-providers',
      title: '15. Model Routing and AI Providers',
      body: [
        'Aerealith AI may route requests to different models, services, providers, or local systems depending on:',
        'Cloud-hosted deployments may use third-party AI providers or infrastructure providers. Self-hosted or air-gapped deployments may use local or organization-controlled models when configured.',
        'Relevant vendors and subprocessors should be listed in the applicable Subprocessor Vendor List.',
      ],
      bullets: [
        'User settings',
        'Organization settings',
        'Deployment type',
        'Feature availability',
        'Cost and performance requirements',
        'Data sensitivity',
        'Tool requirements',
        'Safety requirements',
        'Subscription plan',
        'System availability',
      ],
      links: [
        {
          label: 'Subprocessor Vendor List',
          href: '/Policies/subprocessor-vendor-list',
        },
      ],
    },
    {
      id: 'data-sent-to-models-and-tools',
      title: '16. Data Sent to Models and Tools',
      body: [
        'Depending on configuration and permissions, Aerealith AI may send relevant portions of user prompts, files, metadata, conversation history, retrieved context, or tool results to AI models or tools to generate a response or complete an action.',
        'Aerealith AI should limit data shared with models and tools to what is reasonably needed for the requested function, subject to technical limitations, product behavior, and user or organization settings.',
        'Users should not provide sensitive, confidential, regulated, or restricted information unless they are authorized to do so and the account, workspace, deployment, and settings are appropriate for that data.',
      ],
    },
    {
      id: 'sensitive-data',
      title: '17. Sensitive Data',
      body: [
        'Sensitive data may include:',
        'Users should avoid entering secrets, credentials, private keys, passwords, or access tokens into prompts unless a feature is specifically designed and approved to handle that information securely.',
        'Secrets should be stored in approved secret-management systems, not in ordinary chat memory or general user content.',
      ],
      bullets: [
        'Government identification numbers',
        'Financial account information',
        'Payment card information',
        'Health information',
        'Legal records',
        'Biometric information',
        'Precise location information',
        'Credentials, passwords, tokens, private keys, and secrets',
        'Confidential business information',
        'Regulated customer data',
        'Children’s data',
        'Data protected by contract, law, or policy',
      ],
    },
    {
      id: 'bias-fairness-and-limitations',
      title: '18. Bias, Fairness, and Limitations',
      body: [
        'AI systems may produce biased, unfair, offensive, or unbalanced output.',
        'Bias may result from:',
        'Users should carefully review AI output, especially when it relates to people, protected characteristics, eligibility, access to services, moderation, enforcement, or high-impact decisions.',
        'Aerealith AI should not be used as the sole basis for decisions that materially affect a person’s rights, safety, employment, housing, credit, education, healthcare, legal status, or access to essential services.',
      ],
      bullets: [
        'Training data',
        'User-provided data',
        'Retrieved sources',
        'Missing context',
        'Model limitations',
        'Prompt wording',
        'Tool results',
        'System configuration',
        'Social, cultural, or historical patterns reflected in data',
      ],
    },
    {
      id: 'content-labeling-and-disclosure',
      title: '19. Content Labeling and Disclosure',
      body: [
        'Users should disclose when content is materially AI-generated or AI-assisted if disclosure is required by law, platform rules, professional standards, contract, organization policy, or reasonable audience expectations.',
        'Disclosure may be especially important for:',
        'Users are responsible for following applicable disclosure rules.',
      ],
      bullets: [
        'Public communications',
        'Journalism or media',
        'Political or civic content',
        'Educational submissions',
        'Legal or professional documents',
        'Customer support',
        'Synthetic media',
        'Images, audio, video, or avatars',
        'Marketplace items',
        'Automated messages',
        'Published reports',
      ],
    },
    {
      id: 'synthetic-media',
      title: '20. Synthetic Media',
      body: [
        'Aerealith AI may support or integrate with tools that generate or edit images, audio, video, avatars, voices, or other synthetic media.',
        'Users may not use synthetic media features to:',
        'Synthetic media should be labeled or disclosed when appropriate.',
      ],
      bullets: [
        'Deceive people about whether content is real',
        'Impersonate someone without authorization',
        'Create non-consensual intimate imagery',
        'Harass, threaten, exploit, or defame others',
        'Create fake official records, evidence, identification, or credentials',
        'Commit fraud, scams, phishing, or social engineering',
        'Mislead people in high-impact, political, emergency, legal, medical, or financial contexts',
      ],
    },
    {
      id: 'logs-auditability-and-monitoring',
      title: '21. Logs, Auditability, and Monitoring',
      body: [
        'Aerealith AI may log certain activity to support:',
        'Logs may include account activity, requests, responses, tool calls, automation actions, system events, error traces, metadata, timestamps, feature usage, and administrative actions.',
        'Access to logs should be limited according to role, permission, security controls, retention settings, and applicable policies.',
      ],
      bullets: [
        'Security',
        'Abuse prevention',
        'Troubleshooting',
        'Billing',
        'Reliability',
        'Compliance',
        'Audit trails',
        'Organization administration',
        'Incident response',
        'Product improvement, where permitted',
      ],
    },
    {
      id: 'organization-controls',
      title: '22. Organization Controls',
      body: [
        'Organizations may configure Aerealith AI with additional controls, including:',
        'Organization administrators are responsible for configuring Aerealith AI appropriately for their users, data, industry, and risk profile.',
      ],
      bullets: [
        'Role-based access controls',
        'Attribute-based access controls',
        'Data retention settings',
        'Memory settings',
        'Approved models',
        'Approved tools',
        'Approved integrations',
        'Marketplace allowlists or blocklists',
        'Automation approval rules',
        'Audit log retention',
        'Data export restrictions',
        'Security policies',
        'Compliance policies',
        'Workspace-level assistant behavior',
        'User permission limits',
      ],
    },
    {
      id: 'self-hosted-and-air-gapped-deployments',
      title: '23. Self-Hosted and Air-Gapped Deployments',
      body: [
        'Self-hosted, hybrid, and air-gapped deployments may behave differently from cloud-hosted Aerealith AI.',
        'Differences may include:',
        'The organization or operator of the deployment is responsible for securing, monitoring, configuring, updating, and governing that deployment.',
      ],
      bullets: [
        'Local model usage',
        'Organization-managed infrastructure',
        'Limited or disabled external search',
        'Limited third-party provider usage',
        'Custom logging and retention',
        'Custom security controls',
        'Custom plugin approval rules',
        'Custom marketplace availability',
        'Custom compliance requirements',
        'Different update schedules',
      ],
    },
    {
      id: 'marketplace-and-third-party-items',
      title: '24. Marketplace and Third-Party Items',
      body: [
        'Aerealith AI may support marketplace items, plugins, integrations, workflows, dashboards, templates, personalities, connectors, and other extensions.',
        'Marketplace or third-party items may have their own behavior, permissions, limitations, data access, and terms.',
        'Users should review:',
        'SinLess Games LLC may review, restrict, remove, suspend, or disable marketplace items that violate policy, create risk, or harm users, systems, or third parties.',
      ],
      bullets: [
        'Requested permissions',
        'Data access',
        'Publisher identity',
        'Version history',
        'Documentation',
        'Pricing',
        'Security notes',
        'Privacy behavior',
        'Organization approval status',
      ],
    },
    {
      id: 'safety-systems',
      title: '25. Safety Systems',
      body: [
        'Aerealith AI may use safety systems to detect, prevent, limit, or respond to misuse.',
        'Safety systems may include:',
        'Safety systems are not perfect. They may incorrectly allow, block, limit, or flag content or actions.',
        'Users may not attempt to bypass, disable, manipulate, evade, or interfere with Aerealith AI safety systems.',
      ],
      bullets: [
        'Policy classifiers',
        'Rate limits',
        'Abuse detection',
        'Permission checks',
        'Tool restrictions',
        'Content filters',
        'Human review queues',
        'Organization approval gates',
        'Security monitoring',
        'Audit logging',
        'Feature restrictions',
        'Model routing controls',
      ],
    },
    {
      id: 'availability-and-degraded-behavior',
      title: '26. Availability and Degraded Behavior',
      body: [
        'Aerealith AI features may be unavailable, delayed, degraded, disabled, limited, or changed due to:',
        'When features are degraded, Aerealith AI may provide partial answers, limited tool access, fallback behavior, or no response.',
        'Users should not rely on Aerealith AI as the only system for emergency response, safety-critical operations, compliance obligations, production monitoring, backup, disaster recovery, or business continuity.',
      ],
      bullets: [
        'Maintenance',
        'Outages',
        'Provider issues',
        'Rate limits',
        'Safety restrictions',
        'Billing status',
        'Subscription limits',
        'Organization policy',
        'Security events',
        'Legal requirements',
        'Technical constraints',
      ],
    },
    {
      id: 'feedback-and-correction',
      title: '27. Feedback and Correction',
      body: [
        'Users may provide feedback when Aerealith AI output is inaccurate, unsafe, incomplete, biased, or inappropriate.',
        'Feedback may be used to:',
        'Users should not include sensitive information in feedback unless the feedback channel is approved for that information.',
      ],
      bullets: [
        'Improve user experience',
        'Investigate bugs',
        'Improve documentation',
        'Improve safety systems',
        'Improve product behavior',
        'Support abuse prevention',
        'Support customer service',
      ],
    },
    {
      id: 'reporting-ai-issues',
      title: '28. Reporting AI Issues',
      body: [
        'Report AI safety, transparency, or misuse concerns to:',
        'Before publishing this policy, confirm these email aliases exist and are monitored.',
        'When reporting an issue, include as much detail as possible, such as:',
      ],
      contacts: [
        {
          label: 'AI safety concerns',
          email: 'safety@sinlessgames.com',
          href: 'mailto:safety@sinlessgames.com',
        },
        {
          label: 'Abuse reports',
          email: 'abuse@sinlessgames.com',
          href: 'mailto:abuse@sinlessgames.com',
        },
        {
          label: 'Security concerns',
          email: 'security@sinlessgames.com',
          href: 'mailto:security@sinlessgames.com',
        },
        {
          label: 'Privacy concerns',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
        {
          label: 'Legal notices',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
        {
          label: 'General support',
          email: 'support@sinlessgames.com',
          href: 'mailto:support@sinlessgames.com',
        },
      ],
      bullets: [
        'Account or workspace involved',
        'Feature, tool, model, plugin, or integration involved',
        'Prompt or request, if safe to share',
        'Output or action taken',
        'Timestamp',
        'Screenshots, logs, or message IDs',
        'Description of the concern',
        'Any immediate safety, privacy, or security risk',
      ],
    },
    {
      id: 'relationship-to-other-policies',
      title: '29. Relationship to Other Policies',
      body: [
        'This policy works together with other Aerealith AI policies, including:',
        'If there is a conflict between this policy and a written agreement signed by SinLess Games LLC, the written agreement controls only to the extent of that conflict.',
      ],
      links: [
        {
          label: 'Terms of Use',
          href: '/Policies/terms-of-use',
        },
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy-policy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data-policy',
        },
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
        {
          label: 'Responsible AI Policy',
          href: '/Policies/responsible-ai',
        },
        {
          label: 'User-Generated Content Policy',
          href: '/Policies/user-generated-content',
        },
        {
          label: 'Copyright Takedown Policy',
          href: '/Policies/copyright-takedown',
        },
        {
          label: 'Underage Policy',
          href: '/Policies/underage',
        },
        {
          label: 'Subprocessor Vendor List',
          href: '/Policies/subprocessor-vendor-list',
        },
        {
          label: 'Support Policy',
          href: '/Policies/support',
        },
      ],
    },
    {
      id: 'changes-to-this-policy',
      title: '30. Changes to This Policy',
      body: [
        'We may update this policy from time to time.',
        'When we make material changes, we will update the last_updated date and may provide notice through the service, documentation, email, release notes, or another reasonable method.',
        'Continued use of Aerealith AI after changes become effective means you accept the updated policy.',
      ],
    },
    {
      id: 'contact',
      title: '31. Contact',
      body: ['Questions about this policy may be sent to:'],
      contacts: [
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
      ],
    },
  ],
} satisfies PolicyDocument;

export default aiTransparencyPolicy;
