import type { PolicyDocument } from '../../types';

export const billingRefundCancellationPolicy = {
  slug: 'billing-refund-cancellation',
  path: '/Policies/billing-refund-cancellation',
  meta: {
    title: 'Billing, Refund, and Cancellation Policy',
    description:
      'Explains Aerealith AI billing, subscriptions, renewals, refunds, cancellations, credits, taxes, failed payments, and account changes.',
    effectiveDate: '2026-05-18',
    lastUpdated: '2026-05-18',
    owner: 'SinLess Games LLC',
    status: 'draft',
  },
  relatedPolicies: [
    {
      label: 'Terms of Use',
      href: '/Policies/terms-of-use',
    },
    {
      label: 'Privacy Policy',
      href: '/Policies/privacy-policy',
    },
    {
      label: 'Data Policy',
      href: '/Policies/data-policy',
    },
    {
      label: 'Security Policy',
      href: '/Policies/security-policy',
    },
    {
      label: 'Acceptable Use Policy',
      href: '/Policies/acceptable-use',
    },
    {
      label: 'AI Transparency Policy',
      href: '/Policies/ai-transparency',
    },
    {
      label: 'Responsible AI Policy',
      href: '/Policies/responsible-ai',
    },
    {
      label: 'User-Generated Content Policy',
      href: '/Policies/user-generated-content',
    },
    {
      label: 'Copyright Takedown Policy',
      href: '/Policies/copyright-takedown',
    },
    {
      label: 'Support Policy',
      href: '/Policies/support',
    },
    {
      label: 'Subprocessor Vendor List',
      href: '/Policies/subprocessor-vendor-list',
    },
  ],
  sections: [
    {
      id: 'purpose',
      title: '1. Purpose',
      body: [
        'This Billing, Refund, and Cancellation Policy explains how billing, subscriptions, renewals, refunds, cancellations, credits, add-ons, usage charges, failed payments, and account changes work for Aerealith AI.',
        'Aerealith AI is operated by SinLess Games LLC.',
        'This policy is intended to provide clear expectations for users, customers, organizations, developers, and enterprise accounts.',
        'By purchasing, subscribing to, or using paid Aerealith AI services, you agree to this policy, our Terms of Use, Privacy Policy, Data Policy, Security Policy, Acceptable Use Policy, and any applicable order form, invoice, service agreement, or enterprise agreement.',
      ],
      links: [
        {
          label: 'Terms of Use',
          href: '/Policies/terms-of-use',
        },
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy-policy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data-policy',
        },
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
      ],
    },
    {
      id: 'scope',
      title: '2. Scope',
      body: [
        'This policy applies to:',
        'Some products, services, marketplace items, enterprise contracts, or custom agreements may have separate billing, refund, or cancellation terms. If a signed written agreement with SinLess Games LLC conflicts with this policy, the written agreement controls only to the extent of that conflict.',
      ],
      bullets: [
        'Individual paid subscriptions',
        'Organization subscriptions',
        'Enterprise subscriptions',
        'Trials',
        'Promotional plans',
        'Usage-based billing',
        'Add-ons',
        'Marketplace purchases',
        'API usage',
        'Storage, compute, vector, automation, and integration usage',
        'Support plans',
        'Self-hosted, hybrid, cloud-hosted, and air-gapped licensing, where applicable',
      ],
    },
    {
      id: 'plans-and-pricing',
      title: '3. Plans and Pricing',
      body: [
        'Aerealith AI may offer free, paid, usage-based, custom, and enterprise plans.',
        'Plans may include, but are not limited to:',
        'Plans may include different limits, features, capabilities, support levels, storage amounts, compute limits, vector space, memory limits, automation limits, marketplace access, plugin access, API access, identity limits, workspace limits, organization features, and compliance features.',
        'Pricing, features, and limits may vary by region, currency, billing cycle, promotion, marketplace channel, organization agreement, or deployment type.',
        'We may change plan names, features, limits, pricing, or availability from time to time. If changes materially affect an active paid subscription, we will provide notice as required by applicable law or contract.',
      ],
      bullets: [
        'Free',
        'Basic',
        'Basic+',
        'Premium',
        'Premium+',
        'Pro',
        'Pro+',
        'Enterprise',
      ],
    },
    {
      id: 'billing-cycles',
      title: '4. Billing Cycles',
      body: [
        'Paid subscriptions may be billed monthly, annually, or according to another billing cycle shown at checkout, on an order form, in an invoice, or in a written agreement.',
        'Unless otherwise stated:',
        'Your billing cycle starts when you complete checkout, activate a paid plan, convert from a trial to a paid plan, accept an order form, or otherwise begin paid service.',
      ],
      bullets: [
        'Monthly plans renew each month.',
        'Annual plans renew each year.',
        'Usage-based charges may be billed during or after the usage period.',
        'Add-ons may renew with the main subscription or on their own billing schedule.',
        'Enterprise billing may follow the terms of the applicable order form, invoice, or written agreement.',
      ],
    },
    {
      id: 'automatic-renewal',
      title: '5. Automatic Renewal',
      body: [
        'Paid subscriptions automatically renew unless canceled before the renewal date.',
        'By purchasing a paid subscription, you authorize SinLess Games LLC and its payment processors to charge your payment method for recurring fees, usage charges, add-ons, taxes, and other applicable amounts.',
        'Before completing a purchase, we will make reasonable efforts to show the plan, billing cycle, price, renewal behavior, and any material limits or fees.',
        'You are responsible for reviewing your subscription details before purchasing.',
      ],
    },
    {
      id: 'payment-methods',
      title: '6. Payment Methods',
      body: [
        'Accepted payment methods may include credit cards, debit cards, PayPal, Stripe-supported payment methods, invoices, bank transfers, or other methods made available by SinLess Games LLC.',
        'Available payment methods may depend on:',
        'You represent that you are authorized to use any payment method you provide.',
        'You agree to keep billing information accurate, complete, and current.',
      ],
      bullets: [
        'Country or region',
        'Plan type',
        'Billing amount',
        'Organization type',
        'Enterprise agreement',
        'Payment processor rules',
        'Fraud, risk, or compliance checks',
      ],
    },
    {
      id: 'payment-processors',
      title: '7. Payment Processors',
      body: [
        'SinLess Games LLC may use third-party payment processors, including Stripe, PayPal, or other providers, to process payments.',
        'Payment processors may have their own terms, privacy policies, acceptable use rules, restricted business rules, fraud controls, chargeback processes, tax tools, and compliance requirements.',
        'Your payment information may be processed by the applicable payment processor. SinLess Games LLC does not directly store full payment card numbers unless expressly stated through a secure, approved payment flow.',
        'Use of payment processors is also subject to applicable processor rules and restrictions.',
      ],
    },
    {
      id: 'taxes',
      title: '8. Taxes',
      body: [
        'Prices may not include taxes unless stated otherwise.',
        'You are responsible for all applicable taxes, duties, levies, assessments, or governmental charges, including sales tax, use tax, value-added tax, goods and services tax, digital services tax, withholding tax, or similar charges.',
        'Where required, taxes may be calculated and charged at checkout, on invoices, or through the payment processor.',
        'If you are tax-exempt, you must provide valid tax exemption documentation before the charge is processed. Tax exemptions may not be applied retroactively unless required by law or approved by SinLess Games LLC.',
      ],
    },
    {
      id: 'trials',
      title: '9. Trials',
      body: [
        'Aerealith AI may offer free trials, discounted trials, promotional trials, beta access, early access, or limited-time offers.',
        'Trial terms may vary by offer and may include:',
        'If a trial requires a payment method, the trial may automatically convert to a paid subscription at the end of the trial unless canceled before the trial ends.',
        'Trial eligibility may be limited to new users, specific plans, specific regions, specific organizations, or specific promotional campaigns.',
        'We may modify, revoke, limit, or end trials at any time, subject to applicable law.',
      ],
      bullets: [
        'Trial duration',
        'Feature limits',
        'Usage limits',
        'Storage limits',
        'Automation limits',
        'API limits',
        'Marketplace restrictions',
        'Conversion terms',
        'Cancellation requirements',
        'Eligibility restrictions',
      ],
    },
    {
      id: 'promotional-pricing',
      title: '10. Promotional Pricing',
      body: [
        'Promotional pricing, coupons, credits, discounts, beta pricing, founder pricing, or special offers may be subject to additional terms.',
        'Unless otherwise stated:',
        'After a promotion ends, the subscription may renew at the then-current standard price unless canceled before renewal.',
      ],
      bullets: [
        'Promotions are temporary.',
        'Promotions may apply only to the initial billing period.',
        'Promotions may not apply to renewals.',
        'Promotions may not be combined.',
        'Promotions may not be transferable.',
        'Promotions may be limited to eligible users, plans, regions, or organizations.',
        'Promotional access may be revoked for abuse, fraud, or violation of policy.',
      ],
    },
    {
      id: 'add-ons',
      title: '11. Add-Ons',
      body: [
        'Aerealith AI may offer optional add-ons, including but not limited to:',
        'Add-ons may be billed monthly, annually, usage-based, one-time, prepaid, or according to a custom agreement.',
        'Canceling a main subscription may also cancel, disable, downgrade, or restrict related add-ons.',
        'Some add-ons may be non-refundable once provisioned, consumed, activated, or delivered.',
      ],
      bullets: [
        'Extra storage',
        'Extra vector space',
        'Extra compute',
        'Extra automation runs',
        'Extra API usage',
        'Additional organization seats',
        'Marketplace plugins',
        'Premium personalities',
        'Advanced analytics',
        'Extended audit retention',
        'Enhanced support',
        'Enterprise connectors',
        'Self-hosted deployment features',
      ],
    },
    {
      id: 'usage-based-billing',
      title: '12. Usage-Based Billing',
      body: [
        'Some Aerealith AI features may be billed based on usage.',
        'Usage-based charges may include, but are not limited to:',
        'Usage may be metered, estimated, delayed, adjusted, or corrected if errors are discovered.',
        'You are responsible for monitoring your usage and configuring limits where available.',
        'Usage charges are generally non-refundable once incurred, unless required by law or caused by a confirmed billing error.',
      ],
      bullets: [
        'API requests',
        'Model calls',
        'Token usage',
        'Compute time',
        'Automation executions',
        'Storage usage',
        'Vector database usage',
        'File processing',
        'Data transfer',
        'Plugin execution',
        'Marketplace item usage',
        'Advanced analytics',
        'Third-party integration usage',
      ],
    },
    {
      id: 'billing-limits-and-notifications',
      title: '13. Billing Limits and Notifications',
      body: [
        'Aerealith AI may provide usage dashboards, quota indicators, alerts, or billing notifications.',
        'These tools are provided for convenience and may not always be real-time, complete, or error-free.',
        'You remain responsible for charges incurred through your account, organization, API keys, automations, plugins, connected integrations, and users.',
        'Organization administrators are responsible for managing workspace usage, seat assignments, add-ons, API keys, automations, and billing limits.',
      ],
    },
    {
      id: 'seat-based-billing',
      title: '14. Seat-Based Billing',
      body: [
        'Organization and enterprise plans may be billed by seat, user, role, workspace, team, or another unit described at checkout, on an invoice, order form, or written agreement.',
        'Unless otherwise stated:',
      ],
      bullets: [
        'Adding seats may increase charges immediately or at the next billing cycle.',
        'Removing seats may reduce future charges.',
        'Unused seats may not result in automatic refunds.',
        'Seat changes may be prorated, billed immediately, or reflected on the next invoice depending on the plan and billing system.',
        'Organization administrators are responsible for managing seats and user access.',
      ],
    },
    {
      id: 'plan-upgrades',
      title: '15. Plan Upgrades',
      body: [
        'You may upgrade your plan where supported.',
        'When you upgrade:',
        'Upgrade charges are generally non-refundable once the upgraded features are provisioned, unless required by law or caused by a confirmed billing error.',
      ],
      bullets: [
        'New features may become available immediately or after processing.',
        'Additional charges may apply.',
        'Proration may apply depending on the billing system.',
        'The renewal date may remain the same or change depending on the plan.',
        'Add-ons and usage limits may be adjusted.',
        'Enterprise upgrades may require an order form or written agreement.',
      ],
    },
    {
      id: 'plan-downgrades',
      title: '16. Plan Downgrades',
      body: [
        'You may downgrade your plan where supported.',
        'When you downgrade:',
        'You are responsible for exporting, reducing, or managing data before downgrading.',
        'Downgrades generally do not create refunds or credits for unused time unless required by law or expressly stated in a written agreement.',
      ],
      bullets: [
        'The downgrade may take effect immediately or at the end of the current billing cycle.',
        'Features may be reduced or disabled.',
        'Usage limits may be lowered.',
        'Storage, memory, automation, API, analytics, marketplace, or organization limits may change.',
        'Access to advanced features may be restricted.',
        'Data may become read-only, hidden, archived, queued for deletion, or unavailable if it exceeds the downgraded plan limits.',
      ],
    },
    {
      id: 'cancellation',
      title: '17. Cancellation',
      body: [
        'You may cancel a paid subscription through the account billing page, organization billing settings, payment processor portal, or another cancellation method made available by SinLess Games LLC.',
        'Cancellation should be reasonably easy to find and complete.',
        'Unless otherwise stated:',
        'For organization or enterprise accounts, only authorized billing administrators or contract contacts may be able to cancel.',
      ],
      bullets: [
        'Cancellation stops future renewals.',
        'Cancellation does not automatically refund past charges.',
        'You may retain paid access until the end of the current billing period.',
        'Some features may be disabled immediately if cancellation is connected to abuse, fraud, chargeback risk, security risk, or account termination.',
        'Add-ons may be canceled with the subscription.',
        'Usage-based charges incurred before cancellation may still be billed.',
        'Outstanding invoices remain payable.',
      ],
    },
    {
      id: 'cancellation-timing',
      title: '18. Cancellation Timing',
      body: [
        'To avoid renewal charges, cancel before the renewal date.',
        'If you cancel after a renewal charge has been processed, the charge may be non-refundable unless required by law, covered by this policy, caused by a confirmed billing error, or approved by SinLess Games LLC.',
        'We recommend canceling at least 24 hours before renewal to reduce the risk of payment processor timing issues, pending charges, or invoice generation.',
      ],
    },
    {
      id: 'effect-of-cancellation',
      title: '19. Effect of Cancellation',
      body: [
        'After cancellation:',
        'Canceling a subscription does not automatically delete your account or all associated data.',
        'To request account deletion or data deletion, follow the procedures described in the Privacy Policy and Data Policy.',
      ],
      bullets: [
        'Your subscription will not renew.',
        'Your access may continue until the end of the paid billing period unless otherwise stated.',
        'Your account may be moved to a free plan, suspended state, read-only state, or limited-access state.',
        'Paid features may become unavailable.',
        'Automations may pause or stop.',
        'API keys may be limited or disabled.',
        'Marketplace items may become unavailable.',
        'Storage, memory, vector, and analytics limits may be reduced.',
        'Organization features may be disabled or restricted.',
        'Data retention and deletion will follow our applicable policies.',
      ],
      links: [
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy-policy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data-policy',
        },
      ],
    },
    {
      id: 'refund-policy',
      title: '20. Refund Policy',
      body: [
        'Unless otherwise required by law or expressly stated in a written agreement, paid fees are non-refundable.',
        'This includes, but is not limited to:',
        'SinLess Games LLC may approve refunds at its sole discretion.',
        'Approval of one refund does not guarantee future refunds.',
      ],
      bullets: [
        'Monthly subscriptions',
        'Annual subscriptions',
        'Add-ons',
        'Usage-based charges',
        'API usage',
        'Marketplace purchases',
        'Extra storage',
        'Extra compute',
        'Extra vector space',
        'Automation usage',
        'Seat charges',
        'Setup fees',
        'Support fees',
        'Self-hosted license fees',
        'Enterprise fees',
      ],
    },
    {
      id: 'refund-exceptions',
      title: '21. Refund Exceptions',
      body: [
        'We may consider refunds in limited situations, including:',
        'Refund requests should be submitted as soon as possible after the charge.',
        'We may require account information, billing details, invoice numbers, timestamps, transaction IDs, screenshots, or other information needed to investigate the request.',
      ],
      bullets: [
        'Duplicate charges',
        'Confirmed billing errors',
        'Unauthorized charges reported promptly',
        'Charges after a confirmed cancellation error',
        'Service not provisioned due to a confirmed system issue',
        'Legal requirements',
        'Other situations approved by SinLess Games LLC',
      ],
    },
    {
      id: 'refund-request-window',
      title: '22. Refund Request Window',
      body: [
        'Unless required by law or stated in a written agreement, refund requests should be submitted within 14 days of the charge.',
        'Requests submitted after this period may be denied.',
        'For annual plans, refunds are generally not provided after the subscription has been active, provisioned, used, or renewed unless required by law or approved by SinLess Games LLC.',
      ],
    },
    {
      id: 'refund-method',
      title: '23. Refund Method',
      body: [
        'Approved refunds are usually returned to the original payment method.',
        'Refund timing may depend on the payment processor, bank, card network, region, currency, and payment method.',
        'Processing times are outside the full control of SinLess Games LLC.',
        'If the original payment method is unavailable, we may issue account credit or use another reasonable method where permitted.',
      ],
    },
    {
      id: 'credits',
      title: '24. Credits',
      body: [
        'SinLess Games LLC may issue account credits, promotional credits, service credits, support credits, or billing adjustments.',
        'Unless otherwise stated:',
        'Service credits under an SLA, if any, are governed by the applicable SLA or written agreement.',
      ],
      bullets: [
        'Credits are not cash.',
        'Credits are not transferable.',
        'Credits may expire.',
        'Credits may apply only to eligible services.',
        'Credits may not apply to taxes.',
        'Credits may not apply to marketplace items.',
        'Credits may not be redeemable after cancellation or termination.',
        'Credits may be revoked for abuse, fraud, mistake, or policy violation.',
      ],
    },
    {
      id: 'failed-payments',
      title: '25. Failed Payments',
      body: [
        'If a payment fails, we may:',
        'You remain responsible for unpaid amounts.',
      ],
      bullets: [
        'Retry the payment method',
        'Request updated billing information',
        'Notify the account owner or billing administrator',
        'Suspend paid features',
        'Disable add-ons',
        'Pause automations',
        'Restrict API access',
        'Downgrade the account',
        'Cancel the subscription',
        'Send outstanding amounts to collection where permitted',
        'Terminate access where allowed by the Terms of Use or written agreement',
      ],
    },
    {
      id: 'late-payments',
      title: '26. Late Payments',
      body: [
        'For invoice-based accounts, payment is due according to the invoice or written agreement.',
        'Late payments may result in:',
        'Enterprise accounts should refer to the applicable order form, master services agreement, or invoice terms.',
      ],
      bullets: [
        'Suspension of service',
        'Loss of support access',
        'Late fees, where permitted',
        'Collection costs, where permitted',
        'Termination of the agreement',
        'Loss of promotional pricing',
        'Requirement to move to prepaid billing',
      ],
    },
    {
      id: 'chargebacks-and-payment-disputes',
      title: '27. Chargebacks and Payment Disputes',
      body: [
        'If you believe a charge is incorrect, contact us before initiating a chargeback when possible.',
        'Chargebacks, reversals, or payment disputes may result in:',
        'We reserve the right to contest chargebacks and provide relevant transaction, account, usage, and billing records to payment processors, banks, or card networks.',
      ],
      bullets: [
        'Account suspension',
        'Feature restrictions',
        'Loss of access to paid services',
        'Cancellation of subscriptions',
        'Revocation of credits',
        'Investigation of fraud or unauthorized use',
        'Requirement to use an alternate payment method',
      ],
    },
    {
      id: 'unauthorized-charges',
      title: '28. Unauthorized Charges',
      body: [
        'If you believe your payment method was used without authorization, contact us promptly at billing@sinlessgames.com.',
        'You should also contact your payment provider, bank, or card issuer.',
        'We may investigate unauthorized charge claims and may request information needed to verify the claim.',
        'You are responsible for keeping your account credentials, billing administrator access, organization roles, API keys, and connected accounts secure.',
      ],
      contacts: [
        {
          label: 'Billing',
          email: 'billing@sinlessgames.com',
          href: 'mailto:billing@sinlessgames.com',
        },
      ],
    },
    {
      id: 'account-sharing-and-billing-responsibility',
      title: '29. Account Sharing and Billing Responsibility',
      body: [
        'You are responsible for charges incurred through your account, organization, workspace, API keys, integrations, automations, plugins, and authorized users.',
        'For organization accounts, the organization is responsible for charges incurred by its members, administrators, service accounts, automations, API keys, and connected systems.',
        'You should promptly remove users, rotate credentials, disable unused API keys, and review automation usage when access is no longer needed.',
      ],
    },
    {
      id: 'marketplace-purchases',
      title: '30. Marketplace Purchases',
      body: [
        'Aerealith AI may offer marketplace items, including plugins, integrations, personalities, dashboards, templates, workflows, connectors, or other extensions.',
        'Marketplace purchases may have separate pricing, licensing, renewal, cancellation, and refund terms.',
        'Unless otherwise stated:',
        'If a marketplace item is provided by a third party, refund eligibility may depend on the publisher’s terms and applicable law.',
      ],
      bullets: [
        'Marketplace purchases are non-refundable once installed, activated, downloaded, provisioned, consumed, or used.',
        'Third-party publishers may set additional terms.',
        'Organization administrators may restrict, approve, block, remove, or disable marketplace items.',
        'Removal of a marketplace item does not guarantee a refund.',
        'Marketplace items that violate policy may be removed or disabled without refund.',
      ],
    },
    {
      id: 'beta-preview-and-experimental-features',
      title: '31. Beta, Preview, and Experimental Features',
      body: [
        'Beta, preview, early access, experimental, or unreleased features may be free, paid, limited, unstable, or subject to change.',
        'Unless otherwise stated:',
      ],
      bullets: [
        'Beta features may be changed or removed at any time.',
        'Beta features may have lower support priority.',
        'Beta features may not be covered by SLA commitments.',
        'Beta features may have separate usage limits.',
        'Beta access does not guarantee future availability.',
        'Fees for beta or early-access programs may be non-refundable once access is granted.',
      ],
    },
    {
      id: 'self-hosted-hybrid-and-air-gapped-deployments',
      title: '32. Self-Hosted, Hybrid, and Air-Gapped Deployments',
      body: [
        'Self-hosted, hybrid, and air-gapped deployments may be billed through licenses, support contracts, usage reports, seats, deployments, nodes, environments, or custom enterprise agreements.',
        'Billing terms may include:',
        'Unless stated otherwise in a written agreement, self-hosted, hybrid, and air-gapped license fees are non-refundable once keys, images, packages, documentation, credentials, or access are delivered.',
      ],
      bullets: [
        'License duration',
        'Support duration',
        'Update access',
        'Seat limits',
        'Deployment limits',
        'Environment limits',
        'Marketplace access',
        'Offline activation',
        'Renewal terms',
        'Audit rights',
        'Usage reporting',
        'Professional services',
        'Custom support terms',
      ],
    },
    {
      id: 'professional-services',
      title: '33. Professional Services',
      body: [
        'SinLess Games LLC may offer professional services, including setup, migration, consulting, support, integration work, custom development, training, audits, or implementation assistance.',
        'Professional services may be billed hourly, fixed-fee, milestone-based, prepaid, retainer-based, or according to a statement of work.',
        'Unless otherwise stated in a written agreement:',
      ],
      bullets: [
        'Professional service fees are non-refundable once work begins.',
        'Unused prepaid hours may expire.',
        'Scope changes may require additional fees.',
        'Delays caused by the customer may affect timelines and fees.',
        'Deliverables are governed by the applicable statement of work.',
      ],
    },
    {
      id: 'service-availability-and-billing',
      title: '34. Service Availability and Billing',
      body: [
        'Temporary downtime, maintenance, degraded service, provider outages, rate limits, disabled features, or unavailable beta features do not automatically entitle you to a refund.',
        'If an SLA applies to your plan, your sole remedy for covered availability failures may be the service credits described in that SLA or written agreement.',
        'Free plans, trial plans, beta features, preview features, and experimental features may not be eligible for service credits.',
      ],
    },
    {
      id: 'account-suspension-or-termination',
      title: '35. Account Suspension or Termination',
      body: [
        'If your account is suspended or terminated for violating our policies, law, contract, or payment obligations, you may lose access to paid features without refund.',
        'Reasons for suspension or termination may include:',
        'Termination for cause does not relieve you of responsibility for outstanding charges.',
      ],
      bullets: [
        'Non-payment',
        'Fraud',
        'Abuse',
        'Chargeback risk',
        'Security risk',
        'Policy violations',
        'Illegal activity',
        'Unauthorized access',
        'Misuse of automations, APIs, plugins, or marketplace items',
        'Violation of payment processor rules',
        'Violation of applicable laws or regulations',
      ],
    },
    {
      id: 'price-changes',
      title: '36. Price Changes',
      body: [
        'We may change prices from time to time.',
        'For active subscriptions, price changes will generally apply at the next renewal or after notice as required by law or contract.',
        'If you do not agree to a price change, you may cancel before the new price takes effect.',
        'Continued use after the price change takes effect means you accept the new price.',
      ],
    },
    {
      id: 'feature-changes',
      title: '37. Feature Changes',
      body: [
        'Plan features, limits, and entitlements may change over time.',
        'We may add, modify, replace, restrict, or remove features to improve the service, comply with law, address risk, manage costs, respond to provider changes, or support product development.',
        'If a material feature change affects a paid subscription, we will provide notice where required by law or contract.',
        'Feature changes do not automatically entitle you to a refund unless required by law or expressly provided in a written agreement.',
      ],
    },
    {
      id: 'currency-and-exchange-rates',
      title: '38. Currency and Exchange Rates',
      body: [
        'Prices may be listed in U.S. dollars or another supported currency.',
        'Currency availability may depend on region, payment processor, plan type, or sales channel.',
        'If currency conversion is required, exchange rates, conversion fees, foreign transaction fees, or bank fees may be determined by the payment processor, card issuer, bank, or financial institution.',
        'SinLess Games LLC is not responsible for third-party currency conversion fees or bank fees.',
      ],
    },
    {
      id: 'regional-rules',
      title: '39. Regional Rules',
      body: [
        'Billing, refunds, cancellation rights, taxes, trial rules, consumer rights, and renewal requirements may vary by jurisdiction.',
        'Where applicable law gives you rights that cannot be waived, this policy does not limit those rights.',
        'If a specific regional legal requirement applies, SinLess Games LLC will comply with that requirement.',
      ],
    },
    {
      id: 'data-after-billing-changes',
      title: '40. Data After Billing Changes',
      body: [
        'Billing changes may affect access to data and features.',
        'Depending on the change, Aerealith AI may:',
        'Users should export important data before cancellation, downgrade, non-payment, or termination.',
        'Data handling is governed by the Privacy Policy, Data Policy, and applicable written agreements.',
      ],
      bullets: [
        'Reduce storage limits',
        'Pause automations',
        'Restrict API access',
        'Disable paid models',
        'Disable marketplace items',
        'Move data to read-only mode',
        'Archive data',
        'Queue data for deletion according to retention settings',
        'Restrict organization administration features',
        'Disable export features that require a paid plan, unless export is required by law',
      ],
      links: [
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy-policy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data-policy',
        },
      ],
    },
    {
      id: 'billing-communications',
      title: '41. Billing Communications',
      body: [
        'We may send billing-related communications to account owners, billing contacts, organization administrators, or authorized contacts.',
        'Billing communications may include:',
        'You are responsible for keeping contact information current.',
      ],
      bullets: [
        'Receipts',
        'Invoices',
        'Renewal notices',
        'Failed payment notices',
        'Trial ending notices',
        'Cancellation confirmations',
        'Refund decisions',
        'Tax notices',
        'Pricing changes',
        'Plan changes',
        'Payment method issues',
        'Chargeback notices',
        'Account suspension notices',
      ],
    },
    {
      id: 'enterprise-agreements',
      title: '42. Enterprise Agreements',
      body: [
        'Enterprise customers may have custom terms in an order form, master services agreement, data processing agreement, business associate agreement, security addendum, support agreement, SLA, or statement of work.',
        'Enterprise terms may cover:',
        'If enterprise documents conflict with this policy, the signed enterprise documents control only for that enterprise customer and only to the extent of the conflict.',
      ],
      bullets: [
        'Payment terms',
        'Invoice timing',
        'Renewal terms',
        'Minimum commitments',
        'True-up charges',
        'Seat counts',
        'Usage reporting',
        'Support levels',
        'Service credits',
        'Cancellation rights',
        'Termination rights',
        'Data retention',
        'Self-hosted licensing',
        'Marketplace controls',
        'Compliance requirements',
      ],
    },
    {
      id: 'how-to-cancel',
      title: '43. How to Cancel',
      body: [
        'To cancel a subscription, use one of the available cancellation methods:',
        'If self-service cancellation is unavailable, contact billing@sinlessgames.com.',
        'For enterprise cancellations, contact your account representative or the billing contact listed in your agreement.',
        'Before publishing this policy, confirm the exact cancellation flow and update this section with product-specific instructions.',
      ],
      orderedItems: [
        'Sign in to your Aerealith AI account.',
        'Open account or organization billing settings.',
        'Select the active subscription.',
        'Choose the cancellation option.',
        'Follow the confirmation steps.',
        'Save or download the cancellation confirmation for your records.',
      ],
      contacts: [
        {
          label: 'Billing',
          email: 'billing@sinlessgames.com',
          href: 'mailto:billing@sinlessgames.com',
        },
      ],
    },
    {
      id: 'how-to-request-a-refund',
      title: '44. How to Request a Refund',
      body: [
        'To request a refund, contact billing@sinlessgames.com.',
        'Include:',
        'We may deny incomplete, late, unsupported, abusive, fraudulent, or ineligible refund requests.',
      ],
      contacts: [
        {
          label: 'Billing',
          email: 'billing@sinlessgames.com',
          href: 'mailto:billing@sinlessgames.com',
        },
      ],
      bullets: [
        'Account email',
        'Organization name, if applicable',
        'Invoice number',
        'Transaction ID, if available',
        'Charge date',
        'Charge amount',
        'Payment method type',
        'Reason for the request',
        'Any relevant screenshots or documentation',
      ],
    },
    {
      id: 'contact',
      title: '45. Contact',
      body: [
        'Billing questions, refund requests, and cancellation issues may be sent to:',
        'Before publishing this policy, confirm these email aliases exist and are monitored.',
      ],
      contacts: [
        {
          label: 'Billing',
          email: 'billing@sinlessgames.com',
          href: 'mailto:billing@sinlessgames.com',
        },
        {
          label: 'Support',
          email: 'support@sinlessgames.com',
          href: 'mailto:support@sinlessgames.com',
        },
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
      ],
    },
    {
      id: 'relationship-to-other-policies',
      title: '46. Relationship to Other Policies',
      body: ['This policy works together with other Aerealith AI policies, including:'],
      links: [
        {
          label: 'Terms of Use',
          href: '/Policies/terms-of-use',
        },
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy-policy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data-policy',
        },
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
        {
          label: 'AI Transparency Policy',
          href: '/Policies/ai-transparency',
        },
        {
          label: 'Responsible AI Policy',
          href: '/Policies/responsible-ai',
        },
        {
          label: 'User-Generated Content Policy',
          href: '/Policies/user-generated-content',
        },
        {
          label: 'Copyright Takedown Policy',
          href: '/Policies/copyright-takedown',
        },
        {
          label: 'Support Policy',
          href: '/Policies/support',
        },
        {
          label: 'Subprocessor Vendor List',
          href: '/Policies/subprocessor-vendor-list',
        },
      ],
    },
    {
      id: 'changes-to-this-policy',
      title: '47. Changes to This Policy',
      body: [
        'We may update this policy from time to time.',
        'When we make material changes, we will update the last_updated date and may provide notice through the service, documentation, email, release notes, billing portal, or another reasonable method.',
        'Continued use of Aerealith AI after changes become effective means you accept the updated policy.',
      ],
    },
    {
      id: 'legal-review-notice',
      title: '48. Legal Review Notice',
      body: [
        'This policy is a draft template and should be reviewed by qualified legal counsel before publication.',
        'Billing, refund, cancellation, tax, consumer protection, and subscription renewal requirements may vary by jurisdiction.',
      ],
    },
  ],
} satisfies PolicyDocument;

export default billingRefundCancellationPolicy;
