import type { PolicyDocument } from '../../types';

export const cookieTrackingPolicy = {
  slug: 'cookie-tracking',
  path: '/Policies/cookie-tracking',
  meta: {
    title: 'Cookie and Tracking Policy',
    description:
      'Explains how Aerealith AI uses cookies, pixels, local storage, analytics, device identifiers, and similar tracking technologies.',
    effectiveDate: '2026-05-18',
    lastUpdated: '2026-05-18',
    owner: 'SinLess Games LLC',
    status: 'draft',
  },
  relatedPolicies: [
    {
      label: 'Terms of Use',
      href: '/Policies/terms-of-use',
    },
    {
      label: 'Privacy Policy',
      href: '/Policies/privacy-policy',
    },
    {
      label: 'Data Policy',
      href: '/Policies/data-policy',
    },
    {
      label: 'Security Policy',
      href: '/Policies/security-policy',
    },
    {
      label: 'Acceptable Use Policy',
      href: '/Policies/acceptable-use',
    },
    {
      label: 'AI Transparency Policy',
      href: '/Policies/ai-transparency',
    },
    {
      label: 'Billing, Refund, and Cancellation Policy',
      href: '/Policies/billing-refund-cancellation',
    },
    {
      label: 'Subprocessor Vendor List',
      href: '/Policies/subprocessor-vendor-list',
    },
    {
      label: 'Support Policy',
      href: '/Policies/support-policy',
    },
    {
      label: 'Underage Policy',
      href: '/Policies/underage-policy',
    },
  ],
  sections: [
    {
      id: 'purpose',
      title: '1. Purpose',
      body: [
        'This Cookie and Tracking Policy explains how Aerealith AI uses cookies, pixels, local storage, software development kits, analytics tags, device identifiers, log data, and similar tracking technologies.',
        'Aerealith AI is operated by SinLess Games LLC.',
        'This policy explains:',
        'This policy should be read together with our Privacy Policy, Data Policy, Security Policy, and Terms of Use.',
      ],
      bullets: [
        'What cookies and tracking technologies are',
        'Why we use them',
        'What categories of cookies may be used',
        'How users can manage cookie choices',
        'How tracking relates to analytics, security, personalization, payments, and advertising',
        'How this policy works with our Privacy Policy and Data Policy',
      ],
      links: [
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy-policy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data-policy',
        },
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
        {
          label: 'Terms of Use',
          href: '/Policies/terms-of-use',
        },
      ],
    },
    {
      id: 'scope',
      title: '2. Scope',
      body: [
        'This policy applies to Aerealith AI services, including:',
        'This policy applies to visitors, users, developers, organization members, workspace administrators, customers, and anyone who interacts with Aerealith AI services.',
        'Some self-hosted, hybrid, private, or air-gapped deployments may use different cookie, analytics, or tracking configurations controlled by the deploying organization.',
      ],
      bullets: [
        'Websites',
        'Documentation sites',
        'Web applications',
        'Desktop applications, where applicable',
        'Mobile applications, where applicable',
        'Browser extensions, where applicable',
        'APIs and developer portals',
        'Marketplace pages',
        'Support portals',
        'Billing pages',
        'Login and account pages',
        'Embedded widgets',
        'Analytics dashboards',
        'Community or marketing pages operated by SinLess Games LLC',
      ],
    },
    {
      id: 'what-cookies-are',
      title: '3. What Cookies Are',
      body: [
        'Cookies are small text files placed on a browser or device by a website or service.',
        'Cookies may help a service:',
        'Cookies may be set by Aerealith AI directly or by third-party providers that help operate Aerealith AI.',
      ],
      bullets: [
        'Keep users signed in',
        'Remember preferences',
        'Secure sessions',
        'Prevent fraud',
        'Measure performance',
        'Understand product usage',
        'Support billing and checkout',
        'Improve reliability',
        'Personalize user experience',
        'Provide analytics',
        'Support marketing or attribution, where enabled',
      ],
    },
    {
      id: 'similar-tracking-technologies',
      title: '4. Similar Tracking Technologies',
      body: [
        'In addition to cookies, Aerealith AI may use similar technologies, including:',
        'In this policy, “cookies” may refer to cookies and similar tracking technologies unless the context requires a narrower meaning.',
      ],
      bullets: [
        'Local storage',
        'Session storage',
        'IndexedDB',
        'Pixels',
        'Tags',
        'Beacons',
        'Server logs',
        'Device identifiers',
        'Mobile advertising identifiers, where applicable',
        'Browser fingerprints, where legally permitted and disclosed',
        'SDK telemetry',
        'Analytics events',
        'Error reporting events',
        'Performance monitoring events',
        'Authentication session tokens',
        'Security tokens',
        'Consent preference records',
      ],
    },
    {
      id: 'first-party-and-third-party-cookies',
      title: '5. First-Party and Third-Party Cookies',
      body: [
        'Aerealith AI may use both first-party and third-party cookies.',
        'First-party cookies are set by Aerealith AI or domains controlled by SinLess Games LLC.',
        'Third-party cookies are set by service providers or third-party platforms used by Aerealith AI, such as hosting, analytics, authentication, payments, support, monitoring, marketing, or embedded content providers.',
        'Third-party providers may process data according to their own terms, privacy policies, and cookie policies.',
      ],
    },
    {
      id: 'cookie-categories',
      title: '6. Cookie Categories',
      body: [
        'Aerealith AI may use the following categories of cookies and tracking technologies.',
      ],
    },
    {
      id: 'strictly-necessary-cookies',
      title: '6.1 Strictly Necessary Cookies',
      body: [
        'Strictly necessary cookies are required for Aerealith AI to function.',
        'These may be used for:',
        'These cookies cannot usually be disabled through Aerealith AI cookie settings because the service may not work properly without them.',
        'Users may block these cookies through browser settings, but some features may stop working.',
      ],
      bullets: [
        'Login sessions',
        'Authentication',
        'Account security',
        'Fraud prevention',
        'Load balancing',
        'Consent preference storage',
        'Checkout security',
        'Access control',
        'CSRF protection',
        'Rate limiting',
        'Workspace routing',
        'Organization access controls',
        'Service reliability',
      ],
    },
    {
      id: 'security-cookies',
      title: '6.2 Security Cookies',
      body: [
        'Security cookies and related technologies help protect users, organizations, and Aerealith AI.',
        'These may be used for:',
        'Security cookies may be considered strictly necessary when they are required to provide a safe and secure service.',
      ],
      bullets: [
        'Detecting suspicious activity',
        'Preventing account takeover',
        'Protecting sessions',
        'Identifying abuse',
        'Enforcing rate limits',
        'Preventing spam',
        'Protecting APIs',
        'Supporting audit logs',
        'Detecting unauthorized access',
        'Supporting incident response',
      ],
    },
    {
      id: 'preference-cookies',
      title: '6.3 Preference Cookies',
      body: [
        'Preference cookies remember user choices.',
        'These may be used for:',
        'Preference cookies may improve user experience but are not always required for basic functionality.',
      ],
      bullets: [
        'Theme preference',
        'Language preference',
        'Region preference',
        'Accessibility preferences',
        'Cookie consent choices',
        'Interface layout',
        'Assistant display preferences',
        'Dashboard preferences',
        'Documentation preferences',
      ],
    },
    {
      id: 'analytics-and-performance-cookies',
      title: '6.4 Analytics and Performance Cookies',
      body: [
        'Analytics and performance cookies help us understand how Aerealith AI is used and how the service performs.',
        'These may be used to measure:',
        'Analytics may be used to improve reliability, usability, documentation, onboarding, product design, and support.',
        'Where required, analytics cookies will only be used after consent.',
      ],
      bullets: [
        'Page views',
        'Feature usage',
        'Session duration',
        'Navigation paths',
        'Referring pages',
        'Error rates',
        'Performance metrics',
        'Load times',
        'Conversion events',
        'Documentation usage',
        'Product adoption',
        'Aggregate usage trends',
      ],
    },
    {
      id: 'functional-cookies',
      title: '6.5 Functional Cookies',
      body: [
        'Functional cookies support enhanced features.',
        'These may be used for:',
        'Disabling functional cookies may reduce product quality or disable some features.',
      ],
      bullets: [
        'Remembering workspace state',
        'Saving UI preferences',
        'Supporting chat continuity',
        'Remembering recently used projects',
        'Supporting dashboards',
        'Supporting marketplace browsing',
        'Supporting support chat',
        'Supporting embedded media',
        'Supporting app-to-docs transitions',
      ],
    },
    {
      id: 'personalization-cookies',
      title: '6.6 Personalization Cookies',
      body: [
        'Personalization cookies and related technologies may help customize the Aerealith AI experience.',
        'These may be used for:',
        'Personalization cookies are different from long-term AI memory, although both may affect user experience.',
        'Memory behavior is governed by the Privacy Policy, Data Policy, and user or organization memory settings.',
      ],
      bullets: [
        'Remembering product preferences',
        'Recommending documentation',
        'Customizing onboarding',
        'Improving assistant experience',
        'Adjusting interface behavior',
        'Remembering selected persona or assistant identity settings',
        'Showing relevant product guidance',
        'Supporting workspace-specific experiences',
      ],
      links: [
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy-policy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data-policy',
        },
      ],
    },
    {
      id: 'advertising-and-marketing-cookies',
      title: '6.7 Advertising and Marketing Cookies',
      body: [
        'Aerealith AI may use advertising or marketing cookies where enabled.',
        'These may be used for:',
        'Where required, advertising and marketing cookies will only be used after consent.',
        'Users may opt out of sale, sharing, targeted advertising, or similar activity where applicable.',
      ],
      bullets: [
        'Measuring campaign performance',
        'Understanding referrals',
        'Limiting repeated ads',
        'Showing relevant ads',
        'Measuring signups from ads',
        'Affiliate or partner attribution',
        'Retargeting, where permitted',
        'Preventing advertising fraud',
      ],
    },
    {
      id: 'payment-and-checkout-cookies',
      title: '6.8 Payment and Checkout Cookies',
      body: [
        'Payment processors may use cookies and similar technologies to support payment, fraud prevention, checkout security, tax calculation, and billing workflows.',
        'These may be used by providers such as Stripe, PayPal, or other payment processors made available by SinLess Games LLC.',
        'Payment cookies may be required to complete checkout, detect fraud, process transactions, and comply with payment processor rules.',
      ],
    },
    {
      id: 'embedded-content-cookies',
      title: '6.9 Embedded Content Cookies',
      body: [
        'Aerealith AI pages may include embedded content from third-party providers.',
        'Embedded content may include:',
        'Third-party embedded content may set cookies or collect information when users interact with it.',
      ],
      bullets: [
        'Videos',
        'Images',
        'Maps',
        'Documentation widgets',
        'Support widgets',
        'Status widgets',
        'Analytics dashboards',
        'Authentication widgets',
        'Payment widgets',
        'Social media embeds',
        'Community embeds',
      ],
    },
    {
      id: 'why-we-use-cookies-and-tracking-technologies',
      title: '7. Why We Use Cookies and Tracking Technologies',
      body: [
        'Aerealith AI may use cookies and tracking technologies to:',
      ],
      bullets: [
        'Provide the service',
        'Authenticate users',
        'Keep users signed in',
        'Secure accounts',
        'Prevent fraud and abuse',
        'Remember settings',
        'Respect consent choices',
        'Process payments',
        'Operate billing systems',
        'Improve reliability',
        'Monitor uptime and performance',
        'Debug errors',
        'Understand product usage',
        'Improve documentation',
        'Support customer service',
        'Support marketplace functionality',
        'Support developer tools',
        'Support analytics dashboards',
        'Personalize user experience',
        'Measure marketing effectiveness',
        'Comply with legal, security, and operational obligations',
      ],
    },
    {
      id: 'consent',
      title: '8. Consent',
      body: [
        'Where required by law, Aerealith AI will ask for consent before using non-essential cookies.',
        'Non-essential cookies may include:',
        'Users may accept, reject, or customize cookie choices where a cookie preference tool is available.',
        'Strictly necessary cookies may be used without consent when they are required to provide, secure, or maintain the service.',
      ],
      bullets: [
        'Analytics cookies',
        'Personalization cookies',
        'Advertising cookies',
        'Marketing cookies',
        'Certain third-party cookies',
        'Certain embedded content cookies',
      ],
    },
    {
      id: 'cookie-preference-tool',
      title: '9. Cookie Preference Tool',
      body: [
        'Where available, users may manage cookie preferences through the Aerealith AI cookie banner, cookie settings page, privacy settings, account settings, or another consent management tool.',
        'Users may be able to:',
        'Withdrawing consent does not affect processing that occurred before consent was withdrawn.',
      ],
      bullets: [
        'Accept all optional cookies',
        'Reject all optional cookies',
        'Choose cookie categories',
        'Change prior choices',
        'Withdraw consent',
        'View additional cookie details',
        'Access this policy',
        'Access the Privacy Policy',
      ],
      links: [
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy-policy',
        },
      ],
    },
    {
      id: 'no-dark-patterns',
      title: '10. No Dark Patterns',
      body: [
        'Aerealith AI should not use deceptive or manipulative cookie consent designs.',
        'Cookie choice interfaces should be designed to be clear, fair, and understandable.',
        'Where practical, Aerealith AI should avoid:',
      ],
      bullets: [
        'Hiding rejection options',
        'Making rejection unnecessarily difficult',
        'Using confusing wording',
        'Using misleading button colors or hierarchy',
        'Repeatedly asking after a user rejects optional cookies',
        'Bundling unrelated consent choices',
        'Claiming optional cookies are required when they are not',
        'Pre-selecting optional categories where prohibited',
        'Making consent withdrawal harder than consent acceptance',
      ],
    },
    {
      id: 'browser-controls',
      title: '11. Browser Controls',
      body: [
        'Users can manage cookies through browser settings.',
        'Browser controls may allow users to:',
        'Blocking or deleting cookies may affect Aerealith AI functionality.',
        'For example, users may be signed out, preferences may be lost, checkout may fail, or some app features may not work correctly.',
      ],
      bullets: [
        'Block cookies',
        'Delete cookies',
        'Block third-party cookies',
        'Clear site data',
        'Restrict local storage',
        'Disable tracking technologies',
        'Use private browsing',
        'Control site permissions',
      ],
    },
    {
      id: 'global-privacy-control-and-similar-signals',
      title: '12. Global Privacy Control and Similar Signals',
      body: [
        'Aerealith AI may recognize legally required browser-based opt-out signals, such as Global Privacy Control, where applicable.',
        'Where required by law, a valid opt-out signal may be treated as a request to opt out of sale, sharing, targeted advertising, or similar processing.',
        'Availability and handling of opt-out signals may depend on:',
        'Users may also use privacy settings, cookie settings, or contact methods described in this policy to exercise applicable rights.',
      ],
      bullets: [
        'User location',
        'Applicable law',
        'Browser support',
        'Technical implementation',
        'Service configuration',
        'Organization settings',
        'Deployment type',
      ],
    },
    {
      id: 'do-not-track',
      title: '13. Do Not Track',
      body: [
        'Some browsers may send “Do Not Track” signals.',
        'There is no single universal standard for how all websites must respond to Do Not Track signals.',
        'Aerealith AI may not respond to Do Not Track signals unless required by applicable law or configured to do so.',
        'Where legally required, Aerealith AI may instead recognize Global Privacy Control or other legally recognized opt-out preference signals.',
      ],
    },
    {
      id: 'sale-sharing-and-targeted-advertising',
      title: '14. Sale, Sharing, and Targeted Advertising',
      body: [
        'Some privacy laws define certain advertising, analytics, cross-context behavioral advertising, or third-party tracking as “sale,” “sharing,” or targeted advertising.',
        'Where required, users may have the right to opt out of:',
        'Aerealith AI should provide opt-out controls where required.',
        'Users may contact us using the information in this policy to request additional help with privacy choices.',
      ],
      bullets: [
        'Sale of personal information',
        'Sharing of personal information',
        'Targeted advertising',
        'Cross-context behavioral advertising',
        'Certain profiling activities',
      ],
    },
    {
      id: 'cookie-table',
      title: '15. Cookie Table',
      body: [
        'Aerealith AI should maintain a current cookie table before this policy is published.',
        'The cookie table should include:',
        'Before publishing, replace this example table with the actual cookies used in production.',
      ],
      bullets: [
        'Cookie name',
        'Provider',
        'Domain',
        'Category',
        'Purpose',
        'Duration',
        'Whether it is first-party or third-party',
        'Whether it is strictly necessary',
        'Whether it is used for advertising or targeted advertising',
        'Whether it is used for analytics',
        'Link to provider policy, where applicable',
        'Example: session — Aerealith AI — Strictly Necessary — Maintains authenticated sessions — Session or limited duration — First-party',
        'Example: csrf — Aerealith AI — Security — Helps prevent cross-site request forgery — Session or limited duration — First-party',
        'Example: cookie_consent — Aerealith AI — Strictly Necessary — Stores cookie preference choices — Limited duration — First-party',
        'Example: theme — Aerealith AI — Preference — Remembers light or dark mode — Limited duration — First-party',
        'Example: analytics_id — Analytics provider — Analytics — Measures usage and performance — Limited duration — Third-party or first-party',
        'Example: payment_session — Payment processor — Payment — Supports checkout and fraud prevention — Session or limited duration — Third-party',
      ],
    },
    {
      id: 'potential-service-providers',
      title: '16. Potential Service Providers',
      body: [
        'Depending on configuration, Aerealith AI may use service providers that set cookies or similar technologies.',
        'These may include providers for:',
        'Potential providers may include, depending on the actual production configuration:',
        'Before publishing, confirm the actual providers and ensure they match the Subprocessor Vendor List.',
      ],
      bullets: [
        'Hosting',
        'DNS and edge security',
        'Authentication',
        'Analytics',
        'Feature flags',
        'Payments',
        'Customer support',
        'Documentation',
        'Error monitoring',
        'Product telemetry',
        'Observability',
        'Email delivery',
        'Marketplace operations',
        'Embedded media',
        'Cloudflare',
        'Vercel',
        'Supabase',
        'NextAuth-related authentication providers',
        'Stripe',
        'PayPal',
        'Google Analytics',
        'Hypertune',
        'Grafana Cloud or Grafana Faro',
        'Contentful',
        'Support or helpdesk providers',
        'Email service providers',
        'Marketplace service providers',
      ],
      links: [
        {
          label: 'Subprocessor Vendor List',
          href: '/Policies/subprocessor-vendor-list',
        },
      ],
    },
    {
      id: 'analytics',
      title: '17. Analytics',
      body: [
        'Aerealith AI may use analytics to understand service usage, improve product quality, and monitor performance.',
        'Analytics may include:',
        'Analytics should be configured to minimize unnecessary personal data collection where practical.',
        'Where required, analytics cookies will only be used after consent.',
      ],
      bullets: [
        'Page visits',
        'Clicks',
        'Feature usage',
        'Search terms within Aerealith AI documentation or apps',
        'Signup and onboarding progress',
        'Subscription conversion',
        'Error rates',
        'Latency',
        'Device and browser information',
        'Approximate region',
        'Referring pages',
        'Aggregated usage trends',
      ],
    },
    {
      id: 'product-telemetry',
      title: '18. Product Telemetry',
      body: [
        'Aerealith AI may collect product telemetry to improve reliability, security, and user experience.',
        'Product telemetry may include:',
        'Product telemetry may be necessary for operating, securing, debugging, and improving Aerealith AI.',
        'When telemetry is not strictly necessary, users or organizations may be provided controls where required or where supported by the product.',
      ],
      bullets: [
        'Feature usage events',
        'Performance timing',
        'Error events',
        'API latency',
        'Automation execution status',
        'Tool call status',
        'Marketplace installation events',
        'Integration health events',
        'Dashboard load performance',
        'Documentation search behavior',
        'Subscription entitlement checks',
      ],
    },
    {
      id: 'error-reporting-and-observability',
      title: '19. Error Reporting and Observability',
      body: [
        'Aerealith AI may use error reporting and observability tools to detect, diagnose, and resolve technical issues.',
        'These tools may collect:',
        'Aerealith AI should avoid collecting sensitive prompt content, secrets, credentials, private keys, payment details, or unnecessary personal data in error reporting tools where practical.',
      ],
      bullets: [
        'Error messages',
        'Stack traces',
        'Browser type',
        'Device type',
        'Operating system',
        'Page URL',
        'Request metadata',
        'Timing information',
        'Feature flags',
        'Session identifiers',
        'User or organization identifiers, where needed',
        'Logs related to service reliability',
      ],
    },
    {
      id: 'authentication-and-session-tracking',
      title: '20. Authentication and Session Tracking',
      body: [
        'Aerealith AI may use cookies and similar technologies to manage authentication and sessions.',
        'These may support:',
        'Authentication cookies are typically required for account-based services.',
      ],
      bullets: [
        'Sign-in',
        'Sign-out',
        'Multi-factor authentication',
        'Passkeys',
        'Magic links',
        'OAuth flows',
        'Session expiration',
        'Device recognition',
        'Account recovery',
        'Organization access',
        'Workspace switching',
        'Security monitoring',
      ],
    },
    {
      id: 'ai-memory-and-cookie-tracking',
      title: '21. AI Memory and Cookie Tracking',
      body: [
        'Cookies are not the same as Aerealith AI memory.',
        'Cookies may remember browser-level or device-level settings.',
        'Aerealith AI memory may remember user-controlled preferences, project context, assistant settings, or other information according to user or organization settings.',
        'Memory behavior is governed by:',
        'Users should not rely on deleting cookies as the only way to delete Aerealith AI memory.',
        'To manage memory, use Aerealith AI memory controls or follow the procedures in the Privacy Policy and Data Policy.',
      ],
      bullets: [
        'Privacy Policy',
        'Data Policy',
        'AI Transparency Policy',
        'User settings',
        'Organization settings',
        'Applicable deployment configuration',
      ],
      links: [
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy-policy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data-policy',
        },
        {
          label: 'AI Transparency Policy',
          href: '/Policies/ai-transparency',
        },
      ],
    },
    {
      id: 'local-storage-and-device-storage',
      title: '22. Local Storage and Device Storage',
      body: [
        'Aerealith AI may use browser or device storage to support app functionality.',
        'This may include:',
        'Clearing local storage may remove saved settings, sign users out, or affect app behavior.',
      ],
      bullets: [
        'Session state',
        'Drafts',
        'UI settings',
        'Offline mode, where supported',
        'Cached files or metadata',
        'Recently accessed workspaces',
        'Consent preferences',
        'Authentication support',
        'Performance optimization',
      ],
    },
    {
      id: 'mobile-and-desktop-applications',
      title: '23. Mobile and Desktop Applications',
      body: [
        'If Aerealith AI offers mobile or desktop applications, those apps may use technologies similar to cookies.',
        'These may include:',
        'Users may manage some app permissions through operating system settings.',
        'Some app features may not work if required permissions or identifiers are disabled.',
      ],
      bullets: [
        'Device identifiers',
        'App instance identifiers',
        'Push notification tokens',
        'Crash reporting identifiers',
        'Local app storage',
        'Secure storage',
        'Analytics SDKs',
        'Performance monitoring SDKs',
        'Authentication tokens',
      ],
    },
    {
      id: 'browser-extensions',
      title: '24. Browser Extensions',
      body: [
        'If Aerealith AI offers browser extensions, the extension may use local storage, extension storage, permissions, and browser APIs.',
        'Browser extension data use should be disclosed in the extension listing, privacy documentation, and permission prompts.',
        'Browser extensions should only request permissions needed for their stated functionality.',
        'Users may disable or remove extensions through browser settings.',
      ],
    },
    {
      id: 'developer-apis-and-sdks',
      title: '25. Developer APIs and SDKs',
      body: [
        'Aerealith AI APIs, SDKs, and developer tools may collect technical information needed to operate and secure developer services.',
        'This may include:',
        'Developers are responsible for providing any required notices to their own users when they integrate Aerealith AI into their applications, websites, workflows, plugins, or services.',
      ],
      bullets: [
        'API key usage',
        'Request metadata',
        'Rate limit data',
        'Error responses',
        'SDK version',
        'Integration identifiers',
        'Plugin execution metadata',
        'Marketplace usage',
        'Abuse prevention signals',
      ],
    },
    {
      id: 'marketplace-tracking',
      title: '26. Marketplace Tracking',
      body: [
        'Aerealith AI marketplace features may use cookies and tracking technologies to support:',
        'Third-party marketplace publishers may not use hidden tracking, unauthorized data collection, or undisclosed telemetry through marketplace items.',
        'Marketplace behavior is also governed by applicable marketplace, developer, and acceptable use policies.',
      ],
      bullets: [
        'Publisher accounts',
        'Plugin installation',
        'Plugin updates',
        'License checks',
        'Purchase attribution',
        'Reviews and ratings',
        'Abuse detection',
        'Security review',
        'Organization approvals',
        'Marketplace analytics',
        'Revenue reporting',
        'Refund handling',
        'Fraud prevention',
      ],
    },
    {
      id: 'email-tracking',
      title: '27. Email Tracking',
      body: [
        'Aerealith AI may send emails related to accounts, billing, security, support, product updates, documentation, or marketing.',
        'Some emails may include tracking technologies to understand:',
        'Users may unsubscribe from marketing emails where required.',
        'Transactional, account, security, billing, legal, and service-related emails may still be sent even if a user opts out of marketing emails.',
      ],
      bullets: [
        'Whether an email was delivered',
        'Whether an email bounced',
        'Whether an email was opened',
        'Whether a link was clicked',
        'Whether a security notification was interacted with',
        'Whether a billing or account notice was received',
      ],
    },
    {
      id: 'advertising-and-marketing-partners',
      title: '28. Advertising and Marketing Partners',
      body: [
        'Aerealith AI may use advertising or marketing partners where enabled.',
        'These partners may help with:',
        'Where required, advertising and marketing cookies will only be used after consent.',
        'Users may opt out of targeted advertising, sale, sharing, or similar activity where applicable.',
      ],
      bullets: [
        'Campaign measurement',
        'Referral attribution',
        'Signup attribution',
        'Retargeting, where permitted',
        'Audience measurement',
        'Fraud prevention',
        'Affiliate attribution',
      ],
    },
    {
      id: 'data-retention',
      title: '29. Data Retention',
      body: [
        'Cookie and tracking data may be retained for different periods depending on the category and purpose.',
        'Retention may depend on:',
        'Strictly necessary cookies may last for the duration needed to provide the service.',
        'Consent records may be retained to prove or honor user choices.',
        'Analytics data should be retained only as long as reasonably needed for product, operational, legal, or business purposes.',
      ],
      bullets: [
        'Cookie type',
        'Provider settings',
        'Legal requirements',
        'Security needs',
        'Fraud prevention needs',
        'Analytics configuration',
        'User consent choices',
        'Organization settings',
        'Account status',
        'Deployment type',
      ],
    },
    {
      id: 'data-minimization',
      title: '30. Data Minimization',
      body: [
        'Aerealith AI should minimize cookie and tracking data where practical.',
        'This may include:',
      ],
      bullets: [
        'Limiting optional trackers',
        'Avoiding unnecessary third-party scripts',
        'Reducing sensitive data in analytics',
        'Avoiding secrets in logs',
        'Aggregating analytics where practical',
        'Shortening retention where practical',
        'Respecting user choices',
        'Limiting tracking on documentation or public pages where practical',
        'Reviewing vendor behavior before deployment',
      ],
    },
    {
      id: 'children-and-minors',
      title: '31. Children and Minors',
      body: [
        'Aerealith AI is not intended to use cookies or tracking technologies to knowingly target children with behavioral advertising.',
        'Use by minors is governed by the Underage Policy.',
        'If we learn that tracking data has been collected from a child in violation of applicable law or policy, we may delete or restrict that data.',
      ],
      links: [
        {
          label: 'Underage Policy',
          href: '/Policies/underage-policy',
        },
      ],
    },
    {
      id: 'sensitive-data',
      title: '32. Sensitive Data',
      body: [
        'Aerealith AI should not intentionally collect sensitive data through cookies unless necessary, disclosed, lawful, and appropriately protected.',
        'Sensitive data may include:',
        'Users should not enter secrets, credentials, private keys, or sensitive regulated data into fields or tools not designed for that information.',
      ],
      bullets: [
        'Government identification numbers',
        'Financial account information',
        'Payment card information',
        'Health information',
        'Biometric information',
        'Precise location information',
        'Credentials, passwords, tokens, private keys, and secrets',
        'Children’s data',
        'Regulated customer data',
        'Confidential business information',
      ],
    },
    {
      id: 'location-information',
      title: '33. Location Information',
      body: [
        'Cookies and tracking technologies may infer approximate location from IP address or browser/device information.',
        'Approximate location may be used for:',
        'Aerealith AI should not collect precise location information unless a feature requires it and appropriate notice or consent is provided.',
      ],
      bullets: [
        'Security',
        'Fraud prevention',
        'Regional settings',
        'Tax calculation',
        'Compliance',
        'Analytics',
        'Content localization',
        'Service availability',
      ],
    },
    {
      id: 'cross-device-tracking',
      title: '34. Cross-Device Tracking',
      body: [
        'Aerealith AI may associate activity across devices when a user signs in to the same account.',
        'This may help:',
        'Aerealith AI should not use cross-device tracking for advertising without appropriate consent or legal basis where required.',
      ],
      bullets: [
        'Maintain sessions',
        'Sync preferences',
        'Secure accounts',
        'Support workspace continuity',
        'Provide account-level settings',
        'Detect suspicious access',
        'Improve product experience',
      ],
    },
    {
      id: 'organization-and-enterprise-controls',
      title: '35. Organization and Enterprise Controls',
      body: [
        'Organization administrators may have additional controls over cookies, tracking, telemetry, analytics, and retention depending on their plan and deployment type.',
        'Organization controls may include:',
        'Organization administrators are responsible for configuring Aerealith AI according to their legal, security, and compliance requirements.',
      ],
      bullets: [
        'Disabling optional analytics',
        'Restricting third-party integrations',
        'Configuring self-hosted analytics',
        'Controlling marketplace items',
        'Managing user consent settings',
        'Enforcing regional data handling rules',
        'Configuring audit logs',
        'Managing retention',
        'Disabling marketing trackers in organization workspaces',
        'Using private or air-gapped deployments',
      ],
    },
    {
      id: 'self-hosted-hybrid-and-air-gapped-deployments',
      title: '36. Self-Hosted, Hybrid, and Air-Gapped Deployments',
      body: [
        'Self-hosted, hybrid, private, and air-gapped deployments may use different cookie and tracking behavior.',
        'In these deployments:',
        'The operator of a self-hosted or air-gapped deployment is responsible for configuring cookie and tracking behavior appropriately.',
      ],
      bullets: [
        'The customer or organization may control analytics',
        'Third-party trackers may be disabled',
        'Local telemetry may be used',
        'Internet-based tracking may not be available',
        'Cookie banners may be organization-managed',
        'Logs may remain within the customer environment',
        'Consent tools may be configured by the customer',
        'Marketplace and plugin behavior may differ',
      ],
    },
    {
      id: 'international-users',
      title: '37. International Users',
      body: [
        'Cookie and tracking laws vary by location.',
        'Depending on where users are located, Aerealith AI may provide different consent notices, settings, opt-outs, or disclosures.',
        'Where applicable law gives users rights that cannot be waived, this policy does not limit those rights.',
      ],
    },
    {
      id: 'your-choices',
      title: '38. Your Choices',
      body: [
        'Depending on location, account type, deployment, and settings, users may be able to:',
        'Privacy rights are explained in more detail in the Privacy Policy.',
      ],
      bullets: [
        'Accept optional cookies',
        'Reject optional cookies',
        'Customize cookie categories',
        'Withdraw consent',
        'Delete cookies through browser settings',
        'Use browser privacy controls',
        'Use Global Privacy Control',
        'Opt out of sale or sharing',
        'Opt out of targeted advertising',
        'Unsubscribe from marketing emails',
        'Request access to personal data',
        'Request deletion of personal data',
        'Request correction of personal data',
        'Contact us about privacy choices',
      ],
      links: [
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy-policy',
        },
      ],
    },
    {
      id: 'how-to-manage-cookie-choices',
      title: '39. How to Manage Cookie Choices',
      body: [
        'Where supported, users can manage cookie choices by:',
        'Before publishing this policy, update this section with the exact location of Aerealith AI cookie settings.',
      ],
      orderedItems: [
        'Opening the cookie settings link in the website footer.',
        'Opening privacy settings in the Aerealith AI account.',
        'Adjusting browser cookie settings.',
        'Clearing cookies and site data in the browser.',
        'Using supported browser privacy signals.',
        'Contacting us using the contact information in this policy.',
      ],
    },
    {
      id: 'impact-of-disabling-cookies',
      title: '40. Impact of Disabling Cookies',
      body: [
        'Disabling cookies may affect Aerealith AI.',
        'Possible effects include:',
        'Strictly necessary cookies are required for core service functionality.',
      ],
      bullets: [
        'Users may be signed out.',
        'Login may not work.',
        'Security checks may fail.',
        'Billing or checkout may not complete.',
        'Preferences may not be saved.',
        'Dashboards may not load correctly.',
        'Documentation settings may be lost.',
        'Marketplace features may not work.',
        'Support widgets may not work.',
        'Certain integrations may fail.',
        'Consent choices may need to be re-entered.',
      ],
    },
    {
      id: 'relationship-to-other-policies',
      title: '41. Relationship to Other Policies',
      body: [
        'This policy works together with other Aerealith AI policies, including:',
        'If there is a conflict between this policy and a written agreement signed by SinLess Games LLC, the written agreement controls only to the extent of that conflict.',
      ],
      links: [
        {
          label: 'Terms of Use',
          href: '/Policies/terms-of-use',
        },
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy-policy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data-policy',
        },
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
        {
          label: 'AI Transparency Policy',
          href: '/Policies/ai-transparency',
        },
        {
          label: 'Billing, Refund, and Cancellation Policy',
          href: '/Policies/billing-refund-cancellation',
        },
        {
          label: 'Subprocessor Vendor List',
          href: '/Policies/subprocessor-vendor-list',
        },
        {
          label: 'Support Policy',
          href: '/Policies/support-policy',
        },
        {
          label: 'Underage Policy',
          href: '/Policies/underage-policy',
        },
      ],
    },
    {
      id: 'contact',
      title: '42. Contact',
      body: [
        'Questions about cookies, tracking, consent, or privacy choices may be sent to:',
        'Before publishing this policy, confirm these email aliases exist and are monitored.',
      ],
      contacts: [
        {
          label: 'Privacy',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
        {
          label: 'Support',
          email: 'support@sinlessgames.com',
          href: 'mailto:support@sinlessgames.com',
        },
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
      ],
    },
    {
      id: 'changes-to-this-policy',
      title: '43. Changes to This Policy',
      body: [
        'We may update this policy from time to time.',
        'When we make material changes, we will update the last_updated date and may provide notice through the service, documentation, cookie banner, account settings, email, release notes, or another reasonable method.',
        'Continued use of Aerealith AI after changes become effective means you accept the updated policy.',
      ],
    },
    {
      id: 'legal-review-notice',
      title: '44. Legal Review Notice',
      body: [
        'This policy is a draft template and should be reviewed by qualified legal counsel before publication.',
        'Cookie, tracking, consent, analytics, advertising, sale, sharing, and targeted advertising requirements vary by jurisdiction.',
      ],
    },
  ],
} satisfies PolicyDocument;

export default cookieTrackingPolicy;
