import type { PolicyDocument } from '../../types';

export const copyrightTakedownPolicy = {
  slug: 'copyright-takedown',
  path: '/Policies/copyright-takedown',
  meta: {
    title: 'Copyright Takedown Policy',
    description:
      'Explains how Aerealith AI handles copyright complaints, DMCA notices, counter-notices, repeat infringers, and copyright-related takedown requests.',
    effectiveDate: '2026-05-18',
    lastUpdated: '2026-05-18',
    owner: 'SinLess Games LLC',
    status: 'draft',
  },
  relatedPolicies: [
    {
      label: 'Terms of Use',
      href: '/Policies/terms-of-use',
    },
    {
      label: 'Privacy Policy',
      href: '/Policies/privacy-policy',
    },
    {
      label: 'Data Policy',
      href: '/Policies/data-policy',
    },
    {
      label: 'Security Policy',
      href: '/Policies/security-policy',
    },
    {
      label: 'Acceptable Use Policy',
      href: '/Policies/acceptable-use',
    },
    {
      label: 'AI Transparency Policy',
      href: '/Policies/ai-transparency',
    },
    {
      label: 'Responsible AI Policy',
      href: '/Policies/responsible-ai',
    },
    {
      label: 'User-Generated Content Policy',
      href: '/Policies/user-generated-content',
    },
    {
      label: 'Marketplace Policy',
      href: '/Policies/marketplace',
    },
    {
      label: 'Developer and API Policy',
      href: '/Policies/developer-api',
    },
  ],
  sections: [
    {
      id: 'purpose',
      title: '1. Purpose',
      body: [
        'This Copyright Takedown Policy explains how SinLess Games LLC handles copyright complaints, takedown requests, counter-notices, repeat infringers, and copyright-related disputes involving Aerealith AI.',
        'Aerealith AI may allow users, organizations, developers, marketplace publishers, and third-party integrations to upload, generate, store, publish, share, transform, summarize, distribute, or otherwise process content. Because that content may include copyrighted material, this policy describes how copyright owners may report alleged infringement and how affected users may respond.',
        'This policy is intended to support lawful copyright enforcement, fair dispute handling, and responsible platform operation.',
      ],
    },
    {
      id: 'scope',
      title: '2. Scope',
      body: [
        'This policy applies to Aerealith AI services, including:',
        'This policy applies to users, account owners, organization administrators, developers, marketplace publishers, copyright owners, authorized agents, and anyone who submits or receives a copyright-related notice through Aerealith AI.',
      ],
      bullets: [
        'Websites',
        'Web applications',
        'Desktop applications',
        'Mobile applications',
        'Browser extensions',
        'APIs',
        'Documentation sites',
        'Developer portals',
        'Marketplace items',
        'Plugins',
        'Integrations',
        'Workflows',
        'Dashboards',
        'Templates',
        'Personalities',
        'Uploaded files',
        'Shared content',
        'Published content',
        'User-generated content',
        'Organization workspaces',
        'Cloud-hosted, self-hosted, hybrid, and air-gapped deployments, where applicable',
      ],
    },
    {
      id: 'relationship-to-other-policies',
      title: '3. Relationship to Other Policies',
      body: [
        'This policy works together with other Aerealith AI policies, including:',
        'If there is a conflict between this policy and a written agreement signed by SinLess Games LLC, the written agreement controls only to the extent of that conflict.',
      ],
      links: [
        {
          label: 'Terms of Use',
          href: '/Policies/terms-of-use',
        },
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy-policy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data-policy',
        },
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
        {
          label: 'AI Transparency Policy',
          href: '/Policies/ai-transparency',
        },
        {
          label: 'Responsible AI Policy',
          href: '/Policies/responsible-ai',
        },
        {
          label: 'User-Generated Content Policy',
          href: '/Policies/user-generated-content',
        },
        {
          label: 'Marketplace Policy',
          href: '/Policies/marketplace',
        },
        {
          label: 'Developer and API Policy',
          href: '/Policies/developer-api',
        },
      ],
    },
    {
      id: 'no-legal-advice',
      title: '4. No Legal Advice',
      body: [
        'This policy is provided for informational and operational purposes.',
        'It is not legal advice.',
        'Copyright law can be complex, and rights may vary by country, jurisdiction, content type, license, contract, and use case. If you are unsure about your rights or obligations, consult a qualified attorney.',
      ],
    },
    {
      id: 'copyright-ownership-and-user-responsibility',
      title: '5. Copyright Ownership and User Responsibility',
      body: [
        'Users are responsible for ensuring that they have the rights, licenses, permissions, exceptions, or legal basis needed to upload, generate, store, process, publish, distribute, share, modify, transform, or use content through Aerealith AI.',
        'You may not use Aerealith AI to infringe another person’s copyright or other intellectual property rights.',
        'You are responsible for content and activity associated with your account, organization, workspace, API keys, automations, plugins, integrations, marketplace items, and users.',
      ],
    },
    {
      id: 'prohibited-copyright-activity',
      title: '6. Prohibited Copyright Activity',
      body: ['You may not use Aerealith AI to:'],
      bullets: [
        'Upload, publish, share, or distribute copyrighted material without authorization',
        'Copy, reproduce, or distribute protected works without permission or legal basis',
        'Remove, obscure, or alter copyright notices, license terms, attribution, or provenance information',
        'Circumvent digital rights management, license checks, paywalls, or technical protection measures',
        'Create or distribute tools intended to enable copyright infringement',
        'Publish marketplace items containing content you do not have rights to use',
        'Misrepresent ownership or licensing of content',
        'Use Aerealith AI to mass-copy, scrape, or redistribute copyrighted material in violation of law, contract, or platform rules',
        'Repeatedly upload or publish infringing content after notice',
      ],
    },
    {
      id: 'dmca-designated-agent',
      title: '7. DMCA Designated Agent',
      body: [
        'SinLess Games LLC should designate an agent to receive notices of claimed copyright infringement under the Digital Millennium Copyright Act.',
        'Before publishing this policy, SinLess Games LLC should confirm that the designated agent information has been registered with the U.S. Copyright Office and is accurate.',
        'Copyright notices should be sent to the designated agent listed below.',
        'Before publishing this policy, confirm that the email alias, mailing address, and phone number are valid, monitored, and match the information registered with the U.S. Copyright Office.',
      ],
      bullets: [
        'DMCA Agent: Copyright Agent',
        'Company: SinLess Games LLC',
        'Address: [Insert physical mailing address]',
        'Email: copyright@sinlessgames.com',
        'Phone: [Insert phone number]',
      ],
      contacts: [
        {
          label: 'Copyright',
          email: 'copyright@sinlessgames.com',
          href: 'mailto:copyright@sinlessgames.com',
        },
      ],
    },
    {
      id: 'copyright-takedown-notice-requirements',
      title: '8. Copyright Takedown Notice Requirements',
      body: [
        'If you believe content available through Aerealith AI infringes your copyright, you or your authorized agent may submit a written takedown notice to our designated agent.',
        'Your notice should include:',
        'Incomplete notices may delay processing.',
      ],
      orderedItems: [
        'A physical or electronic signature of the copyright owner or a person authorized to act on behalf of the copyright owner.',
        'Identification of the copyrighted work claimed to have been infringed.',
        'If multiple copyrighted works are covered by one notice, a representative list of those works.',
        'Identification of the allegedly infringing material or activity.',
        'Information reasonably sufficient to allow us to locate the allegedly infringing material or activity.',
        'Your contact information, including name, mailing address, telephone number, and email address.',
        'A statement that you have a good-faith belief that use of the material in the manner complained of is not authorized by the copyright owner, the copyright owner’s agent, or law.',
        'A statement that the information in the notice is accurate.',
        'A statement, under penalty of perjury, that you are the copyright owner or are authorized to act on behalf of the copyright owner.',
      ],
    },
    {
      id: 'helpful-information-to-include',
      title: '9. Helpful Information to Include',
      body: [
        'To help us process a copyright complaint, include as much detail as possible.',
        'Helpful information may include:',
        'Do not include unnecessary sensitive information.',
      ],
      bullets: [
        'The URL or exact location of the allegedly infringing content',
        'The account, workspace, marketplace item, plugin, file, automation, or integration involved',
        'Screenshots',
        'File names',
        'Message IDs',
        'Marketplace listing IDs',
        'API object IDs',
        'Timestamps',
        'A description of the original copyrighted work',
        'Registration numbers, if available',
        'Links to authorized copies of the copyrighted work',
        'Explanation of how the content allegedly infringes',
        'Proof that you are authorized to act for the copyright owner, if submitting as an agent',
      ],
    },
    {
      id: 'where-to-send-takedown-notices',
      title: '10. Where to Send Takedown Notices',
      body: [
        'Send copyright takedown notices to copyright@sinlessgames.com.',
        'You may also send notices by mail to the designated agent address listed in this policy.',
        'Before publishing this policy, confirm whether mail, email, or both will be accepted for formal notices.',
      ],
      contacts: [
        {
          label: 'Copyright',
          email: 'copyright@sinlessgames.com',
          href: 'mailto:copyright@sinlessgames.com',
        },
      ],
    },
    {
      id: 'processing-takedown-notices',
      title: '11. Processing Takedown Notices',
      body: ['When we receive a copyright takedown notice, we may:'],
      bullets: [
        'Review the notice for completeness',
        'Request additional information',
        'Remove or disable access to the allegedly infringing material',
        'Notify the affected user, account owner, workspace administrator, or marketplace publisher',
        'Preserve records related to the complaint',
        'Forward the notice to the affected user or organization',
        'Disable marketplace items, plugins, workflows, templates, or integrations',
        'Restrict accounts, workspaces, API keys, automations, or publishing features',
        'Apply repeat-infringer procedures',
        'Decline to act if the notice is incomplete, invalid, abusive, fraudulent, or unrelated to copyright',
        'We may act quickly when required or appropriate, but submission of a notice does not guarantee removal.',
      ],
    },
    {
      id: 'user-notice-after-removal',
      title: '12. User Notice After Removal',
      body: [
        'If we remove or disable access to content because of a copyright takedown notice, we may notify the affected user or organization.',
        'The notice may include:',
        'We may withhold some information if required by law, policy, safety, privacy, security, or abuse-prevention needs.',
      ],
      bullets: [
        'The content affected',
        'The reason for removal',
        'A copy or summary of the takedown notice',
        'The complaining party’s contact information',
        'Instructions for submitting a counter-notice, where available',
        'Any account, workspace, marketplace, or feature restrictions applied',
      ],
    },
    {
      id: 'counter-notice',
      title: '13. Counter-Notice',
      body: [
        'If your content was removed or disabled because of a copyright takedown notice and you believe the removal was mistaken or the material was misidentified, you may submit a written counter-notice.',
        'Your counter-notice should include:',
        'Counter-notices should be sent to copyright@sinlessgames.com.',
      ],
      orderedItems: [
        'Your physical or electronic signature.',
        'Identification of the material that was removed or disabled.',
        'The location where the material appeared before it was removed or disabled.',
        'A statement, under penalty of perjury, that you have a good-faith belief that the material was removed or disabled because of mistake or misidentification.',
        'Your name, mailing address, telephone number, and email address.',
        'A statement that you consent to the jurisdiction of the federal district court for the judicial district where your address is located.',
        'If your address is outside the United States, a statement that you consent to the jurisdiction of any judicial district where SinLess Games LLC may be found.',
        'A statement that you will accept service of process from the person who submitted the original takedown notice or that person’s agent.',
      ],
      contacts: [
        {
          label: 'Copyright',
          email: 'copyright@sinlessgames.com',
          href: 'mailto:copyright@sinlessgames.com',
        },
      ],
    },
    {
      id: 'counter-notice-processing',
      title: '14. Counter-Notice Processing',
      body: [
        'When we receive a valid counter-notice, we may forward it to the party that submitted the original takedown notice.',
        'We may restore the removed or disabled material after the legally required waiting period unless the original complaining party notifies us that they have filed a court action seeking to restrain the user from engaging in the allegedly infringing activity.',
        'We may decline to restore content if:',
      ],
      bullets: [
        'The counter-notice is incomplete',
        'The counter-notice appears fraudulent or abusive',
        'The content violates another Aerealith AI policy',
        'The content creates security, privacy, safety, or legal risk',
        'The user’s account has been suspended or terminated for other reasons',
        'Restoration is not technically possible',
        'A court order, legal obligation, or written agreement prevents restoration',
      ],
    },
    {
      id: 'repeat-infringer-policy',
      title: '15. Repeat Infringer Policy',
      body: [
        'SinLess Games LLC may terminate or restrict accounts, users, organizations, workspaces, marketplace publishers, plugins, integrations, or developer access for repeat copyright infringement.',
        'Repeat infringement may include:',
        'Enforcement may include:',
        'The exact action may depend on the severity, frequency, context, validity of notices, user response, and legal obligations.',
      ],
      bullets: [
        'Multiple valid copyright takedown notices',
        'Repeated uploads of the same or similar infringing material',
        'Repeated publication of infringing marketplace items',
        'Repeated attempts to evade takedown enforcement',
        'Repeated use of alternate accounts to publish infringing content',
        'Repeated copyright abuse through APIs, automations, plugins, or integrations',
        'Repeated failure to address copyright complaints after notice',
        'Warning the user or organization',
        'Removing or disabling content',
        'Restricting uploads',
        'Restricting sharing or publishing',
        'Restricting marketplace access',
        'Disabling plugins or integrations',
        'Suspending API keys',
        'Suspending accounts or workspaces',
        'Terminating accounts or workspaces',
        'Refusing future service',
      ],
    },
    {
      id: 'standard-technical-measures',
      title: '16. Standard Technical Measures',
      body: [
        'SinLess Games LLC respects standard technical measures used by copyright owners to identify or protect copyrighted works when such measures meet applicable legal requirements.',
        'Users may not interfere with or circumvent standard technical measures, rights-management systems, license checks, provenance systems, watermarking systems, content protection mechanisms, or other lawful copyright-protection controls.',
      ],
    },
    {
      id: 'false-fraudulent-or-abusive-notices',
      title: '17. False, Fraudulent, or Abusive Notices',
      body: [
        'Do not submit false, misleading, fraudulent, abusive, or bad-faith takedown notices or counter-notices.',
        'Misrepresenting that content or activity is infringing, or that content was removed by mistake or misidentification, may result in legal liability.',
        'We may reject, limit, or take action against notices that appear to be:',
        'We may suspend or terminate accounts that abuse copyright reporting systems.',
      ],
      bullets: [
        'Fraudulent',
        'Abusive',
        'Harassing',
        'Retaliatory',
        'Automated without reasonable review',
        'Unsupported by copyright ownership or authorization',
        'Designed to suppress lawful speech',
        'Designed to interfere with competitors',
        'Designed to evade Aerealith AI policies',
        'Repeatedly incomplete or inaccurate',
      ],
    },
    {
      id: 'non-copyright-complaints',
      title: '18. Non-Copyright Complaints',
      body: [
        'This policy is for copyright complaints only.',
        'Do not use this process for:',
        'For non-copyright issues, use the appropriate contact or policy.',
        'Examples:',
      ],
      bullets: [
        'Trademark complaints',
        'Defamation complaints',
        'Privacy complaints',
        'Harassment reports',
        'Security reports',
        'Terms of Use violations',
        'Marketplace quality complaints',
        'Billing disputes',
        'Contract disputes',
        'Data deletion requests',
        'Right of publicity claims',
        'Patent claims',
        'Trade secret claims',
      ],
      contacts: [
        {
          label: 'Privacy',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
        {
          label: 'Security',
          email: 'security@sinlessgames.com',
          href: 'mailto:security@sinlessgames.com',
        },
        {
          label: 'Abuse',
          email: 'abuse@sinlessgames.com',
          href: 'mailto:abuse@sinlessgames.com',
        },
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
        {
          label: 'Support',
          email: 'support@sinlessgames.com',
          href: 'mailto:support@sinlessgames.com',
        },
      ],
    },
    {
      id: 'trademark-and-brand-complaints',
      title: '19. Trademark and Brand Complaints',
      body: [
        'Trademark and brand complaints are not handled through the DMCA takedown process.',
        'If you believe content on Aerealith AI misuses your trademark, brand, logo, trade name, or business identity, contact legal@sinlessgames.com.',
        'Include:',
        'We may review trademark complaints under our Terms of Use, Acceptable Use Policy, marketplace rules, and applicable law.',
      ],
      bullets: [
        'Your name and contact information',
        'The trademark or brand at issue',
        'Registration information, if available',
        'The location of the allegedly infringing content',
        'A description of the issue',
        'Evidence of ownership or authorization',
        'The action you request',
      ],
      contacts: [
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
      ],
      links: [
        {
          label: 'Terms of Use',
          href: '/Policies/terms-of-use',
        },
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
      ],
    },
    {
      id: 'marketplace-copyright-rules',
      title: '20. Marketplace Copyright Rules',
      body: [
        'Marketplace publishers are responsible for ensuring that marketplace items comply with copyright law and licensing requirements.',
        'Marketplace items may include:',
        'Marketplace publishers may not submit items containing copyrighted content unless they have the necessary rights, licenses, permissions, or legal basis.',
        'We may remove, suspend, disable, delist, or restrict marketplace items that are alleged or found to infringe copyright.',
        'Marketplace enforcement may also affect publisher accounts, payouts, ratings, reviews, revenue share, and future publishing privileges.',
      ],
      bullets: [
        'Plugins',
        'Connectors',
        'Workflows',
        'Dashboards',
        'Templates',
        'Personalities',
        'Prompt packs',
        'Documentation',
        'Icons',
        'Images',
        'Audio',
        'Video',
        'Code',
        'Datasets',
        'Model configuration files',
        'Generated assets',
      ],
    },
    {
      id: 'open-source-and-third-party-licenses',
      title: '21. Open Source and Third-Party Licenses',
      body: [
        'Users and developers are responsible for complying with open source and third-party license terms.',
        'This includes obligations related to:',
        'Aerealith AI may remove or restrict code, plugins, templates, workflows, or marketplace items that appear to violate open source or third-party license obligations.',
      ],
      bullets: [
        'Attribution',
        'Copyright notices',
        'Source code availability',
        'Copyleft terms',
        'License compatibility',
        'Redistribution rights',
        'Modification notices',
        'Commercial-use restrictions',
        'Dependency licensing',
        'Third-party asset licensing',
      ],
    },
    {
      id: 'ai-generated-content-and-copyright',
      title: '22. AI-Generated Content and Copyright',
      body: [
        'Aerealith AI may assist users in generating, transforming, summarizing, or analyzing content.',
        'Users remain responsible for reviewing AI-generated or AI-assisted content before using, publishing, distributing, or commercializing it.',
        'AI-generated content may raise copyright, licensing, attribution, originality, publicity, trademark, contract, or platform-policy issues.',
        'Users should not use Aerealith AI to intentionally generate content that infringes copyrighted works or unlawfully imitates protected material.',
        'If you believe AI-generated or AI-assisted content on Aerealith AI infringes your copyright, you may submit a copyright takedown notice under this policy.',
      ],
    },
    {
      id: 'user-content-backups-and-cached-copies',
      title: '23. User Content Backups and Cached Copies',
      body: [
        'Removing or disabling access to content may not immediately remove every backup, cache, log, preview, index, derivative, analytics record, or system copy.',
        'We may retain limited copies or records where necessary for:',
        'Retained copies will be handled according to applicable policies, legal obligations, and retention rules.',
      ],
      bullets: [
        'Legal compliance',
        'Security',
        'Abuse prevention',
        'Audit logs',
        'Dispute resolution',
        'Backup integrity',
        'Incident response',
        'Billing records',
        'Enforcement records',
        'Operation of the service',
      ],
    },
    {
      id: 'organization-workspaces',
      title: '24. Organization Workspaces',
      body: [
        'For organization workspaces, we may notify organization administrators about copyright complaints involving their users, content, marketplace items, plugins, integrations, automations, or shared assets.',
        'Organization administrators may have additional responsibilities to:',
        'Organization agreements may include additional copyright, indemnity, content ownership, and takedown terms.',
      ],
      bullets: [
        'Investigate internal misuse',
        'Remove infringing content',
        'Disable infringing workflows',
        'Manage user access',
        'Preserve relevant records',
        'Enforce organization policies',
        'Respond to legal requests',
        'Cooperate with SinLess Games LLC where appropriate',
      ],
    },
    {
      id: 'self-hosted-hybrid-and-air-gapped-deployments',
      title: '25. Self-Hosted, Hybrid, and Air-Gapped Deployments',
      body: [
        'For self-hosted, hybrid, private, or air-gapped deployments, copyright takedown handling may depend on the deployment model and contract.',
        'The organization operating the deployment may be responsible for:',
        'SinLess Games LLC may still enforce license terms, marketplace rules, account terms, or service terms related to Aerealith AI software, updates, hosted services, cloud components, or official marketplace access.',
      ],
      bullets: [
        'Receiving copyright complaints',
        'Removing or disabling infringing content',
        'Managing users and workspaces',
        'Maintaining audit logs',
        'Enforcing repeat-infringer policies',
        'Responding to legal notices',
        'Complying with local copyright law',
        'Controlling marketplace access',
        'Reviewing private plugins and templates',
      ],
    },
    {
      id: 'international-copyright-complaints',
      title: '26. International Copyright Complaints',
      body: [
        'Although this policy is based primarily on the U.S. DMCA process, SinLess Games LLC may review copyright complaints from outside the United States.',
        'International copyright complaints should include enough information for us to identify:',
        'We may apply DMCA-style procedures, local legal requirements, platform rules, contractual obligations, or other reasonable processes depending on the situation.',
      ],
      bullets: [
        'The copyrighted work',
        'The allegedly infringing material',
        'The complainant',
        'The rights owner',
        'The legal basis for the complaint',
        'The requested action',
        'The relevant country or jurisdiction',
      ],
    },
    {
      id: 'account-and-data-access-during-disputes',
      title: '27. Account and Data Access During Disputes',
      body: [
        'Copyright disputes may affect access to content, accounts, workspaces, marketplace items, plugins, automations, or API features.',
        'Depending on the circumstances, we may:',
        'Content removal does not necessarily delete the user’s entire account or all account data.',
      ],
      bullets: [
        'Remove specific content',
        'Disable sharing links',
        'Disable public publishing',
        'Disable marketplace listings',
        'Pause automations',
        'Disable API access to disputed content',
        'Restrict uploads',
        'Restrict account features',
        'Suspend accounts or workspaces',
        'Preserve records related to the dispute',
      ],
    },
    {
      id: 'privacy-and-notice-sharing',
      title: '28. Privacy and Notice Sharing',
      body: [
        'When processing a copyright complaint, we may share information between the complaining party and the affected user or organization.',
        'This may include:',
        'Do not include sensitive personal information in a notice or counter-notice unless necessary.',
        'Information may also be disclosed where required by law, court order, subpoena, legal process, dispute resolution, enforcement, or safety needs.',
      ],
      bullets: [
        'The takedown notice',
        'The counter-notice',
        'Names',
        'Email addresses',
        'Mailing addresses',
        'Telephone numbers',
        'Content identifiers',
        'URLs',
        'Statements made in the notice or counter-notice',
      ],
    },
    {
      id: 'records-and-retention',
      title: '29. Records and Retention',
      body: [
        'We may retain records related to copyright complaints, takedowns, counter-notices, repeat-infringer decisions, enforcement actions, and related communications.',
        'Records may be retained for purposes including:',
        'Retention periods may vary depending on legal requirements, account status, organization agreements, and operational needs.',
      ],
      bullets: [
        'Legal compliance',
        'Dispute resolution',
        'Repeat-infringer tracking',
        'Abuse prevention',
        'Security',
        'Auditability',
        'Policy enforcement',
        'Litigation hold',
        'Business records',
        'Marketplace enforcement',
        'Organization administration',
      ],
    },
    {
      id: 'no-waiver',
      title: '30. No Waiver',
      body: [
        'Failure to enforce this policy in one situation does not waive our right to enforce it in another situation.',
        'We may take action under this policy, the Terms of Use, the Acceptable Use Policy, marketplace rules, developer rules, security rules, or applicable law.',
      ],
      links: [
        {
          label: 'Terms of Use',
          href: '/Policies/terms-of-use',
        },
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
      ],
    },
    {
      id: 'reporting-copyright-concerns',
      title: '31. Reporting Copyright Concerns',
      body: [
        'Copyright concerns should be sent to copyright@sinlessgames.com.',
        'Other legal concerns may be sent to legal@sinlessgames.com.',
        'Before publishing this policy, confirm these email aliases exist and are monitored.',
      ],
      contacts: [
        {
          label: 'Copyright',
          email: 'copyright@sinlessgames.com',
          href: 'mailto:copyright@sinlessgames.com',
        },
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
      ],
    },
    {
      id: 'changes-to-this-policy',
      title: '32. Changes to This Policy',
      body: [
        'We may update this policy from time to time.',
        'When we make material changes, we will update the last_updated date and may provide notice through the service, documentation, account settings, email, release notes, legal notices page, or another reasonable method.',
        'Continued use of Aerealith AI after changes become effective means you accept the updated policy.',
      ],
    },
    {
      id: 'contact',
      title: '33. Contact',
      body: [
        'Questions about this policy may be sent to legal@sinlessgames.com.',
        'Copyright notices should be sent to copyright@sinlessgames.com.',
      ],
      contacts: [
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
        {
          label: 'Copyright',
          email: 'copyright@sinlessgames.com',
          href: 'mailto:copyright@sinlessgames.com',
        },
      ],
    },
    {
      id: 'publication-checklist',
      title: '34. Publication Checklist',
      body: ['Before publishing this policy, complete the following:'],
      bullets: [
        'Confirm the official legal name: SinLess Games LLC',
        'Confirm the designated DMCA agent name',
        'Confirm the physical mailing address',
        'Confirm the phone number',
        'Confirm copyright@sinlessgames.com exists and is monitored',
        'Confirm legal@sinlessgames.com exists and is monitored',
        'Register or update the DMCA designated agent with the U.S. Copyright Office',
        'Ensure the public agent information matches the Copyright Office directory',
        'Add this policy to the website footer or legal page',
        'Confirm takedown and counter-notice intake workflow',
        'Confirm internal escalation process',
        'Confirm repeat-infringer tracking process',
        'Confirm marketplace enforcement process',
        'Confirm retention and audit logging behavior',
        'Have qualified legal counsel review this policy',
      ],
    },
    {
      id: 'legal-review-notice',
      title: '35. Legal Review Notice',
      body: [
        'This policy is a draft template and should be reviewed by qualified legal counsel before publication.',
        'Copyright, DMCA, platform liability, counter-notice, safe-harbor, marketplace, AI-generated content, and international copyright requirements may vary by jurisdiction.',
      ],
    },
  ],
} satisfies PolicyDocument;

export default copyrightTakedownPolicy;
