import type { PolicyDocument } from '../../types';

export const incidentNotificationPolicy = {
  slug: 'incident-notification',
  path: '/Policies/incident-notification',
  meta: {
    title: 'Incident Notification Policy',
    description:
      'Explains how Aerealith AI identifies, classifies, communicates, escalates, and reports service, security, privacy, data, and operational incidents.',
    effectiveDate: '2026-05-18',
    lastUpdated: '2026-05-18',
    owner: 'SinLess Games LLC',
    status: 'draft',
  },
  relatedPolicies: [
    {
      label: 'Terms of Use',
      href: '/Policies/terms-of-use',
    },
    {
      label: 'Privacy Policy',
      href: '/Policies/privacy-policy',
    },
    {
      label: 'Data Policy',
      href: '/Policies/data',
    },
    {
      label: 'Security Policy',
      href: '/Policies/security-policy',
    },
    {
      label: 'Acceptable Use Policy',
      href: '/Policies/acceptable-use',
    },
    {
      label: 'AI Transparency Policy',
      href: '/Policies/ai-transparency',
    },
    {
      label: 'Responsible AI Policy',
      href: '/Policies/responsible-ai',
    },
    {
      label: 'Billing, Refund, and Cancellation Policy',
      href: '/Policies/billing-refund-cancellation',
    },
    {
      label: 'Cookie and Tracking Policy',
      href: '/Policies/cookie-tracking',
    },
    {
      label: 'Copyright Takedown Policy',
      href: '/Policies/copyright-takedown',
    },
    {
      label: 'User-Generated Content Policy',
      href: '/Policies/user-generated-content',
    },
    {
      label: 'Subprocessor Vendor List',
      href: '/Policies/subprocessor-vendor-list',
    },
    {
      label: 'Support Policy',
      href: '/Policies/support-policy',
    },
  ],
  sections: [
    {
      id: 'purpose',
      title: '1. Purpose',
      body: [
        'This Incident Notification Policy explains how SinLess Games LLC communicates about incidents affecting Aerealith AI.',
        'Aerealith AI is designed to support users, organizations, developers, automations, integrations, analytics, infrastructure workflows, AI memory, and connected services. Because incidents may affect availability, security, privacy, data integrity, automation behavior, integrations, or user trust, SinLess Games LLC will use reasonable processes to identify, investigate, respond to, and notify affected parties when appropriate.',
        'This policy explains:',
      ],
      bullets: [
        'What counts as an incident',
        'How incidents are classified',
        'How users and organizations may be notified',
        'What information may be included in notifications',
        'How updates and post-incident reviews may be handled',
        'How this policy applies to cloud-hosted, self-hosted, hybrid, and air-gapped deployments',
      ],
    },
    {
      id: 'scope',
      title: '2. Scope',
      body: [
        'This policy applies to Aerealith AI services, including:',
        'This policy applies to:',
      ],
      bullets: [
        'Websites',
        'Web applications',
        'Desktop applications',
        'Mobile applications',
        'Browser extensions',
        'APIs',
        'Developer tools',
        'Marketplace features',
        'Plugins',
        'Automations',
        'Integrations',
        'Dashboards',
        'Analytics features',
        'Memory features',
        'Organization workspaces',
        'Documentation sites',
        'Support systems',
        'Cloud-hosted deployments',
        'Self-hosted deployments, where applicable',
        'Hybrid deployments, where applicable',
        'Air-gapped deployments, where applicable',
        'Individual users',
        'Organization users',
        'Workspace administrators',
        'Enterprise customers',
        'Developers',
        'Marketplace publishers',
        'API users',
        'Support contacts',
        'Billing contacts',
        'Security contacts',
        'Legal contacts',
        'Anyone affected by a Aerealith AI incident',
      ],
    },
    {
      id: 'incident-definition',
      title: '3. Incident Definition',
      body: [
        'An incident is an event that may negatively affect the confidentiality, integrity, availability, reliability, safety, security, privacy, compliance, or expected operation of Aerealith AI.',
        'Incidents may include:',
        'Not every bug, support request, failed request, model error, or temporary delay is an incident. SinLess Games LLC will classify events based on severity, impact, scope, risk, and required response.',
      ],
      bullets: [
        'Service outages',
        'Degraded service',
        'API failures',
        'Login or authentication failures',
        'Payment or billing disruptions',
        'Data loss or corruption',
        'Unauthorized access',
        'Security vulnerabilities being actively exploited',
        'Privacy incidents',
        'Data incidents',
        'Misconfigured permissions',
        'Incorrect automation behavior',
        'Marketplace or plugin abuse',
        'AI safety failures',
        'Incorrect model routing',
        'Tool execution failures',
        'Integration failures',
        'Infrastructure failures',
        'Backup or recovery failures',
        'Monitoring or alerting failures',
        'Vendor or subprocessor outages',
        'Legal, compliance, or regulatory events affecting service operation',
      ],
    },
    {
      id: 'incident-categories',
      title: '4. Incident Categories',
      body: [
        'Aerealith AI incidents may be grouped into one or more categories.',
      ],
    },
    {
      id: 'service-availability-incident',
      title: '4.1 Service Availability Incident',
      body: [
        'A service availability incident affects the ability to access or use Aerealith AI.',
        'Examples include:',
      ],
      bullets: [
        'Full service outage',
        'Partial service outage',
        'API unavailability',
        'Dashboard unavailability',
        'Documentation site outage',
        'Login outage',
        'Marketplace outage',
        'Integration outage',
        'Significant latency',
        'Failed model routing',
        'Payment portal outage',
      ],
    },
    {
      id: 'security-incident',
      title: '4.2 Security Incident',
      body: [
        'A security incident involves suspected or confirmed compromise, unauthorized access, exploitation, or security control failure.',
        'Examples include:',
      ],
      bullets: [
        'Unauthorized account access',
        'Unauthorized administrative access',
        'Credential exposure',
        'API key exposure',
        'Token misuse',
        'Exploited vulnerability',
        'Malware or malicious plugin behavior',
        'Suspicious infrastructure activity',
        'Abuse of integrations or automations',
        'Attempted or successful data exfiltration',
        'Compromised vendor or subprocessor account',
      ],
    },
    {
      id: 'privacy-incident',
      title: '4.3 Privacy Incident',
      body: [
        'A privacy incident involves suspected or confirmed unauthorized access, disclosure, misuse, loss, alteration, or improper processing of personal data.',
        'Examples include:',
      ],
      bullets: [
        'Personal data sent to the wrong user',
        'Incorrect workspace access',
        'Incorrect organization membership exposure',
        'Incorrect export or deletion behavior',
        'Misconfigured analytics or tracking',
        'Unauthorized processing of personal data',
        'Improper subprocessor data handling',
        'Inadvertent disclosure in support, logs, or notifications',
      ],
    },
    {
      id: 'data-incident',
      title: '4.4 Data Incident',
      body: [
        'A data incident affects the availability, integrity, accuracy, retention, deletion, confidentiality, or recoverability of data.',
        'Examples include:',
      ],
      bullets: [
        'Data corruption',
        'Data loss',
        'Failed backup',
        'Failed restore',
        'Incorrect deletion',
        'Incorrect retention behavior',
        'Memory corruption',
        'Vector index corruption',
        'Search index corruption',
        'Incorrect workspace data access',
        'Incorrect dashboard calculations',
        'Incorrect analytics data processing',
      ],
    },
    {
      id: 'ai-safety-incident',
      title: '4.5 AI Safety Incident',
      body: [
        'An AI safety incident involves AI behavior that creates meaningful risk to users, organizations, systems, or the public.',
        'Examples include:',
      ],
      bullets: [
        'Unsafe tool use',
        'Improper automation execution',
        'Incorrect high-impact recommendation without safeguards',
        'Bypass of approval gates',
        'Unsafe plugin behavior',
        'Unauthorized model routing',
        'Leakage of restricted context',
        'Repeated hallucination in a sensitive workflow',
        'Failure to respect user or organization safety settings',
        'Misclassification that creates security, privacy, or compliance risk',
      ],
    },
    {
      id: 'marketplace-or-plugin-incident',
      title: '4.6 Marketplace or Plugin Incident',
      body: [
        'A marketplace or plugin incident involves a plugin, connector, workflow, template, dashboard, personality, or marketplace item.',
        'Examples include:',
      ],
      bullets: [
        'Malicious marketplace item',
        'Excessive permission request',
        'Data exfiltration',
        'Hidden tracking',
        'Dependency compromise',
        'Publisher account compromise',
        'Plugin sandbox escape',
        'Incorrect plugin update',
        'Unsafe workflow automation',
        'Marketplace payment or licensing failure',
      ],
    },
    {
      id: 'vendor-or-subprocessor-incident',
      title: '4.7 Vendor or Subprocessor Incident',
      body: [
        'A vendor or subprocessor incident involves a third-party service used to provide Aerealith AI.',
        'Examples include:',
      ],
      bullets: [
        'Hosting outage',
        'AI provider outage',
        'Payment processor outage',
        'Authentication provider outage',
        'Email provider outage',
        'Analytics provider incident',
        'Observability provider outage',
        'Cloud storage incident',
        'Vendor security incident',
        'Vendor privacy incident',
      ],
    },
    {
      id: 'severity-levels',
      title: '5. Severity Levels',
      body: [
        'SinLess Games LLC may classify incidents by severity.',
        'Severity levels may be adjusted as new information becomes available.',
      ],
    },
    {
      id: 'severity-1-critical',
      title: 'Severity 1: Critical',
      body: ['A critical incident may include:'],
      bullets: [
        'Widespread outage of core Aerealith AI services',
        'Confirmed unauthorized access to sensitive data',
        'Confirmed data breach affecting multiple users or organizations',
        'Active exploitation of a critical vulnerability',
        'Loss of production data without immediate recovery',
        'Dangerous automation behavior affecting production systems',
        'Severe privacy or security risk',
        'Severe impact to enterprise customers',
        'Public safety, legal, or regulatory urgency',
      ],
    },
    {
      id: 'severity-2-high',
      title: 'Severity 2: High',
      body: ['A high-severity incident may include:'],
      bullets: [
        'Major feature outage',
        'Significant service degradation',
        'Confirmed limited unauthorized access',
        'High-risk vulnerability without confirmed widespread exploitation',
        'Data integrity issue affecting important features',
        'Significant integration failure',
        'Incorrect permission behavior affecting a limited group',
        'Marketplace item creating meaningful risk',
        'AI safety issue requiring urgent mitigation',
      ],
    },
    {
      id: 'severity-3-medium',
      title: 'Severity 3: Medium',
      body: ['A medium-severity incident may include:'],
      bullets: [
        'Partial feature degradation',
        'Limited API disruption',
        'Limited dashboard or reporting issue',
        'Isolated data inconsistency',
        'Non-critical integration failure',
        'Non-critical marketplace issue',
        'Moderate latency or error-rate increase',
        'Security or privacy concern requiring investigation but no confirmed major impact',
      ],
    },
    {
      id: 'severity-4-low',
      title: 'Severity 4: Low',
      body: ['A low-severity incident may include:'],
      bullets: [
        'Minor service disruption',
        'Minor documentation or status issue',
        'Cosmetic or low-impact product issue',
        'Isolated user-impacting bug',
        'Low-risk misconfiguration',
        'Minor delay in non-critical processing',
        'Degraded feature with available workaround',
      ],
    },
    {
      id: 'notification-principles',
      title: '6. Notification Principles',
      body: [
        'SinLess Games LLC will use reasonable efforts to notify affected users or organizations when an incident materially affects them.',
        'Incident notifications should be:',
        'Initial notifications may be incomplete while an investigation is ongoing.',
        'SinLess Games LLC may delay, limit, or modify notifications when necessary to protect users, prevent further harm, preserve evidence, comply with law, avoid interfering with an investigation, or follow instructions from legal authorities.',
      ],
      bullets: [
        'Timely',
        'Accurate',
        'Clear',
        'Useful',
        'Proportionate to impact',
        'Updated as facts become available',
        'Careful not to expose sensitive details',
        'Consistent with legal, security, privacy, and contractual obligations',
      ],
    },
    {
      id: 'notification-channels',
      title: '7. Notification Channels',
      body: [
        'Incident notifications may be sent through one or more channels depending on the incident type, severity, scope, and affected users.',
        'Notification channels may include:',
        'Before publishing this policy, confirm the official Aerealith AI status page URL and support channels.',
      ],
      bullets: [
        'Status page',
        'In-app banner',
        'Account notification',
        'Organization admin notification',
        'Email',
        'Support ticket',
        'Incident report',
        'Enterprise account contact',
        'Security contact',
        'Legal contact',
        'Billing contact',
        'Developer portal notice',
        'Marketplace publisher notice',
        'API status notice',
        'Documentation update',
        'Release notes',
        'Direct communication from support or customer success',
      ],
    },
    {
      id: 'status-page',
      title: '8. Status Page',
      body: [
        'Aerealith AI should maintain a public or customer-accessible status page for service availability and major incidents.',
        'The status page may include:',
        'Some security, privacy, data, or abuse-related incidents may not be fully described on the public status page if public disclosure would increase risk or expose sensitive information.',
      ],
      bullets: [
        'Current system status',
        'Active incidents',
        'Degraded components',
        'Scheduled maintenance',
        'Past incidents',
        'Updates',
        'Resolution notices',
        'Component-level service health',
        'Subscription options for alerts',
      ],
    },
    {
      id: 'notification-timing',
      title: '9. Notification Timing',
      body: [
        'SinLess Games LLC will use reasonable efforts to provide incident notifications as soon as practical after confirming that notification is appropriate.',
        'Notification timing may depend on:',
        'For security, privacy, or data incidents, SinLess Games LLC will provide notifications according to applicable law, contract, and regulatory requirements.',
      ],
      bullets: [
        'Incident severity',
        'Confirmed impact',
        'Legal requirements',
        'Contractual requirements',
        'Security risk',
        'Availability of reliable facts',
        'Scope of affected users',
        'Need to preserve evidence',
        'Need to prevent further harm',
        'Vendor or subprocessor information',
        'Law enforcement or regulatory restrictions',
      ],
    },
    {
      id: 'initial-incident-notification',
      title: '10. Initial Incident Notification',
      body: [
        'An initial incident notification may include:',
        'Initial notifications may change as the investigation continues.',
      ],
      bullets: [
        'A short incident summary',
        'Date and time detected',
        'Affected services or components',
        'Known impact',
        'Affected users or organizations, if known',
        'Current status',
        'Immediate mitigation steps',
        'Expected next update, if available',
        'Recommended user actions, if any',
        'Support contact information',
      ],
    },
    {
      id: 'incident-updates',
      title: '11. Incident Updates',
      body: [
        'During an active incident, SinLess Games LLC may provide updates when meaningful new information is available.',
        'Updates may include:',
        'SinLess Games LLC should avoid speculative updates that could mislead users or create false certainty.',
      ],
      bullets: [
        'Current service status',
        'Newly identified impact',
        'Components affected',
        'Mitigation progress',
        'Workarounds',
        'User actions needed',
        'Estimated recovery information, if reliable',
        'Confirmation of partial recovery',
        'Confirmation of full recovery',
        'Next update timing, if appropriate',
      ],
    },
    {
      id: 'resolution-notice',
      title: '12. Resolution Notice',
      body: [
        'After an incident is resolved, SinLess Games LLC may provide a resolution notice.',
        'A resolution notice may include:',
        'A resolution notice may be brief for low-impact incidents and more detailed for major incidents.',
      ],
      bullets: [
        'Incident summary',
        'Services affected',
        'Time detected',
        'Time mitigated',
        'Time resolved',
        'User impact',
        'Whether user action is needed',
        'Remaining limitations',
        'Support contact information',
        'Whether a post-incident review will be published',
      ],
    },
    {
      id: 'post-incident-review',
      title: '13. Post-Incident Review',
      body: [
        'For significant incidents, SinLess Games LLC may prepare a post-incident review.',
        'A post-incident review may include:',
        'Post-incident reviews may be shared publicly, with affected customers, with enterprise contacts, or internally only depending on the incident.',
        'SinLess Games LLC may withhold sensitive technical details that could increase risk, expose confidential information, compromise security, or violate legal obligations.',
      ],
      bullets: [
        'Executive summary',
        'Timeline',
        'Root cause, if known',
        'Scope of impact',
        'Affected systems',
        'Detection method',
        'Response actions',
        'Mitigation actions',
        'Recovery actions',
        'User impact',
        'Data impact, if any',
        'Security or privacy impact, if any',
        'Corrective actions',
        'Preventive actions',
        'Monitoring improvements',
        'Process improvements',
        'Follow-up commitments',
      ],
    },
    {
      id: 'security-incident-notification',
      title: '14. Security Incident Notification',
      body: [
        'For security incidents, SinLess Games LLC may notify affected users or organizations when it determines that notification is required or appropriate.',
        'Security notifications may include:',
        'Depending on the incident, users may be advised to:',
      ],
      bullets: [
        'Nature of the incident',
        'Affected systems',
        'Affected accounts or organizations',
        'Types of data involved',
        'Mitigation steps taken',
        'Recommended user actions',
        'Credential rotation guidance',
        'API key rotation guidance',
        'Integration reconnection guidance',
        'Security monitoring guidance',
        'Contact information for security questions',
        'Reset passwords',
        'Rotate API keys',
        'Rotate tokens',
        'Rotate secrets',
        'Revoke sessions',
        'Review audit logs',
        'Review integrations',
        'Review marketplace items',
        'Review automation history',
        'Enable multi-factor authentication',
        'Check for suspicious activity',
      ],
    },
    {
      id: 'privacy-and-data-incident-notification',
      title: '15. Privacy and Data Incident Notification',
      body: [
        'For privacy or data incidents, SinLess Games LLC will assess whether notification is required under applicable law, contract, or policy.',
        'Privacy or data incident notifications may include:',
        'SinLess Games LLC may notify regulators, authorities, enterprise customers, or affected individuals where required by law or contract.',
      ],
      bullets: [
        'Nature of the incident',
        'Categories of data affected',
        'Approximate timeframe',
        'Affected users or organizations',
        'Actions taken to contain the incident',
        'Actions taken to reduce risk',
        'Recommended user actions',
        'Contact information',
        'Rights or options available to affected users, where applicable',
      ],
    },
    {
      id: 'service-availability-notification',
      title: '16. Service Availability Notification',
      body: [
        'For service availability incidents, SinLess Games LLC may notify users through the status page, in-app messages, email, or other channels.',
        'Availability notifications may include:',
        'Availability notifications may not be sent for minor, brief, or isolated service issues.',
      ],
      bullets: [
        'Affected services',
        'Operational status',
        'Impact level',
        'Error rates or affected features',
        'Workarounds',
        'Mitigation progress',
        'Recovery status',
        'Resolution confirmation',
      ],
    },
    {
      id: 'ai-safety-incident-notification',
      title: '17. AI Safety Incident Notification',
      body: [
        'For AI safety incidents, SinLess Games LLC may notify affected users or organizations when the issue creates meaningful risk.',
        'AI safety notifications may include:',
        'Users should review outputs and actions that may have been affected by an AI safety incident.',
      ],
      bullets: [
        'Feature or system involved',
        'Nature of the unsafe behavior',
        'Scope of affected users or organizations',
        'Whether tool use, automation, memory, plugins, or model routing was involved',
        'Mitigation steps taken',
        'Whether features were disabled, limited, or rolled back',
        'Recommended review actions',
        'Whether outputs, automations, or decisions should be rechecked',
      ],
    },
    {
      id: 'automation-incident-notification',
      title: '18. Automation Incident Notification',
      body: [
        'For incidents involving automations, agents, workflows, or tool calls, SinLess Games LLC may notify affected users or organization administrators.',
        'Automation incident notices may include:',
        'Users and organizations are responsible for reviewing their connected systems and confirming whether further remediation is needed.',
      ],
      bullets: [
        'Automation or workflow affected',
        'Trigger involved',
        'Action attempted or completed',
        'Timeframe',
        'Systems or integrations affected',
        'Data affected, if known',
        'Whether the action was reversible',
        'Recommended rollback steps',
        'Recommended audit review',
        'Whether the automation was paused or disabled',
      ],
    },
    {
      id: 'marketplace-and-plugin-incident-notification',
      title: '19. Marketplace and Plugin Incident Notification',
      body: [
        'For marketplace or plugin incidents, SinLess Games LLC may notify affected users, organization administrators, marketplace publishers, or developers.',
        'Marketplace or plugin incident notices may include:',
        'SinLess Games LLC may remove, disable, suspend, or restrict marketplace items during an investigation.',
      ],
      bullets: [
        'Marketplace item involved',
        'Publisher involved',
        'Version affected',
        'Permissions involved',
        'Data access involved',
        'Risk level',
        'Mitigation taken',
        'Whether the item was removed, suspended, disabled, or rolled back',
        'Recommended user or administrator actions',
        'Whether reinstall, update, removal, or credential rotation is recommended',
      ],
    },
    {
      id: 'vendor-and-subprocessor-incident-notification',
      title: '20. Vendor and Subprocessor Incident Notification',
      body: [
        'If a vendor or subprocessor incident affects Aerealith AI users, SinLess Games LLC may notify affected users or organizations when appropriate.',
        'Notifications may include:',
        'SinLess Games LLC may rely on vendor-provided information when assessing vendor incidents.',
      ],
      bullets: [
        'Vendor or subprocessor involved, where disclosure is permitted',
        'Aerealith AI services affected',
        'Nature of the impact',
        'Data affected, if known',
        'Mitigation steps',
        'Vendor status information, where available',
        'Recommended user action',
      ],
    },
    {
      id: 'user-reported-incidents',
      title: '21. User-Reported Incidents',
      body: [
        'Users may report suspected incidents to SinLess Games LLC.',
        'Report suspected incidents to:',
        'Before publishing this policy, confirm these email aliases exist and are monitored.',
        'When reporting an incident, include as much detail as possible, such as:',
        'Do not include passwords, private keys, access tokens, payment card numbers, or unnecessary sensitive data in incident reports.',
      ],
      bullets: [
        'Account email',
        'Organization name',
        'Workspace name',
        'Affected feature',
        'Affected integration',
        'Time of issue',
        'Description of issue',
        'Error messages',
        'Screenshots',
        'Logs',
        'Request IDs',
        'Trace IDs',
        'API response codes',
        'Automation IDs',
        'Plugin or marketplace item names',
        'Any suspected data, privacy, or security impact',
      ],
      contacts: [
        {
          label: 'Security incidents',
          email: 'security@sinlessgames.com',
          href: 'mailto:security@sinlessgames.com',
        },
        {
          label: 'Privacy or data incidents',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
        {
          label: 'Service incidents',
          email: 'support@sinlessgames.com',
          href: 'mailto:support@sinlessgames.com',
        },
        {
          label: 'Abuse or misuse',
          email: 'abuse@sinlessgames.com',
          href: 'mailto:abuse@sinlessgames.com',
        },
        {
          label: 'Legal notices',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
      ],
    },
    {
      id: 'customer-responsibilities-during-incidents',
      title: '22. Customer Responsibilities During Incidents',
      body: [
        'Users and organizations are responsible for reasonable cooperation during incidents.',
        'This may include:',
        'Organizations are responsible for managing incidents within their own environments, connected systems, self-hosted deployments, and user accounts.',
      ],
      bullets: [
        'Providing requested details',
        'Preserving relevant logs',
        'Reviewing account activity',
        'Reviewing audit logs',
        'Rotating credentials when advised',
        'Disabling affected integrations when advised',
        'Pausing affected automations when advised',
        'Notifying internal stakeholders',
        'Following organization incident response procedures',
        'Following legal or regulatory obligations that apply to the customer',
        'Avoiding public disclosure of sensitive incident details before mitigation',
      ],
    },
    {
      id: 'enterprise-customer-notifications',
      title: '23. Enterprise Customer Notifications',
      body: [
        'Enterprise customers may receive additional notification terms under a written agreement.',
        'Enterprise notification terms may include:',
        'If an enterprise agreement conflicts with this policy, the enterprise agreement controls only to the extent of the conflict.',
      ],
      bullets: [
        'Named security contacts',
        'Named privacy contacts',
        'Named legal contacts',
        'Contractual notice timelines',
        'Data processing agreement requirements',
        'Business associate agreement requirements',
        'Service-level agreement requirements',
        'Dedicated support escalation',
        'Custom incident reports',
        'Regulator notification support',
        'Customer-managed investigation requirements',
        'Legal hold requirements',
      ],
    },
    {
      id: 'self-hosted-hybrid-and-air-gapped-deployments',
      title: '24. Self-Hosted, Hybrid, and Air-Gapped Deployments',
      body: [
        'Incident notification responsibilities may differ for self-hosted, hybrid, private, or air-gapped deployments.',
        'For these deployments, the customer or deploying organization may be responsible for:',
        'SinLess Games LLC may provide incident notification for hosted services, licensing systems, official update channels, official marketplace access, support systems, or other SinLess Games LLC-controlled components.',
        'Air-gapped deployments may not receive real-time notifications unless configured by the customer.',
      ],
      bullets: [
        'Monitoring',
        'Logging',
        'Alerting',
        'Incident detection',
        'Incident response',
        'Internal notifications',
        'User notifications',
        'Regulatory notifications',
        'Backups',
        'Recovery',
        'Security patches',
        'Access reviews',
        'Secret rotation',
        'Plugin approval',
        'Marketplace controls',
        'Audit log retention',
        'Forensic preservation',
      ],
    },
    {
      id: 'scheduled-maintenance',
      title: '25. Scheduled Maintenance',
      body: [
        'Scheduled maintenance is not always considered an incident.',
        'SinLess Games LLC may provide advance notice for scheduled maintenance when practical.',
        'Maintenance notices may include:',
        'Emergency maintenance may occur with little or no advance notice when needed to protect users, systems, data, security, or service reliability.',
      ],
      bullets: [
        'Maintenance window',
        'Services affected',
        'Expected impact',
        'Expected duration',
        'Whether downtime is expected',
        'User action needed',
        'Status page link',
        'Support contact',
      ],
    },
    {
      id: 'incident-records',
      title: '26. Incident Records',
      body: [
        'SinLess Games LLC may maintain incident records for security, reliability, compliance, legal, operational, and audit purposes.',
        'Incident records may include:',
        'Incident records may be retained according to applicable retention policies, legal obligations, enterprise agreements, and operational needs.',
      ],
      bullets: [
        'Incident reports',
        'Timelines',
        'Logs',
        'Alerts',
        'Communications',
        'Support tickets',
        'Root cause analysis',
        'Corrective actions',
        'Customer notifications',
        'Regulatory notifications',
        'Evidence preservation records',
        'Vendor reports',
        'Post-incident reviews',
      ],
    },
    {
      id: 'confidentiality',
      title: '27. Confidentiality',
      body: [
        'Incident information may be sensitive.',
        'SinLess Games LLC may limit disclosure of incident details to protect:',
        'Users and organizations receiving confidential incident information should protect it according to their agreements and applicable law.',
      ],
      bullets: [
        'User privacy',
        'Customer confidentiality',
        'Security controls',
        'Internal systems',
        'Vendor confidentiality',
        'Legal privilege',
        'Law enforcement activity',
        'Regulatory investigations',
        'Ongoing investigations',
        'Trade secrets',
        'Platform integrity',
      ],
    },
    {
      id: 'no-guarantee-of-error-free-service',
      title: '28. No Guarantee of Error-Free Service',
      body: [
        'SinLess Games LLC works to operate Aerealith AI reliably and securely, but no online service, AI system, integration, automation platform, or software product can be guaranteed to be error-free, uninterrupted, or completely secure.',
        'This policy does not create a guarantee that every issue will be detected, classified, communicated, resolved, or prevented.',
        'Service commitments, if any, are governed by the applicable Support Policy, service-level agreement, order form, or written enterprise agreement.',
      ],
      links: [
        {
          label: 'Support Policy',
          href: '/Policies/support-policy',
        },
      ],
    },
    {
      id: 'relationship-to-other-policies',
      title: '29. Relationship to Other Policies',
      body: [
        'This policy works together with other Aerealith AI policies, including:',
        'If there is a conflict between this policy and a written agreement signed by SinLess Games LLC, the written agreement controls only to the extent of that conflict.',
      ],
      links: [
        {
          label: 'Terms of Use',
          href: '/Policies/terms-of-use',
        },
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy-policy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
        {
          label: 'AI Transparency Policy',
          href: '/Policies/ai-transparency',
        },
        {
          label: 'Responsible AI Policy',
          href: '/Policies/responsible-ai',
        },
        {
          label: 'Billing, Refund, and Cancellation Policy',
          href: '/Policies/billing-refund-cancellation',
        },
        {
          label: 'Cookie and Tracking Policy',
          href: '/Policies/cookie-tracking',
        },
        {
          label: 'Copyright Takedown Policy',
          href: '/Policies/copyright-takedown',
        },
        {
          label: 'User-Generated Content Policy',
          href: '/Policies/user-generated-content',
        },
        {
          label: 'Subprocessor Vendor List',
          href: '/Policies/subprocessor-vendor-list',
        },
        {
          label: 'Support Policy',
          href: '/Policies/support-policy',
        },
      ],
    },
    {
      id: 'contact',
      title: '30. Contact',
      body: [
        'Questions about this policy may be sent to legal@sinlessgames.com.',
        'Incident reports may be sent to:',
        'Before publishing this policy, confirm these email aliases exist and are monitored.',
      ],
      contacts: [
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
        {
          label: 'Security',
          email: 'security@sinlessgames.com',
          href: 'mailto:security@sinlessgames.com',
        },
        {
          label: 'Privacy',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
        {
          label: 'Abuse',
          email: 'abuse@sinlessgames.com',
          href: 'mailto:abuse@sinlessgames.com',
        },
        {
          label: 'Support',
          email: 'support@sinlessgames.com',
          href: 'mailto:support@sinlessgames.com',
        },
      ],
    },
    {
      id: 'publication-checklist',
      title: '31. Publication Checklist',
      body: ['Before publishing this policy, complete the following:'],
      bullets: [
        'Confirm official company name: SinLess Games LLC',
        'Confirm official Aerealith AI status page URL',
        'Confirm monitored incident intake emails',
        'Confirm internal incident severity definitions',
        'Confirm incident commander role',
        'Confirm escalation path',
        'Confirm security contact process',
        'Confirm privacy contact process',
        'Confirm enterprise notification process',
        'Confirm regulator notification process',
        'Confirm support ticket workflow',
        'Confirm status page ownership',
        'Confirm post-incident review process',
        'Confirm vendor incident intake process',
        'Confirm backup and recovery escalation path',
        'Confirm legal review',
      ],
    },
    {
      id: 'changes-to-this-policy',
      title: '32. Changes to This Policy',
      body: [
        'We may update this policy from time to time.',
        'When we make material changes, we will update the last_updated date and may provide notice through the service, documentation, account settings, email, release notes, legal notices page, or another reasonable method.',
        'Continued use of Aerealith AI after changes become effective means you accept the updated policy.',
      ],
    },
    {
      id: 'legal-review-notice',
      title: '33. Legal Review Notice',
      body: [
        'This policy is a draft template and should be reviewed by qualified legal counsel before publication.',
        'Incident notification, breach notification, privacy notification, security reporting, contractual notice, and regulatory notice requirements may vary by jurisdiction, industry, customer type, and agreement.',
      ],
    },
  ],
} satisfies PolicyDocument;

export default incidentNotificationPolicy;
