import type { PolicyDocument } from '../../types';

export const paymentProcessorCompliancePolicy = {
  slug: 'payment-proccessor-compliance',
  path: '/Policies/payment-proccessor-compliance',
  meta: {
    title: 'Payment Processor Compliance Policy',
    description:
      'Explains Aerealith AI payment processor compliance, prohibited transactions, restricted activity, billing integrity, fraud prevention, chargebacks, sanctions, and marketplace payment rules.',
    effectiveDate: '2026-05-18',
    lastUpdated: '2026-05-18',
    owner: 'SinLess Games LLC',
    status: 'draft',
  },
  relatedPolicies: [
    {
      label: 'Terms of Use',
      href: '/Policies/terms-of-use',
    },
    {
      label: 'Privacy Policy',
      href: '/Policies/privacy-policy',
    },
    {
      label: 'Data Policy',
      href: '/Policies/data',
    },
    {
      label: 'Security Policy',
      href: '/Policies/security-policy',
    },
    {
      label: 'Acceptable Use Policy',
      href: '/Policies/acceptable-use',
    },
    {
      label: 'Billing, Refund, and Cancellation Policy',
      href: '/Policies/billing-refund-cancellation',
    },
    {
      label: 'Marketplace Policy',
      href: '/Policies/marketplace',
    },
    {
      label: 'Developer and API Policy',
      href: '/Policies/developer',
    },
    {
      label: 'User-Generated Content Policy',
      href: '/Policies/user-generated-content',
    },
    {
      label: 'Copyright Takedown Policy',
      href: '/Policies/copyright-takedown',
    },
    {
      label: 'Cookie and Tracking Policy',
      href: '/Policies/cookie-tracking',
    },
    {
      label: 'Subprocessor Vendor List',
      href: '/Policies/subprocessor-vendor-list',
    },
  ],
  sections: [
    {
      id: 'purpose',
      title: '1. Purpose',
      body: [
        'This Payment Processor Compliance Policy explains how SinLess Games LLC manages payment processor, card network, billing, fraud-prevention, marketplace, subscription, and transaction-compliance requirements for Aerealith AI.',
        'Aerealith AI may use third-party payment processors, including Stripe, PayPal, or other providers, to process payments, subscriptions, invoices, marketplace purchases, add-ons, usage charges, refunds, disputes, taxes, and related billing activity.',
        'This policy is intended to help ensure that Aerealith AI, its users, organizations, developers, marketplace publishers, and customers comply with applicable payment processor rules, card network rules, financial regulations, anti-fraud requirements, sanctions restrictions, and Aerealith AI policies.',
      ],
    },
    {
      id: 'scope',
      title: '2. Scope',
      body: ['This policy applies to:', 'This policy applies to:'],
      bullets: [
        'Individual subscriptions',
        'Organization subscriptions',
        'Enterprise subscriptions',
        'Trials and promotions',
        'Add-ons',
        'API usage charges',
        'Marketplace purchases',
        'Plugin purchases',
        'Developer payouts',
        'Publisher payouts',
        'Usage-based billing',
        'Invoices',
        'Refunds',
        'Chargebacks',
        'Disputes',
        'Credits',
        'Taxes',
        'Payment method handling',
        'Self-hosted, hybrid, and air-gapped licensing, where applicable',
        'Any payment, billing, checkout, subscription, marketplace, or payout workflow connected to Aerealith AI',
        'Users',
        'Customers',
        'Organizations',
        'Workspace administrators',
        'Billing administrators',
        'Developers',
        'Marketplace publishers',
        'API users',
        'Enterprise customers',
        'Anyone who purchases, sells, subscribes to, or receives payment through Aerealith AI',
      ],
    },
    {
      id: 'relationship-to-other-policies',
      title: '3. Relationship to Other Policies',
      body: [
        'This policy works together with other Aerealith AI policies, including:',
        'If this policy conflicts with a written agreement signed by SinLess Games LLC, the written agreement controls only to the extent of that conflict.',
        'If a payment processor, card network, bank, or financial institution imposes stricter requirements, those requirements may control for the affected transaction, account, payout, product, feature, or service.',
      ],
      links: [
        {
          label: 'Terms of Use',
          href: '/Policies/terms-of-use',
        },
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy-policy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
        {
          label: 'Billing, Refund, and Cancellation Policy',
          href: '/Policies/billing-refund-cancellation',
        },
        {
          label: 'Marketplace Policy',
          href: '/Policies/marketplace',
        },
        {
          label: 'Developer and API Policy',
          href: '/Policies/developer',
        },
        {
          label: 'User-Generated Content Policy',
          href: '/Policies/user-generated-content',
        },
        {
          label: 'Copyright Takedown Policy',
          href: '/Policies/copyright-takedown',
        },
        {
          label: 'Cookie and Tracking Policy',
          href: '/Policies/cookie-tracking',
        },
        {
          label: 'Subprocessor Vendor List',
          href: '/Policies/subprocessor-vendor-list',
        },
      ],
    },
    {
      id: 'no-legal-tax-or-financial-advice',
      title: '4. No Legal, Tax, or Financial Advice',
      body: [
        'This policy is not legal, tax, financial, accounting, banking, or compliance advice.',
        'Payment rules may vary by jurisdiction, payment method, card network, processor, bank, transaction type, marketplace model, customer type, and product category.',
        'Users, organizations, developers, and marketplace publishers are responsible for understanding and complying with the laws, contracts, and processor rules that apply to their activity.',
      ],
    },
    {
      id: 'supported-payment-processors',
      title: '5. Supported Payment Processors',
      body: [
        'Aerealith AI may use one or more payment processors or billing providers.',
        'Potential providers may include:',
        'The specific providers used by Aerealith AI may change over time.',
        'Before publishing this policy, confirm the actual payment processors and vendors in use and ensure they are listed in the Subprocessor Vendor List, where applicable.',
      ],
      bullets: [
        'Stripe',
        'PayPal',
        'Card networks',
        'Banks',
        'Tax calculation providers',
        'Subscription management providers',
        'Marketplace payout providers',
        'Fraud-prevention providers',
        'Invoice and accounting providers',
      ],
      links: [
        {
          label: 'Subprocessor Vendor List',
          href: '/Policies/subprocessor-vendor-list',
        },
      ],
    },
    {
      id: 'processor-terms-apply',
      title: '6. Processor Terms Apply',
      body: [
        'When using Aerealith AI billing, checkout, marketplace, or payout features, users may also be subject to the terms, policies, acceptable use rules, restricted business rules, risk controls, dispute rules, and privacy policies of the applicable payment processors.',
        'Users may not use Aerealith AI to bypass, evade, obscure, or violate payment processor rules.',
        'SinLess Games LLC may take action when required by a payment processor, card network, bank, regulator, law enforcement agency, court order, or applicable law.',
      ],
    },
    {
      id: 'core-compliance-commitments',
      title: '7. Core Compliance Commitments',
      body: [
        'SinLess Games LLC will make reasonable efforts to operate Aerealith AI payment workflows according to the following principles:',
      ],
      orderedItems: [
        'Payments should be lawful.',
        'Payments should be authorized.',
        'Billing should be clear.',
        'Customers should understand recurring charges.',
        'Refund and cancellation rules should be disclosed.',
        'Fraud and abuse should be actively monitored.',
        'Prohibited transactions should not be processed.',
        'Restricted transactions should require review and approval where applicable.',
        'Customer payment data should be handled securely.',
        'Marketplace payouts should be traceable and compliant.',
        'Sanctions and high-risk jurisdiction restrictions should be respected.',
        'Payment disputes should be handled honestly and promptly.',
        'Payment processor requirements should be followed.',
      ],
    },
    {
      id: 'user-responsibilities',
      title: '8. User Responsibilities',
      body: [
        'Users, customers, organizations, developers, and marketplace publishers are responsible for:',
      ],
      bullets: [
        'Providing accurate billing information',
        'Using authorized payment methods',
        'Ensuring they have permission to make purchases',
        'Paying all applicable fees, taxes, and charges',
        'Keeping payment information current',
        'Avoiding fraudulent or deceptive transactions',
        'Avoiding prohibited or restricted activity',
        'Complying with payment processor rules',
        'Complying with card network rules',
        'Complying with applicable laws',
        'Responding to billing or dispute inquiries',
        'Preventing unauthorized account access',
        'Managing organization billing administrators',
        'Managing marketplace publisher information',
        'Maintaining accurate tax, payout, and identity information',
      ],
    },
    {
      id: 'accurate-business-information',
      title: '9. Accurate Business Information',
      body: [
        'Users, organizations, and marketplace publishers must provide accurate, complete, and current information when required for billing, tax, risk, identity, compliance, or payout purposes.',
        'Required information may include:',
        'Providing false, incomplete, misleading, or outdated information may result in payment failure, payout delay, account restriction, suspension, termination, refund denial, or marketplace removal.',
      ],
      bullets: [
        'Legal name',
        'Business name',
        'Billing address',
        'Tax address',
        'Email address',
        'Phone number',
        'Payment method details',
        'Tax identification information',
        'Organization information',
        'Marketplace publisher information',
        'Bank or payout account information',
        'Ownership or beneficial ownership information',
        'Product or service descriptions',
        'Website or app information',
        'Customer support contact information',
      ],
    },
    {
      id: 'authorized-payment-methods',
      title: '10. Authorized Payment Methods',
      body: [
        'Users may only use payment methods they are authorized to use.',
        'You may not:',
        'Unauthorized payment activity may be reported to payment processors, banks, card networks, law enforcement, or affected parties where appropriate.',
      ],
      bullets: [
        'Use stolen payment cards',
        'Use stolen PayPal accounts',
        'Use unauthorized bank accounts',
        'Use payment credentials without permission',
        'Use another person’s billing information without consent',
        'Use fake identities',
        'Use synthetic identities',
        'Use payment methods to commit fraud',
        'Circumvent payment processor verification',
        'Evade billing controls',
        'Use chargebacks as a substitute for cancellation or refund requests',
      ],
    },
    {
      id: 'prohibited-transactions',
      title: '11. Prohibited Transactions',
      body: [
        'Aerealith AI may not be used to process payments for illegal, deceptive, abusive, unsafe, or payment-processor-prohibited activity.',
        'Prohibited transactions may include, but are not limited to, transactions involving:',
      ],
      bullets: [
        'Illegal goods or services',
        'Fraud',
        'Scams',
        'Phishing',
        'Identity theft',
        'Stolen goods',
        'Counterfeit goods',
        'Unauthorized copyrighted material',
        'Unauthorized access tools',
        'Malware',
        'Credential theft',
        'Exploit kits',
        'Ransomware',
        'Botnets',
        'Illegal surveillance tools',
        'Terrorism or violent extremism',
        'Human trafficking',
        'Child exploitation',
        'Illegal weapons',
        'Illegal drugs',
        'Controlled substances sold unlawfully',
        'Illegal gambling',
        'Money laundering',
        'Sanctions evasion',
        'Bribery or corruption',
        'Pyramid schemes',
        'Ponzi schemes',
        'Get-rich-quick scams',
        'Deceptive investment schemes',
        'False billing',
        'Fake invoices',
        'Products or services that violate applicable law',
        'Products or services prohibited by a payment processor or card network',
      ],
    },
    {
      id: 'restricted-activity',
      title: '12. Restricted Activity',
      body: [
        'Some activity may be restricted rather than fully prohibited.',
        'Restricted activity may require:',
        'Restricted activity may include, depending on processor rules and applicable law:',
        'SinLess Games LLC may deny, restrict, suspend, or terminate restricted activity if it is not approved, not adequately documented, or not supported by the applicable payment processor.',
      ],
      bullets: [
        'Additional review',
        'Written approval',
        'Processor approval',
        'Legal review',
        'Risk review',
        'Enhanced monitoring',
        'Additional disclosures',
        'Additional documentation',
        'Special terms',
        'Separate merchant accounts',
        'Higher reserves',
        'Payout delays',
        'Transaction limits',
        'Regional limitations',
        'High-risk digital goods',
        'High-risk subscriptions',
        'Financial services',
        'Crypto-related services',
        'Credit repair',
        'Debt services',
        'Regulated healthcare services',
        'Regulated legal services',
        'Regulated professional services',
        'Age-restricted products',
        'Certain adult or mature content',
        'Charitable fundraising',
        'Crowdfunding',
        'Sweepstakes or contests',
        'Marketplace payouts',
        'User-generated digital goods',
        'High-chargeback categories',
        'High-refund categories',
        'Services with delayed delivery',
        'Products requiring licenses or permits',
        'Products with elevated consumer-protection risk',
      ],
    },
    {
      id: 'aerealith-ai-product-restrictions',
      title: '13. Aerealith AI Product Restrictions',
      body: [
        'Aerealith AI may not be used to sell, monetize, advertise, facilitate, or process payment for products, services, plugins, workflows, automations, prompts, templates, personalities, dashboards, or marketplace items that violate Aerealith AI policies.',
        'This includes items that:',
      ],
      bullets: [
        'Violate the Acceptable Use Policy',
        'Violate the Security Policy',
        'Violate the Marketplace Policy',
        'Violate the Developer and API Policy',
        'Violate the User-Generated Content Policy',
        'Violate the Copyright Takedown Policy',
        'Violate applicable laws',
        'Violate payment processor rules',
        'Create unacceptable risk for SinLess Games LLC, users, payment processors, or third parties',
      ],
      links: [
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
        {
          label: 'Marketplace Policy',
          href: '/Policies/marketplace',
        },
        {
          label: 'Developer and API Policy',
          href: '/Policies/developer',
        },
        {
          label: 'User-Generated Content Policy',
          href: '/Policies/user-generated-content',
        },
        {
          label: 'Copyright Takedown Policy',
          href: '/Policies/copyright-takedown',
        },
      ],
    },
    {
      id: 'ai-specific-payment-restrictions',
      title: '14. AI-Specific Payment Restrictions',
      body: [
        'Users may not use Aerealith AI payment features to monetize AI activity that is unlawful, abusive, deceptive, unsafe, or prohibited by policy.',
        'Prohibited AI monetization may include:',
      ],
      bullets: [
        'Paid phishing kits',
        'Paid scam-generation tools',
        'Paid malware-generation tools',
        'Paid credential-theft tools',
        'Paid exploit-generation tools for unauthorized systems',
        'Paid impersonation or fraud services',
        'Paid deepfake deception services',
        'Paid non-consensual intimate content',
        'Paid harassment or abuse services',
        'Paid disinformation services',
        'Paid evasion of safety systems',
        'Paid generation of forged records or credentials',
        'Paid unauthorized surveillance workflows',
        'Paid tools that violate laws, rights, contracts, or processor rules',
      ],
    },
    {
      id: 'marketplace-payment-rules',
      title: '15. Marketplace Payment Rules',
      body: [
        'Marketplace publishers must comply with all payment processor, payout provider, tax, legal, and Aerealith AI marketplace requirements.',
        'Marketplace publishers may not:',
        'SinLess Games LLC may remove, suspend, disable, refund, reverse, or withhold marketplace payments for violating this policy.',
      ],
      bullets: [
        'Sell prohibited items',
        'Misrepresent marketplace items',
        'Hide fees',
        'Use deceptive pricing',
        'Use fake reviews',
        'Manipulate ratings',
        'Inflate sales',
        'Launder money through marketplace purchases',
        'Use marketplace purchases to transfer money unrelated to legitimate sales',
        'Split transactions to avoid review',
        'Process transactions outside approved checkout flows to avoid fees',
        'Offer refunds outside the approved process in a deceptive way',
        'Misstate ownership, licensing, support, or functionality',
        'Sell items that collect user data without proper disclosure',
        'Sell items that violate processor or card network rules',
      ],
    },
    {
      id: 'payout-compliance',
      title: '16. Payout Compliance',
      body: [
        'Marketplace publishers, developers, contractors, affiliates, partners, or other payout recipients may be required to complete identity, tax, sanctions, and risk checks before receiving payouts.',
        'Payout requirements may include:',
        'SinLess Games LLC may delay, suspend, withhold, reverse, or deny payouts when required by law, processor rules, card network rules, risk controls, tax rules, contract, or this policy.',
      ],
      bullets: [
        'Identity verification',
        'Business verification',
        'Tax forms',
        'Bank account verification',
        'Address verification',
        'Ownership verification',
        'Sanctions screening',
        'Fraud checks',
        'Processor onboarding',
        'Marketplace approval',
        'Agreement acceptance',
        'Minimum payout thresholds',
      ],
    },
    {
      id: 'taxes',
      title: '17. Taxes',
      body: [
        'Users, customers, organizations, and marketplace publishers are responsible for taxes that apply to their purchases, sales, subscriptions, payouts, and income.',
        'Taxes may include:',
        'SinLess Games LLC may calculate, collect, remit, report, or withhold taxes where required or supported.',
        'Marketplace publishers are responsible for their own tax obligations unless expressly stated otherwise in a written agreement.',
      ],
      bullets: [
        'Sales tax',
        'Use tax',
        'Value-added tax',
        'Goods and services tax',
        'Digital services tax',
        'Withholding tax',
        'Income tax',
        'Marketplace facilitator taxes',
        'Local taxes',
        'Other governmental charges',
      ],
    },
    {
      id: 'sanctions-and-restricted-jurisdictions',
      title: '18. Sanctions and Restricted Jurisdictions',
      body: [
        'Aerealith AI may not be used to process payments in violation of sanctions, export controls, restricted-party rules, embargoes, or high-risk jurisdiction restrictions.',
        'Users may not use Aerealith AI to:',
        'SinLess Games LLC may screen accounts, transactions, organizations, marketplace publishers, and payout recipients for sanctions or restricted-party risk where appropriate.',
      ],
      bullets: [
        'Evade sanctions',
        'Hide restricted-party involvement',
        'Use false locations',
        'Misrepresent beneficial ownership',
        'Use intermediaries to bypass restrictions',
        'Process payments for sanctioned persons or entities',
        'Process payments for prohibited jurisdictions',
        'Circumvent payment processor geographic controls',
      ],
    },
    {
      id: 'anti-money-laundering-and-fraud-prevention',
      title: '19. Anti-Money Laundering and Fraud Prevention',
      body: [
        'Users may not use Aerealith AI to launder money, conceal funds, evade reporting obligations, disguise transaction purpose, or facilitate financial crime.',
        'Prohibited behavior includes:',
        'SinLess Games LLC may monitor transactions for fraud, abuse, suspicious patterns, refund abuse, chargeback abuse, and policy violations.',
      ],
      bullets: [
        'Circular transactions',
        'Fake purchases',
        'Artificial marketplace sales',
        'Self-dealing to move money',
        'Use of stolen payment methods',
        'Splitting transactions to avoid thresholds',
        'Misstating goods or services',
        'Using multiple accounts to avoid limits',
        'Creating fake organizations',
        'Creating fake invoices',
        'Using refunds to move money',
        'Using chargebacks to commit fraud',
        'Using Aerealith AI as a pass-through payment system',
      ],
    },
    {
      id: 'billing-transparency',
      title: '20. Billing Transparency',
      body: [
        'Aerealith AI should make reasonable efforts to clearly disclose billing terms before purchase.',
        'Disclosures may include:',
        'Users are responsible for reviewing billing information before completing a purchase.',
      ],
      bullets: [
        'Plan name',
        'Price',
        'Billing cycle',
        'Renewal behavior',
        'Trial terms',
        'Cancellation method',
        'Refund terms',
        'Usage limits',
        'Add-on pricing',
        'Taxes, where calculated',
        'Marketplace item pricing',
        'Enterprise invoice terms',
        'Usage-based billing terms',
        'Material restrictions',
      ],
    },
    {
      id: 'recurring-billing',
      title: '21. Recurring Billing',
      body: [
        'Paid subscriptions may renew automatically unless canceled before the renewal date.',
        'Recurring billing may apply to:',
        'Users authorize SinLess Games LLC and its payment processors to charge applicable recurring fees, usage charges, taxes, and related amounts.',
        'Cancellation and refund rules are described in the Billing, Refund, and Cancellation Policy.',
      ],
      bullets: [
        'Monthly subscriptions',
        'Annual subscriptions',
        'Add-ons',
        'Marketplace subscriptions',
        'API packages',
        'Extra storage',
        'Extra compute',
        'Extra vector space',
        'Support plans',
        'Enterprise services',
      ],
      links: [
        {
          label: 'Billing, Refund, and Cancellation Policy',
          href: '/Policies/billing-refund-cancellation',
        },
      ],
    },
    {
      id: 'usage-based-billing',
      title: '22. Usage-Based Billing',
      body: [
        'Some Aerealith AI services may be billed based on usage.',
        'Usage-based charges may include:',
        'Users are responsible for monitoring usage, setting limits where available, and securing API keys, automations, integrations, and accounts.',
        'Usage charges are generally non-refundable once incurred unless required by law, caused by a confirmed billing error, or approved by SinLess Games LLC.',
      ],
      bullets: [
        'API calls',
        'Model calls',
        'Tokens',
        'Compute',
        'Automation runs',
        'Storage',
        'Vector space',
        'File processing',
        'Data transfer',
        'Plugin execution',
        'Marketplace usage',
        'Advanced analytics',
        'Integration usage',
      ],
    },
    {
      id: 'refund-compliance',
      title: '23. Refund Compliance',
      body: [
        'Refunds may be subject to:',
        'SinLess Games LLC may approve, deny, reverse, or adjust refunds according to applicable policies and legal obligations.',
        'Refund abuse may result in account restriction, marketplace restriction, suspension, termination, or refusal of future service.',
      ],
      bullets: [
        'Aerealith AI refund rules',
        'Payment processor rules',
        'Card network rules',
        'Marketplace rules',
        'Tax rules',
        'Consumer protection laws',
        'Enterprise agreements',
        'Regional requirements',
        'Fraud and risk review',
      ],
    },
    {
      id: 'chargebacks-and-disputes',
      title: '24. Chargebacks and Disputes',
      body: [
        'Users should contact SinLess Games LLC before initiating a chargeback when possible.',
        'Chargebacks, reversals, or payment disputes may result in:',
        'SinLess Games LLC may contest chargebacks and provide relevant records to payment processors, banks, card networks, or dispute-resolution systems.',
        'Relevant records may include:',
      ],
      bullets: [
        'Account review',
        'Temporary suspension',
        'Loss of paid features',
        'Loss of marketplace access',
        'Payout delay',
        'Account restriction',
        'Subscription cancellation',
        'Revocation of credits',
        'Fraud review',
        'Collection activity where permitted',
        'Termination for abuse or non-payment',
        'Purchase records',
        'Checkout records',
        'Subscription records',
        'Login records',
        'Usage records',
        'IP metadata',
        'Device metadata',
        'Billing communications',
        'Cancellation records',
        'Refund records',
        'Support communications',
        'Marketplace records',
        'Delivery or provisioning records',
      ],
    },
    {
      id: 'failed-payments',
      title: '25. Failed Payments',
      body: [
        'If a payment fails, SinLess Games LLC may:',
        'Users remain responsible for unpaid fees, taxes, usage charges, invoices, and other amounts owed.',
      ],
      bullets: [
        'Retry the charge',
        'Request updated payment information',
        'Send failed-payment notices',
        'Pause paid features',
        'Disable add-ons',
        'Restrict API access',
        'Pause automations',
        'Restrict marketplace purchases',
        'Delay payouts',
        'Downgrade the account',
        'Cancel the subscription',
        'Suspend or terminate access',
        'Send unpaid amounts to collections where permitted',
      ],
    },
    {
      id: 'fraud-review',
      title: '26. Fraud Review',
      body: [
        'SinLess Games LLC may review accounts, transactions, subscriptions, marketplace activity, payouts, and payment methods for fraud or risk.',
        'Fraud review may be triggered by:',
        'During review, SinLess Games LLC may restrict, delay, or suspend payment-related features.',
      ],
      bullets: [
        'Suspicious payment activity',
        'Failed verification',
        'High chargeback rate',
        'High refund rate',
        'Unusual usage spikes',
        'Unusual marketplace activity',
        'Mismatched billing information',
        'Use of multiple accounts',
        'Suspicious login patterns',
        'Processor alerts',
        'Bank alerts',
        'Card network alerts',
        'User reports',
        'Abuse reports',
        'Security alerts',
        'Sanctions screening alerts',
      ],
    },
    {
      id: 'reserves-and-holds',
      title: '27. Reserves and Holds',
      body: [
        'SinLess Games LLC or its payment processors may hold funds, delay payouts, establish reserves, or restrict settlement when required or appropriate.',
        'Reasons may include:',
        'Funds may be released, refunded, reversed, withheld, or remitted according to applicable rules, agreements, and laws.',
      ],
      bullets: [
        'Chargeback risk',
        'Refund risk',
        'Fraud risk',
        'Processor requirements',
        'Card network requirements',
        'Marketplace risk',
        'High-risk product category',
        'Dispute activity',
        'Legal obligations',
        'Account verification issues',
        'Suspicious activity',
        'Policy violations',
        'Sanctions concerns',
        'Tax or reporting obligations',
      ],
    },
    {
      id: 'identity-verification',
      title: '28. Identity Verification',
      body: [
        'Some users, organizations, and marketplace publishers may be required to complete identity verification.',
        'Verification may be required for:',
        'Failure to complete verification may result in denied purchases, delayed payouts, account limits, restricted marketplace access, or termination.',
      ],
      bullets: [
        'Enterprise billing',
        'Marketplace publishing',
        'Marketplace payouts',
        'High-risk transactions',
        'High-volume transactions',
        'Tax reporting',
        'Fraud prevention',
        'Compliance review',
        'Processor onboarding',
        'Restricted activity approval',
      ],
    },
    {
      id: 'payment-data-security',
      title: '29. Payment Data Security',
      body: [
        'SinLess Games LLC should protect payment-related data using reasonable security controls.',
        'Controls may include:',
        'Users should not send full payment card numbers, bank credentials, passwords, private keys, or payment secrets through ordinary support messages, chat prompts, files, or unapproved channels.',
      ],
      bullets: [
        'Use of trusted payment processors',
        'Avoiding direct storage of full payment card numbers',
        'Encryption in transit',
        'Access controls',
        'Least-privilege permissions',
        'Audit logs',
        'Fraud monitoring',
        'Secure checkout flows',
        'Tokenized payment methods',
        'Secure webhook handling',
        'Secret management',
        'Incident response',
        'Vendor review',
      ],
    },
    {
      id: 'pci-dss-considerations',
      title: '30. PCI DSS Considerations',
      body: [
        'If Aerealith AI processes payment card data, SinLess Games LLC should use payment flows designed to reduce direct exposure to cardholder data.',
        'Depending on implementation, PCI DSS responsibilities may include:',
        'Before publishing this policy, confirm the actual cardholder data environment and PCI DSS scope with qualified compliance professionals.',
      ],
      bullets: [
        'Secure payment integration',
        'Secure checkout pages',
        'Secure payment webhooks',
        'Access controls',
        'Vulnerability management',
        'Security monitoring',
        'Vendor management',
        'Annual validation',
        'Documentation',
        'Incident response',
      ],
    },
    {
      id: 'payment-webhooks-and-billing-events',
      title: '31. Payment Webhooks and Billing Events',
      body: [
        'Payment webhooks and billing events must be handled securely.',
        'Security controls may include:',
        'Billing events should not be trusted unless verified through the payment processor’s recommended security process.',
      ],
      bullets: [
        'Signature verification',
        'Replay protection',
        'Idempotency',
        'Event logging',
        'Access controls',
        'Secret rotation',
        'Error handling',
        'Least-privilege service accounts',
        'Secure storage of event records',
        'Monitoring for failed events',
        'Alerts for suspicious billing changes',
      ],
    },
    {
      id: 'marketplace-publisher-misconduct',
      title: '32. Marketplace Publisher Misconduct',
      body: [
        'SinLess Games LLC may take action against marketplace publishers that violate payment or marketplace rules.',
        'Actions may include:',
        'Misconduct may include:',
      ],
      bullets: [
        'Warning',
        'Listing removal',
        'Listing suspension',
        'Payment hold',
        'Payout delay',
        'Payout reversal',
        'Refunds to customers',
        'Publisher account suspension',
        'Publisher account termination',
        'Marketplace ban',
        'Legal escalation',
        'Processor reporting',
        'Law enforcement reporting where appropriate',
        'Fraudulent listings',
        'Hidden fees',
        'Fake sales',
        'Fake reviews',
        'Misleading claims',
        'Data misuse',
        'Unauthorized billing',
        'Selling prohibited items',
        'Selling infringing content',
        'Selling unsafe automations',
        'Selling malware or abuse tools',
        'Evading review',
        'Evading payment fees',
        'Chargeback manipulation',
      ],
    },
    {
      id: 'customer-misconduct',
      title: '33. Customer Misconduct',
      body: [
        'SinLess Games LLC may take action against users or customers that violate payment rules.',
        'Actions may include:',
        'Customer misconduct may include:',
      ],
      bullets: [
        'Payment method removal',
        'Purchase blocking',
        'Refund denial',
        'Credit revocation',
        'API restriction',
        'Marketplace restriction',
        'Subscription cancellation',
        'Account suspension',
        'Account termination',
        'Collection activity where permitted',
        'Reporting to processors, banks, card networks, or law enforcement where appropriate',
        'Unauthorized payments',
        'Fraudulent chargebacks',
        'Refund abuse',
        'Coupon abuse',
        'Trial abuse',
        'Account cycling',
        'Multiple accounts to evade limits',
        'Payment method abuse',
        'False billing information',
        'Fraudulent tax exemption claims',
        'Sanctions evasion',
        'Illegal transactions',
      ],
    },
    {
      id: 'promotional-abuse',
      title: '34. Promotional Abuse',
      body: [
        'Users may not abuse trials, coupons, credits, discounts, referral programs, affiliate programs, marketplace promotions, or promotional pricing.',
        'Prohibited behavior includes:',
        'SinLess Games LLC may revoke credits, cancel subscriptions, deny refunds, restrict accounts, or charge standard pricing for promotional abuse.',
      ],
      bullets: [
        'Creating multiple accounts to claim repeated promotions',
        'Sharing non-transferable coupons',
        'Selling promotional codes',
        'Using fake accounts',
        'Using stolen payment methods',
        'Referring yourself',
        'Creating fake referrals',
        'Manipulating attribution systems',
        'Using bots to claim offers',
        'Exploiting pricing errors',
        'Reselling discounted access without permission',
      ],
    },
    {
      id: 'tax-exemption',
      title: '35. Tax Exemption',
      body: [
        'Users requesting tax exemption must provide valid, current, and accurate documentation before the charge is processed.',
        'SinLess Games LLC may reject, delay, or require updates to tax exemption claims.',
        'False or misleading tax exemption claims may result in:',
      ],
      bullets: [
        'Tax charges',
        'Account review',
        'Suspension',
        'Termination',
        'Reporting where required',
        'Responsibility for penalties, interest, or costs where permitted',
      ],
    },
    {
      id: 'currency-and-regional-restrictions',
      title: '36. Currency and Regional Restrictions',
      body: [
        'Payment options, currencies, taxes, prices, features, plans, trials, marketplace access, and payout availability may vary by region.',
        'SinLess Games LLC may restrict or decline transactions based on:',
        'Users may not use false location information, VPNs, proxies, or intermediaries to evade regional restrictions.',
      ],
      bullets: [
        'Jurisdiction',
        'Currency support',
        'Processor availability',
        'Sanctions',
        'Fraud risk',
        'Tax requirements',
        'Legal requirements',
        'Payment method limitations',
        'Marketplace restrictions',
        'Regional compliance obligations',
      ],
    },
    {
      id: 'enterprise-payment-compliance',
      title: '37. Enterprise Payment Compliance',
      body: [
        'Enterprise customers may have custom payment terms in written agreements.',
        'Enterprise agreements may address:',
        'If an enterprise agreement conflicts with this policy, the enterprise agreement controls only for that enterprise customer and only to the extent of the conflict.',
      ],
      bullets: [
        'Invoicing',
        'Payment terms',
        'Purchase orders',
        'Taxes',
        'Late fees',
        'Renewal terms',
        'Minimum commitments',
        'Usage overages',
        'Support fees',
        'Professional services',
        'Self-hosted licenses',
        'Audit rights',
        'Marketplace restrictions',
        'Cancellation rights',
        'Refund rules',
        'Security and compliance obligations',
      ],
    },
    {
      id: 'self-hosted-hybrid-and-air-gapped-deployments',
      title: '38. Self-Hosted, Hybrid, and Air-Gapped Deployments',
      body: [
        'Self-hosted, hybrid, private, and air-gapped deployments may involve different payment and licensing workflows.',
        'These may include:',
        'Customers operating self-hosted or air-gapped deployments are responsible for ensuring that internal payments, billing, procurement, licensing, and use comply with applicable agreements and laws.',
      ],
      bullets: [
        'License keys',
        'Offline activation',
        'Enterprise invoices',
        'Annual contracts',
        'Support contracts',
        'Professional services',
        'Marketplace access fees',
        'Private marketplace fees',
        'Deployment limits',
        'Seat limits',
        'Node limits',
        'Environment limits',
        'Usage reporting',
        'Renewal verification',
      ],
    },
    {
      id: 'data-sharing-with-payment-processors',
      title: '39. Data Sharing with Payment Processors',
      body: [
        'SinLess Games LLC may share payment-related data with payment processors, banks, card networks, tax providers, fraud-prevention providers, and other payment service providers as needed.',
        'Payment-related data may include:',
        'Payment processors may process this data according to their own terms, privacy policies, and legal obligations.',
      ],
      bullets: [
        'Name',
        'Email address',
        'Billing address',
        'Shipping address, if applicable',
        'Payment method token',
        'Transaction amount',
        'Currency',
        'Tax information',
        'Invoice details',
        'Subscription details',
        'Purchase history',
        'Usage charges',
        'Device metadata',
        'IP address',
        'Fraud signals',
        'Dispute records',
        'Refund records',
        'Marketplace payout information',
      ],
    },
    {
      id: 'data-retention-for-payment-records',
      title: '40. Data Retention for Payment Records',
      body: [
        'SinLess Games LLC may retain payment-related records as needed for:',
        'Payment records may be retained even after account deletion where required or permitted by law, contract, security, tax, accounting, fraud-prevention, or dispute-resolution needs.',
      ],
      bullets: [
        'Accounting',
        'Tax compliance',
        'Billing support',
        'Fraud prevention',
        'Chargeback defense',
        'Dispute resolution',
        'Legal compliance',
        'Audit requirements',
        'Enterprise contract management',
        'Marketplace payout tracking',
        'Processor requirements',
      ],
    },
    {
      id: 'incident-handling',
      title: '41. Incident Handling',
      body: [
        'Payment-related incidents may include:',
        'Payment incidents may be handled according to this policy, the Incident Notification Policy, the Security Policy, and applicable processor requirements.',
      ],
      bullets: [
        'Unauthorized charges',
        'Payment processor outages',
        'Checkout failures',
        'Billing errors',
        'Tax calculation errors',
        'Webhook failures',
        'Refund processing errors',
        'Payout failures',
        'Marketplace payment errors',
        'Fraud events',
        'Chargeback spikes',
        'Processor account restrictions',
        'Data security incidents involving payment data',
      ],
      links: [
        {
          label: 'Incident Notification Policy',
          href: '/Policies/incident-notification',
        },
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
      ],
    },
    {
      id: 'reporting-payment-issues',
      title: '42. Reporting Payment Issues',
      body: [
        'Billing, payment, refund, cancellation, or payout questions may be sent to billing@sinlessgames.com.',
        'Security issues involving payments may be sent to security@sinlessgames.com.',
        'Legal payment concerns may be sent to legal@sinlessgames.com.',
        'Before publishing this policy, confirm these email aliases exist and are monitored.',
        'When reporting a payment issue, include:',
        'Do not send full card numbers, CVV codes, bank passwords, private keys, access tokens, or unnecessary sensitive information.',
      ],
      bullets: [
        'Account email',
        'Organization name, if applicable',
        'Invoice number',
        'Transaction ID, if available',
        'Charge date',
        'Charge amount',
        'Payment method type',
        'Description of the issue',
        'Relevant screenshots or receipts',
      ],
      contacts: [
        {
          label: 'Billing',
          email: 'billing@sinlessgames.com',
          href: 'mailto:billing@sinlessgames.com',
        },
        {
          label: 'Security',
          email: 'security@sinlessgames.com',
          href: 'mailto:security@sinlessgames.com',
        },
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
      ],
    },
    {
      id: 'enforcement',
      title: '43. Enforcement',
      body: [
        'SinLess Games LLC may investigate suspected violations of this policy.',
        'Depending on severity, risk, processor requirements, and legal obligations, SinLess Games LLC may:',
        'SinLess Games LLC may act immediately without prior notice when needed to protect users, payment systems, processors, SinLess Games LLC, or the public.',
      ],
      bullets: [
        'Warn the user or organization',
        'Request additional information',
        'Require verification',
        'Block a payment method',
        'Cancel a transaction',
        'Refund a transaction',
        'Reverse a transaction',
        'Disable checkout',
        'Restrict purchases',
        'Restrict marketplace access',
        'Restrict API access',
        'Restrict subscriptions',
        'Delay or withhold payouts',
        'Remove marketplace listings',
        'Suspend accounts',
        'Terminate accounts',
        'Report activity to payment processors',
        'Report activity to banks or card networks',
        'Report activity to authorities where appropriate',
        'Refuse future service',
      ],
    },
    {
      id: 'appeals',
      title: '44. Appeals',
      body: [
        'If you believe a payment-related enforcement action was taken in error, contact billing@sinlessgames.com.',
        'Appeals should include:',
        'Submitting an appeal does not guarantee reversal, reinstatement, refund, or payout release.',
      ],
      bullets: [
        'Account email',
        'Organization name, if applicable',
        'Affected payment, invoice, subscription, marketplace item, or payout',
        'Explanation of why you believe the action was incorrect',
        'Supporting documentation',
        'Contact information',
      ],
      contacts: [
        {
          label: 'Billing',
          email: 'billing@sinlessgames.com',
          href: 'mailto:billing@sinlessgames.com',
        },
      ],
    },
    {
      id: 'processor-required-changes',
      title: '45. Processor-Required Changes',
      body: [
        'Payment processors, banks, card networks, regulators, or laws may require SinLess Games LLC to change payment-related rules, features, supported products, marketplace items, checkout flows, payout flows, refund rules, risk controls, or account access.',
        'SinLess Games LLC may make such changes without prior notice when necessary.',
        'Processor-required changes may include:',
      ],
      bullets: [
        'Removing payment methods',
        'Blocking certain transactions',
        'Restricting regions',
        'Requiring additional verification',
        'Disabling marketplace categories',
        'Modifying refund behavior',
        'Holding funds',
        'Updating checkout flows',
        'Updating disclosures',
        'Updating this policy',
        'Terminating unsupported activity',
      ],
    },
    {
      id: 'publication-checklist',
      title: '46. Publication Checklist',
      body: ['Before publishing this policy, complete the following:'],
      bullets: [
        'Confirm official company name: SinLess Games LLC',
        'Confirm actual payment processors in use',
        'Confirm Stripe account type and applicable restricted-business terms',
        'Confirm PayPal account type and applicable acceptable-use terms',
        'Confirm whether marketplace payouts are supported',
        'Confirm whether tax calculation is handled by Stripe, PayPal, another vendor, or internally',
        'Confirm whether subscriptions are managed by Stripe Billing, PayPal Subscriptions, another provider, or internally',
        'Confirm payment webhook security implementation',
        'Confirm PCI DSS scope',
        'Confirm refund workflow',
        'Confirm chargeback workflow',
        'Confirm payout review workflow',
        'Confirm fraud monitoring workflow',
        'Confirm sanctions screening workflow',
        'Confirm marketplace publisher verification workflow',
        'Confirm supported countries and currencies',
        'Confirm billing@sinlessgames.com exists and is monitored',
        'Confirm security@sinlessgames.com exists and is monitored',
        'Confirm legal@sinlessgames.com exists and is monitored',
        'Confirm this filename spelling; consider renaming to payment-processor-compliance.md',
        'Have qualified legal and payment compliance counsel review this policy',
      ],
    },
    {
      id: 'changes-to-this-policy',
      title: '47. Changes to This Policy',
      body: [
        'We may update this policy from time to time.',
        'When we make material changes, we will update the last_updated date and may provide notice through the service, documentation, account settings, billing portal, email, release notes, legal notices page, or another reasonable method.',
        'Continued use of Aerealith AI after changes become effective means you accept the updated policy.',
      ],
    },
    {
      id: 'contact',
      title: '48. Contact',
      body: [
        'Questions about this policy may be sent to:',
        'Before publishing this policy, confirm these email aliases exist and are monitored.',
      ],
      contacts: [
        {
          label: 'Billing',
          email: 'billing@sinlessgames.com',
          href: 'mailto:billing@sinlessgames.com',
        },
        {
          label: 'Security',
          email: 'security@sinlessgames.com',
          href: 'mailto:security@sinlessgames.com',
        },
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
        {
          label: 'Support',
          email: 'support@sinlessgames.com',
          href: 'mailto:support@sinlessgames.com',
        },
      ],
    },
    {
      id: 'legal-review-notice',
      title: '49. Legal Review Notice',
      body: [
        'This policy is a draft template and should be reviewed by qualified legal counsel and payment compliance professionals before publication.',
        'Payment processor rules, card network rules, marketplace payout rules, tax requirements, sanctions obligations, consumer protection rules, refund rules, subscription renewal requirements, and financial compliance obligations may vary by jurisdiction, provider, payment method, transaction type, and business model.',
      ],
    },
  ],
} satisfies PolicyDocument;

export default paymentProcessorCompliancePolicy;
