import type { PolicyDocument } from '../../types';

export const privacyPolicy = {
  slug: 'privacy',
  path: '/Policies/privacy',
  meta: {
    title: 'Privacy Policy',
    description:
      'Explains how Aerealith AI collects, uses, shares, protects, retains, and processes personal information.',
    effectiveDate: '2026-05-18',
    lastUpdated: '2026-05-18',
    owner: 'SinLess Games LLC',
    status: 'draft',
  },
  relatedPolicies: [
    {
      label: 'Terms of Use',
      href: '/Policies/terms-of-use',
    },
    {
      label: 'Data Policy',
      href: '/Policies/data',
    },
    {
      label: 'Security Policy',
      href: '/Policies/security-policy',
    },
    {
      label: 'Acceptable Use Policy',
      href: '/Policies/acceptable-use',
    },
    {
      label: 'AI Transparency Policy',
      href: '/Policies/ai-transparency',
    },
    {
      label: 'Responsible AI Policy',
      href: '/Policies/responsible-ai',
    },
    {
      label: 'Cookie and Tracking Policy',
      href: '/Policies/cookie-tracking',
    },
    {
      label: 'Billing, Refund, and Cancellation Policy',
      href: '/Policies/billing-refund-cancellation',
    },
    {
      label: 'Copyright Takedown Policy',
      href: '/Policies/copyright-takedown',
    },
    {
      label: 'User-Generated Content Policy',
      href: '/Policies/user-generated-content',
    },
    {
      label: 'Incident Notification Policy',
      href: '/Policies/incident-notification',
    },
    {
      label: 'Subprocessor Vendor List',
      href: '/Policies/subprocessor-vendor-list',
    },
    {
      label: 'Support Policy',
      href: '/Policies/support-policy',
    },
    {
      label: 'Underage Policy',
      href: '/Policies/underage-policy',
    },
  ],
  sections: [
    {
      id: 'purpose',
      title: '1. Purpose',
      body: [
        'This Privacy Policy explains how SinLess Games LLC collects, uses, shares, protects, retains, and processes personal information through Aerealith AI.',
        'Aerealith AI is designed to help users think, create, automate, analyze, monitor, and act across connected systems. Because Aerealith AI may process user prompts, files, integrations, memory, analytics, automations, plugins, and workspace data, privacy must be clear, user-controlled, and transparent.',
        'This policy explains:',
        'The core privacy commitments are:',
        'Users own their data. Aerealith AI does not sell user data. Aerealith AI does not use user data outside legitimate service business logic and approved research purposes.',
      ],
      bullets: [
        'What personal information we collect',
        'How we collect personal information',
        'Why we use personal information',
        'How we share personal information',
        'How long we retain personal information',
        'How users can access, correct, export, or delete personal information',
        'How Aerealith AI handles AI memory, files, tools, integrations, and research use',
        'How privacy works for organizations, developers, marketplace publishers, and enterprise customers',
        'How users can contact us about privacy questions or requests',
      ],
    },
    {
      id: 'scope',
      title: '2. Scope',
      body: [
        'This Privacy Policy applies to Aerealith AI services, including:',
        'This policy applies to:',
        'Some enterprise, self-hosted, hybrid, private, or air-gapped deployments may have additional privacy terms in a written agreement.',
      ],
      bullets: [
        'Websites',
        'Web applications',
        'Desktop applications',
        'Mobile applications',
        'Browser extensions',
        'APIs',
        'Developer tools',
        'Documentation sites',
        'Marketplace features',
        'Plugins',
        'Automations',
        'Integrations',
        'Dashboards',
        'Analytics features',
        'Memory features',
        'Support systems',
        'Billing systems',
        'Organization workspaces',
        'Cloud-hosted deployments',
        'Self-hosted deployments, where applicable',
        'Hybrid deployments, where applicable',
        'Air-gapped deployments, where applicable',
        'Visitors',
        'Individual users',
        'Organization users',
        'Workspace members',
        'Administrators',
        'Developers',
        'Marketplace publishers',
        'API users',
        'Enterprise customers',
        'Anyone who interacts with Aerealith AI through an account, workspace, integration, automation, shared agent, plugin, or connected service',
      ],
    },
    {
      id: 'relationship-to-other-policies',
      title: '3. Relationship to Other Policies',
      body: [
        'This Privacy Policy works together with other Aerealith AI policies, including:',
        'If there is a conflict between this Privacy Policy and a written agreement signed by SinLess Games LLC, the written agreement controls only to the extent of that conflict.',
      ],
      links: [
        {
          label: 'Terms of Use',
          href: '/Policies/terms-of-use',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
        {
          label: 'AI Transparency Policy',
          href: '/Policies/ai-transparency',
        },
        {
          label: 'Responsible AI Policy',
          href: '/Policies/responsible-ai',
        },
        {
          label: 'Cookie and Tracking Policy',
          href: '/Policies/cookie-tracking',
        },
        {
          label: 'Billing, Refund, and Cancellation Policy',
          href: '/Policies/billing-refund-cancellation',
        },
        {
          label: 'Copyright Takedown Policy',
          href: '/Policies/copyright-takedown',
        },
        {
          label: 'User-Generated Content Policy',
          href: '/Policies/user-generated-content',
        },
        {
          label: 'Incident Notification Policy',
          href: '/Policies/incident-notification',
        },
        {
          label: 'Subprocessor Vendor List',
          href: '/Policies/subprocessor-vendor-list',
        },
        {
          label: 'Support Policy',
          href: '/Policies/support-policy',
        },
        {
          label: 'Underage Policy',
          href: '/Policies/underage-policy',
        },
      ],
    },
    {
      id: 'no-legal-advice',
      title: '4. No Legal Advice',
      body: [
        'This policy is provided for transparency and operational clarity.',
        'It is not legal advice.',
        'Privacy, data protection, AI, consumer protection, security, children’s privacy, employment, healthcare, financial, education, and international transfer requirements may vary by jurisdiction and use case.',
        'Before publishing this policy, SinLess Games LLC should have it reviewed by qualified legal counsel.',
      ],
    },
    {
      id: 'definitions',
      title: '5. Definitions',
      body: ['For this policy:'],
      bullets: [
        '“Aerealith AI,” “we,” “us,” and “our” mean SinLess Games LLC and the Aerealith AI services.',
        '“User,” “you,” and “your” mean anyone who uses or interacts with Aerealith AI.',
        '“Personal information” means information that identifies, relates to, describes, can reasonably be associated with, or could reasonably be linked to an individual or household.',
        '“Customer Data” means data that users or organizations submit, upload, import, connect, generate, or process through Aerealith AI.',
        '“Account Data” means information used to create, secure, administer, and support an account.',
        '“Service Data” means operational data created by Aerealith AI while providing the service.',
        '“Sensitive data” means personal information or confidential information that requires stronger protection because of its nature, legal status, or risk.',
        '“Processing” means collecting, using, storing, transmitting, analyzing, retrieving, sharing, deleting, or otherwise handling data.',
      ],
    },
    {
      id: 'data-ownership',
      title: '6. Data Ownership',
      body: [
        'As between you and SinLess Games LLC, you retain ownership of your data.',
        'SinLess Games LLC does not claim ownership of user prompts, messages, uploaded files, workspace content, organization content, memory entries, dashboards, analytics inputs, API inputs, integrations, plugin content, or other Customer Data.',
        'By using Aerealith AI, you grant SinLess Games LLC a limited right to process your data only as needed to provide, secure, maintain, troubleshoot, improve, support, and research Aerealith AI according to this policy, the Data Policy, the Terms of Use, and applicable agreements.',
      ],
      links: [
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
        {
          label: 'Terms of Use',
          href: '/Policies/terms-of-use',
        },
      ],
    },
    {
      id: 'personal-information-we-collect',
      title: '7. Personal Information We Collect',
      body: [
        'Aerealith AI may collect personal information in the categories below.',
        'The exact information collected depends on how you use Aerealith AI, your account settings, organization settings, deployment type, subscription, integrations, and enabled features.',
      ],
    },
    {
      id: 'account-information',
      title: '7.1 Account Information',
      body: ['We may collect:'],
      bullets: [
        'Name',
        'Email address',
        'Username',
        'Password hash',
        'Profile image',
        'Contact information',
        'Account identifiers',
        'Organization membership',
        'Workspace membership',
        'Role and permission information',
        'Authentication settings',
        'Multi-factor authentication settings',
        'Passkey information',
        'OAuth provider identifiers',
        'Account status',
        'Communication preferences',
        'Consent records',
      ],
    },
    {
      id: 'billing-and-payment-information',
      title: '7.2 Billing and Payment Information',
      body: [
        'We may collect:',
        'SinLess Games LLC generally does not directly store full payment card numbers. Payment data is usually processed by payment processors such as Stripe, PayPal, or other approved providers.',
      ],
      bullets: [
        'Billing name',
        'Billing email',
        'Billing address',
        'Tax address',
        'Organization billing details',
        'Subscription plan',
        'Invoice records',
        'Transaction records',
        'Payment method token',
        'Payment processor customer ID',
        'Refund records',
        'Chargeback records',
        'Tax exemption records',
        'Marketplace purchase records',
        'Marketplace payout records, where applicable',
      ],
    },
    {
      id: 'user-content-and-customer-data',
      title: '7.3 User Content and Customer Data',
      body: ['We may process content you provide or connect to Aerealith AI, including:'],
      bullets: [
        'Prompts',
        'Messages',
        'Conversations',
        'Uploaded files',
        'Connected files',
        'Documents',
        'Images',
        'Audio',
        'Video',
        'Code',
        'Logs',
        'Notes',
        'Reports',
        'Dashboards',
        'Analytics inputs',
        'Workspace content',
        'Organization knowledge',
        'Project data',
        'API inputs',
        'API outputs',
        'Automation inputs and outputs',
        'Plugin inputs and outputs',
        'Marketplace publisher content',
        'Shared content',
        'User-generated content',
      ],
    },
    {
      id: 'ai-memory-and-personalization-data',
      title: '7.4 AI Memory and Personalization Data',
      body: [
        'If memory or personalization features are enabled, Aerealith AI may process:',
        'Users and organizations may have controls to view, edit, delete, export, pause, disable, scope, or restrict memory depending on the feature, deployment, and subscription.',
      ],
      bullets: [
        'User preferences',
        'Communication style',
        'Assistant identity settings',
        'Workspace context',
        'Project context',
        'Organization context',
        'Technical environment details',
        'Prior decisions',
        'Workflow preferences',
        'Automation preferences',
        'Analytics preferences',
        'User-provided facts',
        'User-approved memory entries',
        'System-generated memory summaries',
      ],
    },
    {
      id: 'integration-data',
      title: '7.5 Integration Data',
      body: [
        'If you connect Aerealith AI to third-party services, we may process data from those services according to your permissions.',
        'Integration data may include information from:',
        'Aerealith AI only accesses connected services according to granted permissions, technical configuration, user instructions, organization policies, and applicable agreements.',
      ],
      bullets: [
        'Email',
        'Calendar',
        'Contacts',
        'Cloud storage',
        'Git repositories',
        'Project management tools',
        'Documentation systems',
        'Chat platforms',
        'Ticketing systems',
        'Infrastructure systems',
        'Analytics systems',
        'Payment systems',
        'Developer tools',
        'IoT systems',
        'Marketplace systems',
      ],
    },
    {
      id: 'automation-and-tool-data',
      title: '7.6 Automation and Tool Data',
      body: [
        'When Aerealith AI uses tools, automations, workflows, agents, plugins, or integrations, we may process:',
      ],
      bullets: [
        'Trigger events',
        'User instructions',
        'Action parameters',
        'Tool outputs',
        'Execution status',
        'Approval records',
        'Error messages',
        'Logs',
        'Rollback metadata',
        'Audit records',
        'Integration metadata',
        'Plugin execution records',
        'Automation history',
      ],
    },
    {
      id: 'device-usage-and-technical-information',
      title: '7.7 Device, Usage, and Technical Information',
      body: [
        'We may collect:',
        'Cookie and tracking behavior is described in the Cookie and Tracking Policy.',
      ],
      bullets: [
        'IP address',
        'Device type',
        'Browser type',
        'Operating system',
        'App version',
        'Referring URL',
        'Pages visited',
        'Features used',
        'Session identifiers',
        'Request metadata',
        'Error logs',
        'Performance metrics',
        'API metadata',
        'Rate-limit information',
        'Authentication metadata',
        'Security event metadata',
        'Approximate location derived from IP address',
        'Cookies and similar identifiers',
      ],
      links: [
        {
          label: 'Cookie and Tracking Policy',
          href: '/Policies/cookie-tracking',
        },
      ],
    },
    {
      id: 'support-and-communications-data',
      title: '7.8 Support and Communications Data',
      body: [
        'When you contact us, we may collect:',
        'Do not send passwords, private keys, full payment card numbers, access tokens, or unnecessary sensitive information through support channels.',
      ],
      bullets: [
        'Name',
        'Email address',
        'Organization name',
        'Support ticket content',
        'Chat or email communications',
        'Screenshots',
        'Logs',
        'Files you choose to provide',
        'Troubleshooting details',
        'Feedback',
        'Survey responses',
        'Incident reports',
        'Billing questions',
        'Legal notices',
      ],
    },
    {
      id: 'marketplace-and-developer-data',
      title: '7.9 Marketplace and Developer Data',
      body: ['If you use developer or marketplace features, we may collect:'],
      bullets: [
        'Developer account details',
        'API key metadata',
        'SDK usage data',
        'Plugin metadata',
        'Marketplace publisher profile',
        'Marketplace item listings',
        'Review and rating activity',
        'Installation records',
        'Purchase records',
        'Payout records',
        'Tax and identity verification records',
        'Security review records',
        'Version history',
        'Permission declarations',
        'Support contact details',
        'Abuse and policy enforcement records',
      ],
    },
    {
      id: 'security-and-abuse-prevention-data',
      title: '7.10 Security and Abuse Prevention Data',
      body: [
        'We may collect data to protect users, organizations, Aerealith AI, and third parties.',
        'Security and abuse prevention data may include:',
      ],
      bullets: [
        'Login records',
        'Session records',
        'Failed login attempts',
        'Device and browser metadata',
        'Suspicious activity signals',
        'API abuse signals',
        'Fraud signals',
        'Rate-limit records',
        'Security alerts',
        'Audit logs',
        'Vulnerability reports',
        'Incident response records',
        'Credential exposure indicators',
        'Malware or malicious plugin indicators',
        'Abuse reports',
        'Policy enforcement records',
      ],
    },
    {
      id: 'sensitive-data',
      title: '8. Sensitive Data',
      body: [
        'Aerealith AI may process sensitive data if users or organizations provide it or connect systems containing it.',
        'Sensitive data may include:',
        'Users should only provide sensitive data when authorized and when the account, workspace, deployment, subscription, and settings are appropriate for that type of data.',
        'Secrets should be stored in approved secret-management systems, not ordinary prompts, files, memory, logs, or general user content.',
      ],
      bullets: [
        'Government identification numbers',
        'Financial account information',
        'Payment information',
        'Health information',
        'Legal records',
        'Biometric information',
        'Precise location information',
        'Children’s data',
        'Credentials',
        'Secrets',
        'Passwords',
        'API keys',
        'Tokens',
        'Private keys',
        'Confidential business information',
        'Trade secrets',
        'Regulated customer data',
        'Security-sensitive infrastructure data',
      ],
    },
    {
      id: 'sources-of-personal-information',
      title: '9. Sources of Personal Information',
      body: ['We may collect personal information from:'],
      bullets: [
        'You directly',
        'Your account activity',
        'Your organization',
        'Workspace administrators',
        'Other users who interact with you',
        'Connected integrations',
        'Uploaded files',
        'APIs and developer tools',
        'Plugins and marketplace items',
        'Payment processors',
        'Authentication providers',
        'Security providers',
        'Support providers',
        'Analytics and observability tools',
        'Public sources, where relevant to a requested feature',
        'Service providers and subprocessors',
        'Logs, telemetry, and system events',
        'Cookies and similar technologies',
      ],
    },
    {
      id: 'how-we-use-personal-information',
      title: '10. How We Use Personal Information',
      body: [
        'Aerealith AI uses personal information only for legitimate service business logic and approved research purposes.',
        'We may use personal information to:',
      ],
      bullets: [
        'Provide Aerealith AI services',
        'Create and manage accounts',
        'Authenticate users',
        'Authorize access',
        'Manage organizations and workspaces',
        'Process prompts and generate responses',
        'Process uploaded or connected files',
        'Run automations and workflows',
        'Execute approved tool calls',
        'Operate integrations',
        'Support plugins and marketplace items',
        'Provide AI memory and personalization',
        'Build dashboards and analytics',
        'Provide search and retrieval',
        'Process billing and payments',
        'Manage subscriptions and add-ons',
        'Provide customer support',
        'Send service communications',
        'Send billing communications',
        'Send security notifications',
        'Send incident notifications',
        'Send legal notices',
        'Maintain audit logs',
        'Enforce policies',
        'Prevent fraud and abuse',
        'Detect security threats',
        'Investigate incidents',
        'Debug errors',
        'Improve reliability',
        'Improve performance',
        'Improve accessibility',
        'Improve documentation',
        'Improve user experience',
        'Evaluate AI quality and safety',
        'Conduct approved research',
        'Comply with law',
        'Enforce agreements',
        'Protect users, systems, and the public',
      ],
    },
    {
      id: 'business-logic-use',
      title: '11. Business Logic Use',
      body: [
        'Business logic means data processing reasonably needed to operate, secure, support, and improve Aerealith AI.',
        'Business logic includes:',
        'Aerealith AI does not use user data for unrelated purposes.',
      ],
      bullets: [
        'Account management',
        'Authentication',
        'Authorization',
        'User settings',
        'Organization settings',
        'Subscription entitlements',
        'Billing',
        'Feature flags',
        'Model routing',
        'Prompt processing',
        'File processing',
        'Tool execution',
        'Automation execution',
        'Integration operation',
        'Marketplace operation',
        'Memory operation',
        'Search and retrieval',
        'Dashboard and analytics operation',
        'Support',
        'Security',
        'Abuse prevention',
        'Incident response',
        'Logging',
        'Monitoring',
        'Backups',
        'Compliance',
        'Product improvement',
        'Service reliability',
      ],
    },
    {
      id: 'approved-research-use',
      title: '12. Approved Research Use',
      body: [
        'Aerealith AI may use data for approved research that supports the Aerealith AI product, platform, safety, reliability, security, quality, accessibility, user experience, and responsible AI goals.',
        'Approved research may include:',
        'Research use should follow these principles:',
      ],
      bullets: [
        'Improving AI response quality',
        'Improving retrieval accuracy',
        'Improving memory behavior',
        'Improving automation safety',
        'Improving tool-use reliability',
        'Improving model routing',
        'Improving abuse detection',
        'Improving security detection',
        'Improving policy enforcement',
        'Evaluating hallucination risk',
        'Evaluating model behavior',
        'Evaluating plugin safety',
        'Evaluating marketplace safety',
        'Testing new product features',
        'Improving accessibility',
        'Improving documentation',
        'Evaluating anonymized or aggregated usage trends',
        'Use the minimum data reasonably needed.',
        'Prefer aggregated, anonymized, or de-identified data where practical.',
        'Limit human review of private user content.',
        'Restrict access to authorized personnel or systems.',
        'Protect sensitive data.',
        'Do not publish identifiable user or organization data without permission.',
        'Do not use secrets, credentials, private keys, or tokens for research.',
        'Respect user and organization settings.',
        'Respect enterprise agreements and data restrictions.',
        'Maintain appropriate auditability.',
      ],
    },
    {
      id: 'model-training-and-fine-tuning',
      title: '13. Model Training and Fine-Tuning',
      body: [
        'Aerealith AI distinguishes between:',
        'Unless clearly disclosed, enabled by user or organization settings, or permitted by a written agreement, Aerealith AI should not use private Customer Data to train public or general-purpose models.',
        'If optional training, fine-tuning, or learning features are offered, they should provide clear notice, controls, and documentation.',
        'Enterprise and organization customers may have additional controls over whether their data may be used for model training, evaluation, research, or product improvement.',
      ],
      bullets: [
        'Processing data to provide a requested response',
        'Processing data to operate the service',
        'Processing data to improve product quality',
        'Processing data for approved research and evaluation',
        'Training or fine-tuning models',
      ],
    },
    {
      id: 'ai-providers-and-model-routing',
      title: '14. AI Providers and Model Routing',
      body: [
        'Aerealith AI may route requests to different models, services, providers, local systems, or organization-controlled systems depending on:',
        'Data sent to AI providers may include relevant portions of:',
        'Aerealith AI should limit data sent to AI providers to what is reasonably needed for the requested function.',
        'Relevant providers should be listed in the Subprocessor Vendor List, where applicable.',
      ],
      bullets: [
        'User settings',
        'Organization settings',
        'Deployment type',
        'Feature availability',
        'Cost and performance requirements',
        'Data sensitivity',
        'Tool requirements',
        'Safety requirements',
        'Subscription plan',
        'System availability',
        'Prompts',
        'Conversation context',
        'Files',
        'Retrieved content',
        'Tool outputs',
        'Metadata',
        'Instructions',
        'Memory, when enabled and relevant',
      ],
      links: [
        {
          label: 'Subprocessor Vendor List',
          href: '/Policies/subprocessor-vendor-list',
        },
      ],
    },
    {
      id: 'cookies-and-tracking',
      title: '15. Cookies and Tracking',
      body: [
        'Aerealith AI may use cookies, local storage, pixels, analytics tags, device identifiers, log data, and similar technologies.',
        'These may be used for:',
        'Cookie and tracking behavior is described in the Cookie and Tracking Policy.',
      ],
      bullets: [
        'Authentication',
        'Security',
        'Fraud prevention',
        'Session management',
        'Consent preference storage',
        'Preferences',
        'Product analytics',
        'Performance monitoring',
        'Error reporting',
        'Billing and checkout',
        'Marketplace operation',
        'Documentation usage',
        'Marketing attribution, where enabled and permitted',
      ],
      links: [
        {
          label: 'Cookie and Tracking Policy',
          href: '/Policies/cookie-tracking',
        },
      ],
    },
    {
      id: 'analytics-and-telemetry',
      title: '16. Analytics and Telemetry',
      body: [
        'Aerealith AI may process analytics and telemetry to operate and improve the service.',
        'Analytics and telemetry may include:',
        'Analytics data is not sold.',
        'Analytics data should not be used outside legitimate service business logic and approved research purposes.',
      ],
      bullets: [
        'Page views',
        'Feature usage',
        'Session metadata',
        'Error rates',
        'Performance metrics',
        'API latency',
        'Automation status',
        'Tool call status',
        'Marketplace usage',
        'Dashboard usage',
        'Documentation usage',
        'Aggregated usage trends',
        'Subscription entitlement checks',
        'Security and reliability metrics',
      ],
    },
    {
      id: 'legal-bases-for-processing',
      title: '17. Legal Bases for Processing',
      body: [
        'Where a legal basis is required, SinLess Games LLC may process personal information based on one or more of the following:',
        'Examples:',
        'Users may have rights to withdraw consent, object to processing, or request more information depending on applicable law.',
      ],
      bullets: [
        'Performance of a contract',
        'User consent',
        'Legitimate interests',
        'Legal obligations',
        'Protection of vital interests',
        'Public interest, where applicable',
        'Another lawful basis permitted by applicable law',
        'We process account information to provide and secure the service.',
        'We process billing information to manage subscriptions and payments.',
        'We process prompts and files to provide requested AI features.',
        'We process security logs to protect users and systems.',
        'We process consent records to honor privacy choices.',
        'We process data when required to comply with law.',
      ],
    },
    {
      id: 'legitimate-interests',
      title: '18. Legitimate Interests',
      body: [
        'Where permitted by law, legitimate interests may include:',
        'We balance legitimate interests against user privacy rights where required.',
      ],
      bullets: [
        'Providing Aerealith AI',
        'Securing accounts',
        'Preventing fraud',
        'Preventing abuse',
        'Debugging errors',
        'Improving reliability',
        'Improving product quality',
        'Supporting users',
        'Enforcing policies',
        'Protecting legal rights',
        'Maintaining audit logs',
        'Conducting approved research',
        'Protecting users, organizations, systems, and the public',
      ],
    },
    {
      id: 'how-we-share-personal-information',
      title: '19. How We Share Personal Information',
      body: [
        'Aerealith AI may share personal information only as needed for legitimate business logic, approved research, legal obligations, user direction, or organization configuration.',
        'We may share personal information with:',
        'We do not sell user data.',
      ],
      bullets: [
        'Service providers',
        'Subprocessors',
        'Hosting providers',
        'Storage providers',
        'Database providers',
        'AI providers',
        'Analytics providers',
        'Observability providers',
        'Security providers',
        'Payment processors',
        'Tax providers',
        'Email providers',
        'Support providers',
        'Marketplace providers',
        'Integration providers',
        'Authentication providers',
        'Professional advisors',
        'Legal or regulatory authorities, where required',
        'Organization administrators, where applicable',
        'Third parties authorized by the user or organization',
      ],
    },
    {
      id: 'service-providers-and-subprocessors',
      title: '20. Service Providers and Subprocessors',
      body: [
        'SinLess Games LLC may use service providers and subprocessors to operate Aerealith AI.',
        'Subprocessors may support:',
        'Subprocessors should be listed in the Subprocessor Vendor List.',
        'SinLess Games LLC should require subprocessors to protect personal information using appropriate contractual, technical, and organizational safeguards.',
      ],
      bullets: [
        'Hosting',
        'Storage',
        'Databases',
        'Authentication',
        'Payments',
        'Email',
        'AI processing',
        'Analytics',
        'Observability',
        'Logging',
        'Customer support',
        'Security',
        'Abuse prevention',
        'Marketplace operations',
        'Documentation',
        'Content delivery',
        'Tax calculation',
        'Billing management',
      ],
      links: [
        {
          label: 'Subprocessor Vendor List',
          href: '/Policies/subprocessor-vendor-list',
        },
      ],
    },
    {
      id: 'no-sale-of-personal-information',
      title: '21. No Sale of Personal Information',
      body: [
        'SinLess Games LLC does not sell user data or personal information.',
        'Aerealith AI does not sell:',
        'Use of subprocessors to operate Aerealith AI is not a sale of personal information when they process data only on behalf of SinLess Games LLC or the customer according to applicable agreements and policies.',
      ],
      bullets: [
        'User prompts',
        'User messages',
        'Uploaded files',
        'Memory entries',
        'Workspace data',
        'Organization data',
        'Integration data',
        'API inputs or outputs',
        'Personal information',
        'Private user content',
        'Sensitive data',
        'Secrets',
        'Analytics inputs',
        'Dashboard data',
      ],
    },
    {
      id: 'targeted-advertising-and-sharing',
      title: '22. Targeted Advertising and Sharing',
      body: [
        'Aerealith AI does not use private user content, prompts, files, memory, organization data, or workspace data for third-party targeted advertising.',
        'Public marketing pages may use limited marketing attribution, analytics, or advertising cookies where enabled, disclosed, and permitted.',
        'Where applicable law defines certain activity as “sharing” or “targeted advertising,” Aerealith AI should provide required opt-out controls.',
        'Cookie and advertising choices are described in the Cookie and Tracking Policy.',
      ],
      links: [
        {
          label: 'Cookie and Tracking Policy',
          href: '/Policies/cookie-tracking',
        },
      ],
    },
    {
      id: 'organization-administrator-access',
      title: '23. Organization Administrator Access',
      body: [
        'If you use Aerealith AI through an organization workspace, organization administrators may access, manage, export, restrict, or delete data associated with that organization.',
        'Organization administrators may have access to:',
        'Users should not use organization workspaces for personal data unless permitted by organization policy.',
      ],
      bullets: [
        'Workspace content',
        'Member lists',
        'Usage records',
        'Audit logs',
        'Integrations',
        'Automations',
        'Marketplace installations',
        'Security settings',
        'Billing settings',
        'Memory settings',
        'Shared files',
        'Reports',
        'Dashboard data',
        'Export tools',
      ],
    },
    {
      id: 'public-content',
      title: '24. Public Content',
      body: [
        'Some Aerealith AI features may allow users to publish or share content publicly.',
        'Public content may include:',
        'Users are responsible for ensuring public content does not include private, sensitive, confidential, regulated, or unauthorized data.',
        'Public content may be indexed, copied, downloaded, cached, shared, or retained by others.',
      ],
      bullets: [
        'Shared chats',
        'Public dashboards',
        'Marketplace items',
        'Documentation',
        'Templates',
        'Plugins',
        'Workflows',
        'Reports',
        'Generated assets',
        'Community posts',
        'Reviews',
        'Comments',
      ],
    },
    {
      id: 'user-rights-and-choices',
      title: '25. User Rights and Choices',
      body: [
        'Depending on location, account type, organization settings, and applicable law, users may have rights to:',
        'To exercise privacy rights, contact privacy@sinlessgames.com.',
        'SinLess Games LLC may need to verify your identity or authority before fulfilling a request.',
        'For organization data, you may need to contact your organization administrator.',
      ],
      bullets: [
        'Access personal information',
        'Correct personal information',
        'Delete personal information',
        'Export personal information',
        'Request data portability',
        'Restrict processing',
        'Object to processing',
        'Withdraw consent',
        'Opt out of sale',
        'Opt out of sharing',
        'Opt out of targeted advertising',
        'Limit use of sensitive personal information',
        'Appeal a privacy-rights decision',
        'Lodge a complaint with a regulator',
      ],
      contacts: [
        {
          label: 'Privacy',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
      ],
    },
    {
      id: 'access-requests',
      title: '26. Access Requests',
      body: [
        'Users may request access to personal information associated with their account.',
        'Access requests may include:',
        'Access may be limited by security, privacy, legal, intellectual property, trade secret, organization, or technical restrictions.',
      ],
      bullets: [
        'Account data',
        'Profile data',
        'User content',
        'Memory data',
        'Conversation data',
        'Billing records',
        'Support records',
        'Workspace data, where permitted',
        'Organization data, where permitted',
        'Audit records, where permitted',
      ],
    },
    {
      id: 'correction-requests',
      title: '27. Correction Requests',
      body: [
        'Users may correct certain personal information through account settings or by contacting support.',
        'Correction may be available for:',
        'Some records may not be editable if retained for legal, security, billing, fraud-prevention, audit, or compliance reasons.',
      ],
      bullets: [
        'Name',
        'Email address',
        'Profile information',
        'Communication preferences',
        'Memory entries',
        'Account settings',
        'Billing contact information',
        'Organization profile information, where permitted',
      ],
    },
    {
      id: 'deletion-requests',
      title: '28. Deletion Requests',
      body: [
        'Users may request deletion of certain personal information.',
        'Deletion may include:',
        'Some data may not be deleted immediately or completely if retained for:',
        'Where deletion is not immediately possible, access may be restricted, data may be scheduled for deletion, or data may be retained only as required.',
      ],
      bullets: [
        'Account deletion',
        'File deletion',
        'Memory deletion',
        'Workspace deletion',
        'Organization data deletion, where permitted',
        'Integration disconnection',
        'Automation deletion',
        'API key deletion',
        'Dashboard deletion',
        'Marketplace content removal',
        'Legal compliance',
        'Security',
        'Fraud prevention',
        'Abuse prevention',
        'Billing records',
        'Audit logs',
        'Dispute resolution',
        'Backup rotation',
        'Incident response',
        'Contractual obligations',
        'Organization retention policies',
      ],
    },
    {
      id: 'export-and-portability-requests',
      title: '29. Export and Portability Requests',
      body: [
        'Users and organizations may request export of certain data depending on account type, permissions, product functionality, deployment type, and applicable law.',
        'Exportable data may include:',
        'Exports may be provided in formats such as JSON, CSV, Markdown, PDF, ZIP archives, or other machine-readable formats where supported.',
      ],
      bullets: [
        'Account data',
        'User content',
        'Files',
        'Memory',
        'Conversation history',
        'Project data',
        'Workspace data',
        'Organization data',
        'Dashboard data',
        'Analytics data',
        'Automation records',
        'Integration metadata',
        'Plugin metadata',
        'Audit logs, where permitted',
        'Billing records, where permitted',
      ],
    },
    {
      id: 'consent-and-withdrawal',
      title: '30. Consent and Withdrawal',
      body: [
        'Where Aerealith AI relies on consent, users may withdraw consent where required or supported.',
        'Consent may apply to:',
        'Withdrawing consent does not affect processing that occurred before consent was withdrawn.',
        'Some features may not work if consent is withdrawn.',
      ],
      bullets: [
        'Optional cookies',
        'Marketing emails',
        'Certain analytics',
        'Certain research features',
        'Certain memory features',
        'Certain integrations',
        'Certain AI training or fine-tuning features',
        'Certain sensitive data processing',
      ],
    },
    {
      id: 'marketing-communications',
      title: '31. Marketing Communications',
      body: [
        'Aerealith AI may send marketing communications where permitted.',
        'Users may unsubscribe from marketing emails by using the unsubscribe link or contacting support.',
        'Even if you unsubscribe from marketing communications, we may still send:',
      ],
      bullets: [
        'Account notices',
        'Security notices',
        'Billing notices',
        'Service notices',
        'Legal notices',
        'Incident notices',
        'Support communications',
        'Policy update notices',
      ],
    },
    {
      id: 'children-and-minors',
      title: '32. Children and Minors',
      body: [
        'Aerealith AI is not intended for children unless expressly permitted by applicable law, account settings, organization configuration, and written agreements.',
        'Use by minors is governed by the Underage Policy.',
        'SinLess Games LLC does not knowingly collect personal information from children in violation of applicable law.',
        'If we learn that children’s data has been collected in violation of policy or law, we may delete, restrict, or take other appropriate action.',
        'Parents, guardians, or authorized school or organization administrators may contact privacy@sinlessgames.com.',
      ],
      contacts: [
        {
          label: 'Privacy',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
      ],
      links: [
        {
          label: 'Underage Policy',
          href: '/Policies/underage-policy',
        },
      ],
    },
    {
      id: 'student-education-and-school-use',
      title: '33. Student, Education, and School Use',
      body: [
        'If Aerealith AI is used by schools, educational institutions, students, or minors, additional terms may apply.',
        'Educational use may require:',
        'Before enabling school or student use, SinLess Games LLC should confirm applicable legal and contractual requirements.',
      ],
      bullets: [
        'School authorization',
        'Parent or guardian consent',
        'Student privacy protections',
        'Data processing agreements',
        'Restricted advertising',
        'Restricted profiling',
        'Restricted data retention',
        'Administrator controls',
        'Compliance with applicable education privacy laws',
      ],
    },
    {
      id: 'healthcare-financial-legal-and-regulated-data',
      title: '34. Healthcare, Financial, Legal, and Regulated Data',
      body: [
        'Aerealith AI is not intended to process regulated healthcare, financial, legal, education, employment, biometric, criminal justice, or other regulated data unless the account, deployment, subscription, controls, and written agreements are appropriate for that use.',
        'For example:',
        'Users and organizations are responsible for ensuring their use complies with applicable regulated-data requirements.',
      ],
      bullets: [
        'Aerealith AI should not be used for protected health information unless a proper business associate agreement or equivalent arrangement is in place where required.',
        'Aerealith AI should not be used for payment card processing outside approved payment processor workflows.',
        'Aerealith AI should not be used as the sole decision-maker for legal, medical, financial, employment, housing, credit, insurance, education, or essential service decisions.',
      ],
    },
    {
      id: 'data-retention',
      title: '35. Data Retention',
      body: [
        'Aerealith AI retains personal information only as long as reasonably needed for the purposes described in this policy unless a longer retention period is required or permitted by law, contract, security, compliance, backup, audit, billing, dispute resolution, or legitimate business needs.',
        'Retention may vary by data type.',
        'Examples:',
      ],
      bullets: [
        'Account data may be retained while the account is active.',
        'Billing records may be retained for tax, accounting, fraud prevention, and legal obligations.',
        'Security logs may be retained for incident response and abuse prevention.',
        'Audit logs may be retained for compliance and accountability.',
        'Support records may be retained for customer service and dispute resolution.',
        'Backups may persist for a limited period before rotation or deletion.',
        'Memory may follow user or organization memory settings.',
        'Organization data may follow organization retention policies.',
        'Enterprise data may follow written agreements.',
      ],
    },
    {
      id: 'backups',
      title: '36. Backups',
      body: [
        'Aerealith AI may maintain backups for reliability, disaster recovery, security, and business continuity.',
        'Backups may contain copies of personal information for a limited period.',
        'When data is deleted from active systems, it may remain in backups until backup rotation, expiration, or deletion processes remove it.',
        'Backups should be protected with appropriate security controls.',
        'Backup data should not be used for ordinary business purposes except restoration, security, legal compliance, or disaster recovery.',
      ],
    },
    {
      id: 'security',
      title: '37. Security',
      body: [
        'Aerealith AI should use reasonable technical and organizational safeguards to protect personal information.',
        'Safeguards may include:',
        'No system can be guaranteed to be completely secure.',
        'Security commitments are described further in the Security Policy.',
      ],
      bullets: [
        'Encryption in transit',
        'Encryption at rest',
        'Access controls',
        'Role-based permissions',
        'Attribute-based permissions',
        'Audit logs',
        'Secret management',
        'Network segmentation',
        'Security monitoring',
        'Vulnerability management',
        'Secure development practices',
        'Incident response',
        'Backup controls',
        'Vendor review',
        'Least-privilege access',
        'Administrative controls',
        'Organization-level controls',
      ],
      links: [
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
      ],
    },
    {
      id: 'data-incidents',
      title: '38. Data Incidents',
      body: [
        'If SinLess Games LLC becomes aware of a data incident affecting Aerealith AI, it will evaluate the incident and take appropriate action.',
        'Actions may include:',
        'Incident handling is described further in the Incident Notification Policy.',
      ],
      bullets: [
        'Investigating the incident',
        'Containing the incident',
        'Preserving evidence',
        'Notifying affected users or organizations, where required',
        'Notifying regulators, where required',
        'Notifying subprocessors, where appropriate',
        'Rotating credentials, where appropriate',
        'Publishing incident updates, where appropriate',
        'Improving controls after the incident',
      ],
      links: [
        {
          label: 'Incident Notification Policy',
          href: '/Policies/incident-notification',
        },
      ],
    },
    {
      id: 'international-data-transfers',
      title: '39. International Data Transfers',
      body: [
        'Personal information may be processed and stored in the United States or other countries where SinLess Games LLC, its infrastructure providers, subprocessors, or customers operate.',
        'Data location may depend on:',
        'Where required, SinLess Games LLC should use appropriate safeguards for international transfers, such as contractual terms, data processing agreements, transfer impact assessments, or other approved mechanisms.',
        'Enterprise customers may have additional data residency or transfer terms in written agreements.',
      ],
      bullets: [
        'Deployment type',
        'Customer region',
        'Hosting configuration',
        'Subprocessor configuration',
        'Enterprise agreement',
        'Self-hosted deployment settings',
        'Air-gapped deployment settings',
        'Legal requirements',
        'Product architecture',
      ],
    },
    {
      id: 'california-privacy-rights',
      title: '40. California Privacy Rights',
      body: [
        'California residents may have rights under California privacy law.',
        'Depending on applicability, these rights may include:',
        'SinLess Games LLC does not sell user data.',
        'Aerealith AI does not use private user content, prompts, files, memory, organization data, or workspace data for third-party targeted advertising.',
        'Where applicable law requires opt-out controls for sharing, targeted advertising, or sensitive personal information, Aerealith AI should provide those controls.',
        'Requests may be sent to privacy@sinlessgames.com.',
      ],
      bullets: [
        'Right to know what personal information is collected',
        'Right to know the categories of sources',
        'Right to know the purposes of collection, use, disclosure, sale, or sharing',
        'Right to know categories of third parties to whom information is disclosed',
        'Right to access personal information',
        'Right to delete personal information',
        'Right to correct inaccurate personal information',
        'Right to opt out of sale',
        'Right to opt out of sharing',
        'Right to limit use of sensitive personal information',
        'Right not to be discriminated against for exercising privacy rights',
      ],
      contacts: [
        {
          label: 'Privacy',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
      ],
    },
    {
      id: 'california-notice-at-collection',
      title: '41. California Notice at Collection',
      body: [
        'The categories of personal information Aerealith AI may collect are described in this policy.',
        'The purposes for collection and use are described in How We Use Personal Information, Business Logic Use, and Approved Research Use.',
        'The categories of third parties or service providers with whom information may be shared are described in How We Share Personal Information and Service Providers and Subprocessors.',
        'Retention is described in Data Retention.',
      ],
    },
    {
      id: 'global-privacy-control-and-opt-out-signals',
      title: '42. Global Privacy Control and Opt-Out Signals',
      body: [
        'Aerealith AI may recognize legally required browser-based opt-out signals, such as Global Privacy Control, where applicable.',
        'Where required by law, a valid opt-out signal may be treated as a request to opt out of sale, sharing, targeted advertising, or similar processing.',
        'Availability and handling of opt-out signals may depend on:',
      ],
      bullets: [
        'User location',
        'Applicable law',
        'Browser support',
        'Technical implementation',
        'Service configuration',
        'Organization settings',
        'Deployment type',
      ],
    },
    {
      id: 'european-and-international-privacy-rights',
      title: '43. European and International Privacy Rights',
      body: [
        'Depending on location and applicable law, users may have rights to:',
        'Requests may be sent to privacy@sinlessgames.com.',
        'Before publishing this policy, SinLess Games LLC should confirm whether it needs an EU or UK representative, data protection officer, or additional regional privacy notices.',
      ],
      bullets: [
        'Access personal data',
        'Correct personal data',
        'Delete personal data',
        'Restrict processing',
        'Object to processing',
        'Data portability',
        'Withdraw consent',
        'Lodge a complaint with a data protection authority',
        'Receive information about processing purposes',
        'Receive information about recipients of personal data',
        'Receive information about retention',
        'Receive information about international transfers',
      ],
      contacts: [
        {
          label: 'Privacy',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
      ],
    },
    {
      id: 'data-processing-agreements',
      title: '44. Data Processing Agreements',
      body: [
        'Organization and enterprise customers may require a Data Processing Agreement.',
        'A Data Processing Agreement may address:',
        'If a Data Processing Agreement conflicts with this policy, the signed agreement controls only to the extent of the conflict.',
      ],
      bullets: [
        'Controller and processor roles',
        'Processing instructions',
        'Confidentiality',
        'Security measures',
        'Subprocessors',
        'International transfers',
        'Assistance with user rights',
        'Breach notification',
        'Deletion or return of data',
        'Audits',
        'Compliance documentation',
        'Enterprise-specific restrictions',
      ],
    },
    {
      id: 'business-transfers',
      title: '45. Business Transfers',
      body: [
        'If SinLess Games LLC is involved in a merger, acquisition, financing, reorganization, bankruptcy, sale of assets, or similar transaction, personal information may be transferred as part of that transaction.',
        'In such cases, SinLess Games LLC should take reasonable steps to ensure that personal information remains protected according to this policy or that users receive appropriate notice where required.',
      ],
    },
    {
      id: 'legal-requests-and-required-disclosures',
      title: '46. Legal Requests and Required Disclosures',
      body: [
        'SinLess Games LLC may disclose personal information when required by law, subpoena, court order, warrant, legal process, regulatory request, or emergency request.',
        'Where legally permitted and practical, SinLess Games LLC may attempt to notify affected users or organizations before disclosing data.',
        'SinLess Games LLC may challenge requests that are overbroad, unclear, unlawful, or inappropriate.',
      ],
    },
    {
      id: 'self-hosted-hybrid-and-air-gapped-deployments',
      title: '47. Self-Hosted, Hybrid, and Air-Gapped Deployments',
      body: [
        'For self-hosted, hybrid, private, or air-gapped deployments, the deploying organization may control much of the data environment.',
        'The organization may be responsible for:',
        'SinLess Games LLC may process limited data related to licensing, support, updates, marketplace access, billing, telemetry, or security only where enabled, contracted, or technically required.',
        'Air-gapped deployments should be designed to operate without public SaaS dependencies where practical.',
      ],
      bullets: [
        'Hosting',
        'Storage',
        'Backups',
        'Logs',
        'Access controls',
        'Secret management',
        'Data retention',
        'Data deletion',
        'Data exports',
        'Model selection',
        'Plugin approval',
        'Marketplace controls',
        'Security monitoring',
        'Compliance controls',
        'Incident response',
        'User administration',
      ],
    },
    {
      id: 'developer-and-marketplace-privacy',
      title: '48. Developer and Marketplace Privacy',
      body: [
        'Developers and marketplace publishers must protect user data.',
        'Developers and marketplace publishers may not:',
        'Marketplace and developer privacy rules may be further described in the Marketplace Policy and Developer and API Policy.',
      ],
      bullets: [
        'Collect data without clear disclosure',
        'Request unnecessary permissions',
        'Sell user data',
        'Exfiltrate user data',
        'Use hidden tracking',
        'Retain data longer than disclosed or permitted',
        'Misrepresent privacy behavior',
        'Share data with unauthorized third parties',
        'Bypass Aerealith AI permission controls',
        'Bypass organization controls',
        'Use user data outside approved marketplace functionality',
        'Use user data for unrelated products or services',
      ],
      links: [
        {
          label: 'Marketplace Policy',
          href: '/Policies/marketplace',
        },
        {
          label: 'Developer and API Policy',
          href: '/Policies/developer',
        },
      ],
    },
    {
      id: 'user-responsibilities',
      title: '49. User Responsibilities',
      body: ['Users are responsible for:'],
      bullets: [
        'Providing only data they are authorized to provide',
        'Avoiding unnecessary sensitive data',
        'Avoiding secrets in ordinary prompts, files, or memory',
        'Reviewing outputs before use',
        'Managing account access',
        'Managing integration permissions',
        'Managing shared links',
        'Managing public content',
        'Exporting important data before cancellation',
        'Following organization policies',
        'Following applicable laws and contracts',
        'Reporting suspected data misuse, security issues, or privacy concerns',
      ],
    },
    {
      id: 'organization-responsibilities',
      title: '50. Organization Responsibilities',
      body: ['Organizations are responsible for:'],
      bullets: [
        'Managing users',
        'Managing roles and permissions',
        'Configuring retention',
        'Configuring memory',
        'Configuring integrations',
        'Configuring marketplace access',
        'Configuring automations',
        'Reviewing audit logs',
        'Handling internal data requests',
        'Enforcing internal policies',
        'Managing sensitive and regulated data',
        'Managing legal holds',
        'Managing exports and deletion',
        'Ensuring lawful processing of organization data',
        'Training users on appropriate use',
      ],
    },
    {
      id: 'how-to-make-a-privacy-request',
      title: '51. How to Make a Privacy Request',
      body: [
        'Privacy requests may be sent to privacy@sinlessgames.com.',
        'Include:',
        'SinLess Games LLC may need to verify your identity or authority before fulfilling a request.',
        'For organization data, users may need to contact their organization administrator.',
      ],
      bullets: [
        'Account email',
        'Organization name, if applicable',
        'Workspace name, if applicable',
        'Type of request',
        'Data involved',
        'Any relevant details needed to locate the data',
      ],
      contacts: [
        {
          label: 'Privacy',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
      ],
    },
    {
      id: 'appeals',
      title: '52. Appeals',
      body: [
        'If your privacy request is denied and applicable law gives you a right to appeal, you may appeal by contacting privacy@sinlessgames.com.',
        'Include:',
        'Submitting an appeal does not guarantee reversal.',
      ],
      bullets: [
        'Original request date',
        'Original request details',
        'Reason you believe the decision should be reconsidered',
        'Any supporting information',
      ],
      contacts: [
        {
          label: 'Privacy',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
      ],
    },
    {
      id: 'contact',
      title: '53. Contact',
      body: [
        'Privacy questions, data requests, deletion requests, export requests, correction requests, or privacy concerns may be sent to privacy@sinlessgames.com.',
        'Security concerns may be sent to security@sinlessgames.com.',
        'Legal questions may be sent to legal@sinlessgames.com.',
        'General support may be sent to support@sinlessgames.com.',
        'Before publishing this policy, confirm these email aliases exist and are monitored.',
      ],
      contacts: [
        {
          label: 'Privacy',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
        {
          label: 'Security',
          email: 'security@sinlessgames.com',
          href: 'mailto:security@sinlessgames.com',
        },
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
        {
          label: 'Support',
          email: 'support@sinlessgames.com',
          href: 'mailto:support@sinlessgames.com',
        },
      ],
    },
    {
      id: 'publication-checklist',
      title: '54. Publication Checklist',
      body: ['Before publishing this policy, complete the following:'],
      bullets: [
        'Confirm official company name: SinLess Games LLC',
        'Confirm official product name: Aerealith AI',
        'Confirm physical business address, if required',
        'Confirm monitored privacy contact email',
        'Confirm monitored security contact email',
        'Confirm subprocessors',
        'Confirm payment processors',
        'Confirm analytics providers',
        'Confirm AI providers',
        'Confirm hosting providers',
        'Confirm cookie and tracking tools',
        'Confirm whether targeted advertising is used',
        'Confirm whether Global Privacy Control is supported',
        'Confirm whether EU, UK, or international privacy representatives are required',
        'Confirm whether a Data Protection Officer is required',
        'Confirm data retention schedule',
        'Confirm deletion workflow',
        'Confirm export workflow',
        'Confirm organization admin access behavior',
        'Confirm model training defaults',
        'Confirm research-use defaults',
        'Confirm enterprise opt-out controls',
        'Confirm self-hosted and air-gapped telemetry behavior',
        'Confirm children/minors policy',
        'Confirm regulated-data limitations',
        'Have qualified legal counsel review this policy',
      ],
    },
    {
      id: 'changes-to-this-policy',
      title: '55. Changes to This Policy',
      body: [
        'We may update this policy from time to time.',
        'When we make material changes, we will update the last_updated date and may provide notice through the service, documentation, account settings, email, release notes, legal notices page, cookie banner, or another reasonable method.',
        'Continued use of Aerealith AI after changes become effective means you accept the updated policy.',
      ],
    },
    {
      id: 'legal-review-notice',
      title: '56. Legal Review Notice',
      body: [
        'This policy is a draft template and should be reviewed by qualified legal counsel before publication.',
        'Privacy, data protection, AI processing, research use, model training, children’s privacy, consumer protection, retention, deletion, export, sensitive-data processing, international-transfer, cookie, and state privacy requirements may vary by jurisdiction.',
      ],
    },
  ],
} satisfies PolicyDocument;

export default privacyPolicy;
