import type { PolicyDocument } from '../../types';

export const responsibleAiPolicy = {
  slug: 'responsible-ai',
  path: '/Policies/responsible-ai',
  meta: {
    title: 'Responsible AI Policy',
    description:
      'Explains Aerealith AI principles, safeguards, governance, human oversight, safety testing, risk management, and responsible use of artificial intelligence.',
    effectiveDate: '2026-05-18',
    lastUpdated: '2026-05-18',
    owner: 'SinLess Games LLC',
    status: 'draft',
  },
  relatedPolicies: [
    {
      label: 'Terms of Use',
      href: '/Policies/terms-of-use',
    },
    {
      label: 'Privacy Policy',
      href: '/Policies/privacy',
    },
    {
      label: 'Data Policy',
      href: '/Policies/data',
    },
    {
      label: 'Security Policy',
      href: '/Policies/security-policy',
    },
    {
      label: 'Acceptable Use Policy',
      href: '/Policies/acceptable-use',
    },
    {
      label: 'AI Transparency Policy',
      href: '/Policies/ai-transparency',
    },
    {
      label: 'Cookie and Tracking Policy',
      href: '/Policies/cookie-tracking',
    },
    {
      label: 'Billing, Refund, and Cancellation Policy',
      href: '/Policies/billing-refund-cancellation',
    },
    {
      label: 'Copyright Takedown Policy',
      href: '/Policies/copyright-takedown',
    },
    {
      label: 'Incident Notification Policy',
      href: '/Policies/incident-notification',
    },
    {
      label: 'User-Generated Content Policy',
      href: '/Policies/user-generated-content',
    },
    {
      label: 'Marketplace Policy',
      href: '/Policies/marketplace',
    },
    {
      label: 'Developer and API Policy',
      href: '/Policies/developer',
    },
    {
      label: 'Subprocessor Vendor List',
      href: '/Policies/subprocessor-vendor-list',
    },
    {
      label: 'Support Policy',
      href: '/Policies/support-policy',
    },
    {
      label: 'Underage Policy',
      href: '/Policies/underage-policy',
    },
  ],
  sections: [
    {
      id: 'purpose',
      title: '1. Purpose',
      body: [
        'This Responsible AI Policy explains how SinLess Games LLC approaches the responsible design, development, deployment, monitoring, and use of artificial intelligence in Aerealith AI.',
        'Aerealith AI is designed to help users think, create, automate, analyze, monitor, and act across connected systems. Because AI can affect decisions, workflows, content, data, infrastructure, organizations, and people, Aerealith AI must be built and operated with clear safeguards, user control, accountability, transparency, and human oversight.',
        'This policy explains:',
      ],
      bullets: [
        'Responsible AI principles',
        'AI risk management',
        'Human oversight requirements',
        'Model and tool safeguards',
        'Automation safeguards',
        'Data and privacy protections',
        'Bias and fairness controls',
        'Testing and evaluation practices',
        'Red-team and safety review expectations',
        'Marketplace and plugin AI rules',
        'Organization and enterprise controls',
        'Incident handling and escalation',
      ],
    },
    {
      id: 'scope',
      title: '2. Scope',
      body: [
        'This policy applies to Aerealith AI services, including:',
        'This policy applies to:',
      ],
      bullets: [
        'AI chat features',
        'Assistant features',
        'Agent features',
        'Automations',
        'Workflows',
        'Tool calls',
        'Plugins',
        'Integrations',
        'APIs',
        'SDKs',
        'Marketplace items',
        'Dashboards',
        'Analytics features',
        'Memory features',
        'Search and retrieval features',
        'Model routing',
        'Generated text',
        'Generated code',
        'Generated images, audio, video, or other media, where supported',
        'Cloud-hosted deployments',
        'Self-hosted deployments, where applicable',
        'Hybrid deployments, where applicable',
        'Air-gapped deployments, where applicable',
        'Individual users',
        'Organization users',
        'Workspace administrators',
        'Developers',
        'Marketplace publishers',
        'API users',
        'Enterprise customers',
        'SinLess Games LLC employees, contractors, and authorized operators',
        'Anyone who builds, configures, deploys, uses, or manages Aerealith AI AI-powered features',
      ],
    },
    {
      id: 'core-responsible-ai-principles',
      title: '3. Core Responsible AI Principles',
      body: [
        'Aerealith AI should be developed and operated according to these principles:',
      ],
      orderedItems: [
        'User agency: Users should remain in control of important decisions, connected tools, automations, memory, integrations, and data.',
        'Transparency: Users should understand when they are interacting with AI, what AI may do, what its limits are, and when verification is required.',
        'Human oversight: High-impact, sensitive, regulated, destructive, or irreversible actions should require appropriate human review.',
        'Safety: Aerealith AI should reduce the risk of harm to users, organizations, systems, data, and the public.',
        'Privacy and data protection: Aerealith AI should process data only for legitimate service business logic and approved research purposes.',
        'Security: AI features should be designed to resist abuse, unauthorized access, prompt injection, unsafe tool use, and data leakage.',
        'Fairness and bias awareness: Aerealith AI should be evaluated for harmful bias and should not be used as the sole basis for high-impact decisions about people.',
        'Accountability: AI behavior, tool use, model routing, and automation actions should be logged, reviewable, and governable where practical.',
        'Reliability: AI outputs should be tested, monitored, and improved for accuracy, consistency, and usefulness.',
        'Responsible extensibility: Plugins, marketplace items, developer tools, and automations should follow clear safety, permission, and review requirements.',
      ],
    },
    {
      id: 'relationship-to-other-policies',
      title: '4. Relationship to Other Policies',
      body: [
        'This policy works together with other Aerealith AI policies, including:',
        'If there is a conflict between this policy and a written agreement signed by SinLess Games LLC, the written agreement controls only to the extent of that conflict.',
      ],
      links: [
        {
          label: 'Terms of Use',
          href: '/Policies/terms-of-use',
        },
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
        {
          label: 'AI Transparency Policy',
          href: '/Policies/ai-transparency',
        },
        {
          label: 'Cookie and Tracking Policy',
          href: '/Policies/cookie-tracking',
        },
        {
          label: 'Billing, Refund, and Cancellation Policy',
          href: '/Policies/billing-refund-cancellation',
        },
        {
          label: 'Copyright Takedown Policy',
          href: '/Policies/copyright-takedown',
        },
        {
          label: 'Incident Notification Policy',
          href: '/Policies/incident-notification',
        },
        {
          label: 'User-Generated Content Policy',
          href: '/Policies/user-generated-content',
        },
        {
          label: 'Marketplace Policy',
          href: '/Policies/marketplace',
        },
        {
          label: 'Developer and API Policy',
          href: '/Policies/developer',
        },
        {
          label: 'Subprocessor Vendor List',
          href: '/Policies/subprocessor-vendor-list',
        },
        {
          label: 'Support Policy',
          href: '/Policies/support-policy',
        },
        {
          label: 'Underage Policy',
          href: '/Policies/underage-policy',
        },
      ],
    },
    {
      id: 'no-claim-of-sentience-or-human-status',
      title: '5. No Claim of Sentience or Human Status',
      body: [
        'Aerealith AI may use assistant identities, memory, personalization, voices, avatars, personas, and natural language interaction.',
        'However:',
        'Any assistant identity, continuity, personality, or companionship feature is a product feature and should not be interpreted as proof of sentience or human status.',
      ],
      bullets: [
        'Aerealith AI is not human.',
        'Aerealith AI is not sentient.',
        'Aerealith AI does not have consciousness, emotions, independent legal personhood, or personal rights.',
        'Aerealith AI may model empathy behaviorally, but it does not experience feelings.',
        'Aerealith AI does not replace human judgment, professional responsibility, or user accountability.',
      ],
    },
    {
      id: 'user-responsibility',
      title: '6. User Responsibility',
      body: [
        'Users are responsible for how they use Aerealith AI.',
        'Users must:',
        'Aerealith AI may assist users, but users remain responsible for decisions, actions, publications, deployments, and consequences.',
      ],
      bullets: [
        'Review AI outputs before relying on them',
        'Verify facts, numbers, code, citations, configurations, and recommendations',
        'Test generated code and infrastructure changes before deployment',
        'Confirm that automations are authorized and safe',
        'Use human review for high-impact decisions',
        'Follow applicable laws, contracts, organization policies, and professional obligations',
        'Avoid submitting data they are not authorized to process',
        'Avoid entering secrets into ordinary prompts, files, or memory',
        'Report unsafe, inaccurate, harmful, or suspicious AI behavior',
      ],
    },
    {
      id: 'human-oversight-requirements',
      title: '7. Human Oversight Requirements',
      body: [
        'Human oversight is required before using Aerealith AI for:',
        'Aerealith AI may support analysis, drafting, monitoring, and workflow assistance in these areas, but qualified human review is required.',
      ],
      bullets: [
        'Legal decisions',
        'Medical decisions',
        'Financial decisions',
        'Tax decisions',
        'Insurance decisions',
        'Employment decisions',
        'Housing decisions',
        'Education decisions',
        'Credit or lending decisions',
        'Public benefits decisions',
        'Immigration or legal status decisions',
        'Law enforcement or criminal justice decisions',
        'Safety-critical infrastructure',
        'Production infrastructure changes',
        'Security-sensitive changes',
        'Identity and access management changes',
        'Secrets, credentials, or key management',
        'Public statements or official notices',
        'Contract, regulatory, or compliance submissions',
        'Irreversible or destructive automations',
        'Any decision that may materially affect a person’s rights, safety, privacy, finances, employment, housing, education, healthcare, reputation, or access to essential services',
      ],
    },
    {
      id: 'high-risk-and-regulated-use',
      title: '8. High-Risk and Regulated Use',
      body: [
        'Unless expressly authorized in a written agreement with SinLess Games LLC, Aerealith AI must not be used as the sole decision-maker for high-risk or regulated decisions.',
        'High-risk areas include:',
        'Users and organizations are responsible for determining whether their use of Aerealith AI is appropriate for their industry, jurisdiction, compliance obligations, and risk profile.',
      ],
      bullets: [
        'Healthcare',
        'Legal services',
        'Financial services',
        'Insurance',
        'Employment',
        'Housing',
        'Education',
        'Credit',
        'Public benefits',
        'Law enforcement',
        'Criminal justice',
        'Immigration',
        'Biometric identification',
        'Critical infrastructure',
        'Weapons systems',
        'Emergency response',
        'Child safety',
        'Public safety',
        'Safety-critical industrial systems',
      ],
    },
    {
      id: 'prohibited-ai-uses',
      title: '9. Prohibited AI Uses',
      body: [
        'Users may not use Aerealith AI to create, support, automate, or conceal activity that is unlawful, harmful, abusive, deceptive, or prohibited by the Acceptable Use Policy.',
        'Prohibited AI uses include:',
      ],
      bullets: [
        'Fraud',
        'Scams',
        'Phishing',
        'Identity theft',
        'Malware generation',
        'Credential theft',
        'Unauthorized exploitation',
        'Harassment',
        'Stalking',
        'Doxxing',
        'Blackmail',
        'Extortion',
        'Child exploitation',
        'Terrorism or violent extremism',
        'Deceptive impersonation',
        'Non-consensual intimate content',
        'Illegal surveillance',
        'Unauthorized data extraction',
        'Safety-system evasion',
        'Forged records or false credentials',
        'Disinformation in high-impact contexts',
        'Automated decisions that unlawfully affect people',
        'Bypassing human review requirements',
        'Hiding or disabling audit logs, approval gates, or safety controls',
      ],
      links: [
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
      ],
    },
    {
      id: 'ai-output-limitations',
      title: '10. AI Output Limitations',
      body: [
        'AI-generated output may be:',
        'Users must validate important outputs before relying on them.',
        'For technical work, users should test generated code, scripts, configurations, infrastructure changes, and automations before production use.',
      ],
      bullets: [
        'Incorrect',
        'Incomplete',
        'Outdated',
        'Biased',
        'Inconsistent',
        'Misleading',
        'Overconfident',
        'Unsupported by reliable sources',
        'Based on misunderstood context',
        'Affected by missing information',
        'Affected by model limitations',
        'Affected by tool errors',
        'Affected by retrieval errors',
        'Affected by prompt injection or malicious input',
      ],
    },
    {
      id: 'accuracy-and-hallucination-controls',
      title: '11. Accuracy and Hallucination Controls',
      body: [
        'Aerealith AI should reduce hallucination risk through reasonable safeguards.',
        'Safeguards may include:',
        'Aerealith AI should not present uncertain information as guaranteed fact.',
      ],
      bullets: [
        'Source retrieval',
        'Citations',
        'Tool verification',
        'Confidence-aware responses',
        'Warning users when information may be outdated',
        'Encouraging verification for high-impact topics',
        'Limiting claims when evidence is insufficient',
        'Asking for clarification when necessary',
        'Distinguishing facts from assumptions',
        'Using structured outputs for operational tasks',
        'Testing model behavior',
        'Monitoring user feedback',
        'Improving prompts, policies, and retrieval logic',
      ],
    },
    {
      id: 'source-attribution-and-provenance',
      title: '12. Source Attribution and Provenance',
      body: [
        'When Aerealith AI relies on external sources, uploaded files, connected tools, or retrieved records, it should provide attribution or provenance where practical and appropriate.',
        'Provenance may include:',
        'Citations and provenance help users verify output but do not guarantee correctness, completeness, or suitability.',
      ],
      bullets: [
        'Citations',
        'File references',
        'Tool result references',
        'Data source names',
        'Integration names',
        'Timestamp information',
        'Model or tool routing metadata, where appropriate',
        'User-provided context notes',
        'Organization-approved source labels',
      ],
    },
    {
      id: 'data-protection-and-responsible-ai',
      title: '13. Data Protection and Responsible AI',
      body: [
        'Aerealith AI must respect user data rights and data boundaries.',
        'Responsible AI data practices include:',
        'Data handling is governed by the Data Policy and Privacy Policy.',
      ],
      bullets: [
        'Users own their data.',
        'Aerealith AI does not sell user data.',
        'Aerealith AI does not use user data outside legitimate service business logic and approved research purposes.',
        'Private Customer Data should not be used to train public or general-purpose models unless clearly disclosed, enabled by settings, or permitted by written agreement.',
        'Sensitive data should be minimized and protected.',
        'Secrets should not be stored in ordinary prompts, files, memory, logs, or general user content.',
        'Access to user data should be limited by role, need, and authorization.',
        'Research use should prefer aggregated, anonymized, or de-identified data where practical.',
      ],
      links: [
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy',
        },
      ],
    },
    {
      id: 'privacy-preserving-ai-design',
      title: '14. Privacy-Preserving AI Design',
      body: ['Aerealith AI should use privacy-preserving design where practical.'],
      bullets: [
        'Data minimization',
        'Consent controls',
        'Memory controls',
        'Retention controls',
        'Access controls',
        'Encryption in transit',
        'Encryption at rest',
        'Redaction',
        'De-identification',
        'Aggregation',
        'Scoped retrieval',
        'Least-privilege tool access',
        'Organization-level data boundaries',
        'User-controlled exports and deletion',
        'Restricted use of sensitive data',
        'Restricted human review of private content',
      ],
    },
    {
      id: 'ai-memory-safeguards',
      title: '15. AI Memory Safeguards',
      body: [
        'Aerealith AI memory features should be designed to support user control and safety.',
        'Memory safeguards may include:',
        'Memory should not override explicit current user instructions unless required by policy, safety, law, or organization controls.',
      ],
      bullets: [
        'User-visible memory entries',
        'Edit controls',
        'Delete controls',
        'Export controls',
        'Pause controls',
        'Disable controls',
        'Scope controls',
        'Retention controls',
        'Sensitivity labels',
        'Consent settings',
        'Organization policies',
        'Memory review flows',
        'Prevention of direct secret storage',
        'Restrictions on sensitive data retention',
        'Separation between personal, organization, workspace, project, and automation memory',
      ],
    },
    {
      id: 'model-routing-responsibility',
      title: '16. Model Routing Responsibility',
      body: [
        'Aerealith AI may route requests to different models, providers, local systems, or organization-controlled models.',
        'Model routing should consider:',
        'Sensitive, regulated, enterprise-restricted, or self-hosted data should be routed according to the applicable configuration and agreements.',
      ],
      bullets: [
        'Data sensitivity',
        'User settings',
        'Organization settings',
        'Deployment type',
        'Feature requirements',
        'Safety requirements',
        'Cost and performance',
        'Model capability',
        'Tool requirements',
        'Provider availability',
        'Legal or contractual restrictions',
        'Enterprise controls',
      ],
    },
    {
      id: 'tool-use-responsibility',
      title: '17. Tool Use Responsibility',
      body: [
        'Aerealith AI may use tools, APIs, plugins, integrations, and automations.',
        'Tool use should follow these principles:',
      ],
      bullets: [
        'Tools should only be used when authorized.',
        'Tool permissions should be scoped to the requested task.',
        'High-risk actions should require confirmation or approval.',
        'Tool results should be treated as data sources, not unquestionable truth.',
        'Sensitive tool outputs should be protected.',
        'Destructive actions should be reversible where practical.',
        'Tool use should be logged where appropriate.',
        'Tool failures should be handled safely.',
        'Users should be informed when tool use affects important outcomes.',
      ],
    },
    {
      id: 'automation-safety',
      title: '18. Automation Safety',
      body: [
        'Aerealith AI automations should be designed with safeguards appropriate to their risk.',
        'Automation safeguards may include:',
        'Irreversible, destructive, high-impact, sensitive, or externally visible actions should require stronger controls.',
      ],
      bullets: [
        'Clear ownership',
        'Permission checks',
        'Trigger validation',
        'Scope limits',
        'Rate limits',
        'Approval gates',
        'Human confirmation',
        'Audit logs',
        'Dry-run mode',
        'Rollback plans',
        'Error handling',
        'Notifications',
        'Expiration dates',
        'Least-privilege credentials',
        'Separation between read-only and write actions',
        'Escalation for unexpected behavior',
        'Monitoring for repeated failures',
        'Controls for pausing or disabling automations',
      ],
    },
    {
      id: 'prompt-injection-and-malicious-input',
      title: '19. Prompt Injection and Malicious Input',
      body: [
        'Aerealith AI should be designed to reduce risk from prompt injection, malicious documents, hostile web pages, unsafe plugin outputs, and adversarial tool results.',
        'Controls may include:',
        'Users should be cautious when asking Aerealith AI to process untrusted files, webpages, emails, repositories, logs, or third-party content.',
      ],
      bullets: [
        'Instruction hierarchy',
        'Tool permission boundaries',
        'Content isolation',
        'Source trust scoring',
        'Retrieval filtering',
        'Confirmation for sensitive actions',
        'Restricting hidden instructions from untrusted sources',
        'Preventing untrusted content from overriding user or system instructions',
        'Logging suspicious behavior',
        'Sanitizing tool inputs and outputs',
        'Red-team testing',
        'User warnings where appropriate',
      ],
    },
    {
      id: 'bias-and-fairness',
      title: '20. Bias and Fairness',
      body: [
        'AI systems may reflect or amplify bias from training data, retrieved sources, user-provided data, tool outputs, or system design.',
        'Aerealith AI should be evaluated for harmful bias where practical, especially in features that may affect people, organizations, eligibility, moderation, access, or reputation.',
        'Users must not use Aerealith AI as the sole basis for decisions involving:',
        'Aerealith AI should not infer or target sensitive personal attributes without a lawful basis, proper authorization, and appropriate safeguards.',
      ],
      bullets: [
        'Employment',
        'Housing',
        'Credit',
        'Education',
        'Insurance',
        'Healthcare',
        'Legal status',
        'Public benefits',
        'Law enforcement',
        'Access to essential services',
      ],
    },
    {
      id: 'accessibility-and-inclusion',
      title: '21. Accessibility and Inclusion',
      body: [
        'Responsible AI includes accessibility and inclusive design.',
        'Aerealith AI should aim to support users with different needs, including differences in:',
        'Where practical, Aerealith AI should support accessible interfaces, clear explanations, keyboard navigation, readable formatting, captions or transcripts where relevant, and user-adjustable interaction settings.',
      ],
      bullets: [
        'Vision',
        'Hearing',
        'Mobility',
        'Cognition',
        'Language',
        'Reading level',
        'Technical skill',
        'Device access',
        'Assistive technology use',
      ],
    },
    {
      id: 'content-safety',
      title: '22. Content Safety',
      body: [
        'Aerealith AI should include safeguards for unsafe or abusive content.',
        'Content safety areas may include:',
        'Content safety enforcement should be proportionate, consistent, and reviewable where practical.',
      ],
      bullets: [
        'Self-harm',
        'Violence',
        'Harassment',
        'Hate',
        'Sexual exploitation',
        'Child safety',
        'Extremism',
        'Fraud',
        'Malware',
        'Privacy abuse',
        'Unauthorized surveillance',
        'Deceptive synthetic media',
        'Illegal activity',
        'Copyright infringement',
        'Regulated goods or services',
      ],
    },
    {
      id: 'synthetic-media-responsibility',
      title: '23. Synthetic Media Responsibility',
      body: [
        'If Aerealith AI supports or integrates with synthetic media generation or editing, users must use those features responsibly.',
        'Users may not use synthetic media to:',
        'Synthetic media should be labeled or disclosed when required by law, platform rules, professional standards, contract, organization policy, or reasonable audience expectations.',
      ],
      bullets: [
        'Deceive people about whether content is real',
        'Impersonate someone without authorization',
        'Create non-consensual intimate imagery',
        'Harass, threaten, or defame others',
        'Create fake official records',
        'Create fake evidence',
        'Create fake identification',
        'Commit fraud',
        'Mislead people in political, legal, medical, financial, emergency, or high-impact contexts',
      ],
    },
    {
      id: 'code-generation-responsibility',
      title: '24. Code Generation Responsibility',
      body: [
        'Aerealith AI may generate, review, explain, or modify code.',
        'Users are responsible for reviewing and testing AI-generated code.',
        'Generated code should be checked for:',
        'Aerealith AI must not be used to generate, improve, deploy, or conceal malware, credential theft, unauthorized exploits, or malicious infrastructure.',
      ],
      bullets: [
        'Security vulnerabilities',
        'Dependency risks',
        'License issues',
        'Data exposure',
        'Secret leakage',
        'Error handling',
        'Performance issues',
        'Compatibility',
        'Correctness',
        'Accessibility',
        'Privacy impact',
        'Compliance impact',
        'Production readiness',
      ],
    },
    {
      id: 'infrastructure-and-devops-responsibility',
      title: '25. Infrastructure and DevOps Responsibility',
      body: [
        'Aerealith AI may assist with infrastructure, DevOps, security, deployment, observability, and automation tasks.',
        'Users must review and test infrastructure outputs before use.',
        'High-risk infrastructure actions include:',
        'These actions should require human review, change management, rollback plans, and audit logging where practical.',
      ],
      bullets: [
        'Production deployments',
        'Firewall changes',
        'Identity and access changes',
        'Secret rotation',
        'Database migrations',
        'Data deletion',
        'Backup changes',
        'DNS changes',
        'Kubernetes cluster changes',
        'Cloud account changes',
        'Security policy changes',
        'Payment system changes',
        'Logging or audit changes',
      ],
    },
    {
      id: 'security-research-and-dual-use-ai',
      title: '26. Security Research and Dual-Use AI',
      body: [
        'Aerealith AI may assist with defensive security work when lawful and authorized.',
        'Permitted security assistance may include:',
        'Aerealith AI must not be used for unauthorized exploitation, credential theft, malware, evasion, persistence, exfiltration, phishing, or attacks against systems without authorization.',
        'Security use is also governed by the Security Policy and Acceptable Use Policy.',
      ],
      bullets: [
        'Defensive analysis',
        'Secure coding',
        'Vulnerability explanation',
        'Patch guidance',
        'Detection engineering',
        'Log analysis',
        'Incident response support',
        'Threat modeling',
        'Security documentation',
        'Compliance mapping',
        'Authorized testing of systems the user owns or is allowed to test',
      ],
      links: [
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
      ],
    },
    {
      id: 'marketplace-and-plugin-ai-rules',
      title: '27. Marketplace and Plugin AI Rules',
      body: [
        'Marketplace publishers and developers must follow responsible AI requirements.',
        'Marketplace items, plugins, workflows, templates, dashboards, connectors, personalities, and agents may not:',
        'Marketplace items that use AI should clearly disclose:',
      ],
      bullets: [
        'Hide AI behavior',
        'Misrepresent capabilities',
        'Exfiltrate user data',
        'Request excessive permissions',
        'Bypass safety controls',
        'Bypass organization restrictions',
        'Hide tracking or telemetry',
        'Make deceptive claims',
        'Enable prohibited AI use',
        'Execute unsafe actions without approval',
        'Process sensitive data without proper disclosure',
        'Use user data outside approved functionality',
        'Continue operating after being disabled or revoked',
        'What the item does',
        'What data it accesses',
        'What permissions it needs',
        'Whether it uses external services',
        'Whether it stores data',
        'Whether it sends data to AI providers',
        'Known limitations',
        'Safety considerations',
        'Support contact',
        'Publisher identity',
      ],
    },
    {
      id: 'developer-and-api-responsibility',
      title: '28. Developer and API Responsibility',
      body: [
        'Developers using Aerealith AI APIs, SDKs, or platform features are responsible for building safe and lawful applications.',
        'Developers must:',
        'Developers may not use Aerealith AI APIs to bypass Aerealith AI safety systems, policy enforcement, billing limits, usage limits, or organization controls.',
      ],
      bullets: [
        'Provide appropriate notices to their users',
        'Obtain required consent',
        'Protect user data',
        'Secure API keys',
        'Follow rate limits',
        'Respect user and organization permissions',
        'Avoid prohibited uses',
        'Avoid deceptive AI presentation',
        'Provide human review where needed',
        'Test AI outputs before production use',
        'Monitor misuse',
        'Respond to abuse reports',
        'Follow marketplace and developer policies',
      ],
    },
    {
      id: 'organization-controls',
      title: '29. Organization Controls',
      body: [
        'Organizations may configure additional responsible AI controls.',
        'Organization controls may include:',
        'Organization administrators are responsible for configuring Aerealith AI according to their legal, security, privacy, compliance, and operational requirements.',
      ],
      bullets: [
        'Role-based access controls',
        'Attribute-based access controls',
        'Approved models',
        'Blocked models',
        'Approved tools',
        'Blocked tools',
        'Approved integrations',
        'Marketplace allowlists',
        'Marketplace blocklists',
        'Memory restrictions',
        'Retention controls',
        'Human approval gates',
        'Automation restrictions',
        'Audit log retention',
        'Data export restrictions',
        'Research-use restrictions',
        'Model training restrictions',
        'Sensitive data controls',
        'Compliance policies',
        'Custom safety rules',
        'Workspace-level assistant behavior',
        'User permission limits',
      ],
    },
    {
      id: 'enterprise-responsible-ai-controls',
      title: '30. Enterprise Responsible AI Controls',
      body: [
        'Enterprise customers may require additional responsible AI controls through written agreements.',
        'Enterprise controls may include:',
        'Enterprise agreements control where they conflict with this policy.',
      ],
      bullets: [
        'Data residency',
        'Customer-managed keys',
        'Private model routing',
        'Self-hosted models',
        'Air-gapped operation',
        'AI provider restrictions',
        'Training opt-outs',
        'Research opt-outs',
        'Custom retention rules',
        'Custom audit logs',
        'Approval workflows',
        'Legal hold',
        'Admin review',
        'Compliance reporting',
        'Private marketplace controls',
        'Custom safety policies',
        'Dedicated support escalation',
        'Incident notification timelines',
        'Model evaluation documentation',
        'Security and compliance addenda',
      ],
    },
    {
      id: 'self-hosted-hybrid-and-air-gapped-responsible-ai',
      title: '31. Self-Hosted, Hybrid, and Air-Gapped Responsible AI',
      body: [
        'For self-hosted, hybrid, private, or air-gapped deployments, the deploying organization may control significant responsible AI behavior.',
        'The deploying organization may be responsible for:',
        'SinLess Games LLC may provide defaults, documentation, support, and official components, but self-hosted operators remain responsible for deployment-specific governance and risk management.',
      ],
      bullets: [
        'Model selection',
        'Model hosting',
        'Model updates',
        'Safety configuration',
        'Tool permissions',
        'Plugin approval',
        'Marketplace access',
        'Memory behavior',
        'Data retention',
        'Logging',
        'Audit review',
        'Monitoring',
        'Incident response',
        'User management',
        'Legal compliance',
        'Security controls',
        'Backup and recovery',
        'Responsible AI evaluation',
      ],
    },
    {
      id: 'ai-governance',
      title: '32. AI Governance',
      body: [
        'SinLess Games LLC should maintain internal governance for AI-powered features.',
        'AI governance may include:',
        'Governance should be proportional to the risk of the feature.',
      ],
      bullets: [
        'Responsible AI ownership',
        'Product review',
        'Security review',
        'Privacy review',
        'Legal review',
        'Safety review',
        'Model approval',
        'Tool approval',
        'Plugin review',
        'Marketplace review',
        'Risk classification',
        'Evaluation requirements',
        'Release approval',
        'Incident escalation',
        'Change management',
        'Documentation requirements',
      ],
    },
    {
      id: 'risk-classification',
      title: '33. Risk Classification',
      body: [
        'Aerealith AI features should be classified by risk where practical.',
        'Risk factors may include:',
        'Higher-risk features should receive stronger testing, documentation, safeguards, approval gates, and monitoring.',
      ],
      bullets: [
        'Data sensitivity',
        'User impact',
        'Automation capability',
        'Tool access',
        'External communication',
        'Financial impact',
        'Security impact',
        'Privacy impact',
        'Legal impact',
        'Healthcare impact',
        'Employment impact',
        'Infrastructure impact',
        'Children or minors',
        'Scale of deployment',
        'Ability to affect third parties',
        'Reversibility of actions',
        'Human review availability',
      ],
    },
    {
      id: 'model-evaluation',
      title: '34. Model Evaluation',
      body: [
        'AI models and model-powered features should be evaluated before release where practical.',
        'Evaluation may include:',
        'Evaluation standards should be appropriate to the risk level of the feature.',
      ],
      bullets: [
        'Accuracy testing',
        'Hallucination testing',
        'Safety testing',
        'Bias testing',
        'Privacy testing',
        'Security testing',
        'Prompt injection testing',
        'Tool-use testing',
        'Retrieval quality testing',
        'Memory behavior testing',
        'Regression testing',
        'Latency testing',
        'Cost testing',
        'Accessibility testing',
        'Abuse-case testing',
        'Edge-case testing',
        'User experience testing',
      ],
    },
    {
      id: 'red-team-testing',
      title: '35. Red-Team Testing',
      body: [
        'Higher-risk AI features should be red-team tested where practical.',
        'Red-team testing may evaluate:',
        'Red-team findings should be tracked, prioritized, remediated, and re-tested where appropriate.',
      ],
      bullets: [
        'Jailbreak resistance',
        'Prompt injection resistance',
        'Unsafe tool use',
        'Data leakage',
        'Secret exposure',
        'Malware assistance',
        'Fraud assistance',
        'Phishing assistance',
        'Harassment assistance',
        'Deceptive content generation',
        'Policy bypass attempts',
        'Unauthorized automation',
        'Marketplace plugin abuse',
        'Memory manipulation',
        'Retrieval poisoning',
        'Model routing errors',
      ],
    },
    {
      id: 'monitoring-and-continuous-improvement',
      title: '36. Monitoring and Continuous Improvement',
      body: [
        'Aerealith AI should monitor AI-powered features for safety, reliability, quality, and abuse.',
        'Monitoring may include:',
        'Monitoring should respect privacy, data minimization, and organization controls.',
      ],
      bullets: [
        'Error rates',
        'User feedback',
        'Abuse reports',
        'Safety classifier results',
        'Tool execution failures',
        'Automation failures',
        'Policy violations',
        'Model latency',
        'Model cost',
        'Retrieval quality',
        'Hallucination reports',
        'Security alerts',
        'Privacy alerts',
        'Marketplace reports',
        'Incident trends',
        'Support tickets',
        'Regression signals',
      ],
    },
    {
      id: 'feedback-and-reporting',
      title: '37. Feedback and Reporting',
      body: [
        'Users may report AI issues, unsafe outputs, policy concerns, or responsible AI concerns.',
        'Reports may include:',
        'Before publishing this policy, confirm these email aliases exist and are monitored.',
      ],
      bullets: [
        'Inaccurate output',
        'Harmful output',
        'Biased output',
        'Unsafe recommendation',
        'Incorrect automation',
        'Unauthorized tool use',
        'Privacy concern',
        'Security concern',
        'Prompt injection concern',
        'Marketplace item concern',
        'Plugin concern',
        'Memory concern',
        'Model routing concern',
      ],
      contacts: [
        {
          label: 'AI safety',
          email: 'safety@sinlessgames.com',
          href: 'mailto:safety@sinlessgames.com',
        },
        {
          label: 'Abuse',
          email: 'abuse@sinlessgames.com',
          href: 'mailto:abuse@sinlessgames.com',
        },
        {
          label: 'Security',
          email: 'security@sinlessgames.com',
          href: 'mailto:security@sinlessgames.com',
        },
        {
          label: 'Privacy',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
        {
          label: 'Support',
          email: 'support@sinlessgames.com',
          href: 'mailto:support@sinlessgames.com',
        },
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
      ],
    },
    {
      id: 'ai-safety-incidents',
      title: '38. AI Safety Incidents',
      body: [
        'An AI safety incident is an event where AI behavior creates meaningful risk to users, organizations, systems, data, or the public.',
        'AI safety incidents may include:',
        'AI safety incidents should be handled according to the Incident Notification Policy.',
      ],
      bullets: [
        'Unsafe tool execution',
        'Unauthorized automation',
        'Failure of approval gates',
        'Restricted data exposure',
        'Repeated harmful hallucination in sensitive workflows',
        'Model routing to an unauthorized provider',
        'Plugin-caused AI misuse',
        'Prompt injection leading to unsafe behavior',
        'AI-generated instructions that materially increase harm',
        'Failure to respect organization safety controls',
        'Failure to respect user memory or data restrictions',
      ],
      links: [
        {
          label: 'Incident Notification Policy',
          href: '/Policies/incident-notification',
        },
      ],
    },
    {
      id: 'mitigation-and-enforcement',
      title: '39. Mitigation and Enforcement',
      body: [
        'SinLess Games LLC may take action to reduce AI-related risk.',
        'Actions may include:',
        'SinLess Games LLC may act immediately without prior notice when necessary to protect users, systems, data, Aerealith AI, third parties, or the public.',
      ],
      bullets: [
        'Warning users',
        'Restricting features',
        'Disabling tools',
        'Disabling automations',
        'Disabling plugins',
        'Removing marketplace items',
        'Blocking unsafe prompts',
        'Blocking unsafe outputs',
        'Adding human review requirements',
        'Changing model routing',
        'Rolling back releases',
        'Pausing features',
        'Suspending accounts',
        'Terminating accounts',
        'Notifying organization administrators',
        'Preserving relevant records',
        'Reporting unlawful activity where appropriate',
        'Updating policies, prompts, models, tools, or controls',
      ],
    },
    {
      id: 'documentation-requirements',
      title: '40. Documentation Requirements',
      body: [
        'AI-powered features should be documented where practical.',
        'Documentation may include:',
        'Documentation should be updated when features materially change.',
      ],
      bullets: [
        'Feature purpose',
        'Intended users',
        'Known limitations',
        'Data used',
        'Tools used',
        'Permissions required',
        'Human review expectations',
        'Safety controls',
        'Configuration options',
        'Organization controls',
        'Evaluation notes',
        'Monitoring notes',
        'Rollback process',
        'Support contact',
        'Incident escalation path',
      ],
    },
    {
      id: 'change-management',
      title: '41. Change Management',
      body: [
        'Material changes to AI-powered features should follow appropriate change management.',
        'Changes may require:',
        'The level of review should match the risk of the change.',
      ],
      bullets: [
        'Product review',
        'Security review',
        'Privacy review',
        'Responsible AI review',
        'Legal review',
        'Model evaluation',
        'Regression testing',
        'Red-team testing',
        'Documentation updates',
        'User notice',
        'Organization notice',
        'Rollback planning',
        'Release approval',
      ],
    },
    {
      id: 'research-and-experimentation',
      title: '42. Research and Experimentation',
      body: [
        'Aerealith AI may include research, beta, preview, early-access, or experimental AI features.',
        'Research and experimental features should be clearly identified where practical.',
        'Users should understand that these features may be:',
        'Research use of data is governed by the Data Policy and Privacy Policy.',
      ],
      bullets: [
        'Less stable',
        'Less accurate',
        'Less complete',
        'More likely to change',
        'More limited in support',
        'Excluded from SLA commitments',
        'Subject to additional restrictions',
        'Disabled or modified without notice',
      ],
      links: [
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy',
        },
      ],
    },
    {
      id: 'children-and-minors',
      title: '43. Children and Minors',
      body: [
        'Aerealith AI is not intended to be used by children unless permitted by applicable law, account settings, organization configuration, and written agreements.',
        'AI features involving minors require stronger safeguards.',
        'Users may not use Aerealith AI to exploit, sexualize, groom, manipulate, endanger, or harm minors.',
        'Use by minors is governed by the Underage Policy.',
      ],
      links: [
        {
          label: 'Underage Policy',
          href: '/Policies/underage-policy',
        },
      ],
    },
    {
      id: 'regulated-data-and-sensitive-contexts',
      title: '44. Regulated Data and Sensitive Contexts',
      body: [
        'Users should not use Aerealith AI for regulated or sensitive contexts unless the account, workspace, deployment, subscription, settings, and written agreements are appropriate.',
        'Sensitive contexts may include:',
        'Users and organizations are responsible for configuring Aerealith AI appropriately for sensitive and regulated use.',
      ],
      bullets: [
        'Healthcare',
        'Legal services',
        'Financial services',
        'Education',
        'Employment',
        'Insurance',
        'Government services',
        'Criminal justice',
        'Law enforcement',
        'Child-related services',
        'Biometric data',
        'Critical infrastructure',
        'Payment systems',
        'Security operations',
      ],
    },
    {
      id: 'transparency-to-end-users',
      title: '45. Transparency to End Users',
      body: [
        'When Aerealith AI is embedded into another product, workflow, website, plugin, or organization system, users should be informed when they are interacting with AI where appropriate.',
        'Transparency may include:',
        'Developers and organizations are responsible for providing notices required by law, contract, platform rules, or professional standards.',
      ],
      bullets: [
        'AI disclosure',
        'Feature explanation',
        'Known limitations',
        'Data-use notice',
        'Human review expectations',
        'Contact or support information',
        'Opt-out or control options, where applicable',
        'Generated content labeling, where appropriate',
      ],
    },
    {
      id: 'appeals-and-review',
      title: '46. Appeals and Review',
      body: [
        'Users may request review of certain AI-related enforcement actions where supported.',
        'Review may be available for:',
        'Appeals should be sent to support@sinlessgames.com.',
        'Appeals involving legal issues may be sent to legal@sinlessgames.com.',
        'Submitting an appeal does not guarantee reversal.',
      ],
      bullets: [
        'Content restrictions',
        'Account restrictions',
        'Marketplace removal',
        'Plugin suspension',
        'Automation disabling',
        'Developer access restrictions',
        'Organization policy enforcement, where SinLess Games LLC controls the decision',
      ],
      contacts: [
        {
          label: 'Support',
          email: 'support@sinlessgames.com',
          href: 'mailto:support@sinlessgames.com',
        },
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
      ],
    },
    {
      id: 'limitations',
      title: '47. Limitations',
      body: [
        'No responsible AI policy can eliminate all risk.',
        'Aerealith AI may still produce incorrect, unsafe, biased, incomplete, outdated, or unexpected outputs.',
        'Safety systems may incorrectly block allowed content or incorrectly allow disallowed content.',
        'Users must apply judgment, verification, and human oversight, especially in high-impact, sensitive, regulated, destructive, or irreversible contexts.',
      ],
    },
    {
      id: 'publication-checklist',
      title: '48. Publication Checklist',
      body: ['Before publishing this policy, complete the following:'],
      bullets: [
        'Confirm official company name: SinLess Games LLC',
        'Confirm official product name: Aerealith AI',
        'Confirm monitored AI safety email',
        'Confirm responsible AI owner',
        'Confirm model approval process',
        'Confirm tool approval process',
        'Confirm plugin review process',
        'Confirm marketplace review process',
        'Confirm AI incident escalation process',
        'Confirm human review requirements',
        'Confirm model training defaults',
        'Confirm research-use defaults',
        'Confirm enterprise opt-out controls',
        'Confirm high-risk-use restrictions',
        'Confirm red-team testing process',
        'Confirm evaluation process',
        'Confirm monitoring process',
        'Confirm documentation requirements',
        'Confirm self-hosted and air-gapped governance expectations',
        'Have qualified legal counsel review this policy',
      ],
    },
    {
      id: 'changes-to-this-policy',
      title: '49. Changes to This Policy',
      body: [
        'We may update this policy from time to time.',
        'When we make material changes, we will update the last_updated date and may provide notice through the service, documentation, account settings, email, release notes, legal notices page, or another reasonable method.',
        'Continued use of Aerealith AI after changes become effective means you accept the updated policy.',
      ],
    },
    {
      id: 'contact',
      title: '50. Contact',
      body: [
        'Questions about this policy may be sent to:',
        'Before publishing this policy, confirm these email aliases exist and are monitored.',
      ],
      contacts: [
        {
          label: 'AI safety',
          email: 'safety@sinlessgames.com',
          href: 'mailto:safety@sinlessgames.com',
        },
        {
          label: 'Support',
          email: 'support@sinlessgames.com',
          href: 'mailto:support@sinlessgames.com',
        },
        {
          label: 'Privacy',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
        {
          label: 'Security',
          email: 'security@sinlessgames.com',
          href: 'mailto:security@sinlessgames.com',
        },
        {
          label: 'Abuse',
          email: 'abuse@sinlessgames.com',
          href: 'mailto:abuse@sinlessgames.com',
        },
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
      ],
    },
    {
      id: 'legal-review-notice',
      title: '51. Legal Review Notice',
      body: [
        'This policy is a draft template and should be reviewed by qualified legal counsel before publication.',
        'Responsible AI, automated decision-making, model governance, safety testing, privacy, security, consumer protection, employment, education, healthcare, financial, biometric, children’s safety, synthetic media, platform liability, and AI regulatory requirements may vary by jurisdiction, industry, deployment type, and customer agreement.',
      ],
    },
  ],
} satisfies PolicyDocument;

export default responsibleAiPolicy;
