import type { PolicyDocument } from '../../types';

export const subprocessorVendorListPolicy = {
  slug: 'subprocessor-vendor-list',
  path: '/Policies/subprocessor-vendor-list',
  meta: {
    title: 'Subprocessor and Vendor List',
    description:
      'Lists subprocessors, vendors, service providers, infrastructure providers, AI providers, payment processors, analytics providers, and other third parties used or planned for Aerealith AI.',
    effectiveDate: '2026-05-18',
    lastUpdated: '2026-05-18',
    owner: 'SinLess Games LLC',
    status: 'draft',
  },
  relatedPolicies: [
    {
      label: 'Privacy Policy',
      href: '/Policies/privacy',
    },
    {
      label: 'Data Policy',
      href: '/Policies/data',
    },
    {
      label: 'Security Policy',
      href: '/Policies/security-policy',
    },
    {
      label: 'Cookie and Tracking Policy',
      href: '/Policies/cookie-tracking',
    },
    {
      label: 'AI Transparency Policy',
      href: '/Policies/ai-transparency',
    },
    {
      label: 'Responsible AI Policy',
      href: '/Policies/responsible-ai',
    },
    {
      label: 'Incident Notification Policy',
      href: '/Policies/incident-notification',
    },
    {
      label: 'Payment Processor Compliance Policy',
      href: '/Policies/payment-proccessor-compliance',
    },
    {
      label: 'Terms of Use',
      href: '/Policies/terms-of-use',
    },
  ],
  sections: [
    {
      id: 'purpose',
      title: '1. Purpose',
      body: [
        'This Subprocessor and Vendor List identifies third parties that SinLess Games LLC may use to provide, secure, operate, support, monitor, bill, analyze, improve, and maintain Aerealith AI.',
        'Aerealith AI is operated by SinLess Games LLC.',
        'This list is intended to provide transparency about vendors that may process, store, transmit, access, or support data related to Aerealith AI.',
        'This document should be read together with:',
      ],
      links: [
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
        {
          label: 'Cookie and Tracking Policy',
          href: '/Policies/cookie-tracking',
        },
        {
          label: 'AI Transparency Policy',
          href: '/Policies/ai-transparency',
        },
        {
          label: 'Responsible AI Policy',
          href: '/Policies/responsible-ai',
        },
        {
          label: 'Incident Notification Policy',
          href: '/Policies/incident-notification',
        },
        {
          label: 'Payment Processor Compliance Policy',
          href: '/Policies/payment-proccessor-compliance',
        },
        {
          label: 'Terms of Use',
          href: '/Policies/terms-of-use',
        },
      ],
    },
    {
      id: 'core-commitments',
      title: '2. Core Commitments',
      body: [
        'SinLess Games LLC makes the following commitments for Aerealith AI:',
      ],
      orderedItems: [
        'Users own their data.',
        'Aerealith AI does not sell user data.',
        'Aerealith AI does not use user data outside legitimate service business logic and approved research purposes.',
        'Vendors and subprocessors should only process data for authorized Aerealith AI purposes.',
        'Subprocessors should be reviewed before use where practical.',
        'Sensitive data should receive stronger protection.',
        'Enterprise customers should receive appropriate notice of material subprocessor changes where required by contract.',
        'Self-hosted and air-gapped deployments may use different vendors or no external vendors depending on customer configuration.',
      ],
    },
    {
      id: 'scope',
      title: '3. Scope',
      body: [
        'This list applies to Aerealith AI services, including:',
        'Some vendors may apply only to specific plans, regions, features, integrations, deployment types, or customer configurations.',
      ],
      bullets: [
        'Websites',
        'Web applications',
        'Desktop applications',
        'Mobile applications',
        'Browser extensions',
        'APIs',
        'Developer tools',
        'Documentation sites',
        'Marketplace features',
        'Plugins',
        'Automations',
        'Integrations',
        'Dashboards',
        'Analytics features',
        'AI memory features',
        'Support systems',
        'Billing systems',
        'Cloud-hosted deployments',
        'Hybrid deployments, where applicable',
        'Self-hosted deployments, where applicable',
        'Air-gapped deployments, where applicable',
      ],
    },
    {
      id: 'definitions',
      title: '4. Definitions',
      body: ['For this list:'],
    },
    {
      id: 'subprocessor',
      title: '4.1 Subprocessor',
      body: [
        'A subprocessor is a third party that may process personal data, Customer Data, Account Data, Service Data, or other protected data on behalf of SinLess Games LLC to provide Aerealith AI.',
        'Examples may include hosting providers, database providers, AI model providers, payment processors, support tools, observability tools, email providers, and analytics providers.',
      ],
    },
    {
      id: 'vendor',
      title: '4.2 Vendor',
      body: [
        'A vendor is a third party that provides products or services to SinLess Games LLC.',
        'Some vendors are subprocessors. Others may not process user data directly.',
      ],
    },
    {
      id: 'service-provider',
      title: '4.3 Service Provider',
      body: [
        'A service provider is a third party that performs a business function for SinLess Games LLC or Aerealith AI.',
      ],
    },
    {
      id: 'customer-controlled-vendor',
      title: '4.4 Customer-Controlled Vendor',
      body: [
        'A customer-controlled vendor is a vendor selected, configured, connected, or operated by the user or organization.',
        'Examples include customer GitHub accounts, customer Google Drive accounts, customer Discord servers, customer cloud providers, customer identity providers, customer observability stacks, and customer self-hosted infrastructure.',
      ],
    },
    {
      id: 'vendor-categories',
      title: '5. Vendor Categories',
      body: ['Aerealith AI vendors may fall into the following categories:'],
      bullets: [
        'Hosting and edge infrastructure',
        'DNS and network security',
        'Database and storage',
        'Authentication and identity',
        'AI model providers',
        'AI infrastructure providers',
        'Email and communications',
        'Billing and payments',
        'Tax and accounting',
        'Analytics and telemetry',
        'Observability and monitoring',
        'Error reporting',
        'Feature flags and experimentation',
        'Customer support',
        'Documentation and CMS',
        'Marketplace operations',
        'Security and abuse prevention',
        'Developer tools',
        'Source control and CI/CD',
        'File storage and connected integrations',
        'Legal, compliance, and business operations',
      ],
    },
    {
      id: 'current-and-planned-vendor-list',
      title: '6. Current and Planned Vendor List',
      body: [
        'The list below includes current, planned, or expected vendors for Aerealith AI based on the intended architecture.',
        'Before publishing this document, confirm each vendor’s actual use, data access, region, contract status, and whether the vendor is active, planned, optional, or deprecated.',
      ],
      bullets: [
        'Vercel — Hosting / frontend deployment — Hosts Next.js frontend, edge functions, deployments, previews, and web application infrastructure. Data processed may include account metadata, request metadata, IP addresses, logs, frontend app data, and limited Customer Data depending on request flow. Role: Subprocessor. Status: Planned / Confirm.',
        'Cloudflare — DNS / edge / security / CDN — DNS, CDN, DDoS protection, WAF, edge routing, Workers, tunnels, caching, TLS, and security controls. Data processed may include IP addresses, request metadata, headers, logs, cached assets, security events, and limited Customer Data depending on routing. Role: Subprocessor. Status: Planned / Confirm.',
        'Supabase — Database / authentication / storage — Postgres database, pgvector, authentication support, and object storage where configured. Data processed may include Account Data, Customer Data, Service Data, memory, embeddings, files, workspace data, and organization data. Role: Subprocessor. Status: Planned / Confirm.',
        'Redis provider / managed Redis — Cache / queues / sessions — Caching, rate limits, queues, session support, short-term memory, and automation state. Data processed may include session data, cache data, queue payloads, metadata, and temporary Customer Data depending on feature. Role: Subprocessor. Status: Planned / Confirm Provider.',
        'OpenAI — AI model provider — AI inference, model responses, embeddings, analysis, generation, reasoning, and AI-powered features where enabled. Data processed may include prompts, responses, context, retrieved content, metadata, files, or file excerpts where used. Role: Subprocessor. Status: Planned / Confirm.',
        'Other AI providers — AI model provider — Optional model routing, fallback inference, specialized model use, and local or cloud model choices. Data processed may include prompts, responses, context, retrieved content, metadata, files, or file excerpts where used. Role: Subprocessor. Status: Optional / TBD.',
        'Stripe — Payments / billing — Subscription billing, checkout, invoices, payment method handling, fraud prevention, taxes, usage billing, and marketplace payments where enabled. Data processed may include Billing Data, payment metadata, transaction records, invoice data, tax data, fraud signals, and customer identifiers. Role: Subprocessor. Status: Planned / Confirm.',
        'PayPal — Payments / billing — Payment processing, subscriptions, checkout, customer payments, and refunds where enabled. Data processed may include Billing Data, payment metadata, transaction records, customer identifiers, and dispute records. Role: Subprocessor. Status: Planned / Confirm.',
        'Hypertune — Feature flags / experimentation — Feature flags, entitlements, plan gating, controlled rollout, and experimentation. Data processed may include user IDs, tenant IDs, feature flag metadata, entitlement data, plan data, and usage context. Role: Subprocessor. Status: Planned / Confirm.',
        'Google Analytics — Analytics / marketing — Website analytics, documentation usage, public marketing page measurement, and conversion analytics where enabled. Data processed may include cookie identifiers, device metadata, page views, approximate location, referral data, and usage events. Role: Subprocessor. Status: Planned / Confirm.',
        'Grafana Cloud — Observability / monitoring — Metrics, dashboards, logs, traces, profiles, frontend telemetry, and service monitoring. Data processed may include logs, metrics, traces, errors, metadata, service health data, and limited request data depending on configuration. Role: Subprocessor. Status: Planned / Confirm.',
        'Grafana Faro — Frontend observability — Browser telemetry, frontend errors, performance monitoring, and user experience monitoring. Data processed may include browser metadata, errors, page metadata, performance data, and limited user or session identifiers. Role: Subprocessor. Status: Planned / Confirm.',
        'Contentful — CMS / content management — Marketing content, documentation content, public site content, and content workflows. Data processed may include content metadata, editor account data, public content, and limited user interaction metadata where configured. Role: Subprocessor. Status: Planned / Confirm.',
        'GitHub — Source control / CI/CD / developer workflows — Source control, issue tracking, pull requests, GitHub Actions, self-hosted runner coordination, and release workflows. Data processed may include repository data, developer account data, CI/CD metadata, issue or PR data, and workflow logs. Role: Vendor / Subprocessor depending on use. Status: Planned / Confirm.',
        'Google Workspace / Gmail / Calendar / Drive APIs — User-authorized integrations — User-authorized email, calendar, contacts, Drive, Docs, Sheets, and Slides integrations. Data processed may include data authorized by user or organization, including emails, files, calendar data, contacts, and metadata. Role: Customer-Controlled Integration / Subprocessor depending on feature. Status: Optional.',
        'Discord — User-authorized integration / community — Community spaces, notifications, bots, ChatOps, automations, and support or community operations where enabled. Data processed may include Discord IDs, messages, server metadata, channel metadata, and bot interaction data. Role: Customer-Controlled Integration / Vendor. Status: Optional / Planned.',
        'Twitch — User-authorized integration — Creator and streamer integrations, automation triggers, chat, or stream-related workflows where enabled. Data processed may include Twitch account IDs, stream metadata, chat metadata, and automation data. Role: Customer-Controlled Integration / Vendor. Status: Optional / Planned.',
        'Cloudflare R2 — Object storage — Storage for backups, files, logs, analytics exports, observability archives, or customer assets where configured. Data processed may include files, backups, logs, object metadata, and Customer Data depending on storage use. Role: Subprocessor. Status: Optional / Planned.',
        'Email service provider — Email delivery — Transactional email, account notices, billing notices, incident notices, security notices, and support communications. Data processed may include email address, name, message metadata, email content, and delivery events. Role: Subprocessor. Status: TBD.',
        'Customer support provider — Support / helpdesk — Support tickets, customer communications, troubleshooting, and support history. Data processed may include contact details, support messages, screenshots, logs provided by user, and account metadata. Role: Subprocessor. Status: TBD.',
        'Status page provider — Incident communication — Public or customer status page, incident updates, maintenance notices, and subscriber alerts. Data processed may include subscriber email, incident communication data, and service status data. Role: Subprocessor. Status: TBD.',
        'Tax calculation provider — Tax / billing — Sales tax, VAT, GST, digital tax calculation, tax reporting, and tax exemption handling. Data processed may include billing address, tax IDs, invoice records, and transaction metadata. Role: Subprocessor. Status: TBD.',
        'Accounting provider — Accounting / finance — Bookkeeping, revenue tracking, invoices, financial reporting, and tax preparation support. Data processed may include billing records, customer billing metadata, invoice records, and payment records. Role: Vendor / Subprocessor depending on use. Status: TBD.',
        'Legal and compliance providers — Legal / compliance — Legal review, compliance support, data processing agreements, privacy requests, and contract management. Data processed may include contract data, legal notices, customer contact data, and incident records where needed. Role: Vendor / Subprocessor depending on use. Status: TBD.',
        'Security scanning providers — Security / vulnerability management — Dependency scanning, code scanning, container scanning, secret scanning, and vulnerability review. Data processed may include source code, dependency metadata, security findings, and CI/CD metadata. Role: Vendor / Subprocessor depending on use. Status: TBD.',
        'Error monitoring provider — Error reporting — Application error tracking, exceptions, and performance diagnostics. Data processed may include error logs, stack traces, request metadata, device metadata, and limited user identifiers. Role: Subprocessor. Status: TBD.',
        'Object storage provider — File storage / backups — File uploads, generated artifacts, exports, backups, marketplace assets, and support attachments. Data processed may include files, exports, backups, metadata, and Customer Data depending on use. Role: Subprocessor. Status: TBD.',
        'Identity provider integrations — Authentication / SSO — OAuth, SAML, OIDC, SSO, and enterprise identity or directory sync where enabled. Data processed may include login identifiers, email addresses, names, group membership, and role metadata. Role: Customer-Controlled Integration / Subprocessor depending on configuration. Status: Optional.',
        'Customer cloud providers — Self-hosted / hybrid / air-gapped — Customer-operated infrastructure for private deployments. Data processed is controlled by customer deployment. Role: Customer-Controlled Vendor. Status: Optional.',
        'Customer observability systems — Self-hosted / enterprise monitoring — Customer-managed logs, metrics, traces, dashboards, SIEM, and alerting. Data processed may include logs, metrics, traces, audit records, and service telemetry. Role: Customer-Controlled Vendor. Status: Optional.',
        'Customer secret managers — Secrets / key management — Vault, KMS, cloud secret managers, customer-managed encryption, and secret references. Data processed may include secrets, keys, tokens, credentials, and secret metadata. Role: Customer-Controlled Vendor. Status: Optional.',
      ],
    },
    {
      id: 'active-subprocessors',
      title: '7. Active Subprocessors',
      body: [
        'Before publication, move confirmed active subprocessors into this section.',
      ],
      bullets: [
        'Subprocessor: TBD — Service Provided: TBD — Data Processed: TBD — Location / Region: TBD — Security Documentation: TBD — Status: TBD.',
      ],
    },
    {
      id: 'planned-subprocessors',
      title: '8. Planned Subprocessors',
      body: [
        'The following vendors are expected or planned but must be confirmed before production launch.',
      ],
      bullets: [
        'Vercel — Expected use: Frontend hosting and deployment — Data risk level: Medium — Required review: Security, privacy, DPA.',
        'Cloudflare — Expected use: DNS, CDN, edge security, Workers — Data risk level: Medium — Required review: Security, privacy, DPA.',
        'Supabase — Expected use: Postgres, pgvector, auth, storage — Data risk level: High — Required review: Security, privacy, DPA, data residency.',
        'Redis provider — Expected use: Cache, queues, sessions — Data risk level: Medium / High depending on data — Required review: Security, privacy, DPA.',
        'OpenAI — Expected use: AI model processing — Data risk level: High — Required review: Security, privacy, DPA, model data-use review.',
        'Stripe — Expected use: Billing and payments — Data risk level: High — Required review: Payment, privacy, DPA, processor terms.',
        'PayPal — Expected use: Billing and payments — Data risk level: High — Required review: Payment, privacy, processor terms.',
        'Hypertune — Expected use: Feature flags and entitlements — Data risk level: Medium — Required review: Security, privacy, DPA.',
        'Google Analytics — Expected use: Analytics — Data risk level: Medium — Required review: Cookie, privacy, consent review.',
        'Grafana Cloud — Expected use: Observability — Data risk level: Medium / High depending on log content — Required review: Security, privacy, DPA.',
        'Contentful — Expected use: CMS — Data risk level: Low / Medium — Required review: Security, privacy, DPA.',
      ],
    },
    {
      id: 'optional-and-customer-controlled-integrations',
      title: '9. Optional and Customer-Controlled Integrations',
      body: [
        'Users and organizations may connect Aerealith AI to third-party services.',
        'These integrations may process user-authorized data based on granted permissions.',
        'Examples include:',
        'Customer-controlled integrations are enabled by the user or organization.',
        'Users and organizations are responsible for:',
      ],
      bullets: [
        'Google Drive',
        'Gmail',
        'Google Calendar',
        'Google Contacts',
        'GitHub',
        'Discord',
        'Twitch',
        'Slack',
        'Microsoft 365',
        'Notion',
        'Jira',
        'Linear',
        'Trello',
        'Asana',
        'Cloudflare',
        'Vercel',
        'Supabase',
        'AWS',
        'Azure',
        'Google Cloud',
        'Kubernetes clusters',
        'Proxmox environments',
        'Grafana',
        'Prometheus',
        'Loki',
        'Tempo',
        'Vault',
        'Other customer-selected systems',
        'Reviewing permissions',
        'Granting only necessary access',
        'Disconnecting unused integrations',
        'Securing third-party accounts',
        'Reviewing third-party terms',
        'Reviewing third-party privacy policies',
        'Managing data flow into and out of Aerealith AI',
        'Ensuring lawful use of connected systems',
      ],
    },
    {
      id: 'self-hosted-hybrid-and-air-gapped-deployments',
      title: '10. Self-Hosted, Hybrid, and Air-Gapped Deployments',
      body: [
        'Self-hosted, hybrid, private, and air-gapped deployments may use a different vendor model.',
        'In these deployments, the customer may control:',
        'Air-gapped deployments should be designed to operate without public SaaS dependencies where practical.',
        'SinLess Games LLC may still process limited data related to:',
      ],
      bullets: [
        'Hosting',
        'Database',
        'Cache',
        'Object storage',
        'Search',
        'Vector database',
        'AI models',
        'Authentication',
        'Secrets',
        'Logs',
        'Metrics',
        'Traces',
        'Backups',
        'Marketplace access',
        'Plugin review',
        'Integrations',
        'Email',
        'Billing connection, if applicable',
        'Licensing',
        'Support',
        'Updates',
        'Security advisories',
        'Marketplace access',
        'Billing',
        'Contract management',
        'Optional telemetry, if enabled',
        'Professional services, if purchased',
      ],
    },
    {
      id: 'data-categories-processed-by-vendors',
      title: '11. Data Categories Processed by Vendors',
      body: [
        'Depending on the vendor and feature, subprocessors may process one or more of the following data categories:',
        'Not every vendor processes every data category.',
      ],
      bullets: [
        'Account Data',
        'Customer Data',
        'Personal information',
        'Organization data',
        'Workspace data',
        'User prompts',
        'AI responses',
        'Uploaded files',
        'Connected integration data',
        'Memory data',
        'Embeddings',
        'Search indexes',
        'Analytics data',
        'Usage metadata',
        'Billing data',
        'Payment metadata',
        'Support data',
        'Error logs',
        'Security logs',
        'Audit logs',
        'Device metadata',
        'IP addresses',
        'Cookie identifiers',
        'Authentication metadata',
        'API metadata',
        'Marketplace data',
        'Developer data',
        'Automation data',
        'Tool execution data',
        'Plugin execution data',
        'Incident records',
        'Legal request records',
      ],
    },
    {
      id: 'vendor-review',
      title: '12. Vendor Review',
      body: [
        'SinLess Games LLC should review vendors and subprocessors before production use where practical.',
        'Vendor review may include:',
        'Higher-risk vendors should receive stronger review.',
      ],
      bullets: [
        'Security review',
        'Privacy review',
        'Data processing agreement review',
        'Subprocessor terms review',
        'Data residency review',
        'Incident notification review',
        'Access control review',
        'Encryption review',
        'Retention review',
        'Compliance documentation review',
        'Payment processor rules review',
        'AI data-use review',
        'Marketplace risk review',
        'Business continuity review',
      ],
    },
    {
      id: 'vendor-security-expectations',
      title: '13. Vendor Security Expectations',
      body: [
        'SinLess Games LLC should use vendors that provide reasonable security safeguards appropriate to the data processed.',
        'Vendor safeguards may include:',
      ],
      bullets: [
        'Encryption in transit',
        'Encryption at rest',
        'Access controls',
        'Audit logs',
        'Vulnerability management',
        'Incident response',
        'Data retention controls',
        'Backup controls',
        'Personnel access restrictions',
        'Subprocessor controls',
        'Security documentation',
        'Compliance documentation',
        'Business continuity controls',
      ],
    },
    {
      id: 'vendor-privacy-expectations',
      title: '14. Vendor Privacy Expectations',
      body: [
        'Vendors and subprocessors should process data only for authorized purposes.',
        'Privacy expectations may include:',
      ],
      bullets: [
        'Processing only on documented instructions',
        'No sale of user data',
        'No unrelated use of Customer Data',
        'Appropriate confidentiality commitments',
        'Appropriate deletion or return of data',
        'Appropriate support for privacy requests',
        'Appropriate subprocessor disclosure',
        'Appropriate international transfer mechanisms',
        'Appropriate incident notification obligations',
      ],
    },
    {
      id: 'ai-provider-expectations',
      title: '15. AI Provider Expectations',
      body: [
        'AI providers may process prompts, responses, files, retrieved context, memory snippets, metadata, or tool results when needed to provide AI features.',
        'AI provider expectations may include:',
        'AI provider use is also governed by the AI Transparency Policy, Responsible AI Policy, Privacy Policy, and Data Policy.',
      ],
      bullets: [
        'Clear data-use terms',
        'No training on private Customer Data unless enabled, disclosed, or contractually permitted',
        'Appropriate retention controls',
        'Appropriate security controls',
        'Appropriate privacy controls',
        'Enterprise opt-out support where available',
        'Support for sensitive-data restrictions where applicable',
        'Clear incident notification obligations',
        'Compatibility with organization model-routing rules',
      ],
      links: [
        {
          label: 'AI Transparency Policy',
          href: '/Policies/ai-transparency',
        },
        {
          label: 'Responsible AI Policy',
          href: '/Policies/responsible-ai',
        },
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
      ],
    },
    {
      id: 'payment-processor-expectations',
      title: '16. Payment Processor Expectations',
      body: [
        'Payment processors may process billing, payment, invoice, tax, dispute, refund, and fraud-prevention data.',
        'Payment processor expectations may include:',
        'Payment processor use is also governed by the Billing, Refund, and Cancellation Policy and Payment Processor Compliance Policy.',
      ],
      bullets: [
        'Secure checkout',
        'Payment tokenization',
        'Fraud prevention',
        'Chargeback handling',
        'Tax support',
        'Subscription management',
        'Compliance with processor rules',
        'Compliance with card network rules',
        'Appropriate privacy and security terms',
        'Appropriate incident notification',
        'Appropriate data retention controls',
      ],
      links: [
        {
          label: 'Billing, Refund, and Cancellation Policy',
          href: '/Policies/billing-refund-cancellation',
        },
        {
          label: 'Payment Processor Compliance Policy',
          href: '/Policies/payment-proccessor-compliance',
        },
      ],
    },
    {
      id: 'analytics-and-tracking-vendors',
      title: '17. Analytics and Tracking Vendors',
      body: [
        'Analytics and tracking vendors may process usage metadata, device metadata, page views, events, referral data, approximate location, cookie identifiers, and other analytics data.',
        'Analytics and tracking use should follow the Cookie and Tracking Policy.',
        'Where required, optional analytics and advertising cookies should only be used after consent.',
        'Aerealith AI should not use private user prompts, files, memory, organization data, or workspace data for third-party targeted advertising.',
      ],
      links: [
        {
          label: 'Cookie and Tracking Policy',
          href: '/Policies/cookie-tracking',
        },
      ],
    },
    {
      id: 'observability-vendors',
      title: '18. Observability Vendors',
      body: [
        'Observability vendors may process logs, metrics, traces, profiles, error events, and service telemetry.',
        'SinLess Games LLC should configure observability systems to avoid unnecessary sensitive data collection where practical.',
        'Observability data should avoid:',
      ],
      bullets: [
        'Passwords',
        'API keys',
        'Private keys',
        'Access tokens',
        'Full payment card numbers',
        'Sensitive personal data unless necessary and protected',
        'Private Customer Data unless required for debugging, support, or incident response',
      ],
    },
    {
      id: 'support-vendors',
      title: '19. Support Vendors',
      body: [
        'Support vendors may process support tickets, user messages, screenshots, logs, troubleshooting notes, account metadata, and support history.',
        'Users should not send secrets, private keys, passwords, full payment card numbers, or unnecessary sensitive data through support channels.',
        'Support access to Customer Data should be limited to what is reasonably needed to resolve the issue.',
      ],
    },
    {
      id: 'marketplace-and-plugin-vendors',
      title: '20. Marketplace and Plugin Vendors',
      body: [
        'Marketplace publishers may process data if users or organizations install their marketplace items.',
        'Marketplace items may include:',
        'Marketplace publishers must disclose:',
        'Marketplace publishers may not sell user data, exfiltrate user data, hide tracking, request excessive permissions, or use data outside approved marketplace functionality.',
      ],
      bullets: [
        'Plugins',
        'Connectors',
        'Workflows',
        'Dashboards',
        'Templates',
        'Personalities',
        'Prompt packs',
        'Automation packages',
        'Developer tools',
        'Data accessed',
        'Permissions requested',
        'Network access',
        'Storage behavior',
        'AI provider use',
        'Third-party services',
        'Telemetry behavior',
        'Retention behavior',
        'Support contact',
        'Publisher identity',
      ],
    },
    {
      id: 'subprocessor-changes',
      title: '21. Subprocessor Changes',
      body: [
        'SinLess Games LLC may add, remove, or replace subprocessors as Aerealith AI evolves.',
        'Subprocessor changes may occur due to:',
        'When required by law or contract, SinLess Games LLC will provide notice of material subprocessor changes.',
      ],
      bullets: [
        'New features',
        'Improved security',
        'Improved reliability',
        'Cost optimization',
        'Product changes',
        'Vendor availability',
        'Vendor risk',
        'Legal requirements',
        'Compliance requirements',
        'Enterprise requirements',
        'Regional requirements',
        'Service deprecation',
        'Incident response',
      ],
    },
    {
      id: 'enterprise-subprocessor-notices',
      title: '22. Enterprise Subprocessor Notices',
      body: [
        'Enterprise customers may receive additional subprocessor notice rights under a written agreement.',
        'Enterprise agreements may include:',
        'If an enterprise agreement conflicts with this list, the signed enterprise agreement controls only for that enterprise customer and only to the extent of the conflict.',
      ],
      bullets: [
        'Advance notice of new subprocessors',
        'Objection periods',
        'Data processing agreements',
        'Regional restrictions',
        'Data residency commitments',
        'Subprocessor audit information',
        'Security documentation',
        'Custom vendor restrictions',
        'AI provider restrictions',
        'Self-hosted deployment terms',
        'Air-gapped deployment terms',
      ],
    },
    {
      id: 'objections-to-subprocessors',
      title: '23. Objections to Subprocessors',
      body: [
        'Where required by contract, enterprise customers may object to a new subprocessor.',
        'Objections should be sent to privacy@sinlessgames.com.',
        'The objection should include:',
        'SinLess Games LLC will review valid objections according to the applicable agreement.',
      ],
      bullets: [
        'Customer name',
        'Organization name',
        'Contact information',
        'Subprocessor at issue',
        'Reason for objection',
        'Data protection concern',
        'Security concern',
        'Legal or contractual basis for objection',
      ],
      contacts: [
        {
          label: 'Privacy',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
      ],
    },
    {
      id: 'international-data-transfers',
      title: '24. International Data Transfers',
      body: [
        'Some vendors and subprocessors may process data outside the user’s country, state, province, or region.',
        'International transfer mechanisms may include:',
        'Enterprise customers may have additional data residency or transfer terms in written agreements.',
      ],
      bullets: [
        'Data processing agreements',
        'Standard contractual clauses',
        'Transfer impact assessments',
        'Regional hosting choices',
        'Customer-managed deployment',
        'Self-hosting',
        'Air-gapped deployment',
        'Other legally approved transfer mechanisms',
      ],
    },
    {
      id: 'vendor-incident-notification',
      title: '25. Vendor Incident Notification',
      body: [
        'If a vendor or subprocessor incident materially affects Aerealith AI users, SinLess Games LLC will evaluate the incident and provide notification where required by law, contract, or policy.',
        'Vendor incident handling may include:',
        'Incident handling is described further in the Incident Notification Policy.',
      ],
      bullets: [
        'Reviewing vendor incident reports',
        'Assessing affected data',
        'Assessing affected customers',
        'Coordinating mitigation',
        'Notifying affected users or organizations where required',
        'Updating the status page where appropriate',
        'Updating policies or vendors where needed',
      ],
      links: [
        {
          label: 'Incident Notification Policy',
          href: '/Policies/incident-notification',
        },
      ],
    },
    {
      id: 'vendor-removal',
      title: '26. Vendor Removal',
      body: [
        'SinLess Games LLC may remove, replace, suspend, or restrict a vendor when appropriate.',
        'Reasons may include:',
        'Vendor removal may require migration, data export, data deletion, service changes, downtime, or customer notice depending on the vendor and feature.',
      ],
      bullets: [
        'Security concerns',
        'Privacy concerns',
        'Legal concerns',
        'Reliability issues',
        'Cost changes',
        'Contract changes',
        'Service deprecation',
        'Product architecture changes',
        'Subprocessor changes',
        'Enterprise requirements',
        'Customer requirements',
        'Incident response',
        'Compliance requirements',
      ],
    },
    {
      id: 'no-sale-of-user-data',
      title: '27. No Sale of User Data',
      body: [
        'SinLess Games LLC does not sell user data.',
        'Using vendors and subprocessors to provide Aerealith AI is not a sale of user data when those vendors process data only for authorized Aerealith AI purposes.',
        'Vendors and subprocessors should not use user data for unrelated purposes.',
      ],
    },
    {
      id: 'contact',
      title: '28. Contact',
      body: [
        'Questions about subprocessors, vendors, vendor changes, or data processing may be sent to:',
        'Before publishing this policy, confirm these email aliases exist and are monitored.',
      ],
      contacts: [
        {
          label: 'Privacy',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
        {
          label: 'Security',
          email: 'security@sinlessgames.com',
          href: 'mailto:security@sinlessgames.com',
        },
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
        {
          label: 'Support',
          email: 'support@sinlessgames.com',
          href: 'mailto:support@sinlessgames.com',
        },
      ],
    },
    {
      id: 'publication-checklist',
      title: '29. Publication Checklist',
      body: ['Before publishing this document, complete the following:'],
      bullets: [
        'Confirm official company name: SinLess Games LLC',
        'Confirm official product name: Aerealith AI',
        'Confirm all active vendors',
        'Confirm all active subprocessors',
        'Confirm planned vendors',
        'Confirm optional vendors',
        'Confirm customer-controlled integrations',
        'Confirm vendor categories',
        'Confirm data categories processed by each vendor',
        'Confirm vendor regions',
        'Confirm data residency options',
        'Confirm security documentation links',
        'Confirm privacy documentation links',
        'Confirm data processing agreements',
        'Confirm AI provider data-use terms',
        'Confirm payment processor terms',
        'Confirm analytics and cookie vendors',
        'Confirm support vendor',
        'Confirm email vendor',
        'Confirm status page vendor',
        'Confirm tax provider',
        'Confirm object storage provider',
        'Confirm Redis provider',
        'Confirm observability provider',
        'Confirm error monitoring provider',
        'Confirm legal and compliance vendors',
        'Confirm vendor incident notification process',
        'Confirm enterprise subprocessor notice process',
        'Confirm subprocessor objection process',
        'Confirm self-hosted vendor responsibilities',
        'Confirm air-gapped vendor responsibilities',
        'Have qualified legal counsel review this document',
      ],
    },
    {
      id: 'changes-to-this-list',
      title: '30. Changes to This List',
      body: [
        'We may update this list from time to time.',
        'When we make material changes, we will update the last_updated date and may provide notice through the service, documentation, account settings, email, legal notices page, release notes, or another reasonable method.',
        'Continued use of Aerealith AI after changes become effective means you accept the updated list, subject to any rights provided by applicable law or written agreement.',
      ],
    },
    {
      id: 'legal-review-notice',
      title: '31. Legal Review Notice',
      body: [
        'This document is a draft template and should be reviewed by qualified legal counsel before publication.',
        'Subprocessor notice, vendor disclosure, international transfer, AI provider, payment processor, data residency, privacy, security, marketplace, and enterprise-contract requirements may vary by jurisdiction, customer type, deployment model, and written agreement.',
      ],
    },
  ],
} satisfies PolicyDocument;

export default subprocessorVendorListPolicy;
