import type { PolicyDocument } from '../../types';

export const supportPolicy = {
  slug: 'support-policy',
  path: '/Policies/support-policy',
  meta: {
    title: 'Support Policy',
    description:
      'Explains Aerealith AI support channels, support scope, priority levels, response targets, service availability, escalation, enterprise support, and customer responsibilities.',
    effectiveDate: '2026-05-18',
    lastUpdated: '2026-05-18',
    owner: 'SinLess Games LLC',
    status: 'draft',
  },
  relatedPolicies: [
    {
      label: 'Terms of Use',
      href: '/Policies/terms-of-use',
    },
    {
      label: 'Privacy Policy',
      href: '/Policies/privacy',
    },
    {
      label: 'Data Policy',
      href: '/Policies/data',
    },
    {
      label: 'Security Policy',
      href: '/Policies/security-policy',
    },
    {
      label: 'Acceptable Use Policy',
      href: '/Policies/acceptable-use',
    },
    {
      label: 'AI Transparency Policy',
      href: '/Policies/ai-transparency',
    },
    {
      label: 'Responsible AI Policy',
      href: '/Policies/responsible-ai',
    },
    {
      label: 'Cookie and Tracking Policy',
      href: '/Policies/cookie-tracking',
    },
    {
      label: 'Billing, Refund, and Cancellation Policy',
      href: '/Policies/billing-refund-cancellation',
    },
    {
      label: 'Copyright Takedown Policy',
      href: '/Policies/copyright-takedown',
    },
    {
      label: 'Incident Notification Policy',
      href: '/Policies/incident-notification',
    },
    {
      label: 'Payment Processor Compliance Policy',
      href: '/Policies/payment-proccessor-compliance',
    },
    {
      label: 'Subprocessor and Vendor List',
      href: '/Policies/subprocessor-vendor-list',
    },
    {
      label: 'User-Generated Content Policy',
      href: '/Policies/user-generated-content',
    },
    {
      label: 'Marketplace Policy',
      href: '/Policies/marketplace',
    },
    {
      label: 'Developer and API Policy',
      href: '/Policies/developer',
    },
    {
      label: 'Underage Policy',
      href: '/Policies/underage-policy',
    },
  ],
  sections: [
    {
      id: 'purpose',
      title: '1. Purpose',
      body: [
        'This Support Policy explains how SinLess Games LLC provides support for Aerealith AI.',
        'Aerealith AI is designed to help users think, create, automate, analyze, monitor, and act across connected systems. Because Aerealith AI may involve accounts, subscriptions, AI outputs, memory, automations, integrations, APIs, plugins, marketplace items, dashboards, and self-hosted deployments, support expectations should be clear.',
        'This policy explains:',
      ],
      bullets: [
        'How to contact support',
        'What support covers',
        'What support does not cover',
        'Support priority levels',
        'Target response times',
        'Support availability by plan',
        'Incident escalation',
        'Enterprise support',
        'Self-hosted and air-gapped support',
        'Customer responsibilities',
      ],
    },
    {
      id: 'scope',
      title: '2. Scope',
      body: [
        'This policy applies to Aerealith AI services, including:',
        'This policy applies to:',
      ],
      bullets: [
        'Websites',
        'Web applications',
        'Desktop applications',
        'Mobile applications',
        'Browser extensions',
        'APIs',
        'Developer tools',
        'Documentation sites',
        'Marketplace features',
        'Plugins',
        'Automations',
        'Integrations',
        'Dashboards',
        'Analytics features',
        'AI memory features',
        'Billing systems',
        'Support systems',
        'Cloud-hosted deployments',
        'Self-hosted deployments, where applicable',
        'Hybrid deployments, where applicable',
        'Air-gapped deployments, where applicable',
        'Individual users',
        'Organization users',
        'Workspace administrators',
        'Developers',
        'Marketplace publishers',
        'API users',
        'Enterprise customers',
        'Billing administrators',
        'Security contacts',
        'Support contacts',
        'Anyone who requests help with Aerealith AI',
      ],
    },
    {
      id: 'relationship-to-other-policies',
      title: '3. Relationship to Other Policies',
      body: [
        'This policy works together with other Aerealith AI policies, including:',
        'If there is a conflict between this policy and a written agreement signed by SinLess Games LLC, the written agreement controls only to the extent of that conflict.',
      ],
      links: [
        {
          label: 'Terms of Use',
          href: '/Policies/terms-of-use',
        },
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
        {
          label: 'AI Transparency Policy',
          href: '/Policies/ai-transparency',
        },
        {
          label: 'Responsible AI Policy',
          href: '/Policies/responsible-ai',
        },
        {
          label: 'Cookie and Tracking Policy',
          href: '/Policies/cookie-tracking',
        },
        {
          label: 'Billing, Refund, and Cancellation Policy',
          href: '/Policies/billing-refund-cancellation',
        },
        {
          label: 'Copyright Takedown Policy',
          href: '/Policies/copyright-takedown',
        },
        {
          label: 'Incident Notification Policy',
          href: '/Policies/incident-notification',
        },
        {
          label: 'Payment Processor Compliance Policy',
          href: '/Policies/payment-proccessor-compliance',
        },
        {
          label: 'Subprocessor and Vendor List',
          href: '/Policies/subprocessor-vendor-list',
        },
        {
          label: 'User-Generated Content Policy',
          href: '/Policies/user-generated-content',
        },
        {
          label: 'Marketplace Policy',
          href: '/Policies/marketplace',
        },
        {
          label: 'Developer and API Policy',
          href: '/Policies/developer',
        },
        {
          label: 'Underage Policy',
          href: '/Policies/underage-policy',
        },
      ],
    },
    {
      id: 'support-channels',
      title: '4. Support Channels',
      body: [
        'Support may be available through one or more of the following channels:',
        'Default support contacts:',
        'Before publishing this policy, confirm these email aliases exist and are monitored.',
      ],
      bullets: [
        'Email',
        'Support portal',
        'In-app support',
        'Documentation',
        'Status page',
        'Community channels',
        'Developer issue tracker',
        'Enterprise support contact',
        'Account representative, where applicable',
        'Emergency security contact, where applicable',
      ],
      contacts: [
        {
          label: 'General support',
          email: 'support@sinlessgames.com',
          href: 'mailto:support@sinlessgames.com',
        },
        {
          label: 'Billing support',
          email: 'billing@sinlessgames.com',
          href: 'mailto:billing@sinlessgames.com',
        },
        {
          label: 'Security reports',
          email: 'security@sinlessgames.com',
          href: 'mailto:security@sinlessgames.com',
        },
        {
          label: 'Privacy requests',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
        {
          label: 'Abuse reports',
          email: 'abuse@sinlessgames.com',
          href: 'mailto:abuse@sinlessgames.com',
        },
        {
          label: 'AI safety concerns',
          email: 'safety@sinlessgames.com',
          href: 'mailto:safety@sinlessgames.com',
        },
        {
          label: 'Legal notices',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
        {
          label: 'Copyright notices',
          email: 'copyright@sinlessgames.com',
          href: 'mailto:copyright@sinlessgames.com',
        },
      ],
    },
    {
      id: 'support-is-not-emergency-service',
      title: '5. Support Is Not Emergency Service',
      body: [
        'Aerealith AI support is not an emergency service.',
        'Do not use Aerealith AI support for emergencies involving:',
        'For emergencies, contact the appropriate emergency services or local authorities.',
      ],
      bullets: [
        'Immediate danger',
        'Medical emergencies',
        'Threats of harm',
        'Active crimes',
        'Fire, flood, or disaster response',
        'Urgent law enforcement needs',
        'Critical public safety issues',
      ],
    },
    {
      id: 'support-scope',
      title: '6. Support Scope',
      body: ['Aerealith AI support may assist with:'],
      bullets: [
        'Account access issues',
        'Login issues',
        'Subscription and billing questions',
        'Refund and cancellation questions',
        'Workspace and organization settings',
        'Basic product usage questions',
        'Documentation guidance',
        'Feature behavior questions',
        'Known product issues',
        'Bug reports',
        'Service availability questions',
        'API access issues',
        'Developer tool questions',
        'Marketplace installation issues',
        'Plugin behavior questions',
        'Integration connection issues',
        'Automation troubleshooting',
        'Dashboard and analytics issues',
        'Memory setting questions',
        'Privacy request routing',
        'Security report intake',
        'Abuse report intake',
        'Enterprise support escalation, where applicable',
      ],
    },
    {
      id: 'out-of-scope-support',
      title: '7. Out-of-Scope Support',
      body: [
        'Unless expressly included in a written agreement, Aerealith AI support does not include:',
        'SinLess Games LLC may offer some out-of-scope services separately as paid professional services.',
      ],
      bullets: [
        'Custom software development',
        'Custom plugin development',
        'Custom integration development',
        'Custom infrastructure engineering',
        'Managed service operation',
        'Production incident management for customer systems',
        'Debugging unrelated third-party services',
        'Legal advice',
        'Medical advice',
        'Financial advice',
        'Tax advice',
        'Compliance certification',
        'Penetration testing of customer environments',
        'Forensic investigation of customer systems',
        'Recovery of lost customer credentials outside supported account recovery flows',
        'Repairing user devices',
        'Managing customer cloud accounts',
        'Managing customer Kubernetes clusters',
        'Managing customer databases',
        'Managing customer networks',
        'Writing or maintaining customer codebases',
        'Training customer staff unless purchased separately',
        'Professional services unless purchased separately',
      ],
    },
    {
      id: 'support-availability-by-plan',
      title: '8. Support Availability by Plan',
      body: [
        'Support availability may depend on subscription plan, deployment type, organization agreement, and support add-ons.',
        'Example support model:',
        'Before publishing, confirm actual support availability, support channels, and support targets for each plan.',
      ],
      bullets: [
        'Free — Limited support availability — Documentation, community, and limited email where available — No guaranteed response time.',
        'Basic — Standard support availability — Documentation, email, and in-app support where available — Best-effort support.',
        'Basic+ — Standard support availability — Documentation, email, and in-app support where available — Best-effort support.',
        'Premium — Priority support availability — Email, in-app support, and documentation — Higher priority than Basic.',
        'Premium+ — Priority support availability — Email, in-app support, and documentation — Higher priority than Premium.',
        'Pro — Business support availability — Email, in-app support, developer support, and documentation — Higher priority for business-impacting issues.',
        'Pro+ — Business Plus support availability — Email, in-app support, developer support, and escalation where available — Higher priority for business-impacting issues.',
        'Enterprise — Custom support availability — Named contacts, escalation, and contract-defined support — Governed by order form, SLA, or written agreement.',
      ],
    },
    {
      id: 'support-hours',
      title: '9. Support Hours',
      body: [
        'Unless otherwise stated in a written agreement, standard support is provided during normal business hours.',
        'Standard business hours should be defined before publication.',
        'Example:',
        'Enterprise customers may have different support hours in a written agreement.',
      ],
      bullets: [
        'Monday through Friday',
        'Excluding company holidays',
        'Time zone: [Insert official support time zone]',
        'Hours: [Insert support hours]',
      ],
    },
    {
      id: 'priority-levels',
      title: '10. Priority Levels',
      body: [
        'Support requests may be classified by priority.',
        'Priority may be adjusted as more information becomes available.',
      ],
    },
    {
      id: 'priority-1-critical',
      title: 'Priority 1: Critical',
      body: ['A Priority 1 issue may include:'],
      bullets: [
        'Widespread service outage',
        'Critical production impact',
        'Confirmed security incident',
        'Confirmed data exposure',
        'Inability for an enterprise customer to access core services',
        'Failed authentication affecting many users',
        'Dangerous automation behavior',
        'Active exploitation of a Aerealith AI vulnerability',
        'Major billing system failure affecting many customers',
        'Severe data integrity issue',
      ],
    },
    {
      id: 'priority-2-high',
      title: 'Priority 2: High',
      body: ['A Priority 2 issue may include:'],
      bullets: [
        'Major feature unavailable',
        'Significant service degradation',
        'Important integration failure',
        'Important API failure',
        'Organization administration failure',
        'Workspace access issue affecting multiple users',
        'High-impact automation failure',
        'High-impact marketplace or plugin issue',
        'Security concern requiring investigation',
        'Billing issue blocking paid access',
      ],
    },
    {
      id: 'priority-3-medium',
      title: 'Priority 3: Medium',
      body: ['A Priority 3 issue may include:'],
      bullets: [
        'Non-critical product bug',
        'Isolated feature issue',
        'Limited integration issue',
        'Limited automation issue',
        'Dashboard or analytics issue',
        'Documentation issue that affects usage',
        'API issue with available workaround',
        'Billing question not blocking service',
        'Marketplace issue not creating immediate risk',
      ],
    },
    {
      id: 'priority-4-low',
      title: 'Priority 4: Low',
      body: ['A Priority 4 issue may include:'],
      bullets: [
        'General question',
        'Feature request',
        'Documentation suggestion',
        'Minor user interface issue',
        'Cosmetic issue',
        'Non-urgent configuration question',
        'Product feedback',
        'Enhancement request',
      ],
    },
    {
      id: 'target-response-times',
      title: '11. Target Response Times',
      body: [
        'Target response times are goals, not guarantees, unless expressly stated in a written agreement or SLA.',
        'Example target response times:',
        'Before publishing, confirm actual response targets.',
      ],
      bullets: [
        'Priority 1 — Free: Best effort — Basic / Basic+: Best effort — Premium / Premium+: 1 business day — Pro / Pro+: 8 business hours — Enterprise: Contract-defined.',
        'Priority 2 — Free: Best effort — Basic / Basic+: 2 business days — Premium / Premium+: 1 business day — Pro / Pro+: 8 business hours — Enterprise: Contract-defined.',
        'Priority 3 — Free: Best effort — Basic / Basic+: 3 business days — Premium / Premium+: 2 business days — Pro / Pro+: 1 business day — Enterprise: Contract-defined.',
        'Priority 4 — Free: Best effort — Basic / Basic+: Best effort — Premium / Premium+: Best effort — Pro / Pro+: Best effort — Enterprise: Contract-defined.',
      ],
    },
    {
      id: 'resolution-times',
      title: '12. Resolution Times',
      body: [
        'Response time is not the same as resolution time.',
        'Resolution time may depend on:',
        'SinLess Games LLC does not guarantee a specific resolution time unless a written agreement or SLA says otherwise.',
      ],
      bullets: [
        'Issue complexity',
        'Customer responsiveness',
        'Vendor involvement',
        'Third-party service behavior',
        'Required engineering work',
        'Required security review',
        'Required privacy review',
        'Required legal review',
        'Required product changes',
        'Reproduction difficulty',
        'Severity',
        'Deployment type',
        'Customer environment',
        'Availability of logs or evidence',
      ],
    },
    {
      id: 'service-level-agreements',
      title: '13. Service-Level Agreements',
      body: [
        'Some plans may include a service-level agreement.',
        'An SLA may define:',
        'Unless expressly included in a written agreement, order form, or published SLA, Aerealith AI does not provide service credits or guaranteed uptime.',
      ],
      bullets: [
        'Uptime target',
        'Covered services',
        'Exclusions',
        'Support response targets',
        'Incident notification requirements',
        'Service credits',
        'Maintenance windows',
        'Customer responsibilities',
        'Claim process',
        'Limitations',
      ],
    },
    {
      id: 'status-page',
      title: '14. Status Page',
      body: [
        'Aerealith AI may maintain a status page for service availability, incidents, degraded services, and scheduled maintenance.',
        'The status page may include:',
        'Before publishing this policy, add the official status page URL: [Insert Aerealith AI status page URL].',
        'Security, privacy, abuse, and sensitive incidents may not be fully described on the public status page if public disclosure would increase risk or expose confidential information.',
      ],
      bullets: [
        'Current system status',
        'Component-level health',
        'Active incidents',
        'Incident updates',
        'Resolved incidents',
        'Scheduled maintenance',
        'Subscriber notifications',
      ],
    },
    {
      id: 'incident-support',
      title: '15. Incident Support',
      body: [
        'Incidents are handled according to the Incident Notification Policy.',
        'During an incident, support may:',
        'Support may not be able to provide full technical details while an investigation is ongoing.',
      ],
      bullets: [
        'Confirm whether an issue is known',
        'Direct users to status updates',
        'Collect affected-user details',
        'Collect logs or screenshots',
        'Provide workarounds where available',
        'Escalate critical reports',
        'Coordinate with engineering, security, privacy, billing, marketplace, or vendor teams',
        'Provide post-incident instructions where appropriate',
      ],
      links: [
        {
          label: 'Incident Notification Policy',
          href: '/Policies/incident-notification',
        },
      ],
    },
    {
      id: 'security-support',
      title: '16. Security Support',
      body: [
        'Security issues should be reported to security@sinlessgames.com.',
        'Security support may include:',
        'Do not send passwords, private keys, access tokens, full payment card numbers, or unnecessary sensitive data in security reports.',
        'Security reports are governed by the Security Policy.',
      ],
      bullets: [
        'Vulnerability intake',
        'Security incident triage',
        'Account compromise guidance',
        'API key rotation guidance',
        'Token revocation guidance',
        'Suspicious activity review',
        'Integration security guidance',
        'Plugin or marketplace security escalation',
        'Security advisory coordination',
      ],
      contacts: [
        {
          label: 'Security',
          email: 'security@sinlessgames.com',
          href: 'mailto:security@sinlessgames.com',
        },
      ],
      links: [
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
      ],
    },
    {
      id: 'privacy-support',
      title: '17. Privacy Support',
      body: [
        'Privacy questions and data-rights requests should be sent to privacy@sinlessgames.com.',
        'Privacy support may include:',
        'Privacy requests may require identity verification or organization administrator approval.',
        'Privacy handling is governed by the Privacy Policy and Data Policy.',
      ],
      bullets: [
        'Data access requests',
        'Data deletion requests',
        'Data correction requests',
        'Export requests',
        'Consent questions',
        'Cookie and tracking questions',
        'Data processing questions',
        'Subprocessor questions',
        'Privacy incident reports',
      ],
      contacts: [
        {
          label: 'Privacy',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
      ],
      links: [
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
      ],
    },
    {
      id: 'billing-support',
      title: '18. Billing Support',
      body: [
        'Billing questions should be sent to billing@sinlessgames.com.',
        'Billing support may include:',
        'Billing support is governed by the Billing, Refund, and Cancellation Policy and Payment Processor Compliance Policy.',
      ],
      bullets: [
        'Subscription questions',
        'Plan changes',
        'Refund requests',
        'Cancellation questions',
        'Failed payment issues',
        'Invoice requests',
        'Tax questions',
        'Marketplace purchase questions',
        'Usage charge questions',
        'Payment processor issues',
        'Chargeback or dispute questions',
      ],
      contacts: [
        {
          label: 'Billing',
          email: 'billing@sinlessgames.com',
          href: 'mailto:billing@sinlessgames.com',
        },
      ],
      links: [
        {
          label: 'Billing, Refund, and Cancellation Policy',
          href: '/Policies/billing-refund-cancellation',
        },
        {
          label: 'Payment Processor Compliance Policy',
          href: '/Policies/payment-proccessor-compliance',
        },
      ],
    },
    {
      id: 'abuse-support',
      title: '19. Abuse Support',
      body: [
        'Abuse reports should be sent to abuse@sinlessgames.com.',
        'Abuse support may include reports involving:',
        'Abuse handling is governed by the Acceptable Use Policy.',
      ],
      bullets: [
        'Spam',
        'Phishing',
        'Scams',
        'Malware',
        'Harassment',
        'Impersonation',
        'Unauthorized access',
        'Unsafe automations',
        'Marketplace abuse',
        'Plugin abuse',
        'Copyright abuse',
        'Policy violations',
        'Illegal or harmful use',
      ],
      contacts: [
        {
          label: 'Abuse',
          email: 'abuse@sinlessgames.com',
          href: 'mailto:abuse@sinlessgames.com',
        },
      ],
      links: [
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
      ],
    },
    {
      id: 'ai-safety-support',
      title: '20. AI Safety Support',
      body: [
        'AI safety concerns should be sent to safety@sinlessgames.com.',
        'AI safety support may include reports involving:',
        'AI safety handling is governed by the AI Transparency Policy, Responsible AI Policy, and Incident Notification Policy.',
      ],
      bullets: [
        'Unsafe AI output',
        'Incorrect high-impact recommendations',
        'Unauthorized tool use',
        'Unsafe automation behavior',
        'Prompt injection concerns',
        'Memory concerns',
        'Model routing concerns',
        'Harmful hallucinations',
        'Bias concerns',
        'Synthetic media misuse',
        'Responsible AI concerns',
      ],
      contacts: [
        {
          label: 'AI safety',
          email: 'safety@sinlessgames.com',
          href: 'mailto:safety@sinlessgames.com',
        },
      ],
      links: [
        {
          label: 'AI Transparency Policy',
          href: '/Policies/ai-transparency',
        },
        {
          label: 'Responsible AI Policy',
          href: '/Policies/responsible-ai',
        },
        {
          label: 'Incident Notification Policy',
          href: '/Policies/incident-notification',
        },
      ],
    },
    {
      id: 'developer-support',
      title: '21. Developer Support',
      body: [
        'Developer support may include:',
        'Developer support does not guarantee custom code review, custom integration work, or production debugging unless included in a paid support or professional services agreement.',
      ],
      bullets: [
        'API usage questions',
        'SDK questions',
        'Authentication issues',
        'Rate limit questions',
        'Webhook troubleshooting',
        'Integration behavior',
        'Plugin development guidance',
        'Marketplace submission questions',
        'Developer documentation issues',
        'API error investigation',
        'Developer account issues',
      ],
    },
    {
      id: 'marketplace-support',
      title: '22. Marketplace Support',
      body: [
        'Marketplace support may include:',
        'Third-party marketplace publishers may be responsible for supporting their own marketplace items.',
        'SinLess Games LLC may provide platform-level support but may not be responsible for all third-party item behavior.',
      ],
      bullets: [
        'Marketplace installation issues',
        'Marketplace purchase questions',
        'Plugin behavior questions',
        'Publisher account questions',
        'Listing review questions',
        'Version update questions',
        'Permission questions',
        'Removal or takedown questions',
        'Marketplace policy questions',
        'Publisher payout questions, where applicable',
      ],
    },
    {
      id: 'plugin-and-integration-support',
      title: '23. Plugin and Integration Support',
      body: [
        'Plugin and integration support may depend on whether the item is:',
        'Support may be limited when issues are caused by:',
      ],
      bullets: [
        'Official Aerealith AI software',
        'Official SinLess Games LLC software',
        'Third-party marketplace software',
        'Customer-created software',
        'Open-source community software',
        'Customer-controlled integration',
        'External service integration',
        'Third-party outages',
        'Third-party API changes',
        'Customer configuration',
        'Expired credentials',
        'Revoked permissions',
        'Unsupported customization',
        'Unapproved plugins',
        'Modified source code',
        'Self-hosted environment issues',
        'Network restrictions',
        'Customer security tools',
        'Unsupported versions',
      ],
    },
    {
      id: 'automation-support',
      title: '24. Automation Support',
      body: [
        'Automation support may include:',
        'Users and organizations are responsible for reviewing automations before enabling them.',
        'Support may not be able to reverse actions taken in customer-controlled third-party systems.',
      ],
      bullets: [
        'Trigger issues',
        'Schedule issues',
        'Permission issues',
        'Tool execution failures',
        'Integration failures',
        'Approval gate issues',
        'Logging questions',
        'Error review',
        'Safe configuration guidance',
        'Rollback guidance where available',
      ],
    },
    {
      id: 'ai-output-support',
      title: '25. AI Output Support',
      body: [
        'Aerealith AI support may review reports of incorrect, unsafe, or unexpected AI output.',
        'However:',
        'AI output limitations are described in the AI Transparency Policy and Responsible AI Policy.',
      ],
      bullets: [
        'AI outputs may be inaccurate, incomplete, outdated, or unsuitable.',
        'Support does not verify every generated answer.',
        'Support does not provide professional legal, medical, financial, tax, or compliance advice.',
        'Users are responsible for reviewing and validating outputs before relying on them.',
        'High-impact or regulated use requires qualified human review.',
      ],
      links: [
        {
          label: 'AI Transparency Policy',
          href: '/Policies/ai-transparency',
        },
        {
          label: 'Responsible AI Policy',
          href: '/Policies/responsible-ai',
        },
      ],
    },
    {
      id: 'documentation-support',
      title: '26. Documentation Support',
      body: [
        'Documentation is a primary support resource.',
        'Documentation may include:',
        'Users should consult documentation before submitting non-urgent support requests where practical.',
      ],
      bullets: [
        'Setup guides',
        'User guides',
        'API references',
        'Developer guides',
        'Marketplace guides',
        'Integration guides',
        'Automation guides',
        'Security guides',
        'Release notes',
        'Known issues',
        'Troubleshooting guides',
        'Policy documentation',
      ],
    },
    {
      id: 'community-support',
      title: '27. Community Support',
      body: [
        'Aerealith AI may offer community spaces such as forums, Discord, GitHub Discussions, issue trackers, or other community channels.',
        'Community support may be useful for:',
        'Community support is not guaranteed, may not be private, and should not be used for sensitive data, security incidents, billing issues, legal notices, privacy requests, or account-specific support.',
        'Community conduct is governed by the Acceptable Use Policy and any applicable community rules.',
      ],
      bullets: [
        'General questions',
        'Peer help',
        'Feature discussions',
        'Open-source contributions',
        'Documentation suggestions',
        'Marketplace feedback',
        'Developer collaboration',
      ],
      links: [
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
      ],
    },
    {
      id: 'enterprise-support',
      title: '28. Enterprise Support',
      body: [
        'Enterprise support may include additional services under a written agreement.',
        'Enterprise support may include:',
        'Enterprise support is governed by the applicable order form, master services agreement, SLA, statement of work, or written agreement.',
      ],
      bullets: [
        'Named support contacts',
        'Named security contacts',
        'Named privacy contacts',
        'Dedicated escalation paths',
        'Custom response targets',
        'Custom SLA',
        'Custom incident notification timelines',
        'Security questionnaire support',
        'Data processing agreement support',
        'Business associate agreement support, where applicable',
        'Deployment planning',
        'Self-hosted support',
        'Air-gapped support',
        'Private marketplace support',
        'Integration planning',
        'Migration guidance',
        'Admin training',
        'Premium support reviews',
        'Architecture review',
        'Professional services',
      ],
    },
    {
      id: 'self-hosted-support',
      title: '29. Self-Hosted Support',
      body: [
        'Self-hosted support may be available depending on plan and agreement.',
        'Self-hosted support may include:',
        'Unless expressly agreed, self-hosted support does not include full management of customer infrastructure.',
        'Customers are responsible for:',
      ],
      bullets: [
        'Installation guidance',
        'Upgrade guidance',
        'Configuration guidance',
        'License activation support',
        'Deployment troubleshooting',
        'Log review guidance',
        'Supported reference architecture guidance',
        'Official image or package support',
        'Official Helm chart or manifest support, where applicable',
        'Official plugin or marketplace support, where applicable',
        'Infrastructure',
        'Networking',
        'DNS',
        'TLS certificates',
        'Databases',
        'Cache systems',
        'Object storage',
        'Backups',
        'Secrets',
        'Identity providers',
        'Security monitoring',
        'Logs',
        'SIEM',
        'Kubernetes or container platform',
        'Host operating systems',
        'Firewalls',
        'Proxies',
        'Load balancers',
        'Air-gap integrity',
        'Compliance configuration',
      ],
    },
    {
      id: 'air-gapped-support',
      title: '30. Air-Gapped Support',
      body: [
        'Air-gapped support may require special processes.',
        'Air-gapped support may include:',
        'Air-gapped support may be limited because SinLess Games LLC may not have direct access to logs, telemetry, systems, or live diagnostics.',
        'Customers operating air-gapped deployments are responsible for secure transfer of support artifacts and for removing sensitive data before sharing logs or files.',
      ],
      bullets: [
        'Offline package guidance',
        'Offline activation support',
        'Offline documentation',
        'Update bundle guidance',
        'Manual log export guidance',
        'Security advisory coordination',
        'Private support transfer process',
        'Customer-controlled diagnostics',
      ],
    },
    {
      id: 'professional-services',
      title: '31. Professional Services',
      body: [
        'SinLess Games LLC may offer professional services separately.',
        'Professional services may include:',
        'Professional services require a separate agreement, statement of work, or written approval.',
        'Professional services are not included in standard support unless expressly stated.',
      ],
      bullets: [
        'Setup',
        'Migration',
        'Architecture design',
        'Custom integration work',
        'Custom plugin development',
        'Custom automation development',
        'Custom dashboard development',
        'Security hardening',
        'Training',
        'Documentation',
        'Deployment support',
        'Incident assistance',
        'Compliance support',
        'Marketplace publisher assistance',
      ],
    },
    {
      id: 'support-request-requirements',
      title: '32. Support Request Requirements',
      body: [
        'To help support investigate an issue, include as much detail as possible.',
        'Support requests should include:',
        'Do not include passwords, private keys, access tokens, full payment card numbers, or unnecessary sensitive data.',
      ],
      bullets: [
        'Account email',
        'Organization name, if applicable',
        'Workspace name, if applicable',
        'Plan, if known',
        'Affected feature',
        'Affected integration',
        'Affected plugin or marketplace item',
        'Browser or app version',
        'Device and operating system',
        'Approximate time of issue',
        'Error messages',
        'Screenshots',
        'Logs',
        'Request IDs',
        'Trace IDs',
        'Steps to reproduce',
        'Expected behavior',
        'Actual behavior',
        'Impact level',
        'Any workaround already attempted',
      ],
    },
    {
      id: 'customer-cooperation',
      title: '33. Customer Cooperation',
      body: [
        'Users and organizations may need to cooperate with support.',
        'Cooperation may include:',
        'Failure to cooperate may delay or prevent resolution.',
      ],
      bullets: [
        'Providing accurate information',
        'Responding to follow-up questions',
        'Testing suggested fixes',
        'Providing logs or screenshots',
        'Confirming impact',
        'Confirming whether an issue is resolved',
        'Updating software or app versions',
        'Rotating credentials when advised',
        'Reviewing audit logs when advised',
        'Disabling affected integrations when advised',
        'Pausing affected automations when advised',
        'Contacting third-party vendors when the issue is outside Aerealith AI control',
      ],
    },
    {
      id: 'remote-access',
      title: '34. Remote Access',
      body: [
        'SinLess Games LLC will not access customer systems, accounts, repositories, cloud environments, devices, or self-hosted deployments unless authorized.',
        'If remote access is required, it should be:',
        'Customers should not share passwords or private keys with support.',
        'Use secure temporary access methods where possible.',
      ],
      bullets: [
        'Explicitly approved',
        'Time-limited',
        'Scoped to the support issue',
        'Logged where practical',
        'Revocable',
        'Least-privilege',
        'Conducted through approved support channels',
        'Governed by applicable agreements',
      ],
    },
    {
      id: 'support-data-handling',
      title: '35. Support Data Handling',
      body: [
        'Support may process data needed to investigate and resolve support requests.',
        'Support data may include:',
        'Support data is handled according to the Privacy Policy, Data Policy, and Security Policy.',
      ],
      bullets: [
        'Contact information',
        'Account metadata',
        'Workspace metadata',
        'Support messages',
        'Screenshots',
        'Logs',
        'Error messages',
        'Diagnostic data',
        'Billing records',
        'Integration metadata',
        'Plugin metadata',
        'Automation metadata',
        'User-provided files',
      ],
      links: [
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
      ],
    },
    {
      id: 'sensitive-data-in-support-requests',
      title: '36. Sensitive Data in Support Requests',
      body: [
        'Users should avoid sending sensitive data unless necessary.',
        'Sensitive data may include:',
        'If sensitive data is required for support, use approved secure channels and provide only the minimum information needed.',
      ],
      bullets: [
        'Government identification numbers',
        'Health information',
        'Legal records',
        'Financial account information',
        'Payment card information',
        'Passwords',
        'API keys',
        'Access tokens',
        'Private keys',
        'Confidential business information',
        'Regulated customer data',
        'Children’s data',
      ],
    },
    {
      id: 'support-attachments',
      title: '37. Support Attachments',
      body: [
        'Support may accept attachments where needed.',
        'Attachments may include:',
        'Users are responsible for reviewing attachments before sending them.',
        'Attachments should not include secrets, credentials, private keys, unnecessary personal data, or unrelated confidential information.',
      ],
      bullets: [
        'Screenshots',
        'Logs',
        'Error reports',
        'Configuration files',
        'Diagnostic bundles',
        'Example inputs',
        'Exported data',
      ],
    },
    {
      id: 'third-party-issues',
      title: '38. Third-Party Issues',
      body: [
        'Aerealith AI may depend on third-party services, vendors, integrations, APIs, models, payment processors, hosting providers, and marketplace items.',
        'Support may be limited when an issue is caused by:',
        'SinLess Games LLC may assist with diagnosis, but the user or organization may need to contact the third-party provider.',
      ],
      bullets: [
        'Third-party outage',
        'Third-party API change',
        'Third-party rate limit',
        'Third-party account suspension',
        'Third-party permission issue',
        'Third-party billing issue',
        'Third-party security restriction',
        'Third-party policy enforcement',
        'Customer-controlled integration configuration',
        'Customer network restrictions',
        'Customer identity provider configuration',
        'Customer infrastructure configuration',
      ],
    },
    {
      id: 'unsupported-versions',
      title: '39. Unsupported Versions',
      body: [
        'Support may be limited for unsupported versions.',
        'Unsupported versions may include:',
        'Users may be asked to upgrade before support can continue.',
      ],
      bullets: [
        'Deprecated app versions',
        'Deprecated API versions',
        'Deprecated SDK versions',
        'Unsupported browser versions',
        'Unsupported operating systems',
        'Unsupported self-hosted releases',
        'Modified official images',
        'Modified source code',
        'Unapproved forks',
        'Unapproved plugins',
        'Unapproved deployment configurations',
      ],
    },
    {
      id: 'beta-preview-and-experimental-features',
      title: '40. Beta, Preview, and Experimental Features',
      body: [
        'Beta, preview, early-access, experimental, or research features may have limited support.',
        'These features may be:',
        'Users should not rely on beta or experimental features for critical production workflows unless expressly approved in writing.',
      ],
      bullets: [
        'Less stable',
        'Less complete',
        'Less documented',
        'Subject to change',
        'Removed without notice',
        'Excluded from SLA commitments',
        'Lower priority for support',
        'Subject to additional restrictions',
      ],
    },
    {
      id: 'feature-requests',
      title: '41. Feature Requests',
      body: [
        'Users may submit feature requests.',
        'Feature requests may be used for:',
        'Submitting a feature request does not guarantee implementation, timeline, support, or inclusion in the roadmap.',
      ],
      bullets: [
        'Product planning',
        'Roadmap consideration',
        'Documentation improvements',
        'Usability improvements',
        'Integration planning',
        'Marketplace planning',
        'Accessibility improvements',
      ],
    },
    {
      id: 'bug-reports',
      title: '42. Bug Reports',
      body: [
        'Users may submit bug reports.',
        'Bug reports should include:',
        'SinLess Games LLC may prioritize bugs based on severity, scope, risk, customer impact, security impact, privacy impact, and product roadmap.',
      ],
      bullets: [
        'Steps to reproduce',
        'Expected behavior',
        'Actual behavior',
        'Screenshots or logs',
        'Browser or app version',
        'API version, if applicable',
        'Impact level',
        'Frequency',
        'Workaround, if any',
      ],
    },
    {
      id: 'escalation',
      title: '43. Escalation',
      body: [
        'Support requests may be escalated when appropriate.',
        'Escalation may occur for:',
        'Escalation may involve support, engineering, security, privacy, legal, billing, product, or executive contacts.',
      ],
      bullets: [
        'Critical incidents',
        'Security issues',
        'Privacy issues',
        'Data loss or corruption',
        'Billing failures',
        'Enterprise-impacting issues',
        'Production-blocking issues',
        'Legal notices',
        'Marketplace risk',
        'Unsafe AI behavior',
        'High-impact automation failures',
      ],
    },
    {
      id: 'abuse-of-support',
      title: '44. Abuse of Support',
      body: [
        'Users may not abuse support channels.',
        'Prohibited support abuse includes:',
        'Support abuse may result in ticket closure, account restriction, suspension, termination, or reporting where appropriate.',
      ],
      bullets: [
        'Harassment',
        'Threats',
        'Spam',
        'Repeated duplicate tickets',
        'False reports',
        'Fraudulent refund claims',
        'Social engineering',
        'Attempts to obtain unauthorized access',
        'Attempts to bypass security or billing controls',
        'Sending malware',
        'Sending illegal content',
        'Sending unnecessary sensitive data',
        'Impersonating another user or organization',
        'Abusing emergency or escalation channels',
      ],
    },
    {
      id: 'account-recovery-support',
      title: '45. Account Recovery Support',
      body: [
        'Account recovery support may help users regain access to accounts where supported.',
        'Account recovery may require:',
        'SinLess Games LLC may deny account recovery if it cannot reasonably verify ownership or authorization.',
        'Organization accounts may require administrator involvement.',
      ],
      bullets: [
        'Identity verification',
        'Email verification',
        'Billing verification',
        'Organization administrator approval',
        'Security review',
        'Waiting periods',
        'Session revocation',
        'Credential reset',
        'MFA reset',
        'Passkey reset',
        'Additional documentation',
      ],
    },
    {
      id: 'data-recovery-support',
      title: '46. Data Recovery Support',
      body: [
        'Data recovery may be limited.',
        'SinLess Games LLC does not guarantee recovery of deleted, overwritten, corrupted, or expired data unless expressly stated in a written agreement.',
        'Data recovery may depend on:',
        'Users should maintain their own exports or backups where appropriate.',
      ],
      bullets: [
        'Retention settings',
        'Backup availability',
        'Time since deletion',
        'Account status',
        'Organization policy',
        'Deployment type',
        'Technical feasibility',
        'Legal restrictions',
        'Security restrictions',
        'Customer-controlled environment behavior',
      ],
    },
    {
      id: 'cancellation-and-refund-support',
      title: '47. Cancellation and Refund Support',
      body: [
        'Cancellation and refund support is governed by the Billing, Refund, and Cancellation Policy.',
        'Support may help users:',
        'Support cannot guarantee refunds outside the applicable policy, law, or written agreement.',
      ],
      bullets: [
        'Locate billing settings',
        'Understand plan status',
        'Request cancellation assistance',
        'Request refund review',
        'Understand invoices',
        'Update payment methods',
        'Review failed payments',
        'Review duplicate charges',
        'Escalate billing errors',
      ],
      links: [
        {
          label: 'Billing, Refund, and Cancellation Policy',
          href: '/Policies/billing-refund-cancellation',
        },
      ],
    },
    {
      id: 'legal-notices',
      title: '48. Legal Notices',
      body: [
        'Legal notices should be sent to legal@sinlessgames.com.',
        'Copyright notices should be sent to copyright@sinlessgames.com.',
        'Support channels should not be used as the primary channel for formal legal notices unless expressly permitted by a written agreement or policy.',
      ],
      contacts: [
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
        {
          label: 'Copyright',
          email: 'copyright@sinlessgames.com',
          href: 'mailto:copyright@sinlessgames.com',
        },
      ],
    },
    {
      id: 'no-warranty-through-support',
      title: '49. No Warranty Through Support',
      body: [
        'Support guidance is provided to help users use Aerealith AI.',
        'Support responses do not create warranties, guarantees, legal advice, professional advice, or commitments beyond the applicable Terms of Use, policies, SLA, order form, or written agreement.',
        'Users remain responsible for reviewing, testing, and validating actions taken based on support guidance.',
      ],
    },
    {
      id: 'publication-checklist',
      title: '50. Publication Checklist',
      body: ['Before publishing this policy, complete the following:'],
      bullets: [
        'Confirm official company name: SinLess Games LLC',
        'Confirm official product name: Aerealith AI',
        'Confirm support email aliases',
        'Confirm official support portal URL',
        'Confirm official status page URL',
        'Confirm support hours',
        'Confirm support time zone',
        'Confirm supported plans',
        'Confirm plan-specific support channels',
        'Confirm response time targets',
        'Confirm SLA availability',
        'Confirm enterprise escalation process',
        'Confirm self-hosted support boundaries',
        'Confirm air-gapped support process',
        'Confirm professional services process',
        'Confirm security report workflow',
        'Confirm privacy request workflow',
        'Confirm billing support workflow',
        'Confirm abuse report workflow',
        'Confirm AI safety report workflow',
        'Confirm support data retention',
        'Confirm support attachment handling',
        'Confirm legal review',
      ],
    },
    {
      id: 'changes-to-this-policy',
      title: '51. Changes to This Policy',
      body: [
        'We may update this policy from time to time.',
        'When we make material changes, we will update the last_updated date and may provide notice through the service, documentation, account settings, support portal, email, release notes, legal notices page, or another reasonable method.',
        'Continued use of Aerealith AI after changes become effective means you accept the updated policy.',
      ],
    },
    {
      id: 'contact',
      title: '52. Contact',
      body: [
        'Questions about this policy may be sent to:',
        'Before publishing this policy, confirm these email aliases exist and are monitored.',
      ],
      contacts: [
        {
          label: 'Support',
          email: 'support@sinlessgames.com',
          href: 'mailto:support@sinlessgames.com',
        },
        {
          label: 'Billing',
          email: 'billing@sinlessgames.com',
          href: 'mailto:billing@sinlessgames.com',
        },
        {
          label: 'Security',
          email: 'security@sinlessgames.com',
          href: 'mailto:security@sinlessgames.com',
        },
        {
          label: 'Privacy',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
        {
          label: 'Abuse',
          email: 'abuse@sinlessgames.com',
          href: 'mailto:abuse@sinlessgames.com',
        },
        {
          label: 'AI safety',
          email: 'safety@sinlessgames.com',
          href: 'mailto:safety@sinlessgames.com',
        },
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
      ],
    },
    {
      id: 'legal-review-notice',
      title: '53. Legal Review Notice',
      body: [
        'This policy is a draft template and should be reviewed by qualified legal counsel before publication.',
        'Support obligations, SLA commitments, service credits, consumer support rules, enterprise support obligations, incident response, regulated-data support, accessibility support, self-hosted support, professional services, and warranty limitations may vary by jurisdiction, customer type, deployment model, and written agreement.',
      ],
    },
  ],
} satisfies PolicyDocument;

export default supportPolicy;
