import type { PolicyDocument } from '../../types';

export const termsOfUsePolicy = {
  slug: 'terms-of-use',
  path: '/Policies/terms-of-use',
  meta: {
    title: 'Terms of Use',
    description:
      'Defines the legal terms for accessing and using Aerealith AI services, accounts, subscriptions, content, APIs, automations, integrations, marketplace items, and deployments.',
    effectiveDate: '2026-05-18',
    lastUpdated: '2026-05-18',
    owner: 'SinLess Games LLC',
    status: 'draft',
  },
  relatedPolicies: [
    {
      label: 'Privacy Policy',
      href: '/Policies/privacy',
    },
    {
      label: 'Data Policy',
      href: '/Policies/data',
    },
    {
      label: 'Security Policy',
      href: '/Policies/security-policy',
    },
    {
      label: 'Acceptable Use Policy',
      href: '/Policies/acceptable-use',
    },
    {
      label: 'AI Transparency Policy',
      href: '/Policies/ai-transparency',
    },
    {
      label: 'Responsible AI Policy',
      href: '/Policies/responsible-ai',
    },
    {
      label: 'Cookie and Tracking Policy',
      href: '/Policies/cookie-tracking',
    },
    {
      label: 'Billing, Refund, and Cancellation Policy',
      href: '/Policies/billing-refund-cancellation',
    },
    {
      label: 'Copyright Takedown Policy',
      href: '/Policies/copyright-takedown',
    },
    {
      label: 'Incident Notification Policy',
      href: '/Policies/incident-notification',
    },
    {
      label: 'Payment Processor Compliance Policy',
      href: '/Policies/payment-proccessor-compliance',
    },
    {
      label: 'Subprocessor and Vendor List',
      href: '/Policies/subprocessor-vendor-list',
    },
    {
      label: 'Support Policy',
      href: '/Policies/support-policy',
    },
    {
      label: 'User-Generated Content Policy',
      href: '/Policies/user-generated-content',
    },
    {
      label: 'Marketplace Policy',
      href: '/Policies/marketplace',
    },
    {
      label: 'Developer and API Policy',
      href: '/Policies/developer',
    },
    {
      label: 'Underage Policy',
      href: '/Policies/underage-policy',
    },
  ],
  sections: [
    {
      id: 'purpose',
      title: '1. Purpose',
      body: [
        'These Terms of Use govern access to and use of Aerealith AI.',
        'Aerealith AI is operated by SinLess Games LLC.',
        'Aerealith AI is designed to help users think, create, automate, analyze, monitor, and act across connected systems. Because Aerealith AI may involve artificial intelligence, user data, memory, files, integrations, automations, APIs, plugins, marketplace items, dashboards, analytics, and organization workspaces, these Terms explain the rights, responsibilities, limits, and conditions that apply when using the service.',
        'By accessing or using Aerealith AI, you agree to these Terms and all policies incorporated by reference.',
        'If you do not agree to these Terms, do not use Aerealith AI.',
      ],
    },
    {
      id: 'scope',
      title: '2. Scope',
      body: [
        'These Terms apply to Aerealith AI services, including:',
        'These Terms apply to:',
      ],
      bullets: [
        'Websites',
        'Web applications',
        'Desktop applications',
        'Mobile applications',
        'Browser extensions',
        'APIs',
        'Developer tools',
        'Documentation sites',
        'Marketplace features',
        'Plugins',
        'Automations',
        'Integrations',
        'Dashboards',
        'Analytics features',
        'AI memory features',
        'Billing systems',
        'Support systems',
        'Organization workspaces',
        'Cloud-hosted deployments',
        'Self-hosted deployments, where applicable',
        'Hybrid deployments, where applicable',
        'Air-gapped deployments, where applicable',
        'Any other product, feature, or service that links to these Terms',
        'Visitors',
        'Individual users',
        'Organization users',
        'Workspace members',
        'Administrators',
        'Developers',
        'Marketplace publishers',
        'API users',
        'Enterprise customers',
        'Anyone who accesses or uses Aerealith AI through an account, workspace, integration, automation, shared agent, plugin, API key, or connected service',
      ],
    },
    {
      id: 'company-information',
      title: '3. Company Information',
      body: [
        'Aerealith AI is operated by SinLess Games LLC.',
        'Before publishing these Terms, insert the official business address and required contact information.',
        'Before publishing, confirm that these email aliases exist and are monitored.',
      ],
      contacts: [
        {
          label: 'General contact',
          email: 'support@sinlessgames.com',
          href: 'mailto:support@sinlessgames.com',
        },
        {
          label: 'Legal contact',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
        {
          label: 'Privacy contact',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
        {
          label: 'Security contact',
          email: 'security@sinlessgames.com',
          href: 'mailto:security@sinlessgames.com',
        },
      ],
    },
    {
      id: 'relationship-to-other-policies',
      title: '4. Relationship to Other Policies',
      body: [
        'These Terms work together with other Aerealith AI policies, including:',
        'These policies are incorporated into these Terms by reference.',
        'If there is a conflict between these Terms and a written agreement signed by SinLess Games LLC, the signed written agreement controls only to the extent of the conflict.',
      ],
      links: [
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
        {
          label: 'AI Transparency Policy',
          href: '/Policies/ai-transparency',
        },
        {
          label: 'Responsible AI Policy',
          href: '/Policies/responsible-ai',
        },
        {
          label: 'Cookie and Tracking Policy',
          href: '/Policies/cookie-tracking',
        },
        {
          label: 'Billing, Refund, and Cancellation Policy',
          href: '/Policies/billing-refund-cancellation',
        },
        {
          label: 'Copyright Takedown Policy',
          href: '/Policies/copyright-takedown',
        },
        {
          label: 'Incident Notification Policy',
          href: '/Policies/incident-notification',
        },
        {
          label: 'Payment Processor Compliance Policy',
          href: '/Policies/payment-proccessor-compliance',
        },
        {
          label: 'Subprocessor and Vendor List',
          href: '/Policies/subprocessor-vendor-list',
        },
        {
          label: 'Support Policy',
          href: '/Policies/support-policy',
        },
        {
          label: 'User-Generated Content Policy',
          href: '/Policies/user-generated-content',
        },
        {
          label: 'Marketplace Policy',
          href: '/Policies/marketplace',
        },
        {
          label: 'Developer and API Policy',
          href: '/Policies/developer',
        },
        {
          label: 'Underage Policy',
          href: '/Policies/underage-policy',
        },
      ],
    },
    {
      id: 'changes-to-these-terms',
      title: '5. Changes to These Terms',
      body: [
        'We may update these Terms from time to time.',
        'When we make material changes, we will update the last_updated date and may provide notice through the service, documentation, account settings, email, release notes, legal notices page, or another reasonable method.',
        'Changes become effective when posted unless a later effective date is stated.',
        'Continued use of Aerealith AI after changes become effective means you accept the updated Terms.',
        'If you do not agree to the updated Terms, you must stop using Aerealith AI.',
      ],
    },
    {
      id: 'eligibility',
      title: '6. Eligibility',
      body: [
        'You may use Aerealith AI only if you can legally agree to these Terms and are not prohibited from using the service under applicable law.',
        'You may not use Aerealith AI if:',
        'Use by minors is governed by the applicable Underage Policy, if published, and by applicable law.',
      ],
      bullets: [
        'You are legally barred from using the service.',
        'You are located in a jurisdiction where use is prohibited.',
        'You are subject to sanctions or restricted-party rules that prohibit use.',
        'You were previously suspended or terminated and have not received written permission to return.',
        'Your use would violate these Terms, applicable policies, law, or a written agreement.',
      ],
      links: [
        {
          label: 'Underage Policy',
          href: '/Policies/underage-policy',
        },
      ],
    },
    {
      id: 'use-on-behalf-of-an-organization',
      title: '7. Use on Behalf of an Organization',
      body: [
        'If you use Aerealith AI on behalf of an organization, you represent that:',
        'If you do not have authority to bind the organization, do not use Aerealith AI on behalf of that organization.',
      ],
      bullets: [
        'You have authority to bind that organization to these Terms.',
        'The organization agrees to these Terms.',
        'You will use Aerealith AI only for authorized organization purposes.',
        'You will follow the organization’s policies.',
        'You will ensure organization users comply with these Terms.',
        'The organization is responsible for activity under its workspaces, accounts, API keys, integrations, automations, plugins, and users.',
      ],
    },
    {
      id: 'account-registration',
      title: '8. Account Registration',
      body: [
        'Some features require an account.',
        'When creating an account, you must provide accurate, complete, and current information.',
        'You are responsible for:',
        'You may not create accounts using false, misleading, stolen, or unauthorized information.',
      ],
      bullets: [
        'Keeping account information current',
        'Protecting account credentials',
        'Maintaining control of your email account',
        'Enabling security features where available',
        'Monitoring account activity',
        'Promptly reporting unauthorized access',
        'Ensuring users under your account or organization comply with these Terms',
      ],
    },
    {
      id: 'account-security',
      title: '9. Account Security',
      body: [
        'You are responsible for maintaining the security of your account, devices, credentials, API keys, tokens, sessions, integrations, plugins, automations, and connected systems.',
        'You must not:',
        'If you believe your account has been compromised, contact security@sinlessgames.com.',
      ],
      bullets: [
        'Share passwords',
        'Share API keys publicly',
        'Use another person’s account without permission',
        'Bypass authentication or authorization controls',
        'Allow unauthorized access to your account',
        'Store secrets in ordinary prompts, files, memory, or support messages',
        'Use Aerealith AI in a way that compromises security',
      ],
      contacts: [
        {
          label: 'Security',
          email: 'security@sinlessgames.com',
          href: 'mailto:security@sinlessgames.com',
        },
      ],
    },
    {
      id: 'account-responsibility',
      title: '10. Account Responsibility',
      body: [
        'You are responsible for all activity under your account, organization, workspace, API keys, integrations, automations, plugins, marketplace items, and connected systems.',
        'This includes activity by:',
        'You are responsible for charges, data processing, actions, outputs, and policy violations caused by your account or organization.',
      ],
      bullets: [
        'You',
        'Your employees',
        'Your contractors',
        'Your organization members',
        'Your administrators',
        'Your service accounts',
        'Your API keys',
        'Your automations',
        'Your connected integrations',
        'Anyone you authorize to access Aerealith AI',
      ],
    },
    {
      id: 'the-aerealith-ai-service',
      title: '11. The Aerealith AI Service',
      body: [
        'Aerealith AI may provide features that help users:',
        'Features may vary by plan, region, deployment type, organization settings, account status, technical availability, safety rules, and legal requirements.',
      ],
      bullets: [
        'Draft, rewrite, summarize, and organize content',
        'Analyze files, messages, code, logs, events, and structured data',
        'Generate ideas, plans, checklists, workflows, and documentation',
        'Search, retrieve, compare, and explain information',
        'Create dashboards, reports, and operational summaries',
        'Assist with development, infrastructure, automation, and technical workflows',
        'Execute approved actions through connected tools, plugins, and integrations',
        'Personalize responses based on user-controlled preferences and memory',
        'Use APIs, SDKs, plugins, workflows, marketplace items, and connected services',
      ],
    },
    {
      id: 'ai-nature-of-the-service',
      title: '12. AI Nature of the Service',
      body: [
        'Aerealith AI uses artificial intelligence and automation.',
        'AI-generated output may be:',
        'You are responsible for reviewing, validating, testing, and approving outputs before relying on them.',
        'Aerealith AI is not a human, attorney, doctor, financial advisor, accountant, therapist, emergency responder, government official, or licensed professional.',
        'AI behavior and limitations are described further in the AI Transparency Policy and Responsible AI Policy.',
      ],
      bullets: [
        'Incorrect',
        'Incomplete',
        'Outdated',
        'Biased',
        'Misleading',
        'Inconsistent',
        'Unsuitable for a specific use',
        'Based on incomplete or misunderstood context',
        'Affected by model limitations, retrieval errors, tool errors, or user-provided information',
      ],
      links: [
        {
          label: 'AI Transparency Policy',
          href: '/Policies/ai-transparency',
        },
        {
          label: 'Responsible AI Policy',
          href: '/Policies/responsible-ai',
        },
      ],
    },
    {
      id: 'no-claim-of-sentience-or-human-status',
      title: '13. No Claim of Sentience or Human Status',
      body: [
        'Aerealith AI may use assistant identities, memory, personalization, voices, avatars, personas, and natural language interaction.',
        'However:',
        'Any assistant identity, continuity, personality, or companionship feature is a product feature and should not be interpreted as proof of sentience or human status.',
      ],
      bullets: [
        'Aerealith AI is not human.',
        'Aerealith AI is not sentient.',
        'Aerealith AI does not have consciousness, emotions, independent legal personhood, or personal rights.',
        'Aerealith AI may model empathy behaviorally, but it does not experience feelings.',
        'Aerealith AI does not replace human judgment, professional responsibility, or user accountability.',
      ],
    },
    {
      id: 'professional-advice-disclaimer',
      title: '14. Professional Advice Disclaimer',
      body: [
        'Aerealith AI may help draft, explain, summarize, compare, or organize information related to legal, medical, financial, security, tax, employment, compliance, or business topics.',
        'Aerealith AI does not provide professional advice.',
        'You should consult qualified professionals before relying on Aerealith AI output for regulated, specialized, or high-impact matters.',
        'You may not use Aerealith AI as the sole decision-maker for legal, medical, financial, employment, housing, credit, insurance, education, immigration, public benefits, law enforcement, safety-critical, or other high-impact decisions.',
      ],
    },
    {
      id: 'human-review-requirements',
      title: '15. Human Review Requirements',
      body: ['Human review is required before using Aerealith AI output for:'],
      bullets: [
        'Legal decisions',
        'Medical decisions',
        'Financial decisions',
        'Tax decisions',
        'Insurance decisions',
        'Employment decisions',
        'Housing decisions',
        'Education decisions',
        'Credit or lending decisions',
        'Public benefits decisions',
        'Immigration or legal status decisions',
        'Law enforcement or criminal justice decisions',
        'Safety-critical infrastructure',
        'Production infrastructure changes',
        'Security-sensitive changes',
        'Identity and access management changes',
        'Secrets, credentials, or key management',
        'Public statements or official notices',
        'Contract, regulatory, or compliance submissions',
        'Irreversible or destructive automations',
        'Any decision that may materially affect a person’s rights, safety, privacy, finances, employment, housing, education, healthcare, reputation, or access to essential services',
      ],
    },
    {
      id: 'acceptable-use',
      title: '16. Acceptable Use',
      body: [
        'You must use Aerealith AI lawfully, safely, honestly, and responsibly.',
        'You must comply with the Acceptable Use Policy.',
        'You may not use Aerealith AI to:',
        'SinLess Games LLC may suspend, restrict, or terminate access for violations.',
      ],
      bullets: [
        'Break the law',
        'Harm people or systems',
        'Commit fraud or scams',
        'Create or distribute malware',
        'Steal credentials',
        'Attack systems without authorization',
        'Harass, threaten, or abuse others',
        'Exploit or harm children',
        'Violate privacy rights',
        'Violate intellectual property rights',
        'Evade safety systems',
        'Bypass access controls',
        'Abuse APIs, automations, integrations, or marketplace items',
        'Use Aerealith AI for prohibited or restricted activity',
      ],
      links: [
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
      ],
    },
    {
      id: 'user-data-ownership',
      title: '17. User Data Ownership',
      body: [
        'As between you and SinLess Games LLC, you retain ownership of your data.',
        'Your data may include:',
        'SinLess Games LLC does not claim ownership of your data.',
        'Data handling is described in the Data Policy and Privacy Policy.',
      ],
      bullets: [
        'Prompts',
        'Messages',
        'Uploaded files',
        'Documents',
        'Images',
        'Audio',
        'Video',
        'Code',
        'Configuration files',
        'Logs',
        'Notes',
        'Project data',
        'Workspace data',
        'Organization data',
        'Integration data',
        'Automation data',
        'Memory entries',
        'Dashboard data',
        'Analytics inputs',
        'API inputs',
        'User-generated content',
        'Marketplace publisher content',
        'Any other content you submit, upload, connect, create, import, or process through Aerealith AI',
      ],
      links: [
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy',
        },
      ],
    },
    {
      id: 'no-sale-of-user-data',
      title: '18. No Sale of User Data',
      body: [
        'SinLess Games LLC does not sell user data.',
        'Aerealith AI does not sell:',
        'Aerealith AI does not use user data outside legitimate service business logic and approved research purposes.',
      ],
      bullets: [
        'User prompts',
        'User messages',
        'Uploaded files',
        'Memory entries',
        'Workspace data',
        'Organization data',
        'Integration data',
        'API inputs or outputs',
        'Personal information',
        'Private user content',
        'Sensitive data',
        'Secrets',
        'Analytics inputs',
        'Dashboard data',
      ],
    },
    {
      id: 'license-you-grant-to-sinless-games-llc',
      title: '19. License You Grant to SinLess Games LLC',
      body: [
        'You grant SinLess Games LLC a limited, worldwide, non-exclusive, royalty-free license to host, store, process, transmit, display, copy, modify, create technical transformations of, analyze, and otherwise use your data only as needed to:',
        'This license ends when your data is deleted from active systems, except where continued retention is required or permitted for backups, legal obligations, security, fraud prevention, billing, dispute resolution, audit logs, compliance, or legitimate business needs.',
      ],
      bullets: [
        'Provide Aerealith AI',
        'Generate responses',
        'Process prompts and files',
        'Operate integrations',
        'Run automations',
        'Execute approved tool calls',
        'Provide memory and personalization',
        'Provide dashboards and analytics',
        'Operate APIs and developer tools',
        'Support marketplace functionality',
        'Secure the service',
        'Prevent abuse',
        'Debug errors',
        'Provide support',
        'Process billing',
        'Maintain audit logs',
        'Conduct approved research',
        'Improve reliability and quality',
        'Comply with law',
        'Enforce these Terms and related policies',
      ],
    },
    {
      id: 'your-responsibilities-for-user-content',
      title: '20. Your Responsibilities for User Content',
      body: [
        'You are responsible for content you submit, upload, connect, generate, publish, share, or process through Aerealith AI.',
        'You represent and warrant that:',
        'You are responsible for reviewing generated or transformed content before use, publication, deployment, or distribution.',
      ],
      bullets: [
        'You have the rights needed to use the content with Aerealith AI.',
        'Your content does not violate law.',
        'Your content does not violate another person’s rights.',
        'Your content does not contain malware or harmful code.',
        'Your content does not violate these Terms or related policies.',
        'Your use of Aerealith AI with that content is authorized.',
      ],
    },
    {
      id: 'public-content',
      title: '21. Public Content',
      body: [
        'Some features may allow you to publish or share content publicly.',
        'Public content may include:',
        'You are responsible for ensuring public content does not include private, sensitive, confidential, regulated, or unauthorized data.',
        'Public content may be indexed, copied, downloaded, cached, shared, or retained by others.',
      ],
      bullets: [
        'Shared chats',
        'Public dashboards',
        'Marketplace items',
        'Documentation',
        'Templates',
        'Plugins',
        'Workflows',
        'Reports',
        'Generated assets',
        'Community posts',
        'Reviews',
        'Comments',
      ],
    },
    {
      id: 'feedback',
      title: '22. Feedback',
      body: [
        'You may provide feedback, suggestions, ideas, bug reports, feature requests, comments, or recommendations.',
        'Unless otherwise agreed in writing, you grant SinLess Games LLC a perpetual, irrevocable, worldwide, royalty-free license to use feedback for any lawful business purpose without obligation to compensate you.',
        'Feedback does not include private Customer Data unless you intentionally include that data in the feedback.',
        'Do not include secrets, regulated data, confidential data, or unnecessary personal information in feedback.',
      ],
    },
    {
      id: 'sinless-games-llc-intellectual-property',
      title: '23. SinLess Games LLC Intellectual Property',
      body: [
        'Aerealith AI, including its software, interfaces, designs, documentation, branding, names, logos, trademarks, service marks, workflows, systems, models, prompts, tools, APIs, SDKs, marketplace infrastructure, and other materials, is owned by SinLess Games LLC or its licensors.',
        'These Terms do not transfer ownership of SinLess Games LLC intellectual property to you.',
        'You may not:',
      ],
      bullets: [
        'Copy, modify, distribute, sell, lease, or sublicense Aerealith AI except as allowed by these Terms or a written agreement',
        'Remove proprietary notices',
        'Misuse SinLess Games LLC trademarks',
        'Reverse engineer Aerealith AI except where permitted by law',
        'Bypass technical controls',
        'Access Aerealith AI to build a competing service in violation of these Terms',
        'Use Aerealith AI branding without permission',
      ],
    },
    {
      id: 'open-source-components',
      title: '24. Open Source Components',
      body: [
        'Aerealith AI may include or interact with open source software.',
        'Open source components are governed by their applicable licenses.',
        'Nothing in these Terms limits rights granted to you under applicable open source licenses.',
        'If there is a conflict between these Terms and an open source license for a specific open source component, the open source license controls for that component only.',
      ],
    },
    {
      id: 'third-party-services',
      title: '25. Third-Party Services',
      body: [
        'Aerealith AI may integrate with or link to third-party services.',
        'Third-party services may include:',
        'Third-party services are governed by their own terms, policies, privacy notices, and security practices.',
        'SinLess Games LLC is not responsible for third-party services except as expressly stated in a written agreement.',
        'You are responsible for reviewing permissions and terms before connecting third-party services to Aerealith AI.',
      ],
      bullets: [
        'AI providers',
        'Payment processors',
        'Hosting providers',
        'Authentication providers',
        'Analytics providers',
        'Email services',
        'Cloud storage providers',
        'Git repositories',
        'Calendar services',
        'Chat platforms',
        'Infrastructure systems',
        'Marketplace publishers',
        'Plugins',
        'APIs',
        'Customer-selected integrations',
      ],
    },
    {
      id: 'integrations',
      title: '26. Integrations',
      body: [
        'If you connect Aerealith AI to third-party accounts, tools, systems, or services, you authorize Aerealith AI to access and process information from those integrations according to your permissions, instructions, organization settings, and applicable agreements.',
        'You are responsible for:',
        'SinLess Games LLC may disable integrations that create security, privacy, legal, policy, or operational risk.',
      ],
      bullets: [
        'Ensuring you have authority to connect the integration',
        'Reviewing requested permissions',
        'Granting only necessary access',
        'Disconnecting integrations that are no longer needed',
        'Complying with third-party terms',
        'Securing connected accounts',
        'Reviewing automation behavior involving integrations',
        'Managing organization-approved integrations',
      ],
    },
    {
      id: 'automations-and-tool-calls',
      title: '27. Automations and Tool Calls',
      body: [
        'Aerealith AI may support automations, workflows, agents, schedules, triggers, tool calls, and connected actions.',
        'You are responsible for configuring automations safely.',
        'You must ensure automations are:',
        'SinLess Games LLC is not responsible for damage caused by user-approved automations, misconfigured integrations, unsafe instructions, or customer-controlled systems except as expressly stated in a written agreement.',
      ],
      bullets: [
        'Authorized',
        'Lawful',
        'Properly scoped',
        'Tested before production use',
        'Configured with least privilege',
        'Monitored where appropriate',
        'Reversible where practical',
        'Logged where appropriate',
        'Subject to human approval for high-risk actions',
      ],
    },
    {
      id: 'apis-and-developer-tools',
      title: '28. APIs and Developer Tools',
      body: [
        'Aerealith AI may provide APIs, SDKs, webhooks, developer tools, and integration features.',
        'Developers must:',
        'You may not use APIs or developer tools to bypass safety systems, policy enforcement, billing limits, usage limits, rate limits, or organization controls.',
      ],
      bullets: [
        'Follow these Terms',
        'Follow the Acceptable Use Policy',
        'Follow applicable developer policies',
        'Secure API keys and tokens',
        'Use least-privilege access',
        'Respect rate limits',
        'Respect billing limits',
        'Respect user and organization permissions',
        'Provide required notices to their own users',
        'Obtain required consent',
        'Protect user data',
        'Avoid deceptive AI presentation',
        'Monitor misuse',
        'Respond to abuse reports',
        'Comply with applicable law',
      ],
      links: [
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
        {
          label: 'Developer and API Policy',
          href: '/Policies/developer',
        },
      ],
    },
    {
      id: 'api-keys-and-tokens',
      title: '29. API Keys and Tokens',
      body: [
        'You are responsible for securing API keys, tokens, secrets, credentials, webhook secrets, and related authentication materials.',
        'You may not:',
        'SinLess Games LLC may revoke, rotate, suspend, or disable API keys when needed for security, abuse prevention, billing, compliance, or policy enforcement.',
      ],
      bullets: [
        'Share API keys publicly',
        'Commit API keys to public repositories',
        'Embed secret keys in public client-side code',
        'Use API keys without authorization',
        'Sell, transfer, or misuse API keys',
        'Use API keys to exceed plan limits or evade billing',
        'Use API keys to violate these Terms or policies',
      ],
    },
    {
      id: 'marketplace',
      title: '30. Marketplace',
      body: [
        'Aerealith AI may support a marketplace for plugins, integrations, workflows, dashboards, templates, personalities, prompt packs, connectors, or other items.',
        'Marketplace users and publishers must follow:',
        'Marketplace publishers are responsible for their listings, content, code, dependencies, permissions, data handling, documentation, support, pricing, licensing, and compliance.',
        'SinLess Games LLC may review, approve, reject, remove, suspend, disable, delist, restrict, refund, or modify marketplace items when needed for security, privacy, abuse prevention, compliance, quality, user safety, or policy enforcement.',
      ],
      links: [
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
        {
          label: 'Responsible AI Policy',
          href: '/Policies/responsible-ai',
        },
        {
          label: 'Copyright Takedown Policy',
          href: '/Policies/copyright-takedown',
        },
        {
          label: 'Marketplace Policy',
          href: '/Policies/marketplace',
        },
        {
          label: 'Developer and API Policy',
          href: '/Policies/developer',
        },
      ],
    },
    {
      id: 'marketplace-purchases',
      title: '31. Marketplace Purchases',
      body: [
        'Marketplace purchases may be paid, free, subscription-based, usage-based, or one-time purchases.',
        'Marketplace purchases may have additional terms, publisher terms, licenses, support rules, refund rules, and usage limits.',
        'Unless otherwise stated, marketplace purchases may be non-refundable once installed, activated, downloaded, provisioned, consumed, or used.',
        'Marketplace billing is governed by the Billing, Refund, and Cancellation Policy and Payment Processor Compliance Policy.',
      ],
      links: [
        {
          label: 'Billing, Refund, and Cancellation Policy',
          href: '/Policies/billing-refund-cancellation',
        },
        {
          label: 'Payment Processor Compliance Policy',
          href: '/Policies/payment-proccessor-compliance',
        },
      ],
    },
    {
      id: 'plans-subscriptions-and-billing',
      title: '32. Plans, Subscriptions, and Billing',
      body: [
        'Aerealith AI may offer free, paid, usage-based, custom, and enterprise plans.',
        'Plans may include different:',
        'Billing, refunds, cancellations, trials, renewals, taxes, failed payments, and chargebacks are governed by the Billing, Refund, and Cancellation Policy.',
        'By purchasing a paid plan, you authorize SinLess Games LLC and its payment processors to charge applicable fees, taxes, usage charges, renewals, add-ons, and other amounts according to the billing terms shown at checkout or in a written agreement.',
      ],
      bullets: [
        'Features',
        'Usage limits',
        'Storage limits',
        'Compute limits',
        'Vector limits',
        'Memory limits',
        'Automation limits',
        'API limits',
        'Organization features',
        'Marketplace access',
        'Support levels',
        'Compliance features',
        'Deployment options',
      ],
      links: [
        {
          label: 'Billing, Refund, and Cancellation Policy',
          href: '/Policies/billing-refund-cancellation',
        },
      ],
    },
    {
      id: 'automatic-renewal',
      title: '33. Automatic Renewal',
      body: [
        'Paid subscriptions may renew automatically unless canceled before the renewal date.',
        'You are responsible for reviewing subscription terms before purchase and canceling before renewal if you do not want the subscription to continue.',
        'Cancellation stops future renewals but does not automatically provide a refund for past charges unless required by law, stated in the Billing, Refund, and Cancellation Policy, or approved by SinLess Games LLC.',
      ],
      links: [
        {
          label: 'Billing, Refund, and Cancellation Policy',
          href: '/Policies/billing-refund-cancellation',
        },
      ],
    },
    {
      id: 'free-trials-and-promotions',
      title: '34. Free Trials and Promotions',
      body: [
        'Aerealith AI may offer free trials, beta access, early access, discounts, promotional credits, coupons, founder pricing, or special offers.',
        'Promotions may be subject to additional terms.',
        'Unless otherwise stated:',
      ],
      bullets: [
        'Promotions are temporary.',
        'Promotions may apply only to eligible users.',
        'Promotions may not be transferable.',
        'Promotions may not be combined.',
        'Promotions may be revoked for abuse or fraud.',
        'Trial access may convert to a paid subscription if disclosed at signup.',
        'Promotional pricing may renew at the then-current standard price after the promotion ends.',
      ],
    },
    {
      id: 'taxes',
      title: '35. Taxes',
      body: [
        'You are responsible for all applicable taxes, duties, levies, assessments, or governmental charges related to purchases, subscriptions, usage charges, marketplace purchases, payouts, or professional services.',
        'Where required, taxes may be calculated and charged at checkout, on invoices, or through a payment processor.',
        'If you claim tax exemption, you must provide valid documentation before charges are processed.',
      ],
    },
    {
      id: 'failed-payments',
      title: '36. Failed Payments',
      body: [
        'If payment fails, SinLess Games LLC may:',
        'You remain responsible for unpaid amounts.',
      ],
      bullets: [
        'Retry the payment',
        'Request updated billing information',
        'Suspend paid features',
        'Disable add-ons',
        'Pause automations',
        'Restrict API access',
        'Downgrade the account',
        'Cancel the subscription',
        'Restrict marketplace access',
        'Seek collection where permitted',
        'Terminate access where allowed',
      ],
    },
    {
      id: 'chargebacks-and-payment-disputes',
      title: '37. Chargebacks and Payment Disputes',
      body: [
        'If you believe a charge is incorrect, contact billing@sinlessgames.com.',
        'Chargebacks, reversals, or payment disputes may result in account review, suspension, restriction, cancellation, or termination.',
        'SinLess Games LLC may contest chargebacks and provide relevant records to payment processors, banks, card networks, or dispute-resolution systems.',
      ],
      contacts: [
        {
          label: 'Billing',
          email: 'billing@sinlessgames.com',
          href: 'mailto:billing@sinlessgames.com',
        },
      ],
    },
    {
      id: 'service-availability',
      title: '38. Service Availability',
      body: [
        'SinLess Games LLC works to provide reliable service, but Aerealith AI may be unavailable, delayed, degraded, interrupted, suspended, limited, modified, or discontinued.',
        'Causes may include:',
        'Unless a written SLA applies, Aerealith AI does not guarantee uptime, availability, or error-free operation.',
        'Support and availability are governed by the Support Policy and any applicable written agreement.',
      ],
      bullets: [
        'Maintenance',
        'Outages',
        'Provider failures',
        'Security incidents',
        'Abuse prevention',
        'Rate limits',
        'Model provider issues',
        'Integration issues',
        'Billing status',
        'Subscription limits',
        'Legal requirements',
        'Feature changes',
        'Technical constraints',
        'Force majeure events',
      ],
      links: [
        {
          label: 'Support Policy',
          href: '/Policies/support-policy',
        },
      ],
    },
    {
      id: 'scheduled-maintenance',
      title: '39. Scheduled Maintenance',
      body: [
        'SinLess Games LLC may perform scheduled or emergency maintenance.',
        'Maintenance may cause temporary downtime, degraded service, or feature unavailability.',
        'We may provide advance notice when practical.',
        'Emergency maintenance may occur without advance notice when needed to protect users, systems, data, security, or service reliability.',
      ],
    },
    {
      id: 'beta-preview-and-experimental-features',
      title: '40. Beta, Preview, and Experimental Features',
      body: [
        'Aerealith AI may offer beta, preview, early-access, experimental, research, or unreleased features.',
        'These features may be:',
        'You use beta, preview, and experimental features at your own risk.',
      ],
      bullets: [
        'Less stable',
        'Less accurate',
        'Less complete',
        'Less documented',
        'Subject to change',
        'Removed without notice',
        'Excluded from support commitments',
        'Excluded from SLA commitments',
        'Subject to additional restrictions',
      ],
    },
    {
      id: 'feature-changes',
      title: '41. Feature Changes',
      body: [
        'SinLess Games LLC may add, modify, replace, restrict, suspend, or remove features at any time.',
        'Feature changes may occur for:',
        'If a material change affects a paid subscription, we will provide notice where required by law or contract.',
        'Feature changes do not automatically entitle you to a refund unless required by law, stated in the Billing, Refund, and Cancellation Policy, or agreed in writing.',
      ],
      bullets: [
        'Product improvement',
        'Security',
        'Privacy',
        'Legal compliance',
        'Provider changes',
        'Cost management',
        'Abuse prevention',
        'User safety',
        'Technical reasons',
        'Business reasons',
      ],
      links: [
        {
          label: 'Billing, Refund, and Cancellation Policy',
          href: '/Policies/billing-refund-cancellation',
        },
      ],
    },
    {
      id: 'data-export-and-deletion',
      title: '42. Data Export and Deletion',
      body: [
        'Users may be able to export or delete certain data depending on account type, permissions, product functionality, deployment type, organization controls, and applicable law.',
        'Data export and deletion are governed by the Data Policy and Privacy Policy.',
        'Some data may be retained for:',
        'Canceling a subscription does not automatically delete your account or all associated data.',
      ],
      bullets: [
        'Legal compliance',
        'Security',
        'Fraud prevention',
        'Abuse prevention',
        'Billing records',
        'Audit logs',
        'Dispute resolution',
        'Backup rotation',
        'Incident response',
        'Contractual obligations',
        'Organization retention policies',
      ],
      links: [
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy',
        },
      ],
    },
    {
      id: 'suspension-and-termination-by-sinless-games-llc',
      title: '43. Suspension and Termination by SinLess Games LLC',
      body: [
        'SinLess Games LLC may suspend, restrict, or terminate your access to Aerealith AI if:',
        'We may act immediately and without prior notice when necessary.',
      ],
      bullets: [
        'You violate these Terms',
        'You violate related policies',
        'You fail to pay amounts owed',
        'You create security risk',
        'You create privacy risk',
        'You create legal risk',
        'You create abuse risk',
        'You misuse AI features',
        'You misuse APIs',
        'You misuse automations',
        'You misuse integrations',
        'You misuse marketplace items',
        'You infringe intellectual property rights',
        'You violate payment processor rules',
        'Your use may harm users, systems, Aerealith AI, SinLess Games LLC, third parties, or the public',
        'We are required to do so by law, court order, regulator, payment processor, vendor, or other legal obligation',
      ],
    },
    {
      id: 'termination-by-you',
      title: '44. Termination by You',
      body: [
        'You may stop using Aerealith AI at any time.',
        'You may cancel a paid subscription according to the Billing, Refund, and Cancellation Policy.',
        'You may request account deletion according to the Privacy Policy and Data Policy.',
        'You remain responsible for charges incurred before cancellation or termination.',
      ],
      links: [
        {
          label: 'Billing, Refund, and Cancellation Policy',
          href: '/Policies/billing-refund-cancellation',
        },
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
      ],
    },
    {
      id: 'effect-of-termination',
      title: '45. Effect of Termination',
      body: [
        'After suspension, cancellation, or termination:',
        'Sections that by their nature should survive termination will survive, including ownership, data rights, fees owed, disclaimers, limitation of liability, indemnification, dispute resolution, governing law, and enforcement provisions.',
      ],
      bullets: [
        'Access may be limited or disabled.',
        'Paid features may stop.',
        'Automations may pause or stop.',
        'API keys may be disabled.',
        'Integrations may disconnect.',
        'Marketplace items may become unavailable.',
        'Data may be retained or deleted according to applicable policies.',
        'Outstanding invoices remain payable.',
        'These Terms continue to apply to prior use.',
      ],
    },
    {
      id: 'copyright-and-intellectual-property-complaints',
      title: '46. Copyright and Intellectual Property Complaints',
      body: [
        'SinLess Games LLC respects intellectual property rights.',
        'Copyright complaints are governed by the Copyright Takedown Policy.',
        'Copyright notices should be sent to copyright@sinlessgames.com.',
        'Legal notices should be sent to legal@sinlessgames.com.',
        'Before publishing these Terms, confirm the official DMCA agent information and public notice requirements.',
      ],
      contacts: [
        {
          label: 'Copyright',
          email: 'copyright@sinlessgames.com',
          href: 'mailto:copyright@sinlessgames.com',
        },
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
      ],
      links: [
        {
          label: 'Copyright Takedown Policy',
          href: '/Policies/copyright-takedown',
        },
      ],
    },
    {
      id: 'trademark-and-brand-use',
      title: '47. Trademark and Brand Use',
      body: [
        'You may not use SinLess Games LLC names, logos, trademarks, service marks, branding, product names, icons, screenshots, or trade dress without written permission, except where allowed by law or official brand guidelines.',
        'You may not:',
      ],
      bullets: [
        'Misrepresent affiliation with SinLess Games LLC',
        'Impersonate Aerealith AI or SinLess Games LLC',
        'Use confusingly similar marks',
        'Use branding in a way that suggests endorsement without permission',
        'Use branding for scams, phishing, malware, or misleading services',
      ],
    },
    {
      id: 'privacy',
      title: '48. Privacy',
      body: [
        'Privacy is governed by the Privacy Policy.',
        'By using Aerealith AI, you acknowledge that SinLess Games LLC may process personal information as described in the Privacy Policy and related policies.',
        'If you use Aerealith AI on behalf of an organization, you are responsible for providing any required notices and obtaining any required consents from your users, employees, contractors, customers, or other individuals.',
      ],
      links: [
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy',
        },
      ],
    },
    {
      id: 'security',
      title: '49. Security',
      body: [
        'Security is governed by the Security Policy.',
        'You must not use Aerealith AI to compromise accounts, systems, services, networks, models, plugins, APIs, integrations, or data.',
        'You must report suspected security vulnerabilities to security@sinlessgames.com.',
        'Good-faith security research must follow the Security Policy.',
      ],
      contacts: [
        {
          label: 'Security',
          email: 'security@sinlessgames.com',
          href: 'mailto:security@sinlessgames.com',
        },
      ],
      links: [
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
      ],
    },
    {
      id: 'confidentiality',
      title: '50. Confidentiality',
      body: [
        'You may receive non-public information from SinLess Games LLC, such as beta information, enterprise documentation, roadmap details, security notices, incident details, pricing terms, technical information, or confidential support communications.',
        'You must protect confidential information and may not disclose it without permission unless required by law.',
        'Confidentiality obligations may also be governed by a separate written agreement.',
      ],
    },
    {
      id: 'regulated-data-and-sensitive-use',
      title: '51. Regulated Data and Sensitive Use',
      body: [
        'You must not use Aerealith AI for regulated or sensitive data unless your account, workspace, deployment, settings, subscription, and written agreements are appropriate for that use.',
        'Regulated or sensitive contexts may include:',
        'You are responsible for ensuring your use complies with applicable laws, contracts, professional duties, and organization policies.',
      ],
      bullets: [
        'Healthcare',
        'Legal services',
        'Financial services',
        'Insurance',
        'Education',
        'Employment',
        'Criminal justice',
        'Law enforcement',
        'Government services',
        'Biometric data',
        'Children’s data',
        'Payment card data',
        'Critical infrastructure',
        'Safety-critical systems',
      ],
    },
    {
      id: 'children-and-minors',
      title: '52. Children and Minors',
      body: [
        'Aerealith AI is not intended for children unless expressly permitted by applicable law, account settings, organization configuration, and written agreements.',
        'You may not use Aerealith AI to exploit, sexualize, groom, manipulate, endanger, or harm minors.',
        'Use by minors is governed by the applicable Underage Policy, if published.',
      ],
      links: [
        {
          label: 'Underage Policy',
          href: '/Policies/underage-policy',
        },
      ],
    },
    {
      id: 'self-hosted-hybrid-and-air-gapped-deployments',
      title: '53. Self-Hosted, Hybrid, and Air-Gapped Deployments',
      body: [
        'Aerealith AI may support self-hosted, hybrid, private, or air-gapped deployments.',
        'For these deployments, the customer or deployment operator may be responsible for:',
        'SinLess Games LLC may provide official images, packages, licenses, documentation, updates, support, or professional services according to the applicable plan or written agreement.',
        'Self-hosted use does not permit prohibited activity, license violations, policy violations, or misuse of SinLess Games LLC intellectual property.',
      ],
      bullets: [
        'Infrastructure',
        'Networking',
        'Storage',
        'Databases',
        'Cache systems',
        'Backups',
        'Logs',
        'Monitoring',
        'Identity providers',
        'User management',
        'Roles and permissions',
        'Secrets',
        'TLS certificates',
        'Model hosting',
        'Plugin approval',
        'Marketplace access',
        'Security patching',
        'Updates',
        'Incident response',
        'Disaster recovery',
        'Legal compliance',
        'Data retention',
        'Data deletion',
        'Data exports',
        'Air-gap integrity',
      ],
    },
    {
      id: 'enterprise-terms',
      title: '54. Enterprise Terms',
      body: [
        'Enterprise customers may have additional terms in a written agreement.',
        'Enterprise terms may include:',
        'If enterprise documents conflict with these Terms, the signed enterprise documents control only for that enterprise customer and only to the extent of the conflict.',
      ],
      bullets: [
        'Order forms',
        'Master services agreements',
        'Data processing agreements',
        'Business associate agreements, where applicable',
        'Security addenda',
        'Support agreements',
        'SLAs',
        'Statements of work',
        'Custom retention terms',
        'Custom model-routing terms',
        'Custom data-residency terms',
        'Custom subprocessor terms',
        'Self-hosted licensing terms',
        'Air-gapped deployment terms',
      ],
    },
    {
      id: 'export-controls-and-sanctions',
      title: '55. Export Controls and Sanctions',
      body: [
        'You must comply with applicable export control, sanctions, and trade laws.',
        'You may not use Aerealith AI if your use is prohibited by applicable sanctions, embargoes, restricted-party rules, export controls, or trade restrictions.',
        'You may not use Aerealith AI to:',
        'SinLess Games LLC may restrict access where required or appropriate.',
      ],
      bullets: [
        'Evade sanctions',
        'Hide restricted-party involvement',
        'Export controlled technology unlawfully',
        'Provide services to prohibited jurisdictions or parties',
        'Misrepresent location, ownership, or authorization',
        'Use intermediaries to bypass restrictions',
      ],
    },
    {
      id: 'compliance-with-laws',
      title: '56. Compliance With Laws',
      body: [
        'You are responsible for complying with all laws, regulations, rules, orders, contracts, professional obligations, platform rules, and organization policies that apply to your use of Aerealith AI.',
        'This includes laws and rules related to:',
      ],
      bullets: [
        'Privacy',
        'Data protection',
        'AI',
        'Security',
        'Consumer protection',
        'Intellectual property',
        'Employment',
        'Healthcare',
        'Education',
        'Financial services',
        'Insurance',
        'Tax',
        'Export controls',
        'Sanctions',
        'Telecommunications',
        'Marketing',
        'Accessibility',
        'Children’s privacy and safety',
        'Payment processing',
        'Marketplace activity',
        'Professional licensing',
      ],
    },
    {
      id: 'disclaimers',
      title: '57. Disclaimers',
      body: [
        'To the maximum extent permitted by law, Aerealith AI is provided “as is” and “as available.”',
        'SinLess Games LLC disclaims all warranties, express or implied, including warranties of:',
        'SinLess Games LLC does not warrant that Aerealith AI will meet your requirements, produce correct outputs, prevent all harm, prevent all security incidents, or be available without interruption.',
        'Some jurisdictions do not allow certain warranty disclaimers, so some disclaimers may not apply to you.',
      ],
      bullets: [
        'Merchantability',
        'Fitness for a particular purpose',
        'Non-infringement',
        'Accuracy',
        'Reliability',
        'Availability',
        'Security',
        'Error-free operation',
        'Uninterrupted service',
        'Suitability for regulated use',
        'Suitability for high-impact decisions',
        'Suitability for production deployment',
        'Suitability of AI-generated output',
      ],
    },
    {
      id: 'limitation-of-liability',
      title: '58. Limitation of Liability',
      body: [
        'To the maximum extent permitted by law, SinLess Games LLC and its owners, officers, employees, contractors, affiliates, licensors, service providers, and suppliers will not be liable for:',
        'To the maximum extent permitted by law, the total liability of SinLess Games LLC for all claims arising out of or relating to Aerealith AI will not exceed the greater of:',
        'Some jurisdictions do not allow certain liability limitations, so some limitations may not apply to you.',
      ],
      bullets: [
        'Indirect damages',
        'Incidental damages',
        'Special damages',
        'Consequential damages',
        'Punitive damages',
        'Lost profits',
        'Lost revenue',
        'Lost business',
        'Lost goodwill',
        'Lost data',
        'Data corruption',
        'Business interruption',
        'Security incidents caused by user action',
        'Misconfigured automations',
        'Third-party service failures',
        'AI output errors',
        'Unauthorized access caused by compromised user credentials',
        'Use of generated code or configurations without review',
        'Decisions made based on AI output',
      ],
      orderedItems: [
        'The amount you paid to SinLess Games LLC for Aerealith AI in the 12 months before the event giving rise to the claim.',
        'USD $100.',
      ],
    },
    {
      id: 'indemnification',
      title: '59. Indemnification',
      body: [
        'To the maximum extent permitted by law, you agree to defend, indemnify, and hold harmless SinLess Games LLC and its owners, officers, employees, contractors, affiliates, licensors, service providers, and suppliers from and against claims, damages, losses, liabilities, costs, and expenses, including reasonable attorneys’ fees, arising from or related to:',
        'SinLess Games LLC may control the defense of any claim subject to indemnification.',
        'You agree to cooperate with the defense.',
      ],
      bullets: [
        'Your use of Aerealith AI',
        'Your content',
        'Your automations',
        'Your integrations',
        'Your plugins',
        'Your marketplace items',
        'Your API use',
        'Your violation of these Terms',
        'Your violation of related policies',
        'Your violation of law',
        'Your violation of third-party rights',
        'Your misuse of AI output',
        'Your use of generated code, configurations, or workflows',
        'Your organization’s users',
        'Your customer-controlled systems',
        'Your failure to secure accounts, API keys, credentials, or integrations',
      ],
    },
    {
      id: 'dispute-resolution',
      title: '60. Dispute Resolution',
      body: [
        'Before filing a legal claim, you agree to first contact SinLess Games LLC at legal@sinlessgames.com.',
        'You agree to provide a reasonable description of the dispute and allow a reasonable opportunity to resolve it informally.',
        'Before publishing these Terms, SinLess Games LLC should choose one of the following dispute-resolution models with qualified legal counsel:',
        'Do not publish an arbitration or class-action waiver section without legal review.',
      ],
      bullets: [
        'Court litigation only',
        'Arbitration',
        'Arbitration with class-action waiver',
        'Small-claims exception',
        'Consumer-specific regional terms',
        'Enterprise-specific contract terms',
      ],
      contacts: [
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
      ],
    },
    {
      id: 'governing-law',
      title: '61. Governing Law',
      body: [
        'These Terms are governed by the laws of [Insert governing law jurisdiction] without regard to conflict-of-law rules.',
        'Before publishing, confirm the correct governing law jurisdiction with qualified legal counsel.',
      ],
    },
    {
      id: 'venue',
      title: '62. Venue',
      body: [
        'Any dispute arising out of or relating to these Terms or Aerealith AI will be brought in the courts located in [Insert venue and court location] unless a written agreement, arbitration provision, consumer protection law, or applicable mandatory law requires otherwise.',
        'Before publishing, confirm the correct venue with qualified legal counsel.',
      ],
    },
    {
      id: 'injunctive-relief',
      title: '63. Injunctive Relief',
      body: [
        'Nothing in these Terms prevents SinLess Games LLC from seeking injunctive or equitable relief to protect:',
      ],
      bullets: [
        'Intellectual property',
        'Confidential information',
        'Security',
        'Systems',
        'Users',
        'Data',
        'Marketplace integrity',
        'Payment systems',
        'Legal rights',
        'Platform integrity',
      ],
    },
    {
      id: 'force-majeure',
      title: '64. Force Majeure',
      body: [
        'SinLess Games LLC is not responsible for delay or failure to perform caused by events beyond its reasonable control.',
        'Force majeure events may include:',
      ],
      bullets: [
        'Natural disasters',
        'War',
        'Terrorism',
        'Civil unrest',
        'Labor disputes',
        'Government action',
        'Internet outages',
        'Power outages',
        'Cloud provider outages',
        'Payment processor outages',
        'AI provider outages',
        'Cyberattacks',
        'Security incidents',
        'Supply chain failures',
        'Pandemics',
        'Emergencies',
        'Legal restrictions',
        'Other events beyond reasonable control',
      ],
    },
    {
      id: 'assignment',
      title: '65. Assignment',
      body: [
        'You may not assign or transfer these Terms or your rights under these Terms without written permission from SinLess Games LLC.',
        'SinLess Games LLC may assign these Terms in connection with a merger, acquisition, reorganization, financing, sale of assets, corporate transaction, or transfer of Aerealith AI.',
      ],
    },
    {
      id: 'no-waiver',
      title: '66. No Waiver',
      body: [
        'Failure to enforce any part of these Terms does not waive the right to enforce that part later.',
        'Any waiver must be in writing and signed by SinLess Games LLC.',
      ],
    },
    {
      id: 'severability',
      title: '67. Severability',
      body: [
        'If any part of these Terms is found unenforceable, the remaining parts will remain in effect.',
        'The unenforceable part will be modified to the minimum extent necessary to make it enforceable, if permitted by law.',
      ],
    },
    {
      id: 'entire-agreement',
      title: '68. Entire Agreement',
      body: [
        'These Terms, together with incorporated policies and any applicable written agreement, form the entire agreement between you and SinLess Games LLC regarding Aerealith AI.',
        'These Terms replace prior or contemporaneous understandings about Aerealith AI unless a signed written agreement says otherwise.',
      ],
    },
    {
      id: 'notices',
      title: '69. Notices',
      body: [
        'SinLess Games LLC may provide notices through:',
        'You are responsible for keeping account and billing contact information current.',
        'Formal legal notices to SinLess Games LLC should be sent to legal@sinlessgames.com.',
        'Before publishing, insert any required physical mailing address for formal notices.',
      ],
      bullets: [
        'The service',
        'Account settings',
        'Email',
        'Documentation',
        'Legal notices page',
        'Billing portal',
        'Status page',
        'Support portal',
        'Release notes',
        'Other reasonable methods',
      ],
      contacts: [
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
      ],
    },
    {
      id: 'contact',
      title: '70. Contact',
      body: [
        'Questions about these Terms may be sent to legal@sinlessgames.com.',
        'General support questions may be sent to support@sinlessgames.com.',
        'Billing questions may be sent to billing@sinlessgames.com.',
        'Privacy questions may be sent to privacy@sinlessgames.com.',
        'Security issues may be sent to security@sinlessgames.com.',
        'Before publishing, confirm these email aliases exist and are monitored.',
      ],
      contacts: [
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
        {
          label: 'Support',
          email: 'support@sinlessgames.com',
          href: 'mailto:support@sinlessgames.com',
        },
        {
          label: 'Billing',
          email: 'billing@sinlessgames.com',
          href: 'mailto:billing@sinlessgames.com',
        },
        {
          label: 'Privacy',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
        {
          label: 'Security',
          email: 'security@sinlessgames.com',
          href: 'mailto:security@sinlessgames.com',
        },
      ],
    },
    {
      id: 'publication-checklist',
      title: '71. Publication Checklist',
      body: ['Before publishing these Terms, complete the following:'],
      bullets: [
        'Confirm official company name: SinLess Games LLC',
        'Confirm official product name: Aerealith AI',
        'Confirm physical business address',
        'Confirm official legal notice email',
        'Confirm support email',
        'Confirm billing email',
        'Confirm privacy email',
        'Confirm security email',
        'Confirm copyright email',
        'Confirm governing law jurisdiction',
        'Confirm venue',
        'Decide whether arbitration will be used',
        'Decide whether a class-action waiver will be used',
        'Confirm subscription renewal language',
        'Confirm cancellation flow',
        'Confirm refund policy alignment',
        'Confirm pricing page alignment',
        'Confirm plan names and tiers',
        'Confirm marketplace terms',
        'Confirm developer/API terms',
        'Confirm self-hosted license terms',
        'Confirm air-gapped deployment terms',
        'Confirm enterprise agreement precedence',
        'Confirm DMCA designated agent information',
        'Confirm data ownership promise',
        'Confirm no-sale data promise',
        'Confirm AI limitation language',
        'Confirm professional advice disclaimer',
        'Confirm high-risk-use restrictions',
        'Confirm warranty disclaimers',
        'Confirm liability cap',
        'Confirm indemnification language',
        'Confirm regional consumer-law requirements',
        'Confirm accessibility obligations',
        'Confirm children/minors policy',
        'Confirm export control and sanctions requirements',
        'Have qualified legal counsel review these Terms',
      ],
    },
    {
      id: 'legal-review-notice',
      title: '72. Legal Review Notice',
      body: [
        'These Terms are a draft template and should be reviewed by qualified legal counsel before publication.',
        'Terms of use, consumer protection, subscription renewal, cancellation, refunds, privacy, data ownership, AI output liability, professional advice disclaimers, intellectual property, marketplace liability, API use, self-hosted licensing, arbitration, class-action waivers, governing law, venue, export controls, sanctions, children’s privacy, accessibility, and regional consumer-rights requirements may vary by jurisdiction, customer type, deployment model, and written agreement.',
      ],
    },
  ],
} satisfies PolicyDocument;

export default termsOfUsePolicy;
