import type { PolicyDocument } from '../../types';

export const underagePolicy = {
  slug: 'underage',
  path: '/Policies/underage',
  meta: {
    title: 'Underage Policy',
    description:
      'Explains how Aerealith AI handles minors, age-restricted content, parental controls, guardian consent, child safety, age assurance, and underage account protections.',
    effectiveDate: '2026-05-19',
    lastUpdated: '2026-05-19',
    owner: 'SinLess Games LLC',
    status: 'draft',
  },
  relatedPolicies: [
    {
      label: 'Terms of Use',
      href: '/Policies/terms-of-use',
    },
    {
      label: 'Privacy Policy',
      href: '/Policies/privacy',
    },
    {
      label: 'Data Policy',
      href: '/Policies/data',
    },
    {
      label: 'Security Policy',
      href: '/Policies/security-policy',
    },
    {
      label: 'Acceptable Use Policy',
      href: '/Policies/acceptable-use',
    },
    {
      label: 'AI Transparency Policy',
      href: '/Policies/ai-transparency',
    },
    {
      label: 'Responsible AI Policy',
      href: '/Policies/responsible-ai',
    },
    {
      label: 'Cookie and Tracking Policy',
      href: '/Policies/cookie-tracking',
    },
    {
      label: 'Billing, Refund, and Cancellation Policy',
      href: '/Policies/billing-refund-cancellation',
    },
    {
      label: 'Copyright Takedown Policy',
      href: '/Policies/copyright-takedown',
    },
    {
      label: 'Incident Notification Policy',
      href: '/Policies/incident-notification',
    },
    {
      label: 'Payment Processor Compliance Policy',
      href: '/Policies/payment-proccessor-compliance',
    },
    {
      label: 'Subprocessor and Vendor List',
      href: '/Policies/subprocessor-vendor-list',
    },
    {
      label: 'Support Policy',
      href: '/Policies/support-policy',
    },
    {
      label: 'User-Generated Content Policy',
      href: '/Policies/user-generated-content',
    },
    {
      label: 'Marketplace Policy',
      href: '/Policies/marketplace',
    },
    {
      label: 'Developer and API Policy',
      href: '/Policies/developer',
    },
  ],
  sections: [
    {
      id: 'purpose',
      title: '1. Purpose',
      body: [
        'This Underage Policy explains how SinLess Games LLC handles minors, age-restricted content, parental controls, guardian consent, child safety, and underage account protections for Aerealith AI.',
        'Aerealith AI is designed to help users think, create, automate, analyze, monitor, and act across connected systems. Because some Aerealith AI features may involve AI conversations, memory, files, integrations, automations, marketplace items, user-generated content, analytics, and connected services, minors require additional protections.',
        'SinLess Games LLC will use lawful and verifiable means to help protect age-restricted content and will provide parental or guardian controls for minors where supported and legally required.',
      ],
    },
    {
      id: 'scope',
      title: '2. Scope',
      body: [
        'This policy applies to Aerealith AI services, including:',
        'This policy applies to:',
      ],
      bullets: [
        'Websites',
        'Web applications',
        'Desktop applications',
        'Mobile applications',
        'Browser extensions',
        'APIs',
        'Developer tools',
        'Documentation sites',
        'Marketplace features',
        'Plugins',
        'Automations',
        'Integrations',
        'Dashboards',
        'Analytics features',
        'AI memory features',
        'Support systems',
        'Billing systems',
        'Organization workspaces',
        'Cloud-hosted deployments',
        'Self-hosted deployments, where applicable',
        'Hybrid deployments, where applicable',
        'Air-gapped deployments, where applicable',
        'Visitors',
        'Individual users',
        'Minors',
        'Parents and legal guardians',
        'Organization users',
        'Workspace administrators',
        'School or education administrators',
        'Developers',
        'Marketplace publishers',
        'API users',
        'Enterprise customers',
        'Anyone who accesses or uses Aerealith AI through an account, workspace, integration, automation, shared agent, plugin, API key, or connected service',
      ],
    },
    {
      id: 'relationship-to-other-policies',
      title: '3. Relationship to Other Policies',
      body: [
        'This policy works together with other Aerealith AI policies, including:',
        'If there is a conflict between this policy and a written agreement signed by SinLess Games LLC, the written agreement controls only to the extent of that conflict.',
      ],
      links: [
        {
          label: 'Terms of Use',
          href: '/Policies/terms-of-use',
        },
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
        {
          label: 'AI Transparency Policy',
          href: '/Policies/ai-transparency',
        },
        {
          label: 'Responsible AI Policy',
          href: '/Policies/responsible-ai',
        },
        {
          label: 'Cookie and Tracking Policy',
          href: '/Policies/cookie-tracking',
        },
        {
          label: 'Billing, Refund, and Cancellation Policy',
          href: '/Policies/billing-refund-cancellation',
        },
        {
          label: 'Copyright Takedown Policy',
          href: '/Policies/copyright-takedown',
        },
        {
          label: 'Incident Notification Policy',
          href: '/Policies/incident-notification',
        },
        {
          label: 'Payment Processor Compliance Policy',
          href: '/Policies/payment-proccessor-compliance',
        },
        {
          label: 'Subprocessor and Vendor List',
          href: '/Policies/subprocessor-vendor-list',
        },
        {
          label: 'Support Policy',
          href: '/Policies/support-policy',
        },
        {
          label: 'User-Generated Content Policy',
          href: '/Policies/user-generated-content',
        },
        {
          label: 'Marketplace Policy',
          href: '/Policies/marketplace',
        },
        {
          label: 'Developer and API Policy',
          href: '/Policies/developer',
        },
      ],
    },
    {
      id: 'definitions',
      title: '4. Definitions',
      body: ['For this policy:'],
      bullets: [
        '“Minor” means a person who has not reached the age of majority in their jurisdiction.',
        '“Child” means a minor under the age threshold where parental consent or special child-privacy protections are required by applicable law.',
        '“Teen” means a minor who is old enough to use certain online services with restrictions but has not reached the age of majority.',
        '“Parent” or “guardian” means a person with legal authority to act for a minor.',
        '“Age-restricted content” means content, features, services, marketplace items, integrations, automations, or materials that are not appropriate for minors or may legally require age verification, parental controls, restricted access, or additional safeguards.',
        '“Age assurance” means a method used to estimate, verify, or confirm a user’s age or age range.',
        '“Parental controls” means account, workspace, device, organization, or product settings that allow a parent, guardian, school, or authorized administrator to manage a minor’s access, privacy, safety, spending, communication, content, memory, integrations, and automations.',
      ],
    },
    {
      id: 'core-commitments',
      title: '5. Core Commitments',
      body: [
        'SinLess Games LLC intends to follow these underage safety commitments for Aerealith AI:',
      ],
      orderedItems: [
        'Protect minors from inappropriate and age-restricted content.',
        'Use lawful and verifiable age-assurance methods where required or appropriate.',
        'Provide parental or guardian controls for minors where supported and legally required.',
        'Avoid collecting unnecessary data from minors.',
        'Avoid selling user data, including minors’ data.',
        'Avoid using minors’ private data outside legitimate service business logic and approved research purposes.',
        'Restrict high-risk AI features for minors.',
        'Restrict mature, sexual, exploitative, violent, harmful, or regulated content for minors.',
        'Restrict unsafe automations, public sharing, marketplace access, and integrations for minors where appropriate.',
        'Give parents, guardians, and authorized administrators tools to manage minor accounts where supported.',
        'Treat child safety reports with high priority.',
        'Remove or restrict underage access when required by law, policy, or safety needs.',
      ],
    },
    {
      id: 'minimum-age',
      title: '6. Minimum Age',
      body: [
        'Aerealith AI may require users to meet a minimum age before creating an account or using certain features.',
        'Before publishing this policy, SinLess Games LLC should confirm the official minimum age for Aerealith AI.',
        'Recommended default:',
        'Local law may require different age thresholds.',
      ],
      bullets: [
        'Users under 13 may not create or use personal Aerealith AI accounts unless a legally valid parent, guardian, school, or organization arrangement is in place.',
        'Users ages 13 to 17 may use Aerealith AI only with age-appropriate restrictions and any required parent, guardian, school, or organization consent.',
        'Users must be at least 18, or the age of majority in their jurisdiction, to access age-restricted content, mature content, unrestricted marketplace purchases, payment features, or other adult-only features.',
      ],
    },
    {
      id: 'age-restricted-content',
      title: '7. Age-Restricted Content',
      body: [
        'Aerealith AI may restrict access to content or features that are not appropriate for minors.',
        'Age-restricted content or features may include:',
        'SinLess Games LLC may block, hide, limit, label, age-gate, or remove age-restricted content.',
      ],
      bullets: [
        'Sexually explicit content',
        'Adult or erotic content',
        'Mature companionship or romantic persona modes',
        'Graphic violence',
        'Self-harm content that is not safety-oriented',
        'Gambling-related content',
        'Alcohol-related content',
        'Nicotine or tobacco-related content',
        'Recreational drug-related content',
        'Regulated goods or services',
        'Adult marketplace items',
        'Mature plugins, personalities, workflows, templates, or prompt packs',
        'High-risk financial, legal, medical, insurance, employment, or housing decision workflows',
        'Dangerous challenges or risky behavior',
        'Unsafe cybersecurity content',
        'Destructive infrastructure automations',
        'Public publishing features that expose minors to unwanted contact',
        'Direct messaging or community features that are not age-appropriate',
        'Any other feature restricted by law, platform policy, payment processor rules, or SinLess Games LLC policy',
      ],
    },
    {
      id: 'age-assurance',
      title: '8. Age Assurance',
      body: [
        'SinLess Games LLC may use lawful and verifiable age-assurance methods to protect minors and restrict age-restricted content.',
        'Age-assurance methods may include:',
        'SinLess Games LLC should use the least intrusive method reasonably suitable for the risk level.',
        'Age-assurance data should be minimized, protected, retained only as needed, and deleted or de-identified where appropriate.',
      ],
      bullets: [
        'Date-of-birth entry',
        'Account-level age declaration',
        'Parent or guardian confirmation',
        'School or organization confirmation',
        'Payment-method verification, where lawful and appropriate',
        'Identity provider claims',
        'Third-party age-assurance providers',
        'Government ID verification, where legally required and proportionate',
        'Device, app-store, or platform age settings, where available',
        'Risk-based checks',
        'Manual review in limited cases',
        'Other lawful methods appropriate to the feature and jurisdiction',
      ],
    },
    {
      id: 'age-verification-data',
      title: '9. Age Verification Data',
      body: [
        'Age verification may involve sensitive personal information.',
        'SinLess Games LLC should limit collection and retention of age verification data.',
        'Age verification data may include:',
        'SinLess Games LLC should avoid storing full identity documents unless legally required, expressly disclosed, and supported by appropriate security controls.',
        'If a third-party age-assurance provider is used, that provider should be reviewed and listed in the Subprocessor and Vendor List, where applicable.',
      ],
      bullets: [
        'Date of birth',
        'Age range',
        'Parent or guardian consent record',
        'Verification status',
        'Verification timestamp',
        'Verification provider metadata',
        'Identity proofing result',
        'Limited account metadata',
        'Audit record of verification',
      ],
      links: [
        {
          label: 'Subprocessor and Vendor List',
          href: '/Policies/subprocessor-vendor-list',
        },
      ],
    },
    {
      id: 'parental-and-guardian-controls',
      title: '10. Parental and Guardian Controls',
      body: [
        'Aerealith AI may provide parental or guardian controls where supported.',
        'Parental controls may allow a parent or guardian to:',
        'Parental controls may vary by product, plan, platform, deployment, jurisdiction, and technical availability.',
      ],
      bullets: [
        'Approve or deny account creation',
        'Review account settings',
        'Set age-appropriate content restrictions',
        'Disable mature content',
        'Disable adult persona modes',
        'Disable public sharing',
        'Disable marketplace access',
        'Disable purchases',
        'Disable payment methods',
        'Disable third-party integrations',
        'Disable automations',
        'Disable external tool use',
        'Disable file uploads',
        'Disable AI memory',
        'Review or delete memory entries',
        'Set retention limits',
        'Manage communication settings',
        'Manage notification settings',
        'Restrict community access',
        'Restrict developer tools',
        'Restrict API access',
        'Request data export',
        'Request data deletion',
        'Report safety concerns',
        'Remove the minor’s account, where legally permitted',
      ],
    },
    {
      id: 'guardian-managed-accounts',
      title: '11. Guardian-Managed Accounts',
      body: [
        'Aerealith AI may support guardian-managed accounts for minors.',
        'A guardian-managed account may include:',
        'The parent or guardian is responsible for supervising the minor’s use and ensuring the account is used lawfully and safely.',
      ],
      bullets: [
        'Parent or guardian approval',
        'Guardian contact information',
        'Minor profile settings',
        'Age-appropriate defaults',
        'Restricted AI features',
        'Restricted marketplace access',
        'Restricted payment access',
        'Restricted integrations',
        'Restricted automations',
        'Restricted public sharing',
        'Restricted memory behavior',
        'Additional safety filters',
        'Guardian notification settings',
        'Guardian account recovery process',
      ],
    },
    {
      id: 'school-and-education-use',
      title: '12. School and Education Use',
      body: [
        'Aerealith AI may support school, education, or youth-organization use only under appropriate controls.',
        'School or education use may require:',
        'Schools and educational organizations are responsible for ensuring they have authority to provide student data and manage student accounts.',
      ],
      bullets: [
        'School authorization',
        'Parent or guardian consent, where required',
        'Student privacy protections',
        'Data processing agreement',
        'Restricted advertising',
        'Restricted profiling',
        'Restricted marketplace access',
        'Restricted public sharing',
        'Restricted AI memory',
        'Restricted integrations',
        'Restricted automations',
        'Administrator controls',
        'Teacher or staff supervision',
        'Age-appropriate content settings',
        'Data retention rules',
        'Export and deletion workflows',
        'Compliance with applicable education privacy laws',
      ],
    },
    {
      id: 'minor-account-defaults',
      title: '13. Minor Account Defaults',
      body: [
        'Minor accounts should use safer defaults where practical.',
        'Safer defaults may include:',
      ],
      bullets: [
        'Mature content disabled',
        'Adult persona modes disabled',
        'Public sharing disabled',
        'Marketplace purchases disabled',
        'Payment methods disabled',
        'External integrations disabled unless approved',
        'Automations disabled or approval-gated',
        'API access disabled',
        'Developer tools disabled',
        'Memory disabled or limited unless approved',
        'Sensitive data collection minimized',
        'Data retention limited',
        'Targeted advertising disabled',
        'Direct contact from unknown users disabled',
        'Community access restricted',
        'Safety reporting made easy',
        'Parent, guardian, or administrator controls enabled where applicable',
      ],
    },
    {
      id: 'ai-features-for-minors',
      title: '14. AI Features for Minors',
      body: [
        'Aerealith AI may restrict AI features for minors.',
        'Restricted AI behavior for minors may include:',
        'Aerealith AI may provide age-appropriate educational, creative, productivity, accessibility, and safety-oriented assistance for minors where allowed.',
      ],
      bullets: [
        'Sexual or erotic content',
        'Romantic or adult companionship modes',
        'Highly graphic violent content',
        'Manipulative persuasion',
        'Unsafe mental health responses',
        'Harmful self-harm content',
        'Eating disorder encouragement',
        'Harassment or bullying assistance',
        'Deceptive impersonation',
        'Gambling assistance',
        'Adult marketplace recommendations',
        'Regulated product recommendations',
        'High-risk financial, legal, medical, or employment decision-making',
        'Dangerous activity instructions',
        'Unsafe cybersecurity instructions',
        'Destructive infrastructure actions',
        'Unsuitable synthetic media generation',
      ],
    },
    {
      id: 'ai-memory-for-minors',
      title: '15. AI Memory for Minors',
      body: [
        'AI memory involving minors requires stronger safeguards.',
        'For minor accounts, Aerealith AI may:',
        'Memory involving minors should not be used to manipulate, exploit, profile, or target minors in harmful ways.',
      ],
      bullets: [
        'Disable memory by default',
        'Require parent, guardian, school, or organization approval for memory',
        'Limit memory to low-risk preferences',
        'Avoid sensitive or regulated memory',
        'Avoid storing secrets or credentials',
        'Allow guardian review',
        'Allow guardian deletion',
        'Allow administrator review for school or organization accounts',
        'Apply shorter retention periods',
        'Apply stronger sensitivity labels',
        'Prevent memory from enabling mature content',
      ],
    },
    {
      id: 'advertising-and-tracking-for-minors',
      title: '16. Advertising and Tracking for Minors',
      body: [
        'Aerealith AI should not knowingly use minors’ private data, prompts, files, memory, organization data, or workspace data for third-party targeted advertising.',
        'For minors, Aerealith AI should avoid:',
        'Cookie and tracking behavior is governed by the Cookie and Tracking Policy.',
      ],
      bullets: [
        'Behavioral advertising based on private content',
        'Profiling for unrelated advertising',
        'Sale of personal information',
        'Sharing for targeted advertising where prohibited',
        'Unnecessary tracking',
        'Hidden tracking',
        'Mature-content advertising',
        'Regulated-product advertising',
      ],
      links: [
        {
          label: 'Cookie and Tracking Policy',
          href: '/Policies/cookie-tracking',
        },
      ],
    },
    {
      id: 'purchases-and-billing-by-minors',
      title: '17. Purchases and Billing by Minors',
      body: [
        'Minors may not purchase paid plans, add-ons, marketplace items, usage packages, professional services, or other paid Aerealith AI services unless permitted by law and authorized by a parent, guardian, school, organization, or account administrator.',
        'SinLess Games LLC may restrict minors from:',
        'Billing and payment behavior is governed by the Billing, Refund, and Cancellation Policy and Payment Processor Compliance Policy.',
      ],
      bullets: [
        'Adding payment methods',
        'Starting paid subscriptions',
        'Buying marketplace items',
        'Buying add-ons',
        'Increasing usage limits',
        'Enabling paid APIs',
        'Enabling paid automations',
        'Making publisher accounts',
        'Receiving marketplace payouts',
      ],
      links: [
        {
          label: 'Billing, Refund, and Cancellation Policy',
          href: '/Policies/billing-refund-cancellation',
        },
        {
          label: 'Payment Processor Compliance Policy',
          href: '/Policies/payment-proccessor-compliance',
        },
      ],
    },
    {
      id: 'public-sharing-and-communication',
      title: '18. Public Sharing and Communication',
      body: [
        'Minor accounts may have restricted public sharing and communication features.',
        'Restricted features may include:',
        'Where these features are available to minors, they should include appropriate privacy, safety, moderation, and guardian or administrator controls.',
      ],
      bullets: [
        'Public chat sharing',
        'Public dashboards',
        'Public profiles',
        'Public marketplace publishing',
        'Public comments',
        'Reviews',
        'Community spaces',
        'Direct messages',
        'External communications',
        'Third-party chat integrations',
        'Web publishing',
        'Public API endpoints',
      ],
    },
    {
      id: 'marketplace-access-for-minors',
      title: '19. Marketplace Access for Minors',
      body: [
        'Minor accounts may have limited marketplace access.',
        'Marketplace restrictions may include:',
        'Marketplace publishers may not target minors with inappropriate, deceptive, exploitative, or age-restricted marketplace items.',
      ],
      bullets: [
        'Blocking adult marketplace items',
        'Blocking mature personalities',
        'Blocking unsafe automations',
        'Blocking paid purchases',
        'Blocking developer publishing',
        'Blocking plugins with broad data permissions',
        'Blocking plugins with external network access',
        'Blocking plugins with payment access',
        'Blocking plugins that process sensitive data',
        'Requiring parent, guardian, school, or organization approval',
        'Allowing only age-appropriate official items',
      ],
    },
    {
      id: 'developer-and-api-access-for-minors',
      title: '20. Developer and API Access for Minors',
      body: [
        'Developer and API access may be restricted for minors.',
        'Minor accounts may be blocked from:',
        'Exceptions may be allowed for supervised education, school, organization, or guardian-approved learning environments.',
      ],
      bullets: [
        'Creating API keys',
        'Publishing plugins',
        'Creating marketplace listings',
        'Running paid API workloads',
        'Creating public developer apps',
        'Creating unsafe automations',
        'Connecting high-risk integrations',
        'Accessing security-sensitive tools',
        'Accessing destructive infrastructure tools',
      ],
    },
    {
      id: 'child-safety-prohibitions',
      title: '21. Child Safety Prohibitions',
      body: [
        'Users may not use Aerealith AI to exploit, sexualize, groom, manipulate, endanger, abuse, harass, threaten, or harm minors.',
        'Prohibited activity includes:',
        'SinLess Games LLC may report apparent child exploitation or imminent harm to appropriate authorities where required or appropriate.',
      ],
      bullets: [
        'Child sexual abuse material',
        'Sexual exploitation of minors',
        'Grooming',
        'Predatory behavior',
        'Sexualized conversations with minors',
        'Non-consensual intimate imagery',
        'Sextortion',
        'Trafficking',
        'Encouraging minors to hide unsafe activity from parents or guardians',
        'Encouraging self-harm',
        'Encouraging eating disorders',
        'Encouraging dangerous challenges',
        'Bullying or harassment of minors',
        'Doxxing minors',
        'Impersonating minors for deceptive purposes',
        'Collecting minors’ personal information without proper authorization',
        'Targeting minors with age-restricted goods or services',
      ],
    },
    {
      id: 'self-harm-and-crisis-safety-for-minors',
      title: '22. Self-Harm and Crisis Safety for Minors',
      body: [
        'Aerealith AI is not an emergency service.',
        'If a minor appears to be at immediate risk of self-harm, suicide, abuse, exploitation, or danger, users should contact emergency services, a trusted adult, local authorities, or an appropriate crisis support service.',
        'Aerealith AI may provide supportive, safety-oriented information, but it does not replace professional help, emergency response, parental supervision, or qualified care.',
      ],
    },
    {
      id: 'parent-and-guardian-requests',
      title: '23. Parent and Guardian Requests',
      body: [
        'Parents or legal guardians may contact SinLess Games LLC regarding a minor’s account or data.',
        'Requests may include:',
        'SinLess Games LLC may need to verify the requester’s identity, authority, and relationship to the minor before acting on a request.',
      ],
      bullets: [
        'Account review',
        'Consent review',
        'Data access',
        'Data correction',
        'Data deletion',
        'Memory deletion',
        'Export request',
        'Restriction request',
        'Safety report',
        'Billing dispute',
        'Account closure',
      ],
      contacts: [
        {
          label: 'Privacy',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
        {
          label: 'AI safety',
          email: 'safety@sinlessgames.com',
          href: 'mailto:safety@sinlessgames.com',
        },
        {
          label: 'Support',
          email: 'support@sinlessgames.com',
          href: 'mailto:support@sinlessgames.com',
        },
      ],
    },
    {
      id: 'verification-of-parent-or-guardian-authority',
      title: '24. Verification of Parent or Guardian Authority',
      body: [
        'SinLess Games LLC may require verification before granting access to a minor’s account or data.',
        'Verification may include:',
        'SinLess Games LLC may deny requests where it cannot reasonably verify authority or where disclosure would create legal, privacy, safety, or security risk.',
      ],
      bullets: [
        'Parent or guardian identity verification',
        'Confirmation of legal authority',
        'Account ownership verification',
        'Email verification',
        'Billing verification, where applicable',
        'School or organization confirmation',
        'Signed request, where appropriate',
        'Other lawful verification methods',
      ],
    },
    {
      id: 'data-collection-from-minors',
      title: '25. Data Collection From Minors',
      body: [
        'Aerealith AI should minimize data collection from minors.',
        'Data collected from minors may include:',
        'SinLess Games LLC should collect only the information reasonably needed to provide, secure, support, and improve age-appropriate Aerealith AI services.',
      ],
      bullets: [
        'Account information',
        'Parent or guardian consent records',
        'Age range or age verification status',
        'Prompts and messages',
        'Uploaded content',
        'Settings',
        'Usage metadata',
        'Support requests',
        'Security logs',
        'Billing records, where applicable',
        'School or organization metadata, where applicable',
      ],
    },
    {
      id: 'data-use-for-minors',
      title: '26. Data Use for Minors',
      body: [
        'Data from minors may be used for legitimate service business logic and approved research purposes, subject to stronger safeguards.',
        'Permitted uses may include:',
        'Minor data should not be sold.',
        'Minor data should not be used for unrelated products or unrelated advertising.',
      ],
      bullets: [
        'Providing the service',
        'Maintaining account access',
        'Enforcing age restrictions',
        'Providing parental controls',
        'Supporting safety filters',
        'Preventing abuse',
        'Protecting security',
        'Responding to support requests',
        'Complying with law',
        'Improving safety and reliability',
        'Debugging product issues',
        'Managing school or organization accounts',
        'Maintaining audit records where required',
      ],
    },
    {
      id: 'data-retention-for-minors',
      title: '27. Data Retention for Minors',
      body: [
        'Data involving minors should not be retained longer than reasonably needed.',
        'Retention may depend on:',
        'Parents, guardians, and authorized administrators may request deletion where supported and legally permitted.',
      ],
      bullets: [
        'Account status',
        'Parent or guardian settings',
        'School or organization settings',
        'Legal requirements',
        'Safety needs',
        'Security needs',
        'Billing obligations',
        'Audit obligations',
        'Backup rotation',
        'Incident response needs',
        'Written agreements',
      ],
    },
    {
      id: 'deletion-of-minor-data',
      title: '28. Deletion of Minor Data',
      body: [
        'Parents, guardians, minors, schools, or authorized administrators may request deletion of certain minor data where supported and legally permitted.',
        'Deletion may include:',
        'Some data may be retained where required or permitted for:',
      ],
      bullets: [
        'Account deletion',
        'File deletion',
        'Memory deletion',
        'Conversation deletion',
        'Integration disconnection',
        'Automation deletion',
        'Marketplace restriction',
        'Public content removal',
        'Legal compliance',
        'Security',
        'Fraud prevention',
        'Abuse prevention',
        'Billing records',
        'Audit logs',
        'Dispute resolution',
        'Backup rotation',
        'Incident response',
        'Contractual obligations',
        'School or organization retention policies',
      ],
    },
    {
      id: 'age-misrepresentation',
      title: '29. Age Misrepresentation',
      body: [
        'Users may not misrepresent their age or another person’s age to access Aerealith AI or age-restricted features.',
        'Users may not:',
        'SinLess Games LLC may suspend, restrict, or terminate accounts that bypass age restrictions.',
      ],
      bullets: [
        'Lie about age',
        'Help minors bypass age gates',
        'Use another person’s account to access restricted content',
        'Use a parent or guardian account without permission',
        'Use false identity information',
        'Use VPNs, proxies, or technical tools to bypass age restrictions',
        'Create accounts for minors without required authorization',
        'Publish or distribute age-restricted content to minors',
      ],
    },
    {
      id: 'account-restrictions-and-enforcement',
      title: '30. Account Restrictions and Enforcement',
      body: [
        'If SinLess Games LLC believes an account belongs to a minor or is being used by a minor in violation of this policy, it may:',
      ],
      bullets: [
        'Request age confirmation',
        'Request parent or guardian consent',
        'Restrict features',
        'Disable mature content',
        'Disable public sharing',
        'Disable marketplace access',
        'Disable payment access',
        'Disable integrations',
        'Disable automations',
        'Disable API access',
        'Disable memory',
        'Suspend the account',
        'Delete the account where appropriate',
        'Notify a parent, guardian, school, or organization administrator where appropriate',
        'Preserve records where required',
        'Report child safety concerns to appropriate authorities where required or appropriate',
      ],
    },
    {
      id: 'appeals',
      title: '31. Appeals',
      body: [
        'If a user believes an age restriction, account restriction, or underage enforcement action was applied in error, they may contact support@sinlessgames.com.',
        'Appeals should include:',
        'SinLess Games LLC may require verification before changing an age-related restriction.',
        'Submitting an appeal does not guarantee reversal.',
      ],
      bullets: [
        'Account email',
        'Organization name, if applicable',
        'Description of the restriction',
        'Reason the restriction is believed to be incorrect',
        'Supporting information',
        'Parent or guardian contact, if applicable',
      ],
      contacts: [
        {
          label: 'Support',
          email: 'support@sinlessgames.com',
          href: 'mailto:support@sinlessgames.com',
        },
      ],
    },
    {
      id: 'organization-and-enterprise-controls',
      title: '32. Organization and Enterprise Controls',
      body: [
        'Organizations may configure additional controls for minors.',
        'Organization controls may include:',
        'Organization administrators are responsible for configuring Aerealith AI according to their legal, security, privacy, compliance, and child-safety requirements.',
      ],
      bullets: [
        'Age-based access restrictions',
        'Role-based access controls',
        'Approved models',
        'Blocked models',
        'Approved tools',
        'Blocked tools',
        'Approved integrations',
        'Marketplace allowlists',
        'Marketplace blocklists',
        'Memory restrictions',
        'Retention controls',
        'Public sharing restrictions',
        'Human approval gates',
        'Automation restrictions',
        'Audit log retention',
        'Data export restrictions',
        'Research-use restrictions',
        'Model training restrictions',
        'Sensitive data controls',
        'Compliance policies',
        'School-specific controls',
        'Guardian-access workflows',
        'Custom safety rules',
      ],
    },
    {
      id: 'self-hosted-hybrid-and-air-gapped-deployments',
      title: '33. Self-Hosted, Hybrid, and Air-Gapped Deployments',
      body: [
        'For self-hosted, hybrid, private, or air-gapped deployments, the deploying organization may control much of the underage safety environment.',
        'The deploying organization may be responsible for:',
        'SinLess Games LLC may provide official defaults, documentation, and supported features, but self-hosted operators remain responsible for deployment-specific governance and compliance.',
      ],
      bullets: [
        'Age restrictions',
        'Age assurance',
        'Parent or guardian consent',
        'School consent',
        'Account provisioning',
        'User roles',
        'Parental controls',
        'Content filtering',
        'Marketplace access',
        'Plugin approval',
        'Integration controls',
        'Automation controls',
        'Memory settings',
        'Data retention',
        'Data deletion',
        'Audit logs',
        'Incident response',
        'Legal compliance',
        'Safety reporting',
        'Support processes',
      ],
    },
    {
      id: 'developer-and-marketplace-requirements',
      title: '34. Developer and Marketplace Requirements',
      body: [
        'Developers and marketplace publishers must not design, publish, advertise, or distribute content or tools that exploit, target, manipulate, or endanger minors.',
        'Developers and marketplace publishers must not:',
        'SinLess Games LLC may remove, suspend, disable, delist, or ban marketplace items or developers that violate this policy.',
      ],
      bullets: [
        'Bypass age gates',
        'Bypass parental controls',
        'Hide mature content',
        'Mislabel adult content as child-safe',
        'Collect minor data without proper authorization',
        'Sell minor data',
        'Track minors without proper disclosure and legal basis',
        'Target minors with age-restricted content',
        'Provide unsafe direct messaging features',
        'Provide grooming, exploitation, harassment, or predatory tools',
        'Provide unsafe automations for minors',
        'Provide mature personalities to minors',
        'Use deceptive design to get minors to share data',
        'Encourage minors to hide usage from parents or guardians',
      ],
    },
    {
      id: 'content-labeling',
      title: '35. Content Labeling',
      body: [
        'Aerealith AI may require content, plugins, marketplace items, personalities, workflows, templates, dashboards, and public materials to be labeled by age suitability.',
        'Labels may include:',
        'Mislabeling age-restricted content may result in removal, suspension, account restriction, or marketplace enforcement.',
      ],
      bullets: [
        'General audience',
        'Teen-appropriate',
        'Mature',
        'Adult-only',
        'Restricted',
        'Not suitable for minors',
      ],
    },
    {
      id: 'reporting-underage-safety-concerns',
      title: '36. Reporting Underage Safety Concerns',
      body: [
        'Report underage safety concerns to:',
        'Before publishing this policy, confirm these email aliases exist and are monitored.',
        'Reports should include:',
        'Do not include unnecessary sensitive information.',
        'If a minor is in immediate danger, contact emergency services or local authorities.',
      ],
      bullets: [
        'Account or workspace involved',
        'Feature involved',
        'Description of the concern',
        'Relevant timestamps',
        'Screenshots or logs, if safe to provide',
        'Whether a minor may be in immediate danger',
        'Whether age-restricted content may be involved',
        'Whether public sharing, marketplace, plugin, integration, or automation features are involved',
      ],
      contacts: [
        {
          label: 'Child safety and AI safety',
          email: 'safety@sinlessgames.com',
          href: 'mailto:safety@sinlessgames.com',
        },
        {
          label: 'Abuse',
          email: 'abuse@sinlessgames.com',
          href: 'mailto:abuse@sinlessgames.com',
        },
        {
          label: 'Privacy',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
        {
          label: 'Security',
          email: 'security@sinlessgames.com',
          href: 'mailto:security@sinlessgames.com',
        },
        {
          label: 'Support',
          email: 'support@sinlessgames.com',
          href: 'mailto:support@sinlessgames.com',
        },
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
      ],
    },
    {
      id: 'incident-handling',
      title: '37. Incident Handling',
      body: [
        'Underage safety incidents may be handled according to the Incident Notification Policy, Security Policy, Privacy Policy, Data Policy, Acceptable Use Policy, and applicable law.',
        'Underage safety incidents may include:',
        'SinLess Games LLC may prioritize child-safety incidents and may take immediate protective action.',
      ],
      bullets: [
        'Minor access to age-restricted content',
        'Failure of parental controls',
        'Unauthorized minor account creation',
        'Child privacy incident',
        'Unsafe AI output to a minor',
        'Marketplace item unsafe for minors',
        'Plugin bypass of minor restrictions',
        'Public exposure of minor data',
        'Unauthorized collection of minor data',
        'Grooming or exploitation reports',
        'Self-harm or imminent danger reports',
      ],
      links: [
        {
          label: 'Incident Notification Policy',
          href: '/Policies/incident-notification',
        },
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
      ],
    },
    {
      id: 'law-enforcement-and-safety-reporting',
      title: '38. Law Enforcement and Safety Reporting',
      body: [
        'SinLess Games LLC may preserve and disclose information where required or permitted by law.',
        'This may include reporting apparent child exploitation, imminent harm, threats, abuse, or unlawful activity to appropriate authorities.',
        'Where legally permitted and appropriate, SinLess Games LLC may notify parents, guardians, schools, organizations, users, or administrators about safety risks involving minors.',
      ],
    },
    {
      id: 'no-guarantee',
      title: '39. No Guarantee',
      body: [
        'SinLess Games LLC will use reasonable measures to protect minors and restrict age-restricted content, but no age-assurance method, parental-control system, content filter, AI safety system, or moderation process is perfect.',
        'Users, parents, guardians, schools, and organizations remain responsible for supervising minors and configuring accounts appropriately.',
        'Aerealith AI is not a substitute for parental supervision, professional care, emergency services, school supervision, or legal compliance programs.',
      ],
    },
    {
      id: 'contact',
      title: '40. Contact',
      body: [
        'Questions about this policy may be sent to:',
        'Before publishing this policy, confirm these email aliases exist and are monitored.',
      ],
      contacts: [
        {
          label: 'Support',
          email: 'support@sinlessgames.com',
          href: 'mailto:support@sinlessgames.com',
        },
        {
          label: 'Privacy',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
        {
          label: 'AI safety',
          email: 'safety@sinlessgames.com',
          href: 'mailto:safety@sinlessgames.com',
        },
        {
          label: 'Abuse',
          email: 'abuse@sinlessgames.com',
          href: 'mailto:abuse@sinlessgames.com',
        },
        {
          label: 'Security',
          email: 'security@sinlessgames.com',
          href: 'mailto:security@sinlessgames.com',
        },
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
      ],
    },
    {
      id: 'publication-checklist',
      title: '41. Publication Checklist',
      body: ['Before publishing this policy, complete the following:'],
      bullets: [
        'Confirm official company name: SinLess Games LLC',
        'Confirm official product name: Aerealith AI',
        'Confirm minimum account age',
        'Confirm age thresholds by jurisdiction',
        'Confirm whether users under 13 are allowed under any conditions',
        'Confirm whether users ages 13 to 17 are allowed',
        'Confirm parent or guardian consent workflow',
        'Confirm parental-control features',
        'Confirm school or education workflow',
        'Confirm age-assurance methods',
        'Confirm age-verification data retention',
        'Confirm whether third-party age-assurance providers are used',
        'Confirm content rating taxonomy',
        'Confirm restricted content categories',
        'Confirm marketplace minor restrictions',
        'Confirm developer/API minor restrictions',
        'Confirm payment restrictions for minors',
        'Confirm public sharing restrictions for minors',
        'Confirm AI memory defaults for minors',
        'Confirm targeted advertising restrictions',
        'Confirm child safety escalation path',
        'Confirm report-handling workflow',
        'Confirm law enforcement reporting workflow',
        'Confirm support email aliases',
        'Confirm privacy request workflow for parents or guardians',
        'Confirm self-hosted and air-gapped responsibilities',
        'Confirm links in other policies point to ./underage.md',
        'Have qualified legal counsel review this policy',
      ],
    },
    {
      id: 'changes-to-this-policy',
      title: '42. Changes to This Policy',
      body: [
        'We may update this policy from time to time.',
        'When we make material changes, we will update the last_updated date and may provide notice through the service, documentation, account settings, support portal, email, release notes, legal notices page, or another reasonable method.',
        'Continued use of Aerealith AI after changes become effective means you accept the updated policy.',
      ],
    },
    {
      id: 'legal-review-notice',
      title: '43. Legal Review Notice',
      body: [
        'This policy is a draft template and should be reviewed by qualified legal counsel before publication.',
        'Children’s privacy, parental consent, age verification, age assurance, online safety, education privacy, content restrictions, targeted advertising, biometrics, identity verification, marketplace access, payment access, self-hosted deployment, and regional minor-protection requirements may vary by jurisdiction, customer type, deployment model, and written agreement.',
      ],
    },
  ],
} satisfies PolicyDocument;

export default underagePolicy;
