import type { PolicyDocument } from '../../types';

export const userGeneratedContentPolicy = {
  slug: 'user-generated-content',
  path: '/Policies/user-generated-content',
  meta: {
    title: 'User-Generated Content Policy',
    description:
      'Explains ownership, attribution, licensing, sharing, moderation, public content, AI-generated content, and user responsibilities for content created, uploaded, generated, or shared through Aerealith AI.',
    effectiveDate: '2026-05-19',
    lastUpdated: '2026-05-19',
    owner: 'SinLess Games LLC',
    status: 'draft',
  },
  relatedPolicies: [
    {
      label: 'Terms of Use',
      href: '/Policies/terms-of-use',
    },
    {
      label: 'Privacy Policy',
      href: '/Policies/privacy',
    },
    {
      label: 'Data Policy',
      href: '/Policies/data',
    },
    {
      label: 'Security Policy',
      href: '/Policies/security-policy',
    },
    {
      label: 'Acceptable Use Policy',
      href: '/Policies/acceptable-use',
    },
    {
      label: 'AI Transparency Policy',
      href: '/Policies/ai-transparency',
    },
    {
      label: 'Responsible AI Policy',
      href: '/Policies/responsible-ai',
    },
    {
      label: 'Cookie and Tracking Policy',
      href: '/Policies/cookie-tracking',
    },
    {
      label: 'Billing, Refund, and Cancellation Policy',
      href: '/Policies/billing-refund-cancellation',
    },
    {
      label: 'Copyright Takedown Policy',
      href: '/Policies/copyright-takedown',
    },
    {
      label: 'Incident Notification Policy',
      href: '/Policies/incident-notification',
    },
    {
      label: 'Payment Processor Compliance Policy',
      href: '/Policies/payment-proccessor-compliance',
    },
    {
      label: 'Subprocessor and Vendor List',
      href: '/Policies/subprocessor-vendor-list',
    },
    {
      label: 'Support Policy',
      href: '/Policies/support-policy',
    },
    {
      label: 'Underage Policy',
      href: '/Policies/underage',
    },
    {
      label: 'Marketplace Policy',
      href: '/Policies/marketplace',
    },
    {
      label: 'Developer and API Policy',
      href: '/Policies/developer',
    },
  ],
  sections: [
    {
      id: 'purpose',
      title: '1. Purpose',
      body: [
        'This User-Generated Content Policy explains how Aerealith AI handles content created, uploaded, generated, transformed, published, shared, distributed, or otherwise processed by users.',
        'Aerealith AI is operated by SinLess Games LLC.',
        'Aerealith AI allows users to create and work with prompts, messages, files, code, images, documents, dashboards, workflows, automations, marketplace items, plugins, templates, AI-generated outputs, and other content. This policy explains ownership, user responsibility, required attribution, prohibited content, moderation, takedowns, and public-sharing rules.',
        'The core rule is:',
        'Users own what they generate through Aerealith AI, as between the user and SinLess Games LLC, but Aerealith AI must be attributed in a reasonable manner when generated or AI-assisted content is published, distributed, sold, submitted professionally, or used publicly.',
      ],
    },
    {
      id: 'scope',
      title: '2. Scope',
      body: [
        'This policy applies to Aerealith AI services, including:',
        'This policy applies to:',
      ],
      bullets: [
        'Websites',
        'Web applications',
        'Desktop applications',
        'Mobile applications',
        'Browser extensions',
        'APIs',
        'Developer tools',
        'Documentation sites',
        'Marketplace features',
        'Plugins',
        'Automations',
        'Integrations',
        'Dashboards',
        'Analytics features',
        'AI memory features',
        'Support systems',
        'Organization workspaces',
        'Cloud-hosted deployments',
        'Self-hosted deployments, where applicable',
        'Hybrid deployments, where applicable',
        'Air-gapped deployments, where applicable',
        'Visitors',
        'Individual users',
        'Organization users',
        'Workspace members',
        'Administrators',
        'Developers',
        'Marketplace publishers',
        'API users',
        'Enterprise customers',
        'Anyone who creates, uploads, generates, shares, publishes, distributes, or processes content through Aerealith AI',
      ],
    },
    {
      id: 'relationship-to-other-policies',
      title: '3. Relationship to Other Policies',
      body: [
        'This policy works together with other Aerealith AI policies, including:',
        'If there is a conflict between this policy and a written agreement signed by SinLess Games LLC, the written agreement controls only to the extent of that conflict.',
      ],
      links: [
        {
          label: 'Terms of Use',
          href: '/Policies/terms-of-use',
        },
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
        {
          label: 'Security Policy',
          href: '/Policies/security-policy',
        },
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
        {
          label: 'AI Transparency Policy',
          href: '/Policies/ai-transparency',
        },
        {
          label: 'Responsible AI Policy',
          href: '/Policies/responsible-ai',
        },
        {
          label: 'Cookie and Tracking Policy',
          href: '/Policies/cookie-tracking',
        },
        {
          label: 'Billing, Refund, and Cancellation Policy',
          href: '/Policies/billing-refund-cancellation',
        },
        {
          label: 'Copyright Takedown Policy',
          href: '/Policies/copyright-takedown',
        },
        {
          label: 'Incident Notification Policy',
          href: '/Policies/incident-notification',
        },
        {
          label: 'Payment Processor Compliance Policy',
          href: '/Policies/payment-proccessor-compliance',
        },
        {
          label: 'Subprocessor and Vendor List',
          href: '/Policies/subprocessor-vendor-list',
        },
        {
          label: 'Support Policy',
          href: '/Policies/support-policy',
        },
        {
          label: 'Underage Policy',
          href: '/Policies/underage',
        },
        {
          label: 'Marketplace Policy',
          href: '/Policies/marketplace',
        },
        {
          label: 'Developer and API Policy',
          href: '/Policies/developer',
        },
      ],
    },
    {
      id: 'definitions',
      title: '4. Definitions',
      body: ['For this policy:'],
      bullets: [
        '“User Content” means content submitted, uploaded, imported, connected, generated, transformed, published, distributed, or otherwise processed by a user through Aerealith AI.',
        '“Input” means content a user provides to Aerealith AI, including prompts, files, messages, code, data, instructions, images, audio, video, documents, logs, links, integration data, and other materials.',
        '“Output” means content generated, edited, transformed, summarized, analyzed, classified, formatted, or otherwise produced by Aerealith AI in response to user input, tool results, files, integrations, automations, or other context.',
        '“AI-Assisted Content” means content created with material help from Aerealith AI, including generated text, code, images, reports, workflows, dashboards, scripts, summaries, designs, or other materials.',
        '“Public Content” means User Content made visible outside a private account or workspace, including shared links, public dashboards, marketplace listings, plugins, templates, documentation, community posts, published reports, or other externally visible materials.',
        '“Attribution” means a reasonable notice that Aerealith AI was used to generate, assist, transform, or support the content.',
      ],
    },
    {
      id: 'user-ownership',
      title: '5. User Ownership',
      body: [
        'As between you and SinLess Games LLC, you own your User Content.',
        'This includes:',
        'SinLess Games LLC does not claim ownership of your User Content.',
        'Your ownership may still be limited by applicable law, third-party rights, open-source licenses, marketplace rules, organization policies, employment agreements, contracts, or the rights of other users or rights holders.',
      ],
      bullets: [
        'Your Inputs',
        'Your Outputs',
        'Your uploaded files',
        'Your generated documents',
        'Your generated code',
        'Your generated images, where supported',
        'Your generated reports',
        'Your generated dashboards',
        'Your generated workflows',
        'Your generated automations',
        'Your generated templates',
        'Your marketplace listings',
        'Your plugins',
        'Your published materials',
        'Your private workspace content',
        'Your organization content, subject to organization ownership and permissions',
      ],
    },
    {
      id: 'ai-output-ownership-clarification',
      title: '6. AI Output Ownership Clarification',
      body: [
        'As between you and SinLess Games LLC, you own the Outputs generated for you by Aerealith AI.',
        'However, SinLess Games LLC does not guarantee that any Output is copyrightable, protectable, exclusive, original, non-infringing, or free from third-party claims.',
        'AI-generated or AI-assisted content may raise legal issues involving:',
        'You are responsible for reviewing Outputs before using, publishing, distributing, selling, submitting, or commercializing them.',
      ],
      bullets: [
        'Copyright',
        'Trademark',
        'Patent',
        'Trade secrets',
        'Right of publicity',
        'Privacy',
        'Contractual rights',
        'Open-source licenses',
        'Dataset restrictions',
        'Platform rules',
        'Professional rules',
        'Confidentiality obligations',
      ],
    },
    {
      id: 'required-aerealith-ai-attribution',
      title: '7. Required Aerealith AI Attribution',
      body: [
        'When you publish, distribute, sell, license, submit professionally, submit academically, release publicly, or otherwise make AI-Assisted Content available outside private personal use, you must attribute Aerealith AI in a reasonable manner.',
        'Attribution is required for public or external use of:',
        'Attribution does not transfer ownership of your content to SinLess Games LLC.',
        'Attribution does not mean SinLess Games LLC endorses, approves, sponsors, verifies, or accepts responsibility for your content.',
      ],
      bullets: [
        'AI-generated text',
        'AI-assisted articles',
        'AI-assisted documentation',
        'AI-generated images or media, where supported',
        'AI-assisted code repositories',
        'AI-generated reports',
        'AI-generated dashboards',
        'AI-generated workflows',
        'AI-generated templates',
        'AI-generated plugins',
        'AI-generated marketplace items',
        'AI-assisted presentations',
        'AI-assisted professional submissions',
        'AI-assisted academic submissions, where allowed',
        'AI-assisted public communications',
        'AI-assisted commercial materials',
      ],
    },
    {
      id: 'acceptable-attribution-formats',
      title: '8. Acceptable Attribution Formats',
      body: [
        'Attribution must be clear enough for a reasonable viewer, reader, customer, reviewer, or recipient to understand that Aerealith AI assisted with the content.',
        'Acceptable attribution examples include:',
        'For code projects, attribution may appear in:',
        'For images, videos, audio, or visual content, attribution may appear in:',
        'For reports, documents, articles, or public posts, attribution may appear in:',
      ],
      bullets: [
        'Created with assistance from Aerealith AI.',
        'Generated in part with Aerealith AI.',
        'Drafted with Aerealith AI and reviewed by the author.',
        'AI-assisted content created using Aerealith AI.',
        'This report was prepared with assistance from Aerealith AI.',
        'This dashboard was generated with assistance from Aerealith AI.',
        'This workflow was created with assistance from Aerealith AI.',
        'This plugin includes AI-assisted content generated with Aerealith AI.',
        'Portions of this code were generated with assistance from Aerealith AI.',
        'README files',
        'Project documentation',
        'Source file headers, where appropriate',
        'Commit messages, where appropriate',
        'Release notes',
        'Marketplace listing descriptions',
        'Package metadata, where appropriate',
        'Captions',
        'Metadata',
        'Description fields',
        'Credits',
        'Project notes',
        'Accompanying documentation',
        'Footer notes',
        'Acknowledgments',
        'Endnotes',
        'Disclosures',
        'Publication notes',
      ],
    },
    {
      id: 'private-use-attribution-exception',
      title: '9. Private Use Attribution Exception',
      body: [
        'Attribution is not required for purely private personal use inside your own account or private workspace.',
        'Examples where visible attribution is generally not required include:',
        'Organizations may still require internal attribution or AI-use disclosure under their own policies.',
      ],
      bullets: [
        'Private brainstorming',
        'Private notes',
        'Private drafts',
        'Private study material',
        'Private code experiments',
        'Private internal reminders',
        'Private personal planning',
        'Private conversations with Aerealith AI',
        'Private workspace material that is not distributed externally',
      ],
    },
    {
      id: 'internal-business-use-attribution',
      title: '10. Internal Business Use Attribution',
      body: [
        'For internal business use, attribution may be handled through organization policy.',
        'An organization may require attribution in:',
        'If an organization chooses to waive visible internal attribution, it should still maintain reasonable internal records of AI-assisted content where required by policy, contract, compliance obligations, or professional standards.',
      ],
      bullets: [
        'Internal documentation',
        'Internal reports',
        'Internal dashboards',
        'Internal code repositories',
        'Internal workflows',
        'Internal compliance records',
        'Internal project notes',
        'Internal AI-use logs',
      ],
    },
    {
      id: 'no-false-endorsement',
      title: '11. No False Endorsement',
      body: [
        'You may not use attribution in a way that falsely implies SinLess Games LLC or Aerealith AI:',
        'Do not use Aerealith AI branding, logos, icons, marks, trade dress, or official screenshots unless permitted by SinLess Games LLC brand guidelines or written permission.',
      ],
      bullets: [
        'Endorses your content',
        'Sponsors your content',
        'Guarantees your content',
        'Verified your content',
        'Approved your content',
        'Is responsible for your content',
        'Is affiliated with your business, project, product, campaign, or organization beyond providing the Aerealith AI service',
      ],
    },
    {
      id: 'removal-or-waiver-of-attribution',
      title: '12. Removal or Waiver of Attribution',
      body: [
        'SinLess Games LLC may provide written permission to modify, waive, or replace attribution requirements for certain use cases.',
        'A waiver or modification may be appropriate for:',
        'Any waiver must be written and authorized by SinLess Games LLC.',
        'Silence or lack of enforcement does not waive attribution requirements.',
      ],
      bullets: [
        'Enterprise agreements',
        'White-label deployments',
        'Self-hosted deployments',
        'Air-gapped deployments',
        'Accessibility limitations',
        'Platform character limits',
        'Technical constraints',
        'Private marketplace deployments',
        'Internal-only workflows',
        'Contractually approved branding requirements',
      ],
    },
    {
      id: 'attribution-when-space-is-limited',
      title: '13. Attribution When Space Is Limited',
      body: [
        'If the platform, format, file type, interface, or publication channel makes visible attribution impractical, you must provide attribution in a reasonable alternative location.',
        'Alternative attribution locations may include:',
        'The attribution should be reasonably accessible to the audience or recipient.',
      ],
      bullets: [
        'Project README',
        'Metadata',
        'Credits page',
        'Documentation',
        'Footer',
        'Description field',
        'Release notes',
        'Marketplace listing',
        'Linked disclosure',
        'Internal AI-use register',
        'Appendix',
        'Accompanying file',
        'Package manifest',
      ],
    },
    {
      id: 'user-responsibility-for-content',
      title: '14. User Responsibility for Content',
      body: [
        'You are responsible for your User Content.',
        'You represent and warrant that:',
        'You are responsible for reviewing Outputs before use.',
      ],
      bullets: [
        'You have the rights needed to use your Inputs with Aerealith AI.',
        'You have the rights needed to publish, distribute, sell, or share your User Content.',
        'Your User Content does not violate law.',
        'Your User Content does not violate another person’s rights.',
        'Your User Content does not violate these policies.',
        'Your User Content does not include malware or harmful code.',
        'Your User Content does not include unauthorized confidential information.',
        'Your User Content does not include secrets unless handled through approved secure features.',
        'Your public or commercial use includes required Aerealith AI attribution.',
      ],
    },
    {
      id: 'content-review-before-use',
      title: '15. Content Review Before Use',
      body: [
        'Before publishing, distributing, selling, submitting, deploying, or relying on AI-Assisted Content, you should review it for:',
        'For generated code, scripts, infrastructure configurations, automations, or workflows, you must test before production use.',
      ],
      bullets: [
        'Accuracy',
        'Completeness',
        'Originality',
        'Legal compliance',
        'Copyright issues',
        'Trademark issues',
        'Open-source license issues',
        'Privacy issues',
        'Confidentiality issues',
        'Security issues',
        'Bias or unfairness',
        'Accessibility',
        'Professional standards',
        'Organization policies',
        'Attribution requirements',
        'High-risk decision-making concerns',
      ],
    },
    {
      id: 'prohibited-user-content',
      title: '16. Prohibited User Content',
      body: [
        'You may not create, upload, generate, publish, distribute, sell, or share User Content that violates the Acceptable Use Policy.',
        'Prohibited content includes, but is not limited to:',
      ],
      bullets: [
        'Illegal content',
        'Fraud or scam content',
        'Phishing content',
        'Malware',
        'Credential theft tools',
        'Unauthorized exploit content',
        'Harassment',
        'Threats',
        'Doxxing',
        'Hate or dehumanizing content',
        'Child sexual abuse material',
        'Sexual exploitation of minors',
        'Non-consensual intimate imagery',
        'Terrorism or violent extremism content',
        'Content that encourages self-harm in a harmful way',
        'Dangerous instructions intended to cause harm',
        'Infringing copyrighted content',
        'Trademark misuse',
        'Unauthorized confidential information',
        'Privacy-invasive content',
        'Deceptive impersonation',
        'Fake credentials or forged records',
        'Unlawful regulated goods or services',
        'Content designed to bypass Aerealith AI safety systems',
      ],
      links: [
        {
          label: 'Acceptable Use Policy',
          href: '/Policies/acceptable-use',
        },
      ],
    },
    {
      id: 'age-restricted-and-mature-content',
      title: '17. Age-Restricted and Mature Content',
      body: [
        'Age-restricted content must comply with the Underage Policy.',
        'You may not publish, distribute, sell, or expose minors to age-restricted content through Aerealith AI.',
        'Age-restricted content may include:',
        'SinLess Games LLC may label, restrict, remove, disable, or age-gate age-restricted content.',
      ],
      bullets: [
        'Adult or erotic content',
        'Mature companionship modes',
        'Graphic violence',
        'Gambling content',
        'Alcohol-related content',
        'Nicotine or tobacco-related content',
        'Recreational drug-related content',
        'Regulated goods or services',
        'Mature marketplace items',
        'Adult personalities, prompts, or templates',
        'Unsafe or destructive automations',
        'Content legally restricted to adults',
      ],
      links: [
        {
          label: 'Underage Policy',
          href: '/Policies/underage',
        },
      ],
    },
    {
      id: 'child-safety',
      title: '18. Child Safety',
      body: [
        'You may not use Aerealith AI to create, upload, generate, transform, summarize, store, publish, distribute, or facilitate content that exploits, sexualizes, grooms, manipulates, abuses, endangers, or harms minors.',
        'SinLess Games LLC may report apparent child exploitation or imminent harm to appropriate authorities where required or appropriate.',
        'Child safety concerns should be reported to safety@sinlessgames.com.',
      ],
      contacts: [
        {
          label: 'AI safety',
          email: 'safety@sinlessgames.com',
          href: 'mailto:safety@sinlessgames.com',
        },
      ],
    },
    {
      id: 'copyright-and-intellectual-property',
      title: '19. Copyright and Intellectual Property',
      body: [
        'You may not use Aerealith AI to infringe, misappropriate, or violate intellectual property rights.',
        'You may not:',
        'Copyright complaints are handled under the Copyright Takedown Policy.',
      ],
      bullets: [
        'Upload copyrighted material without authorization',
        'Generate or distribute infringing content',
        'Remove copyright notices',
        'Remove license notices',
        'Remove attribution',
        'Circumvent DRM or technical protection measures',
        'Misrepresent ownership',
        'Publish marketplace items containing content you do not have rights to use',
        'Use Aerealith AI to copy protected works unlawfully',
        'Use Aerealith AI to evade license restrictions',
      ],
      links: [
        {
          label: 'Copyright Takedown Policy',
          href: '/Policies/copyright-takedown',
        },
      ],
    },
    {
      id: 'open-source-content',
      title: '20. Open Source Content',
      body: [
        'If your User Content includes open source software or open source-derived material, you are responsible for complying with applicable licenses.',
        'Open source obligations may include:',
        'Aerealith AI attribution does not replace open source license obligations.',
      ],
      bullets: [
        'Attribution',
        'License notices',
        'Copyright notices',
        'Source code availability',
        'Copyleft requirements',
        'Modification notices',
        'Redistribution restrictions',
        'Patent license terms',
        'Commercial-use restrictions',
        'Dependency license compatibility',
      ],
    },
    {
      id: 'privacy-and-personal-data-in-user-content',
      title: '21. Privacy and Personal Data in User Content',
      body: [
        'You may not upload, generate, publish, or share personal data unless you have the right to do so.',
        'You are responsible for ensuring your User Content complies with privacy laws, contracts, organization policies, and consent requirements.',
        'Do not publicly share:',
        'Privacy handling is governed by the Privacy Policy and Data Policy.',
      ],
      bullets: [
        'Personal data without authorization',
        'Confidential business data',
        'Health information',
        'Financial information',
        'Legal records',
        'Children’s data',
        'Government identification numbers',
        'Precise location data',
        'Private messages',
        'Internal logs containing personal information',
        'Sensitive customer data',
      ],
      links: [
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
      ],
    },
    {
      id: 'secrets-and-credentials-in-user-content',
      title: '22. Secrets and Credentials in User Content',
      body: [
        'You must not include secrets in public or ordinary User Content.',
        'Secrets include:',
        'Secrets should be stored in approved secret-management systems.',
        'If secrets are detected in unsafe locations, SinLess Games LLC may redact, restrict, remove, rotate, alert, or recommend remediation where supported.',
      ],
      bullets: [
        'Passwords',
        'API keys',
        'OAuth tokens',
        'Session tokens',
        'Private keys',
        'SSH keys',
        'Signing keys',
        'Database credentials',
        'Cloud credentials',
        'Payment credentials',
        'Webhook secrets',
        'Recovery codes',
        'Encryption keys',
      ],
    },
    {
      id: 'public-sharing',
      title: '23. Public Sharing',
      body: [
        'If you share User Content publicly, you are responsible for the consequences.',
        'Public content may be:',
        'Before sharing publicly, review content for:',
      ],
      bullets: [
        'Indexed by search engines',
        'Copied by others',
        'Downloaded by others',
        'Cached by third parties',
        'Quoted by others',
        'Reused by others',
        'Archived by third parties',
        'Difficult or impossible to fully remove',
        'Personal data',
        'Confidential information',
        'Secrets',
        'Copyright issues',
        'Organization restrictions',
        'Security-sensitive data',
        'Minor safety concerns',
        'Attribution requirements',
        'Compliance obligations',
      ],
    },
    {
      id: 'shared-links',
      title: '24. Shared Links',
      body: [
        'Aerealith AI may allow users to create shared links.',
        'Shared links may expose content to anyone with access to the link unless configured otherwise.',
        'Users are responsible for:',
        'Organizations may restrict or disable shared links.',
      ],
      bullets: [
        'Reviewing shared content',
        'Limiting link access',
        'Revoking links when no longer needed',
        'Avoiding sensitive data in shared content',
        'Avoiding secrets in shared content',
        'Complying with organization policies',
        'Including attribution where required',
      ],
    },
    {
      id: 'organization-content',
      title: '25. Organization Content',
      body: [
        'If you use Aerealith AI through an organization workspace, User Content may be owned, controlled, accessed, exported, retained, deleted, or governed by the organization.',
        'Organization administrators may be able to access:',
        'Users should not place personal content in organization workspaces unless permitted by organization policy.',
      ],
      bullets: [
        'Workspace content',
        'Member content',
        'Shared files',
        'Dashboards',
        'Reports',
        'Automations',
        'Integrations',
        'Plugin activity',
        'Marketplace installations',
        'Audit logs',
        'Memory settings',
        'Data exports',
        'Usage records',
      ],
    },
    {
      id: 'marketplace-content',
      title: '26. Marketplace Content',
      body: [
        'Marketplace publishers are responsible for all content they publish through Aerealith AI marketplace features.',
        'Marketplace content may include:',
        'Marketplace publishers must:',
        'SinLess Games LLC may remove or restrict marketplace content that violates policy.',
      ],
      bullets: [
        'Plugins',
        'Connectors',
        'Workflows',
        'Dashboards',
        'Templates',
        'Personalities',
        'Prompt packs',
        'Icons',
        'Screenshots',
        'Documentation',
        'Code',
        'Configuration',
        'Example outputs',
        'Listings',
        'Reviews',
        'Support materials',
        'Own or have rights to their content',
        'Include required Aerealith AI attribution for AI-assisted content',
        'Disclose AI-generated or AI-assisted content where appropriate',
        'Disclose required permissions',
        'Disclose data access',
        'Avoid hidden tracking',
        'Avoid excessive permissions',
        'Avoid infringing content',
        'Avoid unsafe or illegal content',
        'Follow marketplace rules',
        'Support their marketplace items where required',
      ],
    },
    {
      id: 'reviews-comments-and-community-content',
      title: '27. Reviews, Comments, and Community Content',
      body: [
        'Users may be able to post reviews, comments, community messages, feedback, ratings, or other public content.',
        'Users may not post community content that is:',
        'SinLess Games LLC may remove, hide, restrict, or moderate reviews, comments, and community content.',
      ],
      bullets: [
        'Harassing',
        'Threatening',
        'Hateful',
        'Defamatory',
        'Fraudulent',
        'Spam',
        'Misleading',
        'Impersonating another person',
        'Infringing',
        'Privacy-invasive',
        'Abusive',
        'Unlawful',
        'Designed to manipulate ratings or reviews',
        'Designed to abuse support or reporting systems',
      ],
    },
    {
      id: 'synthetic-media',
      title: '28. Synthetic Media',
      body: [
        'If Aerealith AI supports or integrates with synthetic media features, users must use those features responsibly.',
        'Users may not create or distribute synthetic media that:',
        'Synthetic media should be labeled or disclosed when required by law, platform rules, professional standards, contract, organization policy, or reasonable audience expectations.',
        'Aerealith AI attribution is required for public or external use of synthetic media generated or assisted by Aerealith AI.',
      ],
      bullets: [
        'Deceives people about whether content is real',
        'Impersonates someone without authorization',
        'Creates non-consensual intimate imagery',
        'Harasses, threatens, exploits, or defames others',
        'Creates fake official records',
        'Creates fake evidence',
        'Creates fake identification',
        'Supports fraud, scams, phishing, or social engineering',
        'Misleads people in political, legal, medical, financial, emergency, or high-impact contexts',
      ],
    },
    {
      id: 'academic-professional-and-regulated-submissions',
      title: '29. Academic, Professional, and Regulated Submissions',
      body: [
        'Users are responsible for following rules that apply to academic, professional, legal, medical, financial, employment, compliance, or regulated submissions.',
        'Before submitting AI-Assisted Content, users must follow applicable:',
        'Aerealith AI must be attributed where required by this policy, and additional AI-use disclosure may be required by the relevant institution or authority.',
      ],
      bullets: [
        'School policies',
        'Employer policies',
        'Client requirements',
        'Court rules',
        'Professional rules',
        'Publication rules',
        'Government filing rules',
        'Platform rules',
        'Contract terms',
        'Disclosure requirements',
        'Attribution requirements',
      ],
    },
    {
      id: 'commercial-use',
      title: '30. Commercial Use',
      body: [
        'Users may commercially use Outputs generated through Aerealith AI, subject to:',
        'SinLess Games LLC does not guarantee that Outputs are exclusive, copyrightable, non-infringing, commercially usable, or suitable for a particular market.',
        'Users are responsible for legal and business review before commercial use.',
      ],
      bullets: [
        'These policies',
        'The Terms of Use',
        'Applicable law',
        'Third-party rights',
        'Open-source licenses',
        'Marketplace rules',
        'Organization policies',
        'Payment obligations',
        'Subscription plan restrictions',
        'Required Aerealith AI attribution',
        'Written agreements, where applicable',
      ],
      links: [
        {
          label: 'Terms of Use',
          href: '/Policies/terms-of-use',
        },
      ],
    },
    {
      id: 'similar-or-duplicate-outputs',
      title: '31. Similar or Duplicate Outputs',
      body: [
        'Because AI systems may generate similar or identical outputs for multiple users, Aerealith AI cannot guarantee that Outputs are unique.',
        'Other users may receive similar:',
        'Your ownership of your Output does not prevent other users from owning or using similar outputs independently generated for them.',
      ],
      bullets: [
        'Text',
        'Code',
        'Designs',
        'Summaries',
        'Templates',
        'Workflows',
        'Dashboards',
        'Reports',
        'Images',
        'Ideas',
        'Names',
        'Concepts',
        'Structures',
      ],
    },
    {
      id: 'content-moderation',
      title: '32. Content Moderation',
      body: [
        'SinLess Games LLC may moderate User Content to enforce policies, protect users, comply with law, and operate Aerealith AI.',
        'Moderation actions may include:',
        'Moderation may involve automated systems, human review, or both.',
      ],
      bullets: [
        'Warning users',
        'Labeling content',
        'Restricting content visibility',
        'Removing content',
        'Disabling shared links',
        'Disabling marketplace listings',
        'Disabling plugins',
        'Restricting public sharing',
        'Restricting uploads',
        'Restricting generation features',
        'Restricting accounts',
        'Suspending accounts',
        'Terminating accounts',
        'Reporting unlawful activity where appropriate',
      ],
    },
    {
      id: 'content-reporting',
      title: '33. Content Reporting',
      body: [
        'Users may report content that may violate this policy.',
        'Reports may be sent to:',
        'Before publishing this policy, confirm these email aliases exist and are monitored.',
        'Reports should include:',
        'Do not include unnecessary sensitive information.',
      ],
      bullets: [
        'Account, workspace, or marketplace item involved',
        'URL or content location',
        'Description of the issue',
        'Screenshots or logs, if safe to provide',
        'Timestamps',
        'Reason the content may violate policy',
        'Any immediate safety, privacy, or security concern',
      ],
      contacts: [
        {
          label: 'Abuse',
          email: 'abuse@sinlessgames.com',
          href: 'mailto:abuse@sinlessgames.com',
        },
        {
          label: 'AI safety',
          email: 'safety@sinlessgames.com',
          href: 'mailto:safety@sinlessgames.com',
        },
        {
          label: 'Copyright',
          email: 'copyright@sinlessgames.com',
          href: 'mailto:copyright@sinlessgames.com',
        },
        {
          label: 'Privacy',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
        {
          label: 'Security',
          email: 'security@sinlessgames.com',
          href: 'mailto:security@sinlessgames.com',
        },
        {
          label: 'Support',
          email: 'support@sinlessgames.com',
          href: 'mailto:support@sinlessgames.com',
        },
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
      ],
    },
    {
      id: 'copyright-takedowns',
      title: '34. Copyright Takedowns',
      body: [
        'Copyright complaints must follow the Copyright Takedown Policy.',
        'Copyright notices should be sent to copyright@sinlessgames.com.',
        'SinLess Games LLC may remove or disable content in response to valid copyright complaints.',
        'Users may be able to submit counter-notices where permitted.',
        'Repeat infringers may be restricted, suspended, or terminated.',
      ],
      contacts: [
        {
          label: 'Copyright',
          email: 'copyright@sinlessgames.com',
          href: 'mailto:copyright@sinlessgames.com',
        },
      ],
      links: [
        {
          label: 'Copyright Takedown Policy',
          href: '/Policies/copyright-takedown',
        },
      ],
    },
    {
      id: 'trademark-and-brand-complaints',
      title: '35. Trademark and Brand Complaints',
      body: [
        'Trademark and brand complaints should be sent to legal@sinlessgames.com.',
        'Complaints should include:',
        'Trademark complaints are not handled through the DMCA process unless they also include copyright claims.',
      ],
      bullets: [
        'Trademark or brand at issue',
        'Registration information, if available',
        'Location of the allegedly infringing content',
        'Description of the issue',
        'Evidence of ownership or authorization',
        'Requested action',
      ],
      contacts: [
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
      ],
    },
    {
      id: 'appeals',
      title: '36. Appeals',
      body: [
        'If your User Content is removed, restricted, disabled, or moderated and you believe the action was taken in error, you may request review.',
        'Appeals should be sent to support@sinlessgames.com.',
        'Appeals should include:',
        'Submitting an appeal does not guarantee reversal, restoration, republication, or reinstatement.',
      ],
      bullets: [
        'Account email',
        'Organization name, if applicable',
        'Content affected',
        'Reason you believe the action was incorrect',
        'Supporting context or evidence',
        'Contact information',
      ],
      contacts: [
        {
          label: 'Support',
          email: 'support@sinlessgames.com',
          href: 'mailto:support@sinlessgames.com',
        },
      ],
    },
    {
      id: 'content-retention-and-deletion',
      title: '37. Content Retention and Deletion',
      body: [
        'User Content may be retained or deleted according to the Data Policy, Privacy Policy, account settings, organization settings, deployment configuration, and applicable agreements.',
        'User Content may remain in:',
        'Deletion from active systems may not immediately remove every backup, cache, index, audit log, or third-party copy.',
      ],
      bullets: [
        'Backups',
        'Logs',
        'Audit records',
        'Moderation records',
        'Support records',
        'Billing records',
        'Incident records',
        'Security records',
        'Marketplace records',
        'Legal hold records',
        'Cached systems',
        'Public third-party copies',
      ],
      links: [
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy',
        },
      ],
    },
    {
      id: 'data-export',
      title: '38. Data Export',
      body: [
        'Users and organizations may be able to export certain User Content depending on account type, permissions, product functionality, deployment type, and applicable law.',
        'Exportable content may include:',
        'Exports are governed by the Data Policy and Privacy Policy.',
      ],
      bullets: [
        'Conversations',
        'Files',
        'Reports',
        'Dashboards',
        'Memory entries',
        'Workspace content',
        'Organization content',
        'Automation records',
        'Plugin metadata',
        'Marketplace content',
        'API records, where supported',
        'Audit logs, where permitted',
      ],
      links: [
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy',
        },
      ],
    },
    {
      id: 'aerealith-ai-use-of-user-content',
      title: '39. Aerealith AI Use of User Content',
      body: [
        'SinLess Games LLC may process User Content only as described in the Terms of Use, Data Policy, and Privacy Policy.',
        'Aerealith AI may process User Content to:',
        'SinLess Games LLC does not sell User Content.',
      ],
      bullets: [
        'Provide the service',
        'Generate Outputs',
        'Process files',
        'Operate integrations',
        'Run automations',
        'Execute approved tool calls',
        'Provide memory and personalization',
        'Provide dashboards and analytics',
        'Secure the service',
        'Prevent abuse',
        'Debug issues',
        'Provide support',
        'Process billing',
        'Maintain audit logs',
        'Conduct approved research',
        'Improve reliability and quality',
        'Comply with law',
        'Enforce policies',
      ],
      links: [
        {
          label: 'Terms of Use',
          href: '/Policies/terms-of-use',
        },
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy',
        },
      ],
    },
    {
      id: 'research-and-product-improvement',
      title: '40. Research and Product Improvement',
      body: [
        'Aerealith AI may use User Content for approved research and product improvement only as described in the Data Policy and Privacy Policy.',
        'Research use should:',
      ],
      bullets: [
        'Use minimum necessary data',
        'Prefer aggregated or de-identified data where practical',
        'Avoid unnecessary human review of private content',
        'Protect sensitive data',
        'Respect user and organization settings',
        'Respect enterprise agreements',
        'Avoid using secrets for research',
        'Avoid publishing identifiable user or organization data without permission',
      ],
      links: [
        {
          label: 'Data Policy',
          href: '/Policies/data',
        },
        {
          label: 'Privacy Policy',
          href: '/Policies/privacy',
        },
      ],
    },
    {
      id: 'model-training',
      title: '41. Model Training',
      body: [
        'Unless clearly disclosed, enabled by user or organization settings, or permitted by written agreement, Aerealith AI should not use private Customer Data to train public or general-purpose models.',
        'If optional training, fine-tuning, or learning features are offered, they should provide clear notice, controls, and documentation.',
        'Enterprise and organization customers may have additional controls over whether their data may be used for model training, evaluation, research, or product improvement.',
      ],
    },
    {
      id: 'content-license-to-sinless-games-llc',
      title: '42. Content License to SinLess Games LLC',
      body: [
        'You grant SinLess Games LLC a limited, worldwide, non-exclusive, royalty-free license to host, store, process, transmit, display, copy, modify, create technical transformations of, analyze, and otherwise use User Content only as needed to:',
        'This license does not transfer ownership of User Content to SinLess Games LLC.',
      ],
      bullets: [
        'Provide Aerealith AI',
        'Generate Outputs',
        'Process prompts and files',
        'Operate integrations',
        'Run automations',
        'Execute approved tool calls',
        'Provide memory and personalization',
        'Provide dashboards and analytics',
        'Operate APIs and developer tools',
        'Support marketplace functionality',
        'Secure the service',
        'Prevent abuse',
        'Debug errors',
        'Provide support',
        'Process billing',
        'Maintain audit logs',
        'Conduct approved research',
        'Improve reliability and quality',
        'Comply with law',
        'Enforce policies',
      ],
    },
    {
      id: 'content-license-for-public-sharing',
      title: '43. Content License for Public Sharing',
      body: [
        'If you publish User Content through Aerealith AI public features, you grant SinLess Games LLC a limited license to display, host, transmit, reproduce, and distribute that public content as needed to provide the public-sharing feature.',
        'Public-sharing features may include:',
        'You may be able to remove public content, but removal may not delete copies already accessed, downloaded, cached, archived, or shared by others.',
      ],
      bullets: [
        'Shared links',
        'Public dashboards',
        'Marketplace listings',
        'Plugin pages',
        'Template pages',
        'Community posts',
        'Reviews',
        'Public documentation',
        'Published workflows',
      ],
    },
    {
      id: 'organization-license-and-control',
      title: '44. Organization License and Control',
      body: [
        'If User Content is created in an organization workspace, the organization may have rights to access, use, retain, export, delete, restrict, or control that content according to organization settings, contracts, and applicable law.',
        'Users should understand their organization’s policies before creating content in organization workspaces.',
      ],
    },
    {
      id: 'self-hosted-hybrid-and-air-gapped-deployments',
      title: '45. Self-Hosted, Hybrid, and Air-Gapped Deployments',
      body: [
        'For self-hosted, hybrid, private, or air-gapped deployments, the deploying organization may control content storage, moderation, attribution enforcement, export, deletion, retention, plugin approval, marketplace access, and public-sharing features.',
        'The deploying organization may be responsible for:',
        'SinLess Games LLC may still enforce license terms, official marketplace rules, hosted service terms, support terms, or intellectual property rights for official Aerealith AI components.',
      ],
      bullets: [
        'Content moderation',
        'Public-sharing controls',
        'Attribution rules',
        'Marketplace restrictions',
        'Plugin review',
        'User permissions',
        'Data retention',
        'Deletion workflows',
        'Export workflows',
        'Audit logs',
        'Legal compliance',
        'Security controls',
        'Child-safety controls',
        'Incident response',
      ],
    },
    {
      id: 'developer-and-api-content',
      title: '46. Developer and API Content',
      body: [
        'Developers using Aerealith AI APIs are responsible for content submitted to or generated through the API.',
        'Developers must:',
        'Developers are responsible for how Aerealith AI content appears in their applications, products, services, plugins, workflows, or websites.',
      ],
      bullets: [
        'Provide required notices to their users',
        'Obtain required consent',
        'Protect user data',
        'Include required Aerealith AI attribution for public or commercial AI-assisted content',
        'Follow policy restrictions',
        'Respect rate limits',
        'Respect user permissions',
        'Avoid unsafe or illegal content',
        'Avoid deceptive AI presentation',
        'Avoid hidden data collection',
        'Avoid content that violates third-party rights',
      ],
    },
    {
      id: 'content-classification-and-labels',
      title: '47. Content Classification and Labels',
      body: [
        'SinLess Games LLC may classify or label User Content to support:',
        'Labels may be generated automatically, manually, or through user and organization settings.',
        'Labels may not always be accurate.',
        'Users and organizations remain responsible for reviewing content and applying appropriate controls.',
      ],
      bullets: [
        'Safety',
        'Age restrictions',
        'Privacy controls',
        'Security controls',
        'Marketplace review',
        'Search and retrieval',
        'Moderation',
        'Compliance',
        'Public sharing',
        'Accessibility',
        'Attribution',
        'Content warnings',
        'Organization policy enforcement',
      ],
    },
    {
      id: 'content-warnings-and-disclosures',
      title: '48. Content Warnings and Disclosures',
      body: [
        'SinLess Games LLC may require warnings or disclosures for certain User Content.',
        'Warnings or disclosures may be required for:',
        'Aerealith AI attribution is separate from any other disclosure required by law, platform rules, professional standards, organization policy, or contract.',
      ],
      bullets: [
        'AI-generated content',
        'Synthetic media',
        'Mature content',
        'Age-restricted content',
        'Sensitive topics',
        'Medical, legal, financial, or professional content',
        'Public reports',
        'Marketplace items',
        'High-risk workflows',
        'Security-related content',
        'Potentially harmful content',
        'User-generated public content',
        'Content involving minors',
      ],
    },
    {
      id: 'content-monetization',
      title: '49. Content Monetization',
      body: [
        'Users may monetize AI-Assisted Content generated through Aerealith AI, subject to:',
        'SinLess Games LLC may restrict monetization of content that violates policy, creates risk, or violates payment processor rules.',
      ],
      bullets: [
        'Required attribution',
        'Subscription plan limits',
        'Marketplace rules',
        'Payment processor rules',
        'Intellectual property rights',
        'Open-source licenses',
        'Privacy obligations',
        'Organization policies',
        'Applicable law',
        'Written agreements',
      ],
    },
    {
      id: 'no-obligation-to-host-content',
      title: '50. No Obligation to Host Content',
      body: [
        'SinLess Games LLC has no obligation to host, display, publish, distribute, preserve, restore, or maintain any User Content except as expressly stated in a written agreement.',
        'SinLess Games LLC may remove, restrict, disable, or delete User Content when required or appropriate under these policies, law, contract, safety needs, security needs, or operational needs.',
      ],
    },
    {
      id: 'no-endorsement-of-user-content',
      title: '51. No Endorsement of User Content',
      body: [
        'User Content belongs to the user or organization that created, uploaded, generated, published, or shared it.',
        'SinLess Games LLC does not endorse, verify, approve, or guarantee User Content unless expressly stated in writing.',
        'Aerealith AI attribution does not mean SinLess Games LLC endorses or is responsible for the attributed content.',
      ],
    },
    {
      id: 'enforcement',
      title: '52. Enforcement',
      body: [
        'SinLess Games LLC may investigate suspected violations of this policy.',
        'Depending on severity, risk, and context, SinLess Games LLC may:',
        'SinLess Games LLC may act immediately and without prior notice when necessary to protect users, systems, data, Aerealith AI, SinLess Games LLC, third parties, minors, or the public.',
      ],
      bullets: [
        'Warn the user or organization',
        'Require attribution correction',
        'Require content correction',
        'Require content removal',
        'Add labels or warnings',
        'Restrict content visibility',
        'Remove content',
        'Disable shared links',
        'Disable marketplace listings',
        'Disable plugins',
        'Disable automations',
        'Restrict public sharing',
        'Restrict uploads',
        'Restrict generation features',
        'Suspend accounts',
        'Terminate accounts',
        'Notify organization administrators',
        'Preserve relevant records',
        'Report unlawful activity where appropriate',
        'Refuse future service',
      ],
    },
    {
      id: 'repeat-violations',
      title: '53. Repeat Violations',
      body: [
        'Repeat violations may result in stronger enforcement.',
        'Repeat violations may include:',
        'Enforcement may include suspension or termination.',
      ],
      bullets: [
        'Repeatedly publishing prohibited content',
        'Repeatedly omitting required Aerealith AI attribution',
        'Repeatedly infringing intellectual property rights',
        'Repeatedly uploading secrets',
        'Repeatedly exposing personal data',
        'Repeatedly mislabeling age-restricted content',
        'Repeatedly abusing marketplace listings',
        'Repeatedly evading moderation',
        'Repeatedly creating harmful AI-assisted content',
        'Repeatedly violating public-sharing rules',
      ],
    },
    {
      id: 'contact',
      title: '54. Contact',
      body: [
        'Questions about this policy may be sent to:',
        'Before publishing this policy, confirm these email aliases exist and are monitored.',
      ],
      contacts: [
        {
          label: 'Support',
          email: 'support@sinlessgames.com',
          href: 'mailto:support@sinlessgames.com',
        },
        {
          label: 'Abuse',
          email: 'abuse@sinlessgames.com',
          href: 'mailto:abuse@sinlessgames.com',
        },
        {
          label: 'AI safety',
          email: 'safety@sinlessgames.com',
          href: 'mailto:safety@sinlessgames.com',
        },
        {
          label: 'Copyright',
          email: 'copyright@sinlessgames.com',
          href: 'mailto:copyright@sinlessgames.com',
        },
        {
          label: 'Privacy',
          email: 'privacy@sinlessgames.com',
          href: 'mailto:privacy@sinlessgames.com',
        },
        {
          label: 'Security',
          email: 'security@sinlessgames.com',
          href: 'mailto:security@sinlessgames.com',
        },
        {
          label: 'Legal',
          email: 'legal@sinlessgames.com',
          href: 'mailto:legal@sinlessgames.com',
        },
      ],
    },
    {
      id: 'publication-checklist',
      title: '55. Publication Checklist',
      body: ['Before publishing this policy, complete the following:'],
      bullets: [
        'Confirm official company name: SinLess Games LLC',
        'Confirm official product name: Aerealith AI',
        'Confirm attribution requirement wording',
        'Confirm whether attribution can be waived for paid or enterprise plans',
        'Confirm acceptable attribution examples',
        'Confirm attribution requirements for code',
        'Confirm attribution requirements for images and media',
        'Confirm attribution requirements for marketplace items',
        'Confirm commercial-use rules',
        'Confirm public-sharing features',
        'Confirm organization workspace ownership behavior',
        'Confirm moderation workflow',
        'Confirm appeal workflow',
        'Confirm copyright takedown workflow',
        'Confirm trademark complaint workflow',
        'Confirm marketplace content workflow',
        'Confirm user review and reporting workflow',
        'Confirm age-restricted content labels',
        'Confirm minor safety restrictions',
        'Confirm API/developer content rules',
        'Confirm self-hosted and air-gapped responsibilities',
        'Confirm all email aliases exist and are monitored',
        'Have qualified legal counsel review this policy',
      ],
    },
    {
      id: 'changes-to-this-policy',
      title: '56. Changes to This Policy',
      body: [
        'We may update this policy from time to time.',
        'When we make material changes, we will update the last_updated date and may provide notice through the service, documentation, account settings, support portal, email, release notes, legal notices page, or another reasonable method.',
        'Continued use of Aerealith AI after changes become effective means you accept the updated policy.',
      ],
    },
    {
      id: 'legal-review-notice',
      title: '57. Legal Review Notice',
      body: [
        'This policy is a draft template and should be reviewed by qualified legal counsel before publication.',
        'User-generated content, AI-generated output ownership, copyrightability, attribution requirements, synthetic media disclosure, public sharing, marketplace content, moderation, takedowns, commercial use, organization ownership, minors, privacy, open-source licensing, and platform liability requirements may vary by jurisdiction, content type, customer type, deployment model, and written agreement.',
      ],
    },
  ],
} satisfies PolicyDocument;

export default userGeneratedContentPolicy;
