/**
 * Gender enum representing the possible values for a person's gender identity.
 */
export enum Gender {
  Unspecified = 'unspecified',
  PreferNotToSay = 'prefer_not_to_say',
  NotListed = 'not_listed',
  SelfDescribe = 'self_describe',
  Questioning = 'questioning',
  Unknown = 'unknown',

  Female = 'female',
  Male = 'male',
  Woman = 'woman',
  Man = 'man',
  Girl = 'girl',
  Boy = 'boy',

  Cisgender = 'cisgender',
  CisgenderFemale = 'cisgender_female',
  CisgenderMale = 'cisgender_male',
  CisgenderWoman = 'cisgender_woman',
  CisgenderMan = 'cisgender_man',
  CisFemale = 'cis_female',
  CisMale = 'cis_male',
  CisWoman = 'cis_woman',
  CisMan = 'cis_man',

  Transgender = 'transgender',
  Trans = 'trans',
  TransFemale = 'trans_female',
  TransMale = 'trans_male',
  TransWoman = 'trans_woman',
  TransMan = 'trans_man',
  TransFeminine = 'trans_feminine',
  TransMasculine = 'trans_masculine',
  Transfeminine = 'transfeminine',
  Transmasculine = 'transmasculine',
  MtF = 'mtf',
  FtM = 'ftm',
  MaleToFemale = 'male_to_female',
  FemaleToMale = 'female_to_male',

  NonBinary = 'non_binary',
  Nonbinary = 'nonbinary',
  Enby = 'enby',
  GenderNonBinary = 'gender_non_binary',
  GenderDiverse = 'gender_diverse',
  GenderExpansive = 'gender_expansive',
  GenderVariant = 'gender_variant',
  GenderMinority = 'gender_minority',
  GenderCreative = 'gender_creative',

  Genderqueer = 'genderqueer',
  GenderQueer = 'gender_queer',
  Genderfluid = 'genderfluid',
  GenderFluid = 'gender_fluid',
  FluidGender = 'fluid_gender',
  Genderflux = 'genderflux',
  GenderFlux = 'gender_flux',
  Fluidflux = 'fluidflux',
  Genderfluidflux = 'genderfluidflux',

  Agender = 'agender',
  Genderless = 'genderless',
  Gendervoid = 'gendervoid',
  GenderVoid = 'gender_void',
  Voidgender = 'voidgender',
  Neutrois = 'neutrois',
  Neutral = 'neutral',
  GenderNeutral = 'gender_neutral',
  Nullgender = 'nullgender',
  NonGendered = 'non_gendered',

  Bigender = 'bigender',
  BiGender = 'bi_gender',
  Trigender = 'trigender',
  TriGender = 'tri_gender',
  Polygender = 'polygender',
  PolyGender = 'poly_gender',
  Pangender = 'pangender',
  PanGender = 'pan_gender',
  Multigender = 'multigender',
  MultiGender = 'multi_gender',
  Omnigender = 'omnigender',
  Ambigender = 'ambigender',
  Androgyne = 'androgyne',
  Androgynous = 'androgynous',

  Demigender = 'demigender',
  DemiGender = 'demi_gender',
  Demigirl = 'demigirl',
  DemiGirl = 'demi_girl',
  Demiwoman = 'demiwoman',
  DemiWoman = 'demi_woman',
  Demifemale = 'demifemale',
  DemiFemale = 'demi_female',
  Demiboy = 'demiboy',
  DemiBoy = 'demi_boy',
  Demiman = 'demiman',
  DemiMan = 'demi_man',
  Demimale = 'demimale',
  DemiMale = 'demi_male',
  Demifluid = 'demifluid',
  Demiflux = 'demiflux',

  Libragender = 'libragender',
  Librafeminine = 'librafeminine',
  Libramasculine = 'libramasculine',
  Libranonbinary = 'libranonbinary',
  Paragender = 'paragender',
  Paragirl = 'paragirl',
  Paraboy = 'paraboy',
  Parafeminine = 'parafeminine',
  Paramasculine = 'paramasculine',

  Masculine = 'masculine',
  Feminine = 'feminine',
  MasculineOfCenter = 'masculine_of_center',
  FeminineOfCenter = 'feminine_of_center',
  Masc = 'masc',
  Femme = 'femme',
  Butch = 'butch',
  Stud = 'stud',
  Tomboy = 'tomboy',
  Femboy = 'femboy',

  Intergender = 'intergender',
  Intersex = 'intersex',
  IntersexMan = 'intersex_man',
  IntersexWoman = 'intersex_woman',
  IntersexNonBinary = 'intersex_non_binary',

  TwoSpirit = 'two_spirit',
  Hijra = 'hijra',
  Kinner = 'kinner',
  Aravani = 'aravani',
  Thirunangai = 'thirunangai',
  Thirunambi = 'thirunambi',
  FaAfafine = 'fa_afafine',
  FaAtama = 'fa_atama',
  Mahu = 'mahu',
  Muxe = 'muxe',
  Bakla = 'bakla',
  Waria = 'waria',
  Kathoey = 'kathoey',
  Travesti = 'travesti',
  Sistergirl = 'sistergirl',
  Brotherboy = 'brotherboy',
  Takatapui = 'takatapui',
  AkavaIne = 'akava_ine',
  Whakawahine = 'whakawahine',
  TangataIraTane = 'tangata_ira_tane',

  ThirdGender = 'third_gender',
  FourthGender = 'fourth_gender',
  OtherGender = 'other_gender',
  AnotherGender = 'another_gender',
  NeitherGender = 'neither_gender',
  BothGenders = 'both_genders',
  AllGenders = 'all_genders',
  MultipleGenders = 'multiple_genders',
  NoGender = 'no_gender',

  Maverique = 'maverique',
  Aporagender = 'aporagender',
  Aliagender = 'aliagender',
  Maverine = 'maverine',
  Epicene = 'epicene',
  Novigender = 'novigender',
  Proxvir = 'proxvir',
  Juxera = 'juxera',
  Femache = 'femache',

  Xenogender = 'xenogender',
  Neurogender = 'neurogender',
  Autigender = 'autigender',
  Astralgender = 'astralgender',
  Cosmicgender = 'cosmicgender',
  Stargender = 'stargender',
  Spacegender = 'spacegender',
  Caelgender = 'caelgender',
  Aesthetigender = 'aesthetigender',
  Colorgender = 'colorgender',
  Mirrorgender = 'mirrorgender',
  Mutogender = 'mutogender',
  Personagender = 'personagender',

  Greygender = 'greygender',
  Graygender = 'graygender',
  Cassgender = 'cassgender',
  Cassflux = 'cassflux',
  Apagender = 'apagender',
  GenderApatic = 'gender_apatic',
  GenderApathetic = 'gender_apathetic',
  Pomogender = 'pomogender',
  Quoigender = 'quoigender',
  PomosexualGender = 'pomosexual_gender',

  Girlflux = 'girlflux',
  Boyflux = 'boyflux',
  Womanflux = 'womanflux',
  Manflux = 'manflux',
  Femflux = 'femflux',
  Mascflux = 'mascflux',
  Nonbinaryflux = 'nonbinaryflux',
  Agenderflux = 'agenderflux',
  Neutroisflux = 'neutroisflux',
  Bigenderflux = 'bigenderflux',

  Genderfae = 'genderfae',
  Genderfaer = 'genderfaer',
  Genderfaun = 'genderfaun',
  Genderfaunet = 'genderfaunet',
  Genderflor = 'genderflor',
  Genderfrith = 'genderfrith',
  Genderdoe = 'genderdoe',
  Genderstag = 'genderstag',

  Boygirl = 'boygirl',
  Girlboy = 'girlboy',
  Manwoman = 'manwoman',
  Womanman = 'womanman',
  MaleFemale = 'male_female',
  FemaleMale = 'female_male',
  NonBinaryWoman = 'non_binary_woman',
  NonBinaryMan = 'non_binary_man',
  NonbinaryWoman = 'nonbinary_woman',
  NonbinaryMan = 'nonbinary_man',

  GenderNonConforming = 'gender_non_conforming',
  GenderNonconforming = 'gender_nonconforming',
  GenderNC = 'gender_nc',
  GenderVariantPerson = 'gender_variant_person',
  GenderQuestioning = 'gender_questioning',
  Queer = 'queer',
  QueerGender = 'queer_gender',

  Transsexual = 'transsexual',
  TranssexualFemale = 'transsexual_female',
  TranssexualMale = 'transsexual_male',
  TranssexualWoman = 'transsexual_woman',
  TranssexualMan = 'transsexual_man',

  Crossdresser = 'crossdresser',
  DragKing = 'drag_king',
  DragQueen = 'drag_queen',
  DragPerformer = 'drag_performer',

  AFABNonBinary = 'afab_non_binary',
  AMABNonBinary = 'amab_non_binary',
  AFABTransmasculine = 'afab_transmasculine',
  AMABTransfeminine = 'amab_transfeminine',

  MasculineNonBinary = 'masculine_non_binary',
  FeminineNonBinary = 'feminine_non_binary',
  NeutralNonBinary = 'neutral_non_binary',
  AndrogynousNonBinary = 'androgynous_non_binary',
  FluidNonBinary = 'fluid_non_binary',
}