// libs/db/src/enums/profile-link-platform.enum.ts

/**
 * ProfileLinkPlatform enum representing known external profile link platforms.
 */
export enum ProfileLinkPlatform {
  Custom = 'custom',
  Other = 'other',

  Website = 'website',
  PersonalWebsite = 'personal_website',
  Portfolio = 'portfolio',
  Blog = 'blog',
  Linktree = 'linktree',
  Carrd = 'carrd',
  Beacons = 'beacons',
  AboutMe = 'about_me',

  Email = 'email',
  Phone = 'phone',
  Sms = 'sms',

  GitHub = 'github',
  GitLab = 'gitlab',
  Bitbucket = 'bitbucket',
  Codeberg = 'codeberg',
  SourceHut = 'sourcehut',
  StackOverflow = 'stackoverflow',
  StackExchange = 'stackexchange',
  DevTo = 'dev_to',
  Hashnode = 'hashnode',
  CodePen = 'codepen',
  Replit = 'replit',
  Glitch = 'glitch',
  Npm = 'npm',
  Packagist = 'packagist',
  PyPI = 'pypi',
  DockerHub = 'docker_hub',

  LinkedIn = 'linkedin',
  X = 'x',
  Twitter = 'twitter',
  Mastodon = 'mastodon',
  Bluesky = 'bluesky',
  Threads = 'threads',
  Facebook = 'facebook',
  Instagram = 'instagram',
  TikTok = 'tiktok',
  Snapchat = 'snapchat',
  Pinterest = 'pinterest',
  Tumblr = 'tumblr',
  Reddit = 'reddit',
  Quora = 'quora',
  Medium = 'medium',
  Substack = 'substack',

  Discord = 'discord',
  Guilded = 'guilded',
  Slack = 'slack',
  Telegram = 'telegram',
  Signal = 'signal',
  WhatsApp = 'whatsapp',
  Matrix = 'matrix',
  Element = 'element',
  Skype = 'skype',

  YouTube = 'youtube',
  YouTubeMusic = 'youtube_music',
  Twitch = 'twitch',
  Kick = 'kick',
  Vimeo = 'vimeo',
  Rumble = 'rumble',
  PeerTube = 'peertube',
  Trovo = 'trovo',

  Spotify = 'spotify',
  AppleMusic = 'apple_music',
  SoundCloud = 'soundcloud',
  Bandcamp = 'bandcamp',
  Audius = 'audius',
  Deezer = 'deezer',
  Tidal = 'tidal',
  Podcast = 'podcast',
  ApplePodcasts = 'apple_podcasts',
  SpotifyPodcasts = 'spotify_podcasts',

  Steam = 'steam',
  EpicGames = 'epic_games',
  Xbox = 'xbox',
  PlayStation = 'playstation',
  Nintendo = 'nintendo',
  ItchIo = 'itch_io',
  GameJolt = 'game_jolt',
  Roblox = 'roblox',
  Minecraft = 'minecraft',
  BattleNet = 'battle_net',
  RiotGames = 'riot_games',
  Ubisoft = 'ubisoft',
  EA = 'ea',
  GOG = 'gog',

  ArtStation = 'artstation',
  Behance = 'behance',
  Dribbble = 'dribbble',
  DeviantArt = 'deviantart',
  Pixiv = 'pixiv',
  Figma = 'figma',
  Canva = 'canva',
  Sketchfab = 'sketchfab',

  Patreon = 'patreon',
  KoFi = 'ko_fi',
  BuyMeACoffee = 'buy_me_a_coffee',
  OpenCollective = 'open_collective',
  GitHubSponsors = 'github_sponsors',
  Liberapay = 'liberapay',
  PayPal = 'paypal',
  Venmo = 'venmo',
  CashApp = 'cash_app',
  Stripe = 'stripe',

  Etsy = 'etsy',
  Shopify = 'shopify',
  Amazon = 'amazon',
  Ebay = 'ebay',
  Gumroad = 'gumroad',
  LemonSqueezy = 'lemon_squeezy',
  Fourthwall = 'fourthwall',
  Teespring = 'teespring',
  Redbubble = 'redbubble',
  Threadless = 'threadless',

  GoogleScholar = 'google_scholar',
  ORCID = 'orcid',
  ResearchGate = 'researchgate',
  AcademiaEdu = 'academia_edu',
  Arxiv = 'arxiv',

  Calendly = 'calendly',
  CalCom = 'cal_com',
  GoogleCalendar = 'google_calendar',
  Resume = 'resume',
  CV = 'cv',
  PressKit = 'press_kit',
  MediaKit = 'media_kit',
}