/**
 * Sexuality enum representing the possible values for a person's sexuality or sexual orientation.
 */
export enum Sexuality {
  Unspecified = 'unspecified',
  PreferNotToSay = 'prefer_not_to_say',
  NotListed = 'not_listed',
  SelfDescribe = 'self_describe',
  Questioning = 'questioning',
  Sapiosexual = 'sapiosexual',
  Unknown = 'unknown',

  Straight = 'straight',
  Heterosexual = 'heterosexual',
  Heteroflexible = 'heteroflexible',
  MostlyStraight = 'mostly_straight',

  Gay = 'gay',
  Lesbian = 'lesbian',
  Homosexual = 'homosexual',
  SameGenderLoving = 'same_gender_loving',
  SameSexAttracted = 'same_sex_attracted',
  SameGenderAttracted = 'same_gender_attracted',
  GayMan = 'gay_man',
  GayWoman = 'gay_woman',
  GayNonBinary = 'gay_non_binary',
  LesbianWoman = 'lesbian_woman',
  LesbianNonBinary = 'lesbian_non_binary',

  Bisexual = 'bisexual',
  Bi = 'bi',
  BiPlus = 'bi_plus',
  Bicurious = 'bicurious',
  BisexualPlus = 'bisexual_plus',
  BiromanticBisexual = 'biromantic_bisexual',
  HeteroromanticBisexual = 'heteroromantic_bisexual',
  HomoromanticBisexual = 'homoromantic_bisexual',

  Pansexual = 'pansexual',
  Pan = 'pan',
  PanromanticPansexual = 'panromantic_pansexual',
  PanCurious = 'pan_curious',

  Omnisexual = 'omnisexual',
  Omni = 'omni',
  Omnicurious = 'omnicurious',

  Polysexual = 'polysexual',
  Poly = 'poly',
  Multisexual = 'multisexual',
  Plurisexual = 'plurisexual',
  Ambisexual = 'ambisexual',

  Monosexual = 'monosexual',
  NonMonosexual = 'non_monosexual',
  Fluid = 'fluid',
  SexuallyFluid = 'sexually_fluid',
  Abrosexual = 'abrosexual',

  Queer = 'queer',
  QueerSexuality = 'queer_sexuality',
  LGBTQPlus = 'lgbtq_plus',
  LGBTQIAPlus = 'lgbtqia_plus',
  Sapphic = 'sapphic',
  Achillean = 'achillean',
  Diamoric = 'diamoric',
  Enbian = 'enbian',
  Toric = 'toric',
  Trixic = 'trixic',

  Asexual = 'asexual',
  Ace = 'ace',
  AceSpectrum = 'ace_spectrum',
  AsexualSpectrum = 'asexual_spectrum',
  Allosexual = 'allosexual',
  Allo = 'allo',
  Graysexual = 'graysexual',
  Greysexual = 'greysexual',
  GrayAsexual = 'gray_asexual',
  GreyAsexual = 'grey_asexual',
  GrayAce = 'gray_ace',
  GreyAce = 'grey_ace',
  Demisexual = 'demisexual',
  Demi = 'demi',
  Demiace = 'demiace',
  Semisexual = 'semisexual',
  Fraysexual = 'fraysexual',
  Aegosexual = 'aegosexual',
  Autochorissexual = 'autochorissexual',
  Akoisexual = 'akoisexual',
  Lithsexual = 'lithsexual',
  Cupiosexual = 'cupiosexual',
  Reciprosexual = 'reciprosexual',
  Requisexual = 'requisexual',
  Apothisexual = 'apothisexual',
  Iamvanosexual = 'iamvanosexual',
  Placiosexual = 'placiosexual',
  Bellussexual = 'bellussexual',
  Myrsexual = 'myrsexual',
  Aceflux = 'aceflux',
  Acespike = 'acespike',
  Acejump = 'acejump',
  Acespikeflux = 'acespikeflux',
  Orchidsexual = 'orchidsexual',
  Caedsexual = 'caedsexual',
  Quoisexual = 'quoisexual',
  Whatsexual = 'whatsexual',
  Idemsexual = 'idemsexual',
  Nebulasexual = 'nebulasexual',
  NoviSexual = 'novi_sexual',
  Aroace = 'aroace',
  AromanticAsexual = 'aromantic_asexual',
  GrayAroAce = 'gray_aro_ace',
  GreyAroAce = 'grey_aro_ace',
  DemiAroAce = 'demi_aro_ace',

  Aromantic = 'aromantic',
  Aro = 'aro',
  AroSpectrum = 'aro_spectrum',
  AromanticSpectrum = 'aromantic_spectrum',
  Alloromantic = 'alloromantic',
  Grayromantic = 'grayromantic',
  Greyromantic = 'greyromantic',
  Demiromantic = 'demiromantic',
  Frayromantic = 'frayromantic',
  Lithromantic = 'lithromantic',
  Akoiromantic = 'akoiromantic',
  Cupioromantic = 'cupioromantic',
  Recipromantic = 'recipromantic',
  Apothiromantic = 'apothiromantic',
  Bellusromantic = 'bellusromantic',
  Quoiromantic = 'quoiromantic',
  Idemromantic = 'idemromantic',
  Nebularomantic = 'nebularomantic',
  Aroflux = 'aroflux',
  Arospike = 'arospike',

  Heteroromantic = 'heteroromantic',
  Homoromantic = 'homoromantic',
  Biromantic = 'biromantic',
  Panromantic = 'panromantic',
  Omniromantic = 'omniromantic',
  Polyromantic = 'polyromantic',
  Multiromantic = 'multiromantic',
  Pluriromantic = 'pluriromantic',
  Androromantic = 'androromantic',
  Gynoromantic = 'gynoromantic',
  Ceteroromantic = 'ceteroromantic',
  Skolioromantic = 'skolioromantic',
  Queerromantic = 'queerromantic',
  Abromantic = 'abromantic',
  Pomoromantic = 'pomoromantic',

  Androsexual = 'androsexual',
  Androphilic = 'androphilic',
  Gynesexual = 'gynesexual',
  Gynosexual = 'gynosexual',
  Gynephilic = 'gynephilic',
  Femmesexual = 'femmesexual',
  Mascsexual = 'mascsexual',
  Minsexual = 'minsexual',
  Finsexual = 'finsexual',
  Ninsexual = 'ninsexual',
  Ceterosexual = 'ceterosexual',
  Skoliosexual = 'skoliosexual',
  Enbisexual = 'enbisexual',
  Neptunic = 'neptunic',
  Uranic = 'uranic',
  Saturnic = 'saturnic',
  Venusic = 'venusic',
  Marsic = 'marsic',
  Solaric = 'solaric',
  Lunaric = 'lunaric',
  Terraric = 'terraric',
  Stellaric = 'stellaric',
  Galactian = 'galactian',
  Mascic = 'mascic',
  Femaric = 'femaric',

  Autosexual = 'autosexual',
  Autoromantic = 'autoromantic',
  AutosexualAutoromantic = 'autosexual_autoromantic',
  Monoromantic = 'monoromantic',
  OmniAroAce = 'omni_aro_ace',
  PanAroAce = 'pan_aro_ace',
  BiAroAce = 'bi_aro_ace',
  LesbianAroAce = 'lesbian_aro_ace',
  GayAroAce = 'gay_aro_ace',
  StraightAroAce = 'straight_aro_ace',

  Pomosexual = 'pomosexual',
  Pomosexuality = 'pomosexuality',
  QueerPlatonic = 'queer_platonic',
  Alterous = 'alterous',
  OrientedAroAce = 'oriented_aro_ace',
  AngledAroAce = 'angled_aro_ace',
  ElectioAroAce = 'electio_aro_ace',

  DemisexualHeteroromantic = 'demisexual_heteroromantic',
  DemisexualHomoromantic = 'demisexual_homoromantic',
  DemisexualBiromantic = 'demisexual_biromantic',
  DemisexualPanromantic = 'demisexual_panromantic',
  AsexualHeteroromantic = 'asexual_heteroromantic',
  AsexualHomoromantic = 'asexual_homoromantic',
  AsexualBiromantic = 'asexual_biromantic',
  AsexualPanromantic = 'asexual_panromantic',
  AsexualLesbian = 'asexual_lesbian',
  AsexualGay = 'asexual_gay',

  SexPositive = 'sex_positive',
  SexNeutral = 'sex_neutral',
  SexAverse = 'sex_averse',
  SexRepulsed = 'sex_repulsed',
  SexIndifferent = 'sex_indifferent',
  SexFavorable = 'sex_favorable',

  RomanticOrientationOnly = 'romantic_orientation_only',
  SexualOrientationOnly = 'sexual_orientation_only',
  MixedOrientation = 'mixed_orientation',
  SplitAttraction = 'split_attraction',
  NoLabel = 'no_label',
}