import { Migration } from '@mikro-orm/migrations';

export class Migration20260515211000_DropLegacyProfileEnumChecks extends Migration {
  override async up(): Promise<void> {
    this.addSql(`alter table "user_profile" drop constraint if exists "check_date_format";`);
    this.addSql(`alter table "user_profile" drop constraint if exists "check_measurement_system";`);
    this.addSql(`alter table "user_profile" drop constraint if exists "check_content_maturity";`);
    this.addSql(`alter table "user_profile" drop constraint if exists "check_time_format";`);
  }

  override async down(): Promise<void> {
    this.addSql(`alter table "user_profile" add constraint "check_date_format" check("date_format" in ('unspecified', 'default', 'locale_default', 'yyyy-MM-dd', 'yyyy/MM/dd', 'yyyy.MM.dd', 'yyyy MM dd', 'yyyyMMdd', 'yyyy-dd-MM', 'yyyy/dd/MM', 'yyyy.dd.MM', 'yyyy dd MM', 'yyyyddMM', 'MM-dd-yyyy', 'MM/dd/yyyy', 'MM.dd.yyyy', 'MM dd yyyy', 'MMddyyyy', 'dd-MM-yyyy', 'dd/MM/yyyy', 'dd.MM.yyyy', 'dd MM yyyy', 'ddMMyyyy', 'yy-MM-dd', 'yy/MM/dd', 'yy.MM.dd', 'yy MM dd', 'yyMMdd', 'MM-dd-yy', 'MM/dd/yy', 'MM.dd.yy', 'MM dd yy', 'MMddyy', 'dd-MM-yy', 'dd/MM/yy', 'dd.MM.yy', 'dd MM yy', 'ddMMyy', 'M-d-yyyy', 'M/d/yyyy', 'M.d.yyyy', 'M d yyyy', 'd-M-yyyy', 'd/M/yyyy', 'd.M.yyyy', 'd M yyyy', 'yyyy-M-d', 'yyyy/M/d', 'yyyy.M.d', 'yyyy M d', 'MMMM d, yyyy', 'MMMM d yyyy', 'MMM d, yyyy', 'MMM d yyyy', 'MMMM dd, yyyy', 'MMM dd, yyyy', 'd MMMM yyyy', 'd MMM yyyy', 'dd MMMM yyyy', 'dd MMM yyyy', 'yyyy MMMM d', 'yyyy MMM d', 'yyyy MMMM dd', 'yyyy MMM dd', 'EEEE, MMMM d, yyyy', 'EEE, MMM d, yyyy', 'EEEE, d MMMM yyyy', 'EEE, d MMM yyyy', 'EEEE, yyyy-MM-dd', 'EEE, yyyy-MM-dd', 'MMMM d', 'MMM d', 'MMMM dd', 'MMM dd', 'd MMMM', 'd MMM', 'dd MMMM', 'dd MMM', 'yyyy-MM', 'yyyy/MM', 'yyyy.MM', 'yyyy MM', 'MMMM yyyy', 'MMM yyyy', 'MM-yyyy', 'MM/yyyy', 'MM.yyyy', 'MM yyyy', 'yyyy', 'yy', 'MMMM', 'MMM', 'MM', 'dd', 'EEEE', 'EEE'));`);
    this.addSql(`alter table "user_profile" add constraint "check_measurement_system" check("measurement_system" in ('unspecified', 'default', 'locale_default', 'auto', 'custom', 'metric', 'si', 'international_system_of_units', 'imperial', 'british_imperial', 'us_customary', 'united_states_customary', 'hybrid', 'metric_with_us_customary', 'us_customary_with_metric', 'imperial_with_metric', 'metric_with_imperial', 'scientific', 'engineering', 'nautical', 'aviation', 'maritime', 'cgs', 'centimeter_gram_second', 'mks', 'meter_kilogram_second', 'natural_units', 'astronomical', 'survey', 'medical', 'fitness', 'culinary_metric', 'culinary_us_customary', 'culinary_imperial'));`);
    this.addSql(`alter table "user_profile" add constraint "check_content_maturity" check("content_maturity" in ('unspecified', 'default', 'unknown', 'not_rated', 'unrated', 'block_all', 'safe_only', 'family_friendly', 'general_audience', 'all_ages', 'everyone', 'early_childhood', 'children', 'kids', 'pre_teen', 'teen', 'older_teen', 'young_adult', 'mature', 'adult', 'adults_only', 'explicit', 'restricted', 'age_3_plus', 'age_7_plus', 'age_10_plus', 'age_12_plus', 'age_13_plus', 'age_15_plus', 'age_16_plus', 'age_17_plus', 'age_18_plus', 'age_21_plus', 'no_sensitive_content', 'mild_sensitive_content', 'moderate_sensitive_content', 'strong_sensitive_content', 'extreme_sensitive_content', 'no_violence', 'mild_violence', 'moderate_violence', 'strong_violence', 'graphic_violence', 'no_language', 'mild_language', 'moderate_language', 'strong_language', 'explicit_language', 'no_sexual_content', 'mild_suggestive_content', 'suggestive_content', 'sexual_content', 'explicit_sexual_content', 'no_nudity', 'mild_nudity', 'partial_nudity', 'nudity', 'explicit_nudity', 'no_substance_content', 'mild_substance_content', 'substance_references', 'substance_use', 'graphic_substance_use', 'no_gambling', 'simulated_gambling', 'gambling_references', 'real_gambling', 'no_horror', 'mild_horror', 'horror', 'intense_horror', 'no_user_generated_content', 'moderated_user_generated_content', 'user_generated_content_allowed', 'educational_only', 'professional_only', 'work_safe', 'not_safe_for_work', 'creator_controlled', 'parental_guidance', 'guardian_approval_required'));`);
    this.addSql(`alter table "user_profile" add constraint "check_time_format" check("time_format" in ('unspecified', 'default', 'locale_default', 'auto', 'custom', 'h:mm a', 'hh:mm a', 'h:mm:ss a', 'hh:mm:ss a', 'h:mm aaa', 'hh:mm aaa', 'H:mm', 'HH:mm', 'H:mm:ss', 'HH:mm:ss', 'HH:mm', 'HH:mm:ss.SSS', 'HH:mm:ssXXX', 'HH:mm:ss.SSSXXX', 'h a', 'hh a', 'H', 'HH', 'mm:ss', 'mm:ss.SSS', 'h:mm a z', 'h:mm a zzzz', 'HH:mm z', 'HH:mm zzzz', 'h:mma', 'hh:mma', 'Hmm', 'HHmm'));`);
  }
}
