import { Migration } from '@mikro-orm/migrations';

export class Migration20260515202951_NormalizeProfileEnumsAndDefaults extends Migration {

  override async up(): Promise<void> {
    this.addSql(`alter table "user_profile" drop constraint if exists "user_profile_date_format_check";`);
    this.addSql(`alter table "user_profile" drop constraint if exists "user_profile_measurement_system_check";`);
    this.addSql(`alter table "user_profile" drop constraint if exists "user_profile_content_maturity_check";`);

    this.addSql(`alter table "user_profile" alter column "field_visibility" type jsonb using ("field_visibility"::jsonb);`);
    this.addSql(`update "user_profile" set "field_visibility" = '{"displayName":"public","givenName":"private","middleName":"private","familyName":"private","pronouns":"public","avatarUrl":"public","bannerUrl":"public","bio":"public","locationLabel":"public","country":"public","gender":"private","sex":"private","sexuality":"private","primaryLanguage":"public","languages":"public","locale":"private","timezone":"private","timezoneUtc":"private","timezoneGreenwich":"private","weekStartDay":"private","dateFormat":"private","timeFormat":"private","nameDisplayOrder":"private","measurementSystem":"private","contentMaturity":"private","websiteUrl":"public","links":"public","createdAt":"public","updatedAt":"private"}' where "field_visibility" is null;`);
    this.addSql(`alter table "user_profile" alter column "field_visibility" set default '{"displayName":"public","givenName":"private","middleName":"private","familyName":"private","pronouns":"public","avatarUrl":"public","bannerUrl":"public","bio":"public","locationLabel":"public","country":"public","gender":"private","sex":"private","sexuality":"private","primaryLanguage":"public","languages":"public","locale":"private","timezone":"private","timezoneUtc":"private","timezoneGreenwich":"private","weekStartDay":"private","dateFormat":"private","timeFormat":"private","nameDisplayOrder":"private","measurementSystem":"private","contentMaturity":"private","websiteUrl":"public","links":"public","createdAt":"public","updatedAt":"private"}';`);
    this.addSql(`alter table "user_profile" alter column "field_visibility" set not null;`);
    this.addSql(`update "user_profile" set "date_format" = 'unspecified' where "date_format" is not null and "date_format" not in ('unspecified', 'yyyy-MM-dd', 'MM/dd/yyyy', 'dd/MM/yyyy');`);
    this.addSql(`update "user_profile" set "measurement_system" = 'unspecified' where "measurement_system" is not null and "measurement_system" not in ('unspecified', 'imperial', 'metric', 'scientific');`);
    this.addSql(`update "user_profile" set "content_maturity" = 'unspecified' where "content_maturity" is not null and "content_maturity" not in ('unspecified', 'safe_only', 'family_friendly', 'explicit', 'restricted');`);
    this.addSql(`alter table "user_profile" add constraint "user_profile_date_format_check" check("date_format" in ('unspecified', 'yyyy-MM-dd', 'MM/dd/yyyy', 'dd/MM/yyyy'));`);
    this.addSql(`alter table "user_profile" add constraint "user_profile_measurement_system_check" check("measurement_system" in ('unspecified', 'imperial', 'metric', 'scientific'));`);
    this.addSql(`alter table "user_profile" add constraint "user_profile_content_maturity_check" check("content_maturity" in ('unspecified', 'safe_only', 'family_friendly', 'explicit', 'restricted'));`);
  }

  override async down(): Promise<void> {
    this.addSql(`alter table "user_profile" drop constraint if exists "user_profile_date_format_check";`);
    this.addSql(`alter table "user_profile" drop constraint if exists "user_profile_measurement_system_check";`);
    this.addSql(`alter table "user_profile" drop constraint if exists "user_profile_content_maturity_check";`);

    this.addSql(`alter table "user_profile" alter column "field_visibility" drop default;`);
    this.addSql(`alter table "user_profile" alter column "field_visibility" type jsonb using ("field_visibility"::jsonb);`);
    this.addSql(`alter table "user_profile" alter column "field_visibility" drop not null;`);
    this.addSql(`alter table "user_profile" add constraint "user_profile_date_format_check" check("date_format" in ('unspecified', 'default', 'locale_default', 'yyyy-MM-dd', 'yyyy-MM-dd', 'yyyy/MM/dd', 'yyyy.MM.dd', 'yyyy MM dd', 'yyyyMMdd', 'yyyy-dd-MM', 'yyyy/dd/MM', 'yyyy.dd.MM', 'yyyy dd MM', 'yyyyddMM', 'MM-dd-yyyy', 'MM/dd/yyyy', 'MM.dd.yyyy', 'MM dd yyyy', 'MMddyyyy', 'dd-MM-yyyy', 'dd/MM/yyyy', 'dd.MM.yyyy', 'dd MM yyyy', 'ddMMyyyy', 'yy-MM-dd', 'yy/MM/dd', 'yy.MM.dd', 'yy MM dd', 'yyMMdd', 'MM-dd-yy', 'MM/dd/yy', 'MM.dd.yy', 'MM dd yy', 'MMddyy', 'dd-MM-yy', 'dd/MM/yy', 'dd.MM.yy', 'dd MM yy', 'ddMMyy', 'M-d-yyyy', 'M/d/yyyy', 'M.d.yyyy', 'M d yyyy', 'd-M-yyyy', 'd/M/yyyy', 'd.M.yyyy', 'd M yyyy', 'yyyy-M-d', 'yyyy/M/d', 'yyyy.M.d', 'yyyy M d', 'MMMM d, yyyy', 'MMMM d yyyy', 'MMM d, yyyy', 'MMM d yyyy', 'MMMM dd, yyyy', 'MMM dd, yyyy', 'd MMMM yyyy', 'd MMM yyyy', 'dd MMMM yyyy', 'dd MMM yyyy', 'yyyy MMMM d', 'yyyy MMM d', 'yyyy MMMM dd', 'yyyy MMM dd', 'EEEE, MMMM d, yyyy', 'EEE, MMM d, yyyy', 'EEEE, d MMMM yyyy', 'EEE, d MMM yyyy', 'EEEE, yyyy-MM-dd', 'EEE, yyyy-MM-dd', 'MMMM d', 'MMM d', 'MMMM dd', 'MMM dd', 'd MMMM', 'd MMM', 'dd MMMM', 'dd MMM', 'yyyy-MM', 'yyyy/MM', 'yyyy.MM', 'yyyy MM', 'MMMM yyyy', 'MMM yyyy', 'MM-yyyy', 'MM/yyyy', 'MM.yyyy', 'MM yyyy', 'MMMM yyyy', 'MMM yyyy', 'yyyy', 'yy', 'MMMM', 'MMM', 'MM', 'dd', 'EEEE', 'EEE'));`);
    this.addSql(`alter table "user_profile" add constraint "user_profile_measurement_system_check" check("measurement_system" in ('unspecified', 'default', 'locale_default', 'auto', 'custom', 'metric', 'si', 'international_system_of_units', 'imperial', 'british_imperial', 'us_customary', 'united_states_customary', 'hybrid', 'metric_with_us_customary', 'us_customary_with_metric', 'imperial_with_metric', 'metric_with_imperial', 'scientific', 'engineering', 'nautical', 'aviation', 'maritime', 'cgs', 'centimeter_gram_second', 'mks', 'meter_kilogram_second', 'natural_units', 'astronomical', 'survey', 'medical', 'fitness', 'culinary_metric', 'culinary_us_customary', 'culinary_imperial'));`);
    this.addSql(`alter table "user_profile" add constraint "user_profile_content_maturity_check" check("content_maturity" in ('unspecified', 'default', 'unknown', 'not_rated', 'unrated', 'block_all', 'safe_only', 'family_friendly', 'general_audience', 'all_ages', 'everyone', 'early_childhood', 'children', 'kids', 'pre_teen', 'teen', 'older_teen', 'young_adult', 'mature', 'adult', 'adults_only', 'explicit', 'restricted', 'age_3_plus', 'age_7_plus', 'age_10_plus', 'age_12_plus', 'age_13_plus', 'age_15_plus', 'age_16_plus', 'age_17_plus', 'age_18_plus', 'age_21_plus', 'no_sensitive_content', 'mild_sensitive_content', 'moderate_sensitive_content', 'strong_sensitive_content', 'extreme_sensitive_content', 'no_violence', 'mild_violence', 'moderate_violence', 'strong_violence', 'graphic_violence', 'no_language', 'mild_language', 'moderate_language', 'strong_language', 'explicit_language', 'no_sexual_content', 'mild_suggestive_content', 'suggestive_content', 'sexual_content', 'explicit_sexual_content', 'no_nudity', 'mild_nudity', 'partial_nudity', 'nudity', 'explicit_nudity', 'no_substance_content', 'mild_substance_content', 'substance_references', 'substance_use', 'graphic_substance_use', 'no_gambling', 'simulated_gambling', 'gambling_references', 'real_gambling', 'no_horror', 'mild_horror', 'horror', 'intense_horror', 'no_user_generated_content', 'moderated_user_generated_content', 'user_generated_content_allowed', 'educational_only', 'professional_only', 'work_safe', 'not_safe_for_work', 'creator_controlled', 'parental_guidance', 'guardian_approval_required'));`);
  }

}
