import type { ExecutionContext, Fetcher } from '@cloudflare/workers-types';

import { applyCloudflareMiddlewares } from './middlewares/cloudflare-chain';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore -- `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
import nextWorker from '../.open-next/worker.js';

export interface CloudflareEnv {
  ASSETS: Fetcher;
  NEXTJS_ENV: string;
  NEXT_PUBLIC_APP_NAME: string;
  NEXT_PUBLIC_APP_ENV: string;
  WORKER_SELF_REFERENCE: Fetcher;
}

export default {
  async fetch(
    request: Request,
    env: CloudflareEnv,
    ctx: ExecutionContext,
  ): Promise<Response> {
    const result = await applyCloudflareMiddlewares(request, env, ctx);

    if (result.response) {
      return result.response;
    }

    return nextWorker.fetch(result.request, env, ctx);
  },
};
